### ISSUE TITLE
Add page in alphamanual.audacityteam.org for application preferences like: https://alphamanual.audacityteam.org/man/Application_Preferences

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#1005]

**Comment by SteveDaulton** [comment]
Are "Application_Preferences" different from "Preferences" (https://alphamanual.audacityteam.org/man/Preferences)?

**Comment by Paul-Licameli** [comment]
@SteveDaulton The automatic checking for updates has a don't-tell-me-again checkbox, but then a place is needed in Preferences to reverse that decision if you wish.  There will be a new page just for that.

For DIY builds of Audacity, this will only appear if you opt-in at configuration time with the right CMake options.

As also the rest of checking for updates and anything else that uses networking.

**Comment by Paul-Licameli** [comment]
@Tantacrul the new preference dialog pane needs a manual page, but I suppose the pop-up when a new version is detected will not?  It is not a command the user invokes, and will explain itself when you see it.

**Comment by Paul-Licameli** [comment]
@SteveDaulton this new Preferences pane will be bare at first but may grow as a place for other such opt-ins and _outs.

**Comment by JamesCrook** [comment]
@jounih The steps for doing this are:

1 Create a page in the wiki https://alphamanual.audacityteam.org/man/Application_Preferences and edit the text to say what you want it to say.
2.a Upload the image for it.  Make sure to use the same pattern of naming as for the other preference pages.
2.b Upload the updated images for all other preference pages, since they will all have changed.
3 Update the template https://alphamanual.audacityteam.org/man/Template:Prefs-imagemap

You can get all the preference page images automatically from within Audacity: 
![image](https://user-images.githubusercontent.com/1621525/122415565-eeda1d00-cf7f-11eb-823c-4da9124918fb.png)

You can either update the template by hand to indicate the new hotspots, or I can show you how to use a tool that does that.
