### ISSUE TITLE
Decompose Plug-in manager

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1180]
1. Details are TBD - needs meeting
2. Decomposition needed

Design attached #999

**Comment by gera-gas** [comment]
**Description of task decomposition.**
All estimation times have two borders: this is not 100% precision time frame, this is the approximate time window for solving this.

1. Preferences for the custom plugin search path.
1.1 Create the preference type, by analogy `BoolSettings`, but for describing plugins paths that will contain a `wxArrayString` objects, something like - `ArrayStringSettings` or using `StringSetting` for economy time.
1.2 If we using `StringSetting`, the path will be separated by `;`, and this is a not a problem to parse this by `wxTokenizer`.
1.3 Second, need patch `PluginManager::FindFilesInPathList()` with additional search directories from settings.
Estimate: 4 - 6 hrs.

2. Check method.
For each plugin type, needed a static method for validation each plugin instance of each plugin type, something like: `VSTEffectsModule::Check()`.
2.1 Get information about Audacity CLI command.
2.2 Run a new Audacity process with check command with output result to `STDOUT`.
2.3 Catch and parsing `STDOUT` after this on success.
2.4 Create this check method for each plugin type: VST, AU, LV2, LADSPA.
2.5 Call this methods at startup (for example in `PluginManager::Initialize()` and collect failed information.
2.6 Output dialog with incompatible plugins list.
Estimate: 24 - 32 hrs.

3. Remake `PluginRegistrationDialog` dialog.
to be continued . . .

**Comment by Paul-Licameli** [comment]
This looks like a good decomposition.  But I think part 1 might make do simply with existing StringSetting, splitting the string on ; characters.

Questions.

- Do you have at least one example of LADSPA, LV2, Vamp, VST2 plug-ins that you can test with?
- This is still supposing only VST2 support -- not yet VST3.  Correct?
- I recall we said the new dialog also needs a "failed" state.  Instead of one choice in a drop-down menu as now, perhaps a line of the list control is disabled.  Do you account for that?
- If the user interface specification is firm enough, perhaps you can attempt step 3 first, to get early feedback and testing.  While you have not yet implemented validation for LADSPA, LV2, and Vamp, you might simply always make them "failed."

The user interface can be sent to review and testing, while you concurrently continue working on the AU, LADSPA, LV2, Vamp cases.  And perhaps each of those becomes a separate PR.

**Comment by gera-gas** [comment]
1 - I can download this plugins or at leat build empty plugins for AU, VST2, LV2 and LADSPA.
2 - yes, correct.
3 - yes, I remember that about "failed" state.
4 - okay
I agree about separate and move UI developing part to first order.

**Comment by AnitaBats** [comment]
Decomposition is done
