### ISSUE TITLE
Deleted Releases

### ISSUE THREAD

**Issue by catSIXe** [audacity/audacity#1222]
This Software absolutely sucks, why do they delete releases prior to 3.X??? 

Audashitty!

**Comment by shoogle** [comment]
No releases (or release binaries) have been deleted.

Prior to version 3, release binaries were published on FOSSHUB. The old releases are [still available on FOSSHUB](https://www.fosshub.com/Audacity-old.html).

Since version 3, release binaries have been published [here on GitHub](https://github.com/audacity/audacity/releases).
