### ISSUE TITLE
New policy is backstabbing yourself

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [audacity/audacity#1237]
**Describe the bug**
Your privacy policy is the bug.

**To Reproduce**
Hhmmmmm
Read your own privacy policy! It brakes the GPL2 License as previously said!

**Expected behavior**
Backstabbing yourself and losing millions of users. Also maintainers Do not Close this issue to hide. I can and WILL repost this.
Schools that use the software won't use it. Maybe add an opt in or opt out of data collection

**Additional information (please complete the following information):**
Fix it now

**Comment by inmicro** [comment]
I am switching to the libre audacity builds.

**Comment by sqlskid** [comment]
+rep imma use some fork of audacity

**Comment by julienmary** [comment]
It's incredible to see that repetitive behavior, consisting in trying to bend Open source spirit at preparing license type swap.
Each time, it's leading to a fork. But from time to time, we still see an idiot who convinced himself, that the community, this time, will react in a different fashion. LibreOffice, MariaDB, NextCloud ... are example of what's happening in those cases. Because it's just insupportable.

**Comment by zearp** [comment]
@JamesCrook Why don't you respond to any of the issues you close about the age restriction? These people are making a very valid point. Educational use will no longer be possible with the age restriction plus it breaks the GPL. But instead of addressing the issue you just close all related issues. I guess that tells us all we need to know.
