### ISSUE TITLE
Renaming clips

### ISSUE THREAD

**Issue by jounih** [audacity/audacity#1258]
### User Story
As a developer, I would like to know the UX details for implementing clip names and renaming.

### Description

Currently there is no concept of clip names in Audacity, only track names. Individual clip names are very useful when organising a project, or separating between copies or takes.

The new affordance UX has a space for a clip name top left, below are the designs which allow the user to change the clip name.

For keyboard navigation Tabbing should select a clip, and "Enter" could edit the clip name.

Audio/Midi clips:

![Clip names@2x](https://user-images.githubusercontent.com/10109867/126309380-68a8db34-691a-4eb7-a6ca-4efd0807d102.jpg)

Label clips:

Described here https://github.com/audacity/audacity/issues/1195

### Accessibility

Keyboard shortcuts for selecting and editing audio/midi clip names and label clip names should be identical. Tab to select/forward cycle selection, enter to edit currently selected.

Furthermore, they should both respect the accessibility preference for editing the name in a dialog: Tracks->Track Behaviours-> Use dialog for the name of a new label (Also this should be renamed to "Use dialog for the name of a new label or clip"

**Comment by DavidBailes** [comment]
Re: keyboard navigation:

1. Clip selection would be better than clip focus for renaming. For example, in file managers, if the focused and selected items are different and you press F2, then the name of the selected item is opened for editing. In addition, using the selected item (or items?) allows for the possibility of easily being able to rename multiple clips if that is ever required. If selection is used, then using tab is no longer appropriate.

2. However (!), proper selection of clips if not yet implemented. If this is still the case when renaming clips is implemented, as an alternative to the selected clip, you could use the clip which contains the cursor in the focused track. There already are commands for selecting (time range) next/previous clip, and commands for moving the cursor to next/previous clip boundary.

3. I'm assuming that a custom text box will be used for editing the clip name. Unfortunately, on Windows and using the wxWidgets accessibility framework this can't be made accessible for users of screen readers. So there will need to be the option of using a standard text box in a dialog box. Such an option is already present in Audacity for entering the name of a label when it's created. (Preferences-> Tracks Behaviors -> Use dialog for the name of a new label.)

4. Enter toggles the selectedness of the track, so another shortcut would have to be used for the rename clip command.

**Comment by Paul-Licameli** [comment]
Can this design really be considered done, @AnitaBats ?  David's points are unaddressed.

**Comment by jounih** [comment]
Will be reviewing David's feedback today @Paul-Licameli

**Comment by DavidBailes** [comment]
> 3. I'm assuming that a custom text box will be used for editing the clip name. Unfortunately, on Windows and using the wxWidgets accessibility framework this can't be made accessible for users of screen readers. So there will need to be the option of using a standard text box in a dialog box. Such an option is already present in Audacity for entering the name of a label when it's created. (Preferences-> Tracks Behaviors -> Use dialog for the name of a new label.)

Providing the option of using a standard text box in a dialog box will also provide a workaround for IME input. See https://bugzilla.audacityteam.org/show_bug.cgi?id=1804

**Comment by DavidBailes** [comment]
> Keyboard shortcuts for selecting and editing audio/midi clip names and label clip names should be identical. Tab to select/forward cycle selection, enter to edit currently selected.

The existing use of Tab and Shift + Tab in the label track is somewhat of an anomaly in Audacity. These shortcuts are hard coded - normally there are commands, possibly with default shortcuts, and the user is able to customize these shortcuts. Maybe part of the reason for this anomaly is that in all previous versions of Audacity, these shortcuts changed the focus, and so were felt to be appropriate.

However, for the actions of selecting the next/previous item in an audio or wave track I think it would be much better to have commands for these actions, so that their shortcuts can be customized. I don't think that Tab and Shift + Tab would make good default shortcuts for these commands, given that at some point there will probably be commands for selecting multiple items. For the Tab and Shift + Tab pair of shortcuts the Shift modifier indicates a change of direction. However when there are commands for selecting single items and for extending the selection, the Shift modifier is normally used to indicate extending the selection, rather than the direction. So for example in Reaper (at least when using the osara extension),  the shortcuts for selecting the next/previous clip are  Ctrl + right/left arrow, and the shortcuts for extending the clip selection forwards or backwards are Ctrl + Shift + right/left arrow.

I didn't notice that the design had been edited, otherwise I would have commented earlier.

**Comment by jounih** [comment]
@DavidBailes makes sense to have customisable commands for selecting clips and editing names rather than hardcode these shortcuts. @vsverchinsky can you do this please?

@DavidBailes I'm ok with ctrl/command + right/left arrow for selecting the next/previous clip if that's preferred, makes sense to add shift to that when extending the selection to multiple clips. 

Which keyboard shortcut would you prefer for editing the name, once the clip is selected?

**Comment by DavidBailes** [comment]
> @DavidBailes makes sense to have customisable commands for selecting clips and editing names rather than hardcode these shortcuts. @vsverchinsky can you do this please?

@Jouni. There are existing commands to select the next/previous clip (Alt + comma/period). As you've previously pointed out they don't change the state of the clip to selected, but they could be changed to do so.
Are you wanting to use different commands rather than modifying these existing commands?

Tantacrul mentioned somewhere (which I can no longer find) that he was working on a selection model for 3.1. Do you know if this is finished? It would be really useful to know what the big picture is for selection when thinking about the commands are needed for 3.1 so that all the new features are accessible for keyboard users.

> 
> I'm ok with ctrl/command + right/left arrow for selecting the next/previous clip if that's preferred, makes sense to add shift to that when extending the selection to multiple clips.

ctrl+right/left arrow wouldn't work at the moment because looking to the future when commands that extend the clip selection are added, ctrl+shift+left/right arrow are already used.
In addition if modified versions of the existing clip selection commands are used, we could just use the existing shortcuts (and alt + shift + comma/period are available).

As a slight aside, I appreciate with all the changes in Audacity, at some stage shortcuts may well need to be reassigned so that there's a coherent set of shortcuts for all the new functionality.

> 
> @DavidBailes Which keyboard shortcut would you prefer for editing the name, once the clip is selected?

Given that F2 is already taken, Ctrl + F2 may be as good as any.

> And which keyboard shortcut for selecting the first clip overall?

Could you expand on what you meant by that, I don't understand what you mean?

**Comment by Paul-Licameli** [comment]
See also issue #1644 -- the Set Clip command should now be extended to make clip name change available to macros
