### ISSUE TITLE
Update Preferences -> Application: updates

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1269]
User story
As a user of Audacity, I want to be able to opt-in / opt-out for the app updates so that I can decide whether I want to receive updates.

1. Add Check for the updates option checkbox to the Preferences -> Application
2. Default value is on
3. Privacy Policy should be mentioned in this doc

Details on the requirements and design will be added as soon as they are approved.

**Comment by OldYin** [comment]
I don't see any reason why this could not apply to crash reports too.

An open source mod tracker I use, opens up a dialogue on first use which give the user these options on one page. Can also be accessed through options at any time. 

Do I trust the developers? Absolutely because they have been up-front and open.
Am I more likely to opt in to allow crash reports to be sent? Hell yes.

**Comment by petersampsonaudacity** [comment]
This is the case in 3.0.3
