### ISSUE TITLE
Use monitor refresh rate for play head/track moving

### ISSUE THREAD

**Issue by HeyBanditoz** [audacity/audacity#1278]
**Is your feature request related to a problem? Please describe.**
The play head and/or track scrolls slowly across the window, making it jittery if using a higher refresh rate monitor.

**Describe the solution you'd like**
The window to scroll at the speed of the monitor's refresh rate.

**Describe alternatives you've considered**
N/A

**Additional context**
Attached is a video illustrating the problem. (It may be best to download the video and play it on a 144 fps monitor to best illustrate the issue, some browsers might not like it.)
https://user-images.githubusercontent.com/7574664/125233202-52afe700-e29b-11eb-91b2-ab2125c073fb.mp4

**Comment by qubodup** [comment]
Ideally this would be configurable, as not everyone will want to use the max visible refresh rate, since it impacts CPU use quite a bit and 240 fps is becoming common on gaming screens. Some discussion in https://forum.audacityteam.org/viewtopic.php?f=46&t=124660

The meter panel allows configuring refresh rate already https://github.com/audacity/audacity/blob/698f8aea2747ac6a423111e55064136be78d1ac0/src/widgets/MeterPanel.cpp - perhaps some of this can be re-used.

Not sure where the refresh code is for the timeline though. Perhaps the "30" in registeredStatusWidthFunction in https://github.com/audacity/audacity/blob/a92a9c5b04693249d3ed4b820cb37b640a40f55b/src/tracks/ui/Scrubbing.cpp ...

**Comment by LWinterberg** [comment]
closing in favor of https://github.com/audacity/audacity/issues/2289
