### ISSUE TITLE
On Windows what Inbound and Outbound firewall rules need to be set-up to block telemetry?

### ISSUE THREAD

**Issue by Myron-S** [audacity/audacity#1351]
On Windows what Inbound and Outbound firewall rules need to be set-up to block telemetry?

**Comment by SteveDaulton** [comment]
For versions of Audacity up to and  including Audacity 3.0.2, you don't need any because those versions of Audacity don't have any networking / telemetry / or anything like that.

I think that Audacity  3.0.3, when it becomes available, will have:
1. Update checking
2.  Crash reporting
(both are disabled by default if you build from source, so this only applies to the pre-built "executable" versions)

Crash reporting isn't an issue because nothing gets sent without asking you first. If you don't want to send a crash report, then simply  click  the "Don't Send" button. (but note that sending crash reports can help the Audacity developers to debug and fix problems)

To completely disable update checking:
1. Temporarily disconnect from the Internet,
2. Install Audacity.
3. When Audacity launches, go to:
Windows: "Edit menu > Preferences > Application" and uncheck the "Check for updates" option.
macOS: "Audacity menu > Preferences > Application" and uncheck the "Check for updates" option.
4. You can now re-enable your Internet connection.

Note that this has no affect on telemetry, crash reporting or update settings for any other app -  for other apps you will need to check their documentation.

Since you asked about firewall rules, yes I believe that  you can block updates and crash report sending with the Windows firewall (though not  necessary with the above steps). I'm no expert on the Windows firewall, but  I found these instructions: https://www.howtogeek.com/227093/how-to-block-an-application-from-accessing-the-internet-with-windows-firewall/

**Comment by SteveDaulton** [comment]
Update:
Further to my previous reply, the Audacity desktop app privacy notice was updated today (22nd July 2021).
https://www.audacityteam.org/about/desktop-privacy-notice/

(The privacy notice says what data is sent from Audacity, for what purpose, and what happens to that data.)

PS. If you decide to disable or block update checking in future  versions of Audacity, you can manually check if updates are available by visiting the download page of the official Audacity website: https://www.audacityteam.org/download/

**Comment by Myron-S** [comment]
>     2\. (both are disabled by default if you build from source, so this only applies to the pre-built "executable" versions)

Thanks for the info.  Right, I'm a newbie regarding compiling from GitHub source.

Exactly what do I need to do to compile the source myself?  I got Windows 10 with Visual Studio Community Edition installed and also got a fully working WSL2 Ubuntu with Xfce desktop usable by RDP and/or X10.

**Comment by SteveDaulton** [comment]
Personally I wouldn't bother building on Windows unless you have to. A standard Windows installation lacks a "build environment" and requires many big downloads and updates to set up the build environment - that's the hardest part of building on Windows, and it can easily go wrong even for developers.

Building on Linux  is much  easier, but  you still need to follow the instructions very carefully. The instructions are included in the source code here: https://github.com/audacity/audacity/blob/master/BUILDING.md

I've never used WSL2, so I've no idea if there are any gotchas that could cause problems. If you have a spare hdd or old computer available, I'd recommend setting up a proper Xubuntu installation for building (or create a partition so that you can dual boot Windows / Linux.
(Xubuntu is Ubuntu with Xfce, and is a good choice for building. It's a lot lighter than the standard Ubuntu, but still has access to all of Ubuntu's software repository.)

Note that the current Audacity code is between versions ("alpha") so may have bugs /  incomplete  features and should not be used for production work. To  build a version for actual use (rather than just testing), download the most recent source code from the "Releases" section of GitHub: https://github.com/audacity/audacity/releases/tag/Audacity-3.0.2

If you run into difficulties and need help building, try posting to this section of  the community help forum: https://forum.audacityteam.org/viewforum.php?f=19

By the way, I've just tested the most recent alpha version of Audacity 3.0.3, and was pleased to see that on first run, you are informed about update checking (an unmissable pop-up dialog) and can enable / disable update checking before Audacity does it's first check (no need to disconnect from the Internet). The pop-up is still a bit rough around the edges, but reassuring to see it's there.

**Comment by petersampsonaudacity** [comment]
@Myron-S  - See these sections from the alpha manual for 3.0.3 What's New page:
https://alphamanual.audacityteam.org/man/New_features_in_this_release#updates
