### ISSUE TITLE
Shortcut Instead Brings Up Keyboard Preferences Dialog

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#1358]
There are two reports on the forum for MacOS users where trying to use a keyboard shortcut will instead bring up the Keyboard Preferences Dialog.

See: https://forum.audacityteam.org/viewtopic.php?f=70&t=119343
and: https://forum.audacityteam.org/viewtopic.php?p=410469#p410469

**Comment by petersampsonaudacity** [comment]
I do not get this on SW10  with 3.0.2 or 3.0.3 RC3

**Comment by JohnColket** [comment]
Note that this bug was originally reported on Bugzilla under Linux, but was closed April 26th of this year as "Works For Me" after not seeing it for over a year. See https://bugzilla.audacityteam.org/show_bug.cgi?id=2253

Note that most the most recent reports are under 3.0.2 on MacOS and also on Windows.

**Comment by petersampsonaudacity** [comment]
This was logged originally on Bugzilla, closed and then reopened>
https://bugzilla.audacityteam.org/show_bug.cgi?id=2253
Bug 2253 - Mac/Linux: Keyboard Shortcut Preferences may open unexpectedly

Paul Licameli wrote in the big thread.
>I think it's because of the code controlled by EXPERIMENTAL_EASY_CHANGE_KEY_BINDINGS
>
>The intent was to take you to keyboard preferences only when you shift+click in a menu item of the the main toolbar.
>
>I don't understand how you get there without opening a menu.
>
>If this is it, we could consider disabling this feature on Linux, or we could make the code implementing this test 
>that control is also not down.

James Crook wrote later in the bug thread
>If not a Heisenbug on Macbook Air macOS 11.4, then it's P2 not P4, and RM should decide whether it should 
>block release or not.  
>The problem for sure is quite unnecessary, given Paul's comment

**Comment by petersampsonaudacity** [comment]
This bug is a regression on 2.2.1

**Comment by Paul-Licameli** [comment]
Remember this feature:  you can hold Shift while releasing a toolbar menu item, and go to Keyboard Preferences to change the hotkey of the item (instead of doing the command).

I added that in 2018, but it is mis-firing on Mac sometimes when there are shortcuts with Shift in them.

Quick fix might be just to eliminate my little known feature.

**Comment by Tantacrul** [comment]
@Paul-Licameli believes this has been caused by his inclusion of a Shift modifier to help users jump to a keyboard shortcut preference quickly.

After discussing it, neither of us feels this modifier is especially discoverable and perhaps we can simply remove it (to fix this bug) and focus more on improving the usability of shortcuts in the medium term

**Comment by petersampsonaudacity** [comment]
I would vote for removing this little-know feature
