### ISSUE TITLE
Jack Audio System unavailable with AppImage

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1360]
**Describe the bug**
"Jack Audio System" does not appear as a "host" option when Jack is running

**To Reproduce**
1. Start Jack
2. Launch Audacity
3. Try to select "Jack Audio System" as "host" in the "Device Toolbar"
4. Observe that the only host option is "ALSA"

**Expected behavior**
"Jack Audio  System" should be available as "host" when Jack is running.

**Additional information (please complete the following information):**
 - OS: Xubuntu  20.04
 - Version: Audacity RC3 AppImage

**Comment by falkTX** [comment]
Word of caution, because so many get this wrong.
Please do not ship with libjack.so*, as libjack needs to be in sync with the jack server.
Let it be found during runtime.

**Comment by shoogle** [comment]
@falkTX, thanks for the hint! Though we depend on `libjack.so*` we might run into this issue:

- __Bundle `libjack.so*`__ - application starts but Jack doesn't work (like you said)
- __Don't bundle `libjack.so*`__ - Jack works when available on the system, but when Jack isn't available the application refuses to start at all

The solution we found on MuseScore was to [bundle `libjack.so*`](https://github.com/musescore/MuseScore/blob/e914f0fabd9837127ac65f750f91f2bdc29956b8/build/Linux%2BBSD/portable/Recipe#L281-L291) in a special ["fallback" directory](https://github.com/musescore/MuseScore/blob/e914f0fabd9837127ac65f750f91f2bdc29956b8/build/Linux%2BBSD/portable/Recipe#L237-L255) within the AppImage that is only [added to `LD_LIBRARY_PATH` at runtime if `libjack.so*` is not found on the system](https://github.com/musescore/MuseScore/blob/e914f0fabd9837127ac65f750f91f2bdc29956b8/build/Linux%2BBSD/portable/AppRun.in#L9-L23).

But it's getting a bit late to try adding this to 3.0.3 without proper testing. The AppImage is new, so it might be better to accept that it lacks one or two features rather than doing something that could potentially cause it to not start at all on some systems, then we can investigate and properly fix the issue in time for the next release.

**Comment by falkTX** [comment]
There is an alternative, use something alike https://github.com/x42/weakjack/.
weakjack being GPL doesnt fit into audacity as a dependency though.

Feel free to use the code I have at https://github.com/DISTRHO/DPF/tree/develop/distrho/src/jackbridge which is more liberally licensed.
The commit that add it kinda explains the setup https://github.com/DISTRHO/DPF/commit/a4f511c6189fe37e6c22e2d3e16f1c84e490a413
(Basically jack_* calls are replaced with jackbridge_* ones, which can be configured at build time what they do - link to jack directly, dlopen/dlsym jack on start, or dummy/nothing)

**Comment by crsib** [comment]
>GPL doesnt fit into audacity as a dependency though.

There are no issues with GPL dependencies. Though thank you for offering your library :)

However, problem is that Audacity uses Jack via PortAudio. The vendored version of PA had a hack, that allowed dynamic Jack loading, which no longer compiles :( So it looks like a hack will be quite a bit more complex.

**Comment by falkTX** [comment]
Right, it would involve changing PortAudio.

Since Audacity + PortAudio current use for JACK is quite broken (in terms of expectations on how a JACK client is supposed to behave, there is a ticket already about this) it might be best to just do a brand new implementation for native JACK support instead.

**Comment by crsib** [comment]
This issue was fixed quite some time ago. I have just verified - generally Jack can be used, the requirement is to have a system version of PortAudio installed. @LWinterberg probably it is worth mentioning somewhere in the docs
