### ISSUE TITLE
Option to export & overwrite current file

### ISSUE THREAD

**Issue by alex-tee** [audacity/audacity#1383]
**Is your feature request related to a problem? Please describe.**
There should be an option to overwrite the current file (like in GIMP -> File -> Overwrite)

**Describe the solution you'd like**
Add an option to "Overwrite", or at least make the export dialog location default to the directory the file is in.

**Describe alternatives you've considered**
Manually looking for the directory the file is in to overwrite it. This is bad UX

**Additional context**
Since audacity allows you to open multiple files, perhaps add this option in the dropdown next to the file:
![Screenshot from 2021-07-29 13-53-14](https://user-images.githubusercontent.com/3407655/127495471-07b86c13-3e88-455f-8495-899e06670dd1.png)

If you think it shouldn't be easy to overwrite files to avoid mistakes, then you could add a confirmation dialog "are you sure you want to overwrite this file?"

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.0.3 I can already overwrote an existing audio file - and I get a warning message when trying to do so:

![image](https://user-images.githubusercontent.com/50205984/127778322-97509548-b5b7-4cfe-ad80-d1eb1c31f601.png)

**Comment by alex-tee** [comment]
@petersampsonaudacity is there an option to overwrite the file or did you have to click "export" and then find the file? my request is about having a quick option to overwrite the opened file without having to click export + browse

**Comment by petersampsonaudacity** [comment]
> 
> 
> @petersampsonaudacity is there an option to overwrite the file or did you have to click "export" and then find the file? my request is about having a quick option to overwrite the opened file without having to click export + browse

I had to find the file to overwrite it.

But for me that's expected behavior:
a) by default Audacity will use the last-used location for Exports when it Exports
b) alternatively you can set a preferred location in Directories Preferences

So with a) default settings

1) Import a file from <location path>
2) edit it
3) Export it (in the same format
4) Observe same filename as in step 1
5) Observe: offered path location if this is your first save) is ...Documents\Audacity on Win (or just ...Documents in Mac or Linux) - OR
6) Observe if you have exported previously the offered path location is your last-used
7) navigate to your location from step 1
8) Export the file 
9) OK the overwrite warning
10) Edit the file some more
11) Export it again
12) Observe this time the path location is your last-used i.e. the path from step 7 - but this is now the same path as in step 1

The underlying issue here is that Audacity is designed as an audio editor, NOT an audio file editor - it is not designed as a WAV editor or an MP3 editor etc,

Note that when you import an audio file for editing that Audacity is not operating on that file per se - but rather it works on it's own internal copy of the audio converted to its own internal project format AUP3 (actually a SQLite database).

For details of the Directories preferences settings see:  https://manual.audacityteam.org/man/directories_preferences.html

**Comment by alex-tee** [comment]
>The underlying issue here is that Audacity is designed as an audio editor, NOT an audio file editor - it is not designed as a WAV editor or an MP3 editor etc,

>Note that when you import an audio file for editing that Audacity is not operating on that file per se - but rather it works on it's own internal copy of the audio converted to its own internal project format AUP3 (actually a SQLite database).

ok thanks, it makes sense. it sounds like Audacity doesn't even remember the path of other imported file since it uses its own copy. I'll close the issue then

**Comment by petersampsonaudacity** [comment]
@alex-tee  - oh yes, Audacity does remember the import path used and it will re-use that by default the next time you import (unless you have set a default import path in Directories prefs).

The problem for you, you request is that Audacity has separate remembered paths for import and for export - the two are not combined or linked.

**Comment by alex-tee** [comment]
my actual use case is actually a bit more advanced than a user wishing to overwrite an imported file. I have a DAW and I have an option to edit some audio with audacity. I can already manage to open audacity with the given file but the user is expected to overwrite the file and exit audacity. currently, this means that the user should go to export and navigate to where the file is (some random directory in `/tmp`) and this is tedious. I want to suggest a command line option to help in this case but I'll make a separate issue for it in the future

**Comment by SteveDaulton** [comment]
> this means that the user should go to export and navigate to where the file is (some random directory in `/tmp`) and this is tedious.

You could use a Nyquist-Macro to do the export (reading the location of the last imported file from Audacity "preferences" file ("audacity.cfg"). I think there's already a macro available on the Audacity forum - I'll see if I can find it.

**Comment by SteveDaulton** [comment]
>  I think there's already a macro available on the Audacity forum - I'll see if I can find it.

Here: https://forum.audacityteam.org/viewtopic.php?p=422002#p422002

**Comment by alex-tee** [comment]
@SteveDaulton awesome, thanks! I'll add this to our user manual

**Comment by petersampsonaudacity** [comment]
@alex-tee  - and to make life even simpler you could set up a custom shortcut for the Macro.

See:  https://manual.audacityteam.org/man/keyboard_preferences.html#custom
