### ISSUE TITLE
Track resampling affects to track speed

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1386]
**Describe the bug**
Track resampling works incorrectly

**To Reproduce**

1. Launch Audacity
2. Change rate in audio-interface settings
3. Click Play in Audacity

**Expected result:** Track rate has changed correctly and does not affect track speed.
Actual Result: Track speed had been changed
Win 10
Audacity 3.0.3.
Focusrite Scarlett 2i2

https://user-images.githubusercontent.com/25851359/127655827-c7798f6e-cbdf-409d-806c-79c42271391b.mp4

**Comment by SteveDaulton** [comment]
When you change the "track rate" (from the track's drop down menu) the length of the track **_should_** change, because you are NOT resampling, you are only changing the track's properties.

Example: 
If the track's sample rate is 100 Hz, then samples will be spaced at intervals of 1/100th second.
If there are 200 samples in the track, then the length of the track  will be 2 seconds.
If you change the track's sample rate (without resampling) to 200 Hz, then the samples will be spaced at intervals of 1/200th second, and the length will now be 1 second.

If you want to resample the track to a sample rate of 200 Hz, then:
1. Select the track
2. "Tracks menu > Resample" and set the rate to 200.

**Comment by AnitaBats** [comment]
It seems to be an UX issue rather than a bug. Needs some UX/UI work

**Comment by LWinterberg** [comment]
We have a design for resampling from the track header in Qt, this bug is no longer needed
