### ISSUE TITLE
build failure in Raspberry Pi OS

### ISSUE THREAD

**Issue by djsg** [audacity/audacity#1390]
**Describe the bug**
Raspberry OS is an Linux variant, so I follow the Linux section in BUILDING.md
Error occurs in step 2: cmake -G "Unix Makefiles" -Daudacity_use_ffmpeg=loaded ../audacity

ERROR: Not able to automatically detect '/usr/bin/cc' version
ERROR: Unable to find a working compiler
WARN: wxwidgets/3.1.3.1-audacity: requirement expat/2.2.9 overridden by your conanfile to expat/2.2.9@audacity/stable 
wxwidgets/3.1.3.1-audacity: ERROR: while executing system_requirements(): local variable 'arch_suffix' referenced before assignment
ERROR: Error in system requirements
CMake Error at cmake-proxies/cmake-modules/conan.cmake:631 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:233 (conan_cmake_install)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:254 (_conan_install)
  CMakeLists.txt:509 (resolve_conan_dependencies)

**Additional information (please complete the following information):**
 - OS: Raspberry OS
 - Version: Audacity 3.0.3
[CMakeError.log](https://github.com/audacity/audacity/files/6911111/CMakeError.log)
[CMakeOutput.log](https://github.com/audacity/audacity/files/6911112/CMakeOutput.log)

 
**Additional context**
My gcc version meets requirement.

**Comment by djsg** [comment]
BTW, I successfully built 3.0.2 Release version under Raspberry OS; however, failed at "make" 3.0.2 debug version.
I was told to try 3.0.3.

**Comment by djsg** [comment]
I want to contribute by trying debug myself. I am not sure where to start. Is there any document I can refer to with regard to this Audacity code structure and build environment?
I have been doing programming for many years, familiar with c/c++; but I have little knowledge on audio part including device drivers, audio apps.

**Comment by djshaw** [comment]
@djsg, were you able to resolve the issue? I'm attempting to compile a subset of Audacity on the raspberry pi and I'm getting the same error.

**Comment by djsg** [comment]
No, I haven't. The Audacity build system is quite complicated. Don't know where to start.

**Comment by djshaw** [comment]
Thanks for getting back to me so quickly. I was able to investigate a little bit, and I think I found something useful:

I found that the error is in the conan-wxWidgets project, https://github.com/bincrafters/conan-wxwidgets/blob/testing/3.1.3/conanfile.py#L107. `system_requirements()` is only accounting for x86 and x64 systems. I found that if I add a case for `arm`, I'm able to proceed:

    elif self.settings.arch == 'armv7':
        arch_suffix = ':armhf'

This probably needs a check for `armv8`. I assume the `arch_suffix` for it would be `:arm64`. 

The build takes an excruciatingly long time on my raspberry pi 3b+. Get a coffee after invoking the build.

I had to stop monitoring the build. My custom utility compiles, so I'm happy. I'm running a full Audacity build to see what happens.  Make reports that it's 75% done, so maybe it will finish successfully.

I do not know what the correct course of action will be. I think patching `connan-wxWidgets` is probably the best course of action. We can also consider applying a patch before the conan build is called. (Though because a raspberry pi build isn't officially supported, the later option should be even more unlikely). I'm not familiar with conan--I should probably familiarize myself with the conan idioms.

**Comment by djsg** [comment]
That's great news. Nice work.
In fact I didn't have time to work on this since I last reported. My plan B is to use a Windows system.
If I have time, I will try what you have done.

**Comment by djshaw** [comment]
After a lot of waiting, I can say that my pi compiled Audacity. When you compile, you might run out of space on `/tmp`. I set the build TMP to . with `TMP=. make`, and I suspect that you'll have to do the same. I am working on a 3B+. I hope you're working on a 4. 

Because I'm running on a headless machine, I am not able to verify that Audacity runs on my pi.

**Comment by djsg** [comment]
Yes, mine is Pi 4 Model B.

**Comment by djsg** [comment]
In fact my original problem with Audacity in Pi is when I turn on Transport --> Transport Options --> Software Playthrough,
Audacity will crash.
I wonder for your successfully compiled Audacity, does it still happen? I guess it still happens.
