### ISSUE TITLE
Range selection does not work in affordance area

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1427]

**Comment by petersampsonaudacity** [comment]
Why would you expect it to?

When the cursor is over the Clip-handle drag-bar the cursor changes to the open hand which is the affordance to indicate that you can click and drag to move/drag  - NOT click and select.

**Comment by vsverchinsky** [comment]
Sorry, a bad wording from my side. When selection tool is active it's not possible to start selection when cursor is over empty affordance area (where no clips at all)
![image](https://user-images.githubusercontent.com/20165230/128239078-5a596da0-d070-4012-970f-540dfc2c4ede.png)

**Comment by petersampsonaudacity** [comment]
> When selection tool is active it's not possible to start selection when cursor is over empty affordance area (where no clips at all)

Ah I see what you mean - there is a visual cue to the user:
a) when the cursor is over the waveform area the cursor is the I-beam (default tool setting) - indicating selection is available
b) when you move the cursor into the space where the Clip-handle drag bars could be dragged the cursor changes to the default Widows broad white arrow - indicating selection is not possible from there.

Since all the space above the waveform for the Clip-handle drag bars is really only usable by the drag bars, what I would suggest is partitioning that part of the track off with a thin black line.  That would alos have the avdantage of a visual cue suggesting that the user can slide/drag the drag bars along horizontally.  See mockup:

![image](https://user-images.githubusercontent.com/50205984/128318380-3a22745d-f36e-4e3d-b91e-23c08feac98e.png)

@Tantacrul  and @jounih  - as the UX specialists on the team what are your thoughts on this please?

**Comment by Tantacrul** [comment]
> @Tantacrul and @jounih - as the UX/GUI specialists on the team what are your thoughts on this please?

I would be careful about trying to make changes to try and solve this potential issue until we've tested it in the wild. It may be the case that users don't experience this problem.

If they do, I can think of a few interesting ideas but I won't try articulate them here.

**Comment by petersampsonaudacity** [comment]
@Tantacrul I don't actually see a real problem here anyway - for me the visual cue of the change of cursor icon is sufficient.

As a user I wouldn't dream of trying to start a selection while my cursor was in that dead space without the I-beam selection cursor/tool showing.

I would be surprised if we ever get user complaints about this.

**Comment by Tantacrul** [comment]
@petersampsonaudacity - a related issue: we are planning on allowing users to multi-select clips as well as select wave data, so selection will need to be revisited holistically anyway. I'll be working on designs for this over the next 2-3 weeks.

**Comment by petersampsonaudacity** [comment]
And the GUI makes it entirely clear that the Clip-handle drag-bars do not participate in the selectiom:

![image](https://user-images.githubusercontent.com/50205984/128630707-3b32ffe2-5699-4a3b-938d-1be4b683d1b0.png)

**Comment by Penikov** [comment]
Please, note this specific behaviour, depends on the region that the cursor points to:



https://user-images.githubusercontent.com/25851359/135601730-7d9ae8d9-469e-47ff-affd-f8dfbf47cd3a.mp4


@LWinterberg Do we have this behaviour described in the latest manual version?
