### ISSUE TITLE
Windows: NVDA screen reader not speaking typed characters

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1562]
**Describe the bug**
In certain parts of the main window, nvda is not speaking the typed characters:
- typing numbers into the time controls in the selection bar
- on tracks, not speaking a character if it is a command - for example, j,k,[ or ].
- on a label track not speaking characters typed into a label.

The TimeText controls in Analyze > Contrast... are also affected.

This is due to changes in the handling of wxKeyEvents in 2.1.2.

Does not happen in timetext controls, for shortcuts, and for label text.

This was originally logged on Bugzilla as P3 1245
https://bugzilla.audacityteam.org/show_bug.cgi?id=1245

**To Reproduce**
1. Try reading characters as they are typed in, using NVDA.

**Expected behavior**
NVDA to read the characters as they are typed

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 
 - Version Audacity 3.0.4 and earlier

**Additional context**
David Bailes wrote on Bugzilla:
>I've discovered that nvda does not speak typed a character anywhere in the main window if it is a command.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
