### ISSUE TITLE
Track Spectrogram settings may change global preferences

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1567]
**Describe the bug**
When the preference "Use half-wave display when collapsed" is enabled and the track is collapsed, the Max frequency changes to 22050 Hz as well and in turn, the vertical scale displays a wrong value.

**Steps To Reproduce** (updated as of 3.4.2)

1. Generate some noise
2. Change the track to "Spectrogram" view
3. Open up Spectrogram settings and set "Max Frequency" = 8000 Hz
4. Enable preference Tracks->Use half-wave display when collapsed.
5. Collapse the track
6. See the vertical frequency scale value
7. Open up Spectrogram settings and see the Max Frequency value out there

**Actual Behavior**
6. 10000 is displayed
<img width="300" alt="image" src="https://github.com/audacity/audacity/assets/70063970/3fa94631-3c33-43d2-8f6d-dcf4d447c5db">
7. 22050 Hz is the new Max Frequency value

**Expected Behavior**
6. Half of the Max Frequency value, i.e. 4000
7. Max Freq is still 8000 Hz

**Additional information (please complete the following information):**
 - OS: all OS
 - Version: Audacity 3.4.2

**Additional context**
Steve wrote in GitHub:
>Individual track options should have a scope that is limited to the individual track and should never cause global preferences to change.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
