### ISSUE TITLE
Spectral Selection center frequency dragging issues

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1574]
**Describe the bug**
Spectral Selection center frequency dragging issues

Originally logged as Bugzilla P3 2370
https://bugzilla.audacityteam.org/show_bug.cgi?id=2370

**To Reproduce**
1. Make a chirp
2. Switch to spectral view and enable spectral selection
3. Make a spectral selection from 1KHz to 3KHz (approx)
4. Attempt to drag the centre frequency up and down
5. Observe:   It only moves in very big jumps, e.g. to about 9KHz, without going through intermediate values.

**Expected behavior**
See https://bugzilla.audacityteam.org/show_bug.cgi?id=2370
for detailed discussion thread

**Screenshots**

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
See https://bugzilla.audacityteam.org/show_bug.cgi?id=2370
for detailed discussion thread

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
