### ISSUE TITLE
Orca issues on Linux

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1610]
**Describe the bug**
There were three Orca accessibility issues previously logged on Bugzilla:

1.  P3 Bug 727 - Linux: Orca: Tracks not read
https://bugzilla.audacityteam.org/show_bug.cgi?id=727

2. P3 Bug 853 - Linux: Orca: Many plugin labels not read
https://bugzilla.audacityteam.org/show_bug.cgi?id=853

3. P3 Bug 1256 - Linux: Orca: Keyboard Preferences bindings list not read
https://bugzilla.audacityteam.org/show_bug.cgi?id=1256https://bugzilla.audacityteam.org/show_bug.cgi?id=1256 

**To Reproduce**

**Expected behavior**
Audacity should oroperly handle reading through Orca on Linux

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Linux
 - Version: all Audacity
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
See Bugzilla bugthreads for details

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
