### ISSUE TITLE
Double right-click on the clip drag bar makes a clip selected

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1659]
**Describe the bug**
Double right-click on the clip drag bar makes a clip selected.

**To Reproduce**

1. Add a new audio-track
2. Add some audio clips
3. Select one clip as usual by left mouse click
4. make a double right-click on the clip drag bar of another clip

**Expected behaviour**
Nothing happens

**Actual behaviour**
Another clip is selecting by double right-click

**Additional information (please complete the following information):**
 - OS: all OSes
 - Version 3.1 +

**Comment by petersampsonaudacity** [comment]
As @SteveDaulton  pointed out elsewhere double-right click is an undefined function and thus is is correct the the user should expect no action with that gesture.

It also means, as it stands, that the user may inadvertently lose a carefully made selection elsewhere in their project.

**Comment by Penikov** [comment]
I think binding mouse keys would be the best option there. A user can change mouse bindings in almost all modern applications and video games. E.g. Blender has a weird binding for the model rotating action. But any user can change it. I believe there are a lot of users who are demanding the binding mouse keys option. 
But this is a too complicated thing to be solved instantly. So in this Issue,  we could revert right-mouse double click.
BTW, I can add a feature request for mouse keys binding and we could discuss it there )

**Comment by petersampsonaudacity** [comment]
> I can add a feature request for mouse keys binding and we could discuss it there

I think that would be good.

There is a long-standing Feature Request in the Audacity Wiki for configurable mouse bindings - it had garnered 18 votes by 12Mar 19 (not quite enough to lift it into the **Highest-rated Feature Requests** table:
https://wiki.audacityteam.org/wiki/Feature_Requests#Highest-rated_Feature_Requests
But if I add your vote and my vote that would take it to 20 and make it into the table.

Also apart from the recorded votes I recall many other posters on the Forum over the years wanting customized mouse bindings.

It is something that Old-Team considered over the years, but never got around to doing because as @Penikov points out the "binding feature is a too complicated thing to be solved instantly".

**Comment by petersampsonaudacity** [comment]
But note that if you decide to leave the double right-click gesture on Clip-handles than it should be properly documented in the Manual - and _**not**_ just left as an Easter-egg _(just another bear-trap for the unwary)_.

**Comment by petersampsonaudacity** [comment]
@LWinterberg testing on W10 with 3.1.3 and latest 3.2.0 alpha master audacity-win-3.2.0-alpha-20220608+a2b9986-x64-msvc2022

This is no longer the case so this has been "fixed" by some other change ...
