### ISSUE TITLE
Windows: WDM/KS support

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1718]
**Is your feature request related to a problem? Please describe.**
This is an enhancement request transferred here from Bugzilla: 
https://bugzilla.audacityteam.org/show_bug.cgi?id=1973

**Describe the solution you'd like**
Support in Audacity on Windows for WDM/KS as an audio host

**Describe alternatives you've considered**
WDM/KS was supported in 2.0.4 but removed from 2.0.5 and onwards

**Additional context**
WDM/KS support was withdrawn for 2.0.5 and onwards as:
a) many sound-cards were found to be buggy with WDM/KS (at the time) leading to crashes/ Blue-Screen-Of-Death
b) old Team did not have sufficient manpower to address the issue
c) hence support for it was removed

I retested WDM/KS today as a host by running 2.0.4 on my W10 laptop and it worked fine for both recording (from onboard mic) and playback.

@Steve wrote in this Forum thread in November 2018
https://forum.audacityteam.org/viewtopic.php?f=46&t=102236&p=358100&hilit=WDM%2FKS#p358100
>WDM-KS is again very old technology (introduced in Win 98. I think, like DirectSound, it is emulated in current versions of Windows.

**Comment by petersampsonaudacity** [comment]
@SteveDaulton wrrote in this Forum post in November 2018
https://forum.audacityteam.org/viewtopic.php?f=46&t=102236&p=358100&hilit=WDM%2FKS#p358100
>WDM-KS is again very old technology (introduced in Win 98. I think, like DirectSound, it is emulated in current versions of Windows.  A long time ago, support for WDM-KS was enabled in Audacity, but at that time WDM-KS support in sound card drivers was frequently unstable, resulting in a surge of BSOD problems on some machines. 


Gale Andrews wrote in this Forum post in July 2015
https://forum.audacityteam.org/viewtopic.php?p=282259#p282259
>The last time we released Audacity with WDM-KS (2.0.4) there were almost 500 users who reported freezes or blue screens that I almost single-handedly dealt with. I will not do that again - even the developers agree with me about that. We simply do not have the resources, without some automated support system.  
There were about 10000 downloads of the unofficial 2.0.4 release "without WDM-KS" that I posted. So clearly large numbers of users were affected, even though it is a small proportion of the total. WDM-KS is useful, because it allows users of some hardware to record 24-bit or multi-channel, and has low latency, but it is an old API and likely to become increasingly incompatible.

**Comment by petersampsonaudacity** [comment]
@crsib wrote on Discord:
>we can actually support WDM/KS now, but we need to make error messages better first

**Comment by werame** [comment]
Frankly it's probably not a great idea. MSFT itself doesn't encourage its use due direct exposure to driver bugs that WASAPI otherwise papers over. There was at least one such report on the Audacity forum, although I can't easily re-find it right now. [It was](https://wiki.hydrogenaudio.org/index.php?title=Foobar2000:Components_0.9/Kernel_Streaming_Output_(foo_out_ks)) actually a bug in the audio drivers the person was using, not "in Windows", as they thought. 

> With certain soundcards, Kernel Streaming mutes all other sounds while playing. However, this behavior entirely depends on soundcard driver implementation details and varies between soundcards. If you need all other sounds muted, consider using WASAPI instead.

One can debug such issues with the MSFT-provided [KsStudio](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/ksstudio-utility), but without access to the driver source code, one can't fix them. Never mind the target audience for that tool. But with access to the hardware and driver, one can tell customers "not our bug". But that's probably not a real solution if you can't access the customer's computer.

**Comment by petersampsonaudacity** [comment]
> @crsib wrote on Discord:
> 
> > we can actually support WDM/KS now, but we need to make error messages better first

I really don't see the point - I can recall of no-one in past years on Forum or feedback@ (or more recently on GitHub or Discord) asking us to provide support for WDM/KS as a host for Windows.

**Comment by petersampsonaudacity** [comment]
> we can actually support WDM/KS now, but we need to make error messages better first

Ideally we would need no errors, no BSODs and **_not_** just better error messages

**Comment by LWinterberg** [comment]
What exactly would be the benefit of supporting WDM/KS? Because right now, the pro/con list seems to be: 

```diff
- it can crash/BSOD your PC
- it is very old
- nobody has asked for it in the past many years

o it used to work in the past

+ nothing?
```

**Comment by LWinterberg** [comment]
Alright, in that case, let's just not have it then.

**Comment by mirh** [comment]
WDM-KS isn't "old" and it is in fact what WASAPI currently uses behind the scenes. 
https://github.com/dechamps/FlexASIO/blob/master/BACKENDS.md#wdm-ks-backend
I don't know how much of that "500 bsods" figure is metaphorical, but be it improvements in portaudio's code or be it the fact that now everybody and their aunt is using WaveRT (i.e. the new revision introduced in Vista) but I'm not aware of such catastrophic scenarios. 

Then yes, in the current year of the lord there isn't exactly \*that much\* of a reason to go at such great lengths (especially if your device did happen to support modern `IAudioClient3` low latency audio, something that I still haven't seen confirmed anywhere though) but that's pretty much your ticket to get native ASIO-like features on every single pc.

**Comment by SteveDaulton** [comment]
"WDM KS" and "kernel streaming" are not the same  thing. "WDM KS" is indeed old, dating back to Windows 98, but it is still one of the front ends supplied by Windows. I used extensively with Windows XP as there were excellent drivers available for my sound card, but it generally fell out of favour towards the end of the 20th c. due to  gaining a terrible reputation for BSOD crashes, and rising popularity of ASIO.

I rarely use Windows these days, but my impression is that it has better driver support these days than it had then, and that Windows has become much more resistant to BSOD crashes.
