### ISSUE TITLE
Add GitHub workflow to build Linux system packages

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#1786]

**Comment by ericfont** [comment]
sorry to chime in but have you considered the cross platform open source package manager vcpkg?  Looking through some of audacity dependencies I see the following libraries are supported for x64-linux:

portaudio v19.7
ffmpeg v4.4
gtk v4.3.0
jack2 v1.9.19
libuuid v1.0.3

but unfortunately their wxwidgets v3.1.5 package works on all other platforms except linux (I don't know what that issue is but I would expect it be resolved sometime).  And I don't see any asound2 package, though they do support rtaudio[asio] v2021-08-15 and portaudio v19.7.

Then using a github action (https://github.com/marketplace/actions/run-vcpkg) it is easy to cache built vcpkg libraries.

But sorry if I my comment is irrelevant, in which case you can delete this and ignore it.
