### ISSUE TITLE
Toggle Focused Track ("Return" or "NUMPAD_ENTER") fails

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1842]
**Describe the bug**
Pressing the "Enter" or "NUMPAD_ENTER" does not toggle selection of the focused track.

**To Reproduce**
1. Generate a "Chirp"
2. "Ctrl + D" (duplicate)
3. "Enter" to deselect the first track
4. The first track is still selected.

**Expected behavior**
The "Toggle Focused Track" keybindings should toggle the selection of the focused track.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: 3.1.0-alpha-20211006

**Additional context**
This is a very important command when working with multiple tracks.

**Comment by Paul-Licameli** [comment]
#1857 did mitigate the problem:  it occurs now only when the selection coincides with the extent of a clip, not always.

A fuller solution that we will do:  Remove the hard coded Return key so Start name editing.  (But not for finishing it.)

That will solve this issue as stated, but then leave @DavidBailes unsatisfied that there is any keyboard accessibility for clip name editing.

That will deserve a different issue, and I don’t promise a fix for that in 3.1.0.

I think it would be a good idea to allow various hierarchical levels of focus (none, track, or labels or clips within the track) and overload keystroke bindings depending on the focus, so that Return would be free to repurpose in this context, instead of using some other less mnemonic key (and running out of keys).

But we can’t do that yet.

I think this is exposing some of the limitations of our system of focus, navigation, and keystroke binding.  Watch for a new Gitub Issue from me about my ideas for a better system.

**Comment by SteveDaulton** [comment]
> #1857 did mitigate the problem: it occurs now only when the selection coincides with the extent of a clip, not always.

Testing with 3.1.0-alpha-20211007

> **To Reproduce** 
> Steps to reproduce the behavior:
> 
>     1. Generate a "Chirp"
>     2. "Ctrl + D" (duplicate)
>     3. "Enter" to deselect the first track
>     4. The first track is still selected.

I see no mitigation.

**Comment by Paul-Licameli** [comment]
> > #1857 did mitigate the problem: it occurs now only when the selection coincides with the extent of a clip, not always.
> 
> Testing with 3.1.0-alpha-20211007
> 
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > ```
> > 1. Generate a "Chirp"
> > 2. "Ctrl + D" (duplicate)
> > 3. "Enter" to deselect the first track
> > 4. The first track is still selected.
> > ```
> 
> I see no mitigation.

As I said, it's mitigated in case the selection does not coincide with a clip.  But those steps are not enough to do that.
