### ISSUE TITLE
Timeline Quick Play without looping

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1846]
**Describe the bug**
Timeline Quick Play should play a dragged region once
https://manual.audacityteam.org/man/timeline.html#tqp

It should loop play on "Shift +drag"

**To Reproduce**
1. Click and drag on the Timeline
2. Observe that playback loops instead of stopping at the end of the selection.

**Expected behavior**
To work like it did in previous versions and as described in the manual

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version 3.1.0-alpha-20211006

**Comment by petersampsonaudacity** [comment]
Actually (testing on 3.1.2 and 3.1.3 Beta-1) at step 2 loop play does not in fact start.

Rather a loop region is created in the Timeline and Looping is activated with the Loop button shown as down.
The user thn needs to press Play at that stage to initiate loop play

I believe that this is current indeed, designed, behavior (and thus nor a "bug".
Whether or not that is good design could be a matter for some debate - flagging @Tantacrul  as a UX issue.



And ideally the cursor, or selection, should be within the bounds of the Timeline loop region otherwise audio that is is not in the loop may be played before getting to the loop region.
See:  Loop play plays the preceding selection before looping #2112 

And worse if the cursor or selection is present in time after the loop region then the loop will not get loop-played at all, rather playback starts from the start of the section or cursor position and plays to the end of the project.  So looping just gets ignored in this use case despite that fact that
a) the loop button is down and
b) a loop region is extant in the Timeline

I am not convinced that this is "good behavior" - or good UX @Tantacrul

**Comment by LWinterberg** [comment]
Re: Peter's 2 and 3, it is planned for 3.2 to make a mode/option/preference/something that would only allow playing the loop region and nothing else. 

As a sidenote, if we do end up with such a mode, I wonder how useful TQP will be while a looping region is present. Maybe it'd be better if a single click onto the looping region disables/enables looping? *if* that turns out to be true, I wonder if TQP might find a better home in something similar to the scrubbing toolbar. 

Anyhow - all of this is a discussion for the design or 3-2 channels in the discord. Click-and-drag now creates loop regions, region-TQP is gone.

**Comment by Paul-Licameli** [comment]
> Re: Peter's 2 and 3, it is planned for 3.2 to make a mode/option/preference/something that would only allow playing the loop region and nothing else.
> 
> As a sidenote, if we do end up with such a mode, I wonder how useful TQP will be while a looping region is present. Maybe it'd be better if a single click onto the looping region disables/enables looping? _if_ that turns out to be true, I wonder if TQP might find a better home in something similar to the scrubbing toolbar.
> 
> Anyhow - all of this is a discussion for the design or 3-2 channels in the discord. Click-and-drag now creates loop regions, region-TQP is gone.

Oh no, you said the “S” word in front of @petersampsonaudacity !

Scrubbing, I mean...  That part of the UI that still pleases none of us enough.

We would all favor allocating some effort to improving that.

**Comment by petersampsonaudacity** [comment]
> As a sidenote, if we do end up with such a mode, I wonder how useful TQP will be while a looping region is present.

A possible use case I can think of is the the user may have a loop region but wants to use Quick-Play to identify a different start end point for the loop.

But they can of course do that by extending-shrinking the loop region

**Comment by Tantacrul** [comment]
The way a lot of other apps solve these issues is to have two horizontal sections: one for looping (and displaying the time/beat measurement) and another for displaying the timeline marker and allowing for things like quick play, etc. See this example of BandLab (the red rectangle is the loop region)

![image](https://user-images.githubusercontent.com/21022311/145389635-438be975-dddf-4ce9-990f-5f77f9f0e360.png)

In general, I want to alter Audacity as little as possible... but this might be the natural end destination if we want to be able to do everything we currently do without conflicting interactions
