### ISSUE TITLE
Change Pitch on clip deletes subsequent clip

### ISSUE THREAD

**Issue by robmcmullen** [audacity/audacity#1891]
**Describe the bug**
Using the built-in Change Pitch effect on a clip deletes the clip that follows.

**To Reproduce**
1. Need a sample file with multiple named clips
2. Select a clip
3. Choose Change Pitch from Effects menu
4. Drag frequency slider to adjust percent change to a *positive* value (negative values don't exhibit this effect)

**Expected behavior**
Clip should be adjusted, subsequent clip should not be affected in any way

**Screenshots**

![change-pitch](https://user-images.githubusercontent.com/896656/136836394-99205e76-e370-430f-ae4a-0d5d396e81f0.gif)

**Additional information (please complete the following information):**
 - OS: Linux Mint 20.2
 - Version: Audacity 3.1.0-alpha-20211010

**Additional context**
This effect also triggers the clip renaming problem in bug #1889

**Comment by dozzzzer** [comment]
The original issue isn't the case anymore as of 3.4.2.
Applying a high-quality Change Pitch doesn't exhibit such behavior as described originally. However, low-quality Change Pitch appears not to be working on shorter clips like this. The new ticket for this problem is https://github.com/audacity/audacity/issues/5872
