### ISSUE TITLE
There is no visual cue for a shrunk clip

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1912]
**Describe the bug**
If the user shrinks a clip, from right or left, there is no visual cue to indicate that part of the clip is hidden and inactive.

**To Reproduce**
1. Generate a chirp
2. Click Ctrl+Select in the TCP to deselect the clip
3. Zoom out one level
4. Use drag-bar affordance to move clip to mid-screen
5. shorten the clip from the right or the left (or both)
6. Observe: no visual cue to indicate that part(s) of the clip are hidden and inactive

**Expected behavior**
A clear visual cue to indicate hidden clip part(s) - _cf. the arrows for audio before T=0_

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/137124972-93d63620-c9b3-4d20-ac97-4d6452188e50.png)

Note that if you omit Step 2 (the deselection) then the selection boundaries remain on-screen:
![image](https://user-images.githubusercontent.com/50205984/137125343-03ce4104-a199-46e0-8791-f85744cb1391.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version:  Audacity 3.1.0 alpha master 

**Additional context**
This is particularly important as when applying effects to a reduced clip the effect is ONLY applied to the visible part of the clip and NOT the entire clip (I understand that this is by design).

**Comment by LWinterberg** [comment]
Having had a bit more of a think with @teetow about this:

We think that indicating a shrunk clip is only fixing a symptom, but that the underlying cause goes deeper. 

The symptom fix could be just to take the Clips 2.0 clip handles: `< [clip] >`, ie ![image](https://user-images.githubusercontent.com/87814144/156366141-459896f6-3db1-4bd7-af03-8f31b8e32f4b.png), and show an additional line next to the triangle when you reach the end of a clip:` |< [clip] >`- or alternatively, showing inwards-pointing arrows when you can only shrink it ( like `> [clip] <`) , and double arrows ( `<> [clip] <>` ) when it is also expandable. 

However, when drag-to-loop becomes a thing (when you reach the end of a clip and continue dragging outwards, it starts repeating the start of the clip), you *always* can drag outwards. There may be some snapping to multiples, but there'll always be infinite content to both sides. 

The underlying issue here is that we mix non-destructive and destructive operations in novel ways. In a similar vein to this issue, if you were to put a real-time delay effect onto a clip, you'd hear the clip echoing beyond the original clip length, "bleeding" into the next clip. In a fully non-destructive world, this is fully expected. For us, this *is* new, and we don't yet have aforementioned clip looping. So if we pick a solution for this, it very likely will be a temporary one.

**Comment by petersampsonaudacity** [comment]
BUMP  @LWinterberg @DilsonsPickles @Tantacrul 

This seems more than a mere "minor feature" to me".

It is all too easy to inadvertently create a smart-clip with hidden data by accidentally nudging the clip boundary, thereby hiding data in the project.

With no visual cue the user is likely to be totally unaware that the have hidden data, a smart-clip with potential for expansion to expose the hidden data.  

This has lain as an open issue for almost 14 months now, is there any chance please that this could be addressed?


_Note that we do have a visual cue (albeit very subtle) for other hidden data - and that is when the user has audio in negative time,_

**Comment by teetow** [comment]
At face value, I think it's reasonable to present zero-length audio clips as infinitely thin clips that can be expanded in any direction there is audio data available. If looping clips were to be implemented, it'd play nicely into this as there would _always_ be audio data in both directions.

This solution will not cover clips with _no_ audio data, an artifact somewhat unique to Audacity, but maybe that's a subject for another discussion.

**Comment by LWinterberg** [comment]
After some more consideration, this indication won't get added, at least not as part of a always-visible visual cue, simply because there are many more sometimes-visible and always-visible things we want to add (like: trim handles, fade handles, fade lines, envelopes) which already are creeping towards information overload and visual noise. Ultimately, as soon as a user learns that non-destructive trimming is a thing and has a vague memory of which cuts and trims they made, they can use this memory to have a fairly good guess as to where they can untrim. And if they're wrong and there's nothing to untrim, it's just a drag outwards followed by an "oh, I guess I made a destructive cut", followed by finding another way to achieve the desired result.
