### ISSUE TITLE
Non-standard metadata get malformed or lost in Audacity

### ISSUE THREAD

**Issue by deus-e-x** [audacity/audacity#1944]
I regularly import FLAC audio files into Audacity that hold a complete set of metadata, including the tag 'Total Tracks '. When exporting this audio data, the tag 'Total Tracks' is unavailable in the 'Edit Metadata Tags' dialog and absent from the exported audio data. This issue affects the import formats FLAC, MP3, and WAV.

However, when importing an OGG file with a 'Total Tracks' tag, the tag is retained. Though on export, the tag is renamed to 'TRACKTOTAL' (all uppercase).

In previous versions of Audacity (e.g. v3.0.4) the import/export of the 'Total Tracks' tag used to work with every supported audio format, although on export the tag was renamed to 'TRACKTOTAL' (all uppercase).

**To Reproduce**
1. Import a FLAC or WAV or MP3 audio file that at least holds the 'Total Tracks' metadata tag.
2. Export the audio (choose any available format)
3. If enabled, the 'Edit Metadata Tags' dialog will show that the 'Total Tracks' tag is not available.
4. The exported audio file is missing the 'Total Tracks' tag

**Expected behavior**
Every valid metadata tag of an imported audio file should be retained and saved unaltered with the exported audio data (WAV, MP3, OGG).

**Additional information**
 - OS: Windows 10 Pro 21H1 (19043.1288) 64-bit
 - Audacity: 3.1.0 beta 1
 - Sound device: Windows WASAPI

**Comment by LWinterberg** [comment]
Possibly related: https://forum.audacityteam.org/viewtopic.php?f=46&t=121636

ReplayGain also is not retained.

**Comment by LWinterberg** [comment]
I started with an MP3 with the following info in its first line:

```

ID3    TIT2   -  ÿþE y e s   t h r o u g h   t h e   V e i l TPE1     ÿþH e t e r o d y n e . TALB   M  ÿþD E A T H M A R C H   O F   J I A N G S H I ' S   P A R A D I S E J A C K TYER     ÿþ0 TRCK   	  ÿþ2 / 2 TPOS   	  ÿþ0 / 0 PRIV   .  Google/OriginalClientId <some ID which I redacted here just in case>                              Info     $ù –ì» 

```

And when exporting it again, it leaves me with this info  in the first line instead: 

```
ID3    TIT2      Eyes through the VeilTPE1      Heterodyne.TALB   &   DEATHMARCH OF JIANGSHI'S PARADISEJACKTRCK      2/2TXXX      Part of a set 0/0ÿûd                                Xing     $ø ZþL  #&(+-0357:=@BEHJMPSUX[]`begiloqtwz|‚„‡Š’•—šœž¡£¦©¬®±´·º¼¿ÂÅÇÊÍÏÒÔÖÙÜÞáäæéëîðòõ÷ùûýÿ   PLAME3.100¹        5 $üM à ZþLo’í                                                                                                                                                                                                                                 ÿûd ð  i     
```

If I understand this correctly, there are the following things happening here: 

1. Audacity is parsing ID3 frames for display (in this case, the `TPOS`-tag gets translated to `Part of a set` as per id3v4 (and v2) specification. However, on saving, it does not get translated back to the ID3-form, but stays as a bog-standard string saying `Part of a set`.
2. Audacity cannot parse certain frames at all (in this case, `PRIV`) and plainly discards them
3. There is some parsing of the content happening as well - the original has NUL-bytes between each character for whatever reason, which also get discarded. 

FWIW: The original file probably wasn't the cleanest example to take for this (it's got 37 lines of LAME3.93UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU... following the ID3 tag, which Audacity reduces to only 30 lines of ...UUUUULAME3.100UUUUUUU... upon export). I wanted to say that just in case this turns out to be an edge case.

**Comment by LWinterberg** [comment]
Upgrading as this affects the (apparently) third-most-common use case (converting files from one format to another). 

#2175 may be an acceptable stop-gap solution.

**Comment by petersampsonaudacity** [comment]
See also

1. #1506
2.  #1464 
3. #1505 
4. #1696

**Comment by LWinterberg** [comment]
Improving metadata handling is not planned for the moment, closing for now. There may be a bigger metadata release eventually, follow https://github.com/audacity/audacity/issues/1464 for that.
