### ISSUE TITLE
Smart clips. Clip Names. The second double-click doesn't select the whole clip name string

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1991]
**Describe the bug**
The second double-click doesn't select the whole clip name string

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a clip
2. Double-click on the clip name: Whole clip name is selected
3. Click once between any signs within the string.
4. Do double-click on the string one more time

**Expected behaviour**

https://user-images.githubusercontent.com/25851359/138259919-bd968f27-a0a8-4a2b-8645-5cb736de70ca.mp4

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.1

**Comment by AnitaBats** [comment]
@Penikov please test if already fixed

**Comment by Penikov** [comment]
Still reproducible in 3.2

**Comment by LWinterberg** [comment]
incidentally, "double click to select a word" does work when the "use dialog for the name of a new label" preference is turned on. When it's off, double clicking either a clip name or a label does nothing.

**Comment by Penikov** [comment]
@LWinterberg Sure, but I was guided by a default label behavior on Windows, macOS and majority of Linux DE.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
