### ISSUE TITLE
Xfce: "Ctrl + F2" conflicts with default global key binding

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1997]
**Describe the bug**
On Xubuntu (any Linux  with Xfce Desktop), the new "Ctrl +  F2" key binding conflicts with the default global key binding for "Go to workspace 2". See: https://defkey.com/xfce-shortcuts#32727

**To Reproduce**
1. Add a track
2. Press "Ctrl + F2"
3. Observe that Audacity "disappears" (Xfce has switched to workspace 2)

**Expected behavior**
Avoid default global Desktop key bindings.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: [Xubuntu 20.04
 - Version 3.1.0-alpha-20211021

**Additional context**
https://defkey.com/xfce-shortcuts#32727

**Comment by werame** [comment]
I agree Ctrl+F2 should not be hardcoded. I guess it's so because there's no scriptable item for it, which would allow it to be a "normal" shortcut. A scriptable like EditSelectedLabel should probably be created.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
