### ISSUE TITLE
Using the Time shift left/right commands crashes Audacity

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#2061]
**Describe the bug**
Using the Time shift left/right commands crashes Audacity

**To Reproduce**
1. Create an audio track containing a clip
2. Extra > Edit > Time shift left/right
3. Audacity crashes

**Expected behavior**
A time shift rather than a crash

**Additional information (please complete the following information):**
- Windows 10
- Audacity 3.1.0

**Additional context**
Reported on the Audacity4Blind list

**Comment by buaabyl** [comment]
Maybe the problem is the format of config file changed?

When I upgrade from previous version today, UI crash...

## details:

I am using v2.3.3, and upgrade to 3.1.0 and 3.1.3 beta1.

1. open audacity
2. drag audio file in
3. move the Horizontal scrollbar: mouse roll wheel + hold shift-key
4. the UI hang (no response).

After I delete `C:/Users/ww/AppData/Roaming/audacity`, 
Reinstall 3.1.3 beta1, everything works fine.
