### ISSUE TITLE
Looping can play wrong audio and silence (was: Relocating the loop region while looping elsewhere exhibits wrong behavior)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2103]
**Describe the bug**
When the loop region is changed while loop playing is active the looping playback does not jump to the user's new loop region.

This is a regression on 3.0.5 and earlier Audacity versions.

**To Reproduce**
1. create a 30 second chirp
2. Click+drag in the Timeline to create a loop region from 5-6 seconds
3. Press Play
4. Observe: Play loops from 5-6 seconds
5. With that looping still active, change the loop range to be 15-16 seconds
6. Observe: The cursor moves back to 5 second and plays the audio that is at 15-16 seconds
7. Observe: then the cursor moves steadily on to 15 seconds - but from 6-15 seconds silence is played
8. Observe:  now looping occurs at 15-16 seconds
9. This gets worse if you now reset the loop region to 5-6 seconds
10. Observe play starts from 16 seconds and plays to 30 seconds where it stops - i.e no looping at 5-6

**Expected behavior**
When the loop region is changed while loop playing is active the looping playback should immediately jump to the user's new loop region

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS:  Windows 10 - but assume all OS
 - Version Audacity 3.1.0

**Additional context**
This is very confusing behavior for the user.

**Comment by petersampsonaudacity** [comment]
Observe also that when extending a loop play region Audacity now makes one last play of the pr-existing loop region before playing the extended loop.  So there is a latency in the use of the new extended loop region.

There is similar latency if you shorten the loop region.

**Comment by petersampsonaudacity** [comment]
Also:

1. create 3 30 second chirp
2. Click+drag in the Timeline to create a loop region from 5-6 seconds
3.  Select all 30 seconds
4. Press Play
5. Observe Play starts from T-0 and plays to 6 seconds
6. Observe then Play loops from 5-6 seconds

**Comment by Paul-Licameli** [comment]
The only thing that is a bug is the playing of silence in step 7.

i don’t know why it is considered a regression when there was never any adjustability of the loop region with play in progress before 3.1.

The desired behavior as I understood it is that play starts from the left edge of selection and proceeds right until the right edge of the loop region “traps” the play head and sends it back to the left.  So play may start left of the loop, and play may be right of the loop and reach the end instead of jumping back.

**Comment by petersampsonaudacity** [comment]
> i don’t know why it is considered a regression when there was never any adjustability of the loop region with play in progress before 3.1.

There certainly was adjustability of the loop region with loop play in progress - both for extending/shortening and for relocation.  I tested this thoroughly on 3.0.5 before I logged this.

The trick to achieve this is to hold down the Shift button while making the cjanges.

**Comment by Tantacrul** [comment]
I think some lag is affecting the looping not immediately updating. However, we don't want the playback to jump around to a loop region. It needs to be 'in' a loop region in order to loop.

the silence is a problem.

Incidentally, I think we should have an option (feature improvement) that allows a user to specify whether they'd like playback to always be 'trapped' in a loop or whether they prefer it to work the way it does now.

**Comment by Paul-Licameli** [comment]
I retitled the bug again.  The actual misbehavior needing fix is not only at step 7 in the description, but also step 6.  Using a rising chirp, you can see the looping head in one place but hear the higher frequencies for the moved loop selection, before the play becomes silent, waiting for the next leftward jump of the play head, before you hear the correct sounds again.
