### ISSUE TITLE
Tools toolbar looks odd and incomplete with a blank tool cell

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2131]
**Describe the bug**
With the recent removal of Time Shift Tool, the Tools toolbar looks odd and incomplete with a blank tool cell

**To Reproduce**
1. Launch Audacity 3.1.1
2. Observe the Tools toolbar

**Expected behavior**
**Short term**, I would suggest removing one of the remaining tools from the toolbar.  

The Zoom tool is the obvious candidate - there are plenty of other ways to Zoom
a) the Edit toolbar
b) shortcuts
Plus it is pretty pointless to have to switch from the I-beam selection tool to zoom and then have to switch back to select

Long term>  it would be good to be able to remove the Tools toolbar altogether with ts mode-switching and accompanying bear-traps that users keep falling into.

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/141678641-d97c5ab9-2105-42db-8fb1-5f2641819899.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 and macOS 12.0.1 Monterey (but I assume all OS)
 - Version Audacity 3.1.1

**Additional context**
Flagging this for @Tantacrul as this is a UX/GUI issue

**Comment by petersampsonaudacity** [comment]
Note that this leads users to think that the Move tool is just accidentally "missing" (as seen on several Forum posts).

**Comment by Tantacrul** [comment]
FWIW: we have a general plan to replace these modes (timeshift, magnifying tool, etc.) so that the user can use them all at once. The only exception is the pen tool, which I feel is a special case.

Basically, we want Audacity to work like it does when the multitool is active. I think the envelope tool should be a state that you can enable or disable but should not interfere with the ability to select wave data.

I feel the unique advantages of the magnifying glass tool could be incorporated into the other zoom options.

All this is to say that we will likely be reducing that panel down further and slightly simplifying the overall layout.

**Comment by SteveDaulton** [comment]
FWIW: I'm aware that some people like the Multi-Tool, but personally I hate it.

**Comment by Tantacrul** [comment]
the only thing I like about the multi-tool is that it proves that a multi-tool isn't necessary :)

It is ugly as sin for sure. If we just get rid of the modes, then the multi-tool becomes unnecessary.

**Comment by Paul-Licameli** [comment]
My opinion is that the multi tool should be default behavior.  Sample editing as with the pencil only applies at close zoom levels.

The envelope button should be a toggle but not a mode, to turn envelope point display and interaction on and off.

Zoom is my least favorite button, but if you want to keep it, then it is a mode, not a toggle.  It changes what clicks and drags mean.

So I think that leaves three buttons: one toggle, and two mutually exclusive modes.

Spectral brush tool in the prototype would have been another mode, but we don’t yet have an agreed upon user interface for that.
