### ISSUE TITLE
Playback cursor issues

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2133]
**Describe the bug**
The playback cursor may disappear or de-synchronize if play position moved before zero

@DavidBailes added:
There are numerous other examples of playback not corresponding to the playback position after seeking. These include:
1. Using play once, if you seek before the start of playback (looping either on or off).
2. Using standard playback (no looping) and there is a time selection, if you seek before the start of the selection.
3. Using standard playback with looping: a) If the start of playback is included in the loop region, if you seek before the start of the loop region; b) if the start of the playback is before the start of the loop region, and playback has already played the loop region once, if you seek before the start of the loop region.

**To Reproduce**
1. Generate a 30 second chirp
4. start playback
5. "Left cursor" to move the play position before zero
6. Observe that the playback cursor disappears, even when the play position has reached positive time
7. Observe there is also weird behaviour when there is audio before zero and "Pinned Playhead" is enabled

**Additional information (please complete the following information):**
 - Version Audacity 3.1.1

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.0.5 and earlier

**Comment by DavidBailes** [comment]
Unfortunately, the problem is more general than just the above.
Seeking left can take the playback position to the left of the cursor, or before selection start if there's a time selection. This is an unwanted  change in behaviour from 3.0.5 and earlier. It's not what the user expects.

Also the de-synchronization problem in not restricted to playback positions before zero.
If there's a time selection, then seeking to the left of selection start results in the audio being played back not being the audio indicated by the playback position. This is really confusing.
1. Make a short recording of yourself counting up to ten.
2. Select a short section of audio, for example the counts of 5 and 6.
3. Start playback, and immediately press left arrow three times.
4. The playback position indicates that audio is being played back before selection start, but the audio actually being played back is after selection start, and continues after selection end.

**Comment by DavidBailes** [comment]
The bug that seek left can take the playback position to the left of the cursor or before selection start appears to have been introduced by this commit:
Author:			Dmitry Vedenko <dmitry@crsib.me>
Date:			3 weeks ago (25/10/2021 10:18:02)
Committer:		GitHub <noreply@github.com>
Commit hash:	5af2a265e2090f449395435e9647f6e692976b3f
Child:			8ee6cea1
Parents:		69d2a274 705c0b71

Merge pull request #2002 from Paul-Licameli/Fix-playback-policies

Fix playback policies
Contained in branches:
master
i2119
release-3.1.0
Contained in tags:
Audacity-3.1.0
Audacity-3.1.1
list

Derives from tag: Audacity-3.1.0-beta-1 + 36 commits

**Comment by DavidBailes** [comment]
@Penikov Please can this be assigned a priority rating.

**Comment by Penikov** [comment]
P2 because the bug affects Playback.
