### ISSUE TITLE
Corrupt project preceded by aup3-wal file

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#2140]
Two Windows users have reported on the forum that sometimes Audacity leaves an aup3-wal file and that this somehow leads to a corrupt project.  See: https://forum.audacityteam.org/viewtopic.php?f=46&t=121553

**Comment by LWinterberg** [comment]
This is unfixable on Audacity's side. If you use a sync client for your projects, try to exclude `*-wal` and `*-shm` files from the sync, or if the sync client doesn't support that (Google Drive doesn't, Google Backup & Sync did), use a different client which does, or a different service altogether (specifically, if you use a pure backup service rather than a sync service, this kind of issue won't happen)
