### ISSUE TITLE
Linked ffmpeg for ABI tracking

### ISSUE THREAD

**Issue by mikhailnov** [audacity/audacity#2161]
Audacity previously allowed to link ffmpeg instead of dlopen()-ing it, but now it does not:

[00:00:54] CMake Error at cmake-proxies/cmake-modules/AudacityFunctions.cmake:140 (message):
[00:00:54]   Invalid value "linked" for option audacity_use_ffmpeg.  Valid values are:
[00:00:54]   loaded off

When building distro packages, dlopen is very bad because:
- runtime dependencies are not resolved automatically (see e.g. dependencies of RPM packages)
- ABI tracking becomes broken, trackers do not know which symbols are used and so cannot detect when a rebuild is required

Also, CMAKE_OPTIONS.md still suggests to use "linked"

**Comment by crsib** [comment]
Audacity can now load three different ABIs versions of FFmpeg at runtime; the implementation does not allow just linking to a specific one. There are no immediate plans to fix that, as it will generally mean to have a separate set of Import/Export plugins for FFmpeg. At the time of speaking, Audacity supports avformat versions 55, 57, and 58. 59 will be added shortly after the release. This was checked on Fedora with an RPM as well. 

This effectively means that FFmpeg becomes an *optional* runtime dependency, not a build-time dependency.

>ABI tracking becomes broken, trackers do not know which symbols are used and so cannot detect when a rebuild is required

ABI changes on FFmpeg do require changes to the software generally. There is a version-specific code already; I expect more to come with FFmpeg 59, as Audacity currently uses long deprecated APIs. Any ABI breaking change must be verified and supported by the application maintainers first. Otherwise, there is a chance to end up having an unstable (and I mean crashing, not API) software.

**Comment by mikhailnov** [comment]
Of course I understand that supporting linked ffmpeg is additional work, I just tried to explain why this change is a regression from the point of view of package maintainting.

> Any ABI breaking change must be verified and supported by the application maintainers first

In real world compilers and linkers do this quite well. But not when dlopen is used.

Standard mechanics is to rebuild packages linked with a library when its soname changes or when its ABI changes (http://ftp.altlinux.org/pub/people/at/protva-2010.pdf)

**Comment by mikhailnov** [comment]
What will happen if libavcodec is 59, not 58 during build of Audacity? Will the build fail?

**Comment by crsib** [comment]
>What will happen if libavcodec is 59, not 58, during the build of Audacity? Will the build fail?

It will build fine, but FFmpeg won't work :-) However, what could fail is building against 59 because the change in a major version can lead to APIs being removed, or some structures fields, or whatnot. Behavioral changes are possible as well. We had some code working fine for 55 and 57, but not for 58, while everything compiled fine. Nor linker neither compiler will help with that :-)

**Comment by mikhailnov** [comment]
It is very bad. I will have to add "Requires: libavocodec.so.58%{_isa}" into the RPM spec, I think no other packages do such tricks that break existing maintainance pipelines :(

**Comment by crsib** [comment]
But it does not require libavcodec at all! Not to build, not to run.

**Comment by crsib** [comment]
>It is very bad

That FFmpeg can make source incompatible changes between the major versions? But it does, sometimes. I think this is the sole reason for increasing a major version anyway.

**Comment by mikhailnov** [comment]
Certain fucntionality will stop working without a compatible libavcodec and this regression may be left unnoticed if it is dlopened. That is the problem - not trackable sudden regressions. Different people maintain audacity and ffmpeg, a standard pipeline is to rebuild dependant packages when upgrading libraries, e.g. ffmpeg, and you say that audacity will be rebuilded ok, nobody will notice that a regression is introduced.

**Comment by crsib** [comment]
>nobody will notice that a regression is introduced.

I'm afraid this assertion is false. I have personally encountered a scenario where code compiled fine, but FFmpeg was not working. This is a regression that approach "rebuild on ABI change" won't ever notice. Can we blame FFmpeg? Indeed no, they have changed their major library version! And it was rather a bug in Audacity (and keep in mind, FFmpeg support was implemented a decade ago), but Audacity worked fine with older FFmpeg versions, so that bug remained unnoticed for years!

This can be mitigated to some extent if dependent software has a good test coverage checked regularly against all supported dependencies versions. This is not the case for Audacity right now, although we plan to improve that. This will take a lot of time, sadly

**Comment by mikhailnov** [comment]
> This is a regression that approach "rebuild on ABI change" won't ever notice.

Why? If ffmpeg is linked and changes ABI, it will be noticed that Audacity has to be rebuilt. If API remained compatible, a simple rebuild will be enough. If not, the build will fail.
FFmpeg was linked previously for ages (or did not it work despite being linked?)

**Comment by mikhailnov** [comment]
Very interesting, I have a build of Audacity from commit b5e5a3 (near v3.0.3), importing a video file with audio works OK, see screenshots:
![2021-11-19_14-11](https://user-images.githubusercontent.com/15802528/142613346-565fc2b6-f0ed-46e9-870a-73afdc38defc.png)
![image](https://user-images.githubusercontent.com/15802528/142613547-5a90336b-fe2b-496a-905a-c7771b99fc2d.png)
It is linked against libavcodec.so.58 (`-Daudacity_use_ffmpeg:STRING=linked`)

**Comment by mikhailnov** [comment]
strace confirms that libavcodec.so.58 is loaded when launching Audacity

**Comment by StefanBruens** [comment]
I think Audacity is the only program I know which has a problem with build time linking of FFMpeg.

Fedora is not the only distribution where such a setup is frowned upon, the same is true for openSUSE, and likely several others.

**Comment by crsib** [comment]
Audacity does not depend on FFmpeg. If a compatible version is available - it will be used. If not - nothing wrong will happen.

**Comment by StefanBruens** [comment]
"Not working" is something wrong. With runtime only detection, tracking of supported versions becomes much harder for distributions.

Without linking to FFMpeg, the supported versions may silently be dropped from the distribution in favor of newer versions. It is much better when these issues are already visible at build time.
