### ISSUE TITLE
Up / Down cursor keys do not move cursor up / down

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2174]
**Describe the bug**
The up / down cursor keys should move the cursor up / down to the next track. This does not happen in 3.1.2

**To Reproduce**
1. Create a multi-track project
2. Click on one track
3. Observe the playback cursor is at the position and on the track that has been clicked
4. Use the Up or Down cursor keys to move the cursor to the track above or below
5. Observe that the cursor does not move.

**Expected behavior**
The cursor to move up / down, as in Audacity 3.0.2

**Additional information (please complete the following information):**
 - OS: Windows / Linux
 - Version Audacity 3.1.2

**Additional context**
Reported on the forum: https://forum.audacityteam.org/viewtopic.php?p=440010#p440010

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.0.5 - tested on W10

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
