### ISSUE TITLE
Keyboard. Pressing the Windows key calls the 'Set Left Selection Boundary' dialog

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2256]
**Describe the bug**
In the case of using Winkey + Space as a shortcut to switch keyboard layouts, 
pressing the Winkey calls the 'Set left selection' dialog

The problem is the Winkey does not exist at all even in default Full Set.

This bug is a sort of a heisenbug. So it may be not so simple to reproduce It. But, It still appears since 3.0.4 or maybe earlier.

![изображение](https://user-images.githubusercontent.com/25851359/145530987-39f6b377-5bcf-4dd6-829c-b7c0c0dfdada.png)

**To Reproduce**
1. Set up the Winkey + Space in Windows as the layout switching shortcut
2. Work in Audacity as usual 
3. Press the Winkey + Space
4. See the unexpected dialog

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: 3.0.4 + (and 3.1.3 too)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
