### ISSUE TITLE
Incorrect snap line positions when clip moves to another track

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#2260]
STR:
1. Generate mono clip
2. Split clip in two places
3. Create gaps between clips
4. Create empty mono track
5. Select move tool(or use clip handle), move one of the clips to an empty track and keep dragging it

Observe:
Snap line appear in the wrong places
![image](https://user-images.githubusercontent.com/20165230/145566362-0993eb12-d051-4863-84b3-f374a47367fe.png)

 - Version: Audacity 3.0.3+

**Comment by Penikov** [comment]
Reproduces at 3.1.3.

**Comment by Penikov** [comment]
Still reproducible in 3.2

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
