### ISSUE TITLE
Playback sometimes gets stuck "on"

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2285]
**Describe the bug**
When playing a clip, playback does not always terminate correctly at the end of the clip. It can get stuck in a state where play has "ended", but Audacity is  still in play mode.

**To Reproduce**
See video: https://youtu.be/D4xoUnN6nfk

**Expected behavior**
Playback to terminate at end of selection.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version : 3.2.0-alpha-20211210

**Additional context**
Once the bug appears, it happens whenever the clip is played.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
