### ISSUE TITLE
Playback Looping. Assigning a new looping region doesn't work well if 'Enable scrolling left of zero' option is on

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2290]
**Describe the bug**
Assigning a new looping region doesn't work well if 'Enable scrolling left of zero' option is on

**To Reproduce**
1. Go to [Preferences][Tracks][Track behaviors] and check the tickbox 'Enable scrolling left of zero'
2. Point the audio cursor on the track at the left of zero and generate a new clip as on the picture below:
![изображение](https://user-images.githubusercontent.com/25851359/146192537-a551949e-c418-4ab8-a2e3-f5c2a9f371ed.png)
3.  Try to create a new looping region as shown on the screencast:

https://user-images.githubusercontent.com/25851359/146194389-86c5138b-c0c8-457a-b568-06bc61a429d9.mp4

**Expected behavior**
A new looping region should be created as usual, but playback starts from zero.

**Additional information (please complete the following information):**
 - OS: All
 - Version 3.1.3

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
