### ISSUE TITLE
Warnings. In case of "importing" the project file, the error window appears at the bottom layer

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2302]
**Describe the bug**
If the user has tried to drag-n-drop the project file from Explorer right to the Audacity window, the error message is closed beneath the Explorer window. Thus that, the cursor focuses on the warning dialog at the bottom layer, which makes the window at the top inaccessible.

**To Reproduce**
1. Run Audacity
2. Drag-and-drop any project file right to the Audacity window
3. Try to interact with the Explorer window (close it, for example)

https://user-images.githubusercontent.com/25851359/146515437-75493bf2-a66d-48f3-9aea-95fcd55e4fae.mp4

**Expected behavior**

The warning dialogue appears at the top, the cursor is focused at this dialog.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: 3.1.3

**Additional context**
On macOS, this case works well

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
