### ISSUE TITLE
Import and re-export of 16 bit data should be bit-perfect

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2387]
**Describe the bug**
Dithering is applied (to spread out the spectrum of quantization noise) when making a lossy save of newly recorded or computed sample data from a wider bit width to a narrower one.

But 16 bit data imported into memory and stored in 32 bit float format, perhaps edited with some cutting and pasting, and then re-exported, should not require dithering.  The re-exported data should be bit-perfectly identical to the originally imported data.

The results of most effects applied to such an import (even a simple amplification) could require dithering because sample values at the 16 bit quantization levels might transform to values at other levels.  But some effects like Invert and Reverse are exceptions.

**To Reproduce**
First, this is the procedure to tell whether a track containing silence is absolute silence:
A. Select that track only, with the "Select" button
B. Effect > Amplify; but do not press OK in the dialog
C. Read the "New Peak Amplitude" value; if it is "-Infinity" and OK is disabled, then that is absolute silence (all samples exactly zero); but if a number, then it is not.
D. Optionally, press OK if you can, and see the noisy waveform, then undo; or, just press Esc to exit the effect dialog.

Procedure to "subtract" one track from another:
A. Select the second track only
B. Effect > Invert
C. Select the first and second tracks (Ctrl + Click on their Select buttons)
D. Tracks > Mix > Mix and Render to New Track

1. Record or generate some sound
2. File > Export > Export as WAV; choose 16 bit PCM encoding; Ok, Ok
3. File > Import > Audio... ; choose the file just exported (and now there are two tracks)
4. Subtract second track from first and test for silence:  it isn't, but that shows correct application of dithering.
5. New Audacity project (Ctrl + N); import the file again (or File > Open Recent)
6. Again, Export as WAV, to another file name
7. Import the file just exported
8. Optionally, do some cuts and pastes, deletions, time-shifts, inversions or reversals, to both tracks at once
9. Again, subtract the second track from the first and test for silence -- but it is not!

**Expected behavior**
At step 9, there should be absolute silence, becuase the exported and re-imported sound should be identical

**Comment by Paul-Licameli** [comment]
This is related to issue #1584, which motivated pull request #698.  That pull request should fix this issue.  Whether #1584 is still a correctly described issue is debatable:  see comment there from @rbdannenberg as quoted by @petersampsonaudacity.  See my comments in the issue description about most effects.  But #1584 was motivated by @SteveDaulton 's concerns originally.

**Comment by pietro68** [comment]
Tried all steps and I can reproduce the behavior. I understood the issue in this way, please confirm or correct me:

If we import a 16-bit pcm, and do nothing else than invert/reverse/cut/paste to it, 
and then we export it again to 16-bit pcm, then we should not apply dithering before the export.

**Comment by Paul-Licameli** [comment]
> Tried all steps and I can reproduce the behavior. I understood the issue in this way, please confirm or correct me:
> 
> If we import a 16-bit pcm, and do nothing else than invert/reverse/cut/paste to it, and then we export it again to 16-bit pcm, then we should not apply dithering before the export.

That is correct.

**Comment by Tyco72** [comment]
Hi, it happens also even if you open a 16bit wav file and export it again to the same 16 bit format, without to apply any change. The files are not binary identical.
The same happens when you convert a 16bit FLAC file back to wave, it is not binary identical to the original. This should never happen.
I would say that Audacity should not force you to work with 32bit float, when you don't need or don't require it.
As rule it should work natively with the same format of the opened file, unless you specify differently. Without adding unwanted conversions.

**Comment by LWinterberg** [comment]
> I would say that Audacity should not force you to work with 32bit float, when you don't need or don't require it.
As rule it should work natively with the same format of the opened file, unless you specify differently. Without adding unwanted conversions.

Short answer: No, that causes other, much more severe problems.

Long answer:

You *can* set Preferences > Quality to have Audacity work in 24 or 16 bit. However, if you

1. Generate noise with an Amplitude 1
2. Amplify noise by 50dB (allowing clipping)
3. Amplify noise by -50dB

you'll find that the 32bit float version still is noise at amplitude 1 (not necessarily bit-perfect but very close), whereas the 24/16 bit versions will have lost all clipping information and are now at -50dB. Maybe not massively problematic for random noise, but 50dB clipping on actual files is a massive problem. Further, if you have generated a sufficiently long noise clip (eg 1h), you'll also find that doing the above in 24/16 bit is *much slower* as Audacity internally is working with 32bit float, so every single time you apply an effect, you are doing an int -> float -> int conversion on top of the actual effect. 

Because of that, Audacity definitely *shouldn't* keep the format the same.

**Comment by Paul-Licameli** [comment]
> Hi, it happens also even if you open a 16bit wav file and export it again to the same 16 bit format, without to apply any change. The files are not binary identical.
> The same happens when you convert a 16bit FLAC file back to wave, it is not binary identical to the original. This should never happen.
> I would say that Audacity should not force you to work with 32bit float, when you don't need or don't require it.
> As rule it should work natively with the same format of the opened file, unless you specify differently. Without adding unwanted conversions.

I reject this suggestion.

The implementation of the fix for this issue will be more complicated.  Intermediate form will always be float.  But tracks will carry flags around as to whether dither should be done on export again.  That will be false when the source of data is an import.  It will remain false for cut and paste operations.  It will become true though if you apply most effects.  (Reverse and invert among the exceptions to that.)

**Comment by Paul-Licameli** [comment]
> you'll find that the 32bit float version still is noise at amplitude 1 (not necessarily bit-perfect but very close), whereas the 24/16 bit versions will have lost all clipping information and are now at -50dB. Maybe not massively problematic for random noise, but 50dB clipping on actual files is a massive problem. Further, if you have generated a sufficiently long noise clip (eg 1h), you'll also find that doing the above in 24/16 bit is _much slower_ as Audacity internally is working with 32bit float, so every single time you apply an effect, you are doing an int -> float -> int conversion on top of the actual effect.
> 

The problem with repeated int > float > int conversions whenever you do some destructive effect edit, instead of int > float > float > float ... > int, would be not so much the speed as the unnecessary compounding of roundoffs and dither noise each time you narrow from float to int again.  That should happen only once at the end of it all.

**Comment by Tyco72** [comment]
I always speak about working on single tracks, recorded with 16 bits. Not mixing tracks.
I'm not a developer, but why should it be so difficult to implement, to can select whether to work on 16bit integer instead of 32 float?
I don't know how Nero Wave Editor works natively, but I have not this issue. It changes only the part that I edit on a file. It lacks about other editing features that I have in Audacity.

**Comment by Ryan-Miller-Audacity** [comment]
Verified with build (https://github.com/audacity/audacity/actions/runs/3758557971) from PR #698 on Windows using the steps listed above confirming that the exported and reimported sound are identical. 

Other dithering checks were also completed to ensure proper application of dithering when it is needed vs not based off the following: 

... Mixing stereo down to mono.  Because -- averaging of 16 bit values might make fractional values that must be quantized again 
... resampling to a different rate
... Applying a destructive effect to ANY PART of the track (this may dither untouched parts unnecessarily, but it would complicate things to tag portions of track separately, so pessimistically, any effect application anywhere causes dithering everywhere) 
... BUT exception to the last:  Invert, Reverse, Truncate Silence, and Repair effects.  (Truncate Silence does make cross-fades, but they are few and of short duration, so I reasoned, we skip dithering.  Repair, little used really, is an effect that only makes spot corrections for very short durations).
... and the Pencil tool also does not cause dithering.  (Reasoning as with Repair)
... Things that do cause dithering:  pasting any new material, that was not imported from a 16 bit file, into the imported track, "contaminates" it just as applying most effects to any part of it.
... If a stereo track is not center-panned, then rendering it (either in the app with mix-and-render, or by exporting) must dither because the pan value can vary continuously.
... Likewise if the gain slider is not at default position
... Likewise if there are any envelope points on the track

**Comment by Paul-Licameli** [comment]
> Verified with build (https://github.com/audacity/audacity/actions/runs/3758557971) from PR #698 on Windows using the steps listed above confirming that the exported and reimported sound are identical.
> 
> Other dithering checks were also completed to ensure proper application of dithering when it is needed vs not based off the following:
> 
> ... Applying a destructive effect to ANY PART of the track (this may dither untouched parts unnecessarily, but it would complicate things to tag portions of track separately, so pessimistically, any effect application anywhere causes dithering everywhere)

For "track" should substitute "clip".

**Comment by SteveDaulton** [comment]
> why should it be so difficult to implement, to can select whether to work on 16bit integer instead of 32 float?

That is not the difficult part. That is very easy to implement.

The reason that it is difficult is because the development team wants to _automatically_ avoid quantization distortion when applying floating point processes to _a significant amount_ of integer data while also retaining integer precision in all other cases. This is tricky because most, but not all processing produces non-integer sample values, and rounding floating point samples to integer values produces quantization noise.

There are other approaches to the problem that are much more simple, but the development team have chosen the approach that they want, and this approach is complicated.
