### ISSUE TITLE
Render MIDI tracks to audio

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2393]
**Describe the bug**
What users can do with MIDI files imported into Note Tracks is extremely limited.  Audacity is **_not_** a MIDI editor.

What Audacity **_is_** is an audio editor.  Thus it would be extremely useful if Audacity could Mix & Render Note Tacks to Audio tracks, then users could at least edit the audio and mix the rendered MIDI tracks with their normal audio tracks.

There have been calls for this on the Forum over the years https://forum.audacityteam.org/viewtopic.php?f=47&t=115110  beingan example.

**To Reproduce**
1. Import a MIDI track
2. try to turn it into a usable, editable, audio track
3. Observe:  you can't

**Expected behavior**
Commands to Render MIDI tracks to audio.

The simplest solution would be to add two new commands to the Tracks menu that just act **_only_** on Note Tracks/MIDI.
*Tracks > Mix > Mix and Render MIDI to Audio Track
*Tracks > Mix > Mix and Render MIDI to New Audio Track
Where the former command removes the MIDI tracks as part of the process but the latter leaves them in place.

More complex would be to extend the current Mix & Render commands to work on audio on MIDI, or a mixture of both.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all
 - Version: Audacity 3.1.1 and earlier

**Additional context**
Flagged for @Tantacrul as a UX/design issue

Originally logged as a Proposal in the Audacity Wiki:
https://wiki.audacityteam.org/wiki/Proposal:_Render_MIDI_tracks_to_audio

There is a possible workaround but it depends on being able to set up Audacity to record audio that is playing on the computer and this is not always possible:
1. turn on Overdubbing in the Transport > Transport Options menu
2. import a MIDI file
3. set Audacity to record what is playing on computer (on W10 use WASAPI loopback)
4. Press Record.
The downside is that this is a real-time recording so for a long MIDI track will take a long time.

**Comment by petersampsonaudacity** [comment]
This alternative feature request logged on the Audacity Wiki garnered a fair few votes over the years.

>Allow direct import of MIDI files into Projects as sampled audio waveforms, which are then editable and exportable as WAV, MP3 etc.

**Comment by LWinterberg** [comment]
IMHO, as long as MIDI is in the sorry state that it is, it's somewhat pointless having such an option. Once a vaguely usable piano roll (and mayhaps VSTi/LV2 instrument support so you can actually change the sound of what you're playing) is on the plate, this one can be revisited though.

**Comment by petersampsonaudacity** [comment]
> IMHO, as long as MIDI is in the sorry state that it is, it's somewhat pointless having such an option.

I disagree the WHOLE point of this is to enable the user to convert an fairly useless imported MIDI track into something thy can actually use and edit with Audacity's tools - and export as audio.

**Comment by SteveDaulton** [comment]
FWIW, I think this feature request would be very useful. 
Most DAWs provide a way to render MIDI tracks as audio, even if they have good MIDI support. The case for Audacity to have MIDI rendering is even stronger **because** it is so strongly aligned to editing audio (rather than MIDI).

**Comment by petersampsonaudacity** [comment]
@LWinterberg  I would like to strongly appeal to have this re-instated

**Comment by LWinterberg** [comment]
The current MIDI support in Audacity is an unfinished and borderline unusable alpha, and while I do agree that a "render MIDI as audio" thing is needed before MIDI support is release ready, it just is the wrong starting place. Again, before such a feature becomes really useful in Audacity, it first needs to support assigning instruments of some kind, because right now, any online  "midi to wav" converter is able to produce an output as good as Audacity's.

**Comment by SteveDaulton** [comment]
> any online "midi to wav" converter is able to produce an output as good as Audacity's.

You must be using a crappy synth. A nice soundfont in Fluid produces a much better render than any online converter that I've come across.

**Comment by werame** [comment]
For a cheesy alternative, one could write a midi to labels converter and expand on a [STK based solution via Nyquist](https://forum.audacityteam.org/viewtopic.php?f=39&t=122972), although this won't easily give a [General MIDI](https://en.wikipedia.org/wiki/General_MIDI) synth. There's no direct Nyquist support for that... [nor for soundfonts](https://sourceforge.net/p/nyquist/discussion/410800/thread/c78e3e92/), which is often how GM is implemented, e.g. in fluidsynth. 

There's no direct support for [Nyquist reading the Audacity Note track](https://forum.audacityteam.org/viewtopic.php?f=39&t=122951&p=44382) either, which is why I had to resort to labels for my quick attempt at this.

**Comment by Paul-Licameli** [comment]
Why close this issue so soon?

Might this be a fine GSOC project idea?

**Comment by werame** [comment]
@Paul-Licameli  Fluidsynth for instance can opened as a library. But it has a really complex, even-based api, so it would be pretty much like yet another VSTi, but with its own API.
