### ISSUE TITLE
Graphic indicator of optimum recording level on the waveform display

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2399]
**Describe the bug**
Because the default waveform view is linear (where 50% would be a good recording level) many users needlessly oversaturate their signal believing that the waveform should fill the display area.

The default display of a Linear waveform encourages many users to try to fill the whole of the available 0.0 to plus or minus 1.0 of the gray space leading to an over-saturated (and sometimes clipped) capture. 

Note that this is less of a problem with the, non-default, "Waveform (dB)" display mode as the signal fills much more the visually available gray space, however the default view is the linear waveform display and this is the display type that most users will deploy. 

**To Reproduce**
1. Press Record
2. Observe no indication in the waveform display of an optimum recording level

**Expected behavior**
*A grey dashed line extending along the available wave form display set at +0.5 and -0.5 for linear waveform displays and set at -6dB for Waveform (dB) display.  Could be a line or dotted gray line if though visually superior.
*The gray dashed line should be super-imposed on the waveform so that it remains visible once the waveform exceeds the optimum level.
*This indicator display to be controlled by a Preferences setting (on or off) in the Recording section, or via a dialog accessed via a right-click in the waveform display   - default to be "on".
*Optionally: the user should be able to set their own "optimal" recording level via a further additional Preferences setting in the Recording section or via a dialog accessed via a right-click in the waveform display - default to be +/-0.5 or -6dB.

**Screenshots**
This screenshot uses an older version of Audacity - hence the different colorway and no Clip-handles
![image](https://user-images.githubusercontent.com/50205984/148936586-468d02e2-f533-4c7f-98cf-52b09443a242.png)

**Additional information (please complete the following information):**
 - OS: all
 - Version: all

**Additional context**
This was originally logged in the Audacity Wiki as a Proposal:
https://wiki.audacityteam.org/wiki/Proposal_Graphic_indicator_of_optimum_recording_level_on_the_waveform_display

_There are countless examples on the Internet where users post images or videos of Audacity usage where their signals are ridiculously over-saturated._

Flagging @Tantacrul  as a UX/design issue

**Comment by petersampsonaudacity** [comment]
### My Personal use-case
When I first started using Audacity to record and digitize my vinyl collect I initially fell into this trap.  

I was formerly used to pushing the levels on my Nakamichi tape deck to almost the red to saturate the signal to the tape record head.  I assumed similar was needed with Audacity and tried to produce full fat waveforms that filled the waveform display - it was only later that I learned that this was far from ideal.

**Comment by LWinterberg** [comment]
Question: Why shouldn't dB view be the default instead?

**Comment by petersampsonaudacity** [comment]
> Question: Why shouldn't dB view be the default instead?

I kinda have to pass on that one - you'd really need to ask that of Dominic Mazzoni and @rbdannenberg as that's the way they had it from the outset in 1.2.x - _in fact in 1.0.0 there was only linear waveform with no option at all for dB view_

**Comment by SteveDaulton** [comment]
> Question: Why shouldn't dB view be the default instead?

1. Because it's horrible for setting recording levels. 
2. Waveforms are visually distorted beyond recognition.
3. Depending on where the low end of the scale is pegged, the difference between a safe peak of -3dB and a critically dangerous level of 0 dB may be as small as 1 px.
4. There would undoubtedly be a massive increase in support questions for "why does my recording have so much noise" (due to misunderstanding the logarithmic scaling)
5. By default, anything below -60 dB is totally invisible, even when zoomed in.
6. For novice users, log scaling is much harder to interpret than a linear scale
7. Linear scaling is far more common in other apps.

Personally I think that dB labeling with linear scaling (like most other audio editor and DAWs) would be helpful (retaining the +/-1 labeling as an option).

**Comment by rbdannenberg** [comment]
Well said, Steve. I think once you have experience with other editors and have a feel for linear waveform displays, the dB view is very strange. It may have some advantages, but it would take a lot of getting used to. IMO, dB view might make more sense, at least when zoomed out, if it were unsigned, e.g., range from -60 to 0, instead of 0 (negative) to -60 to 0 (positive). I like how Logic switches views depending on the vertical space available.

**Comment by SteveDaulton** [comment]
Maybe it would be sufficient to just show the recording meter at full screen width by default.

Going a bit further, make the clip indicator on the meters more prominent (bigger).

Going much further, in addition to "View menu > Show Clipping", there could be a "View menu > Show Recording Guides". When both are enabled, it might look something like:


![show-recording-level-guides](https://user-images.githubusercontent.com/11681097/148979746-2d835b3f-74fc-4ecb-9a21-52ea6c92c195.png)

**Comment by petersampsonaudacity** [comment]
> Maybe it would be sufficient to just show the recording meter at full screen width by default.

Well that's what Koz and I have always done - I had it that way throughout my entire vinyl transcription, but that's because back then the default meters were much smaller than they are now.

Personally I think the default meters size (on W10 at least) are perfectly fine at half window size:
![image](https://user-images.githubusercontent.com/50205984/148984302-cc5ff1f7-afcc-4584-9043-faf1c4ea0763.png)

**Comment by LWinterberg** [comment]
We decided to not implement this, but add

* https://github.com/audacity/audacity/issues/2683 

eventually.
