### ISSUE TITLE
Latest audacity download has a trojan in it

### ISSUE THREAD

**Issue by julieljones** [audacity/audacity#2411]
**Describe the bug**
see title

sha 256 checksum matches, but it has a trojan

![image](https://user-images.githubusercontent.com/30325380/149038282-c309a258-d6d8-42e5-a0b2-0cacebf36f87.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**

**Comment by LWinterberg** [comment]
Windows: https://www.virustotal.com/gui/file/1a3e536efffc26dfb236d3961f4841116e3320485dcfaba2e86123a93998f505
Linux: https://www.virustotal.com/gui/file/c9db0b91e04830684b0322b4f9eb6d473bc42f4fef38acc91d5e576edb68791b
Mac: https://www.virustotal.com/gui/file/0e940c1c31213ea3c8c3cd3d56e893f74a595b3bae29456827f6c34173eabb1b - the Bkav Pro hit already got removed since your report.

The Audacity 3.0.0 dmg also got hit by Maxsecure: https://forum.audacityteam.org/viewtopic.php?t=116672
Seems like Maxsecure's heuristics just keep tripping up about something Audacity does. It's a false positive. Audacity does not have malware in it. 

Incidentally, [maxsecure itself gets flagged as a virus by Comodo and Webroot](https://www.virustotal.com/gui/url/2d1d0a427f9c69717e34fc7da2bc9fd3f4272b7cdde812cd130c9a51050d9c7b)
