### ISSUE TITLE
FFMPEG 5.0 support

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2445]
https://ffmpeg.org/download.html#release_5.0

**Comment by CanadianJeff** [comment]
i'm confused why would you create a duplicate issue that I already started and close mine it's kinda rude

**Comment by guiguidu60** [comment]
Should to be an important task because Audacity doesn't work on Fedora 36 due to this distro provides ffmpeg 5.0.

**Comment by Ryan-Miller-Audacity** [comment]
Verified on both Windows and MacOS with FFmpeg 5.0.1 exporting and importing of audio files of varying types is working as expected including FFMpeg needed types like: M4A, Opus (OggOpus), WMA, VC3 etc. I worked with a few custom FFmpeg export options as well and noted they worked as expected. Exported audios were properly usable as well as importable. 

Note that @LWinterberg observed #3185 which noted, but this was fixed by PR #3189 and confirmed to be working as part of this test. 

@crsib should open a separate issue to note the updates possibly needed to the prompt as we had discussed in DM? About older builds utilizing ffmpeg.64bit.dylib and newer libavformat.59.dylib and clearing that up?

**Comment by crsib** [comment]
We need a new issue, yes. I will open one

**Comment by ValZapod** [comment]
We need this commit to fix wrong decoding of HE-AAC. https://github.com/FFmpeg/FFmpeg/commit/5114ce1e2a4c71ddf4971ad3cf9bd43ae16571c3

Are you going to support master of ffmpeg?

**Comment by crsib** [comment]
As long as the master is binary compatible there will be no problem. The latest avformat version supported is now 59.

**Comment by ValZapod** [comment]
> The latest avformat version supported is now 59.

But it does not work. Shared build every 24 hours is here: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip

**Comment by crsib** [comment]
I have checked the latest build, importing and exporting work in general. Please provide more details on what does not work.

**Comment by ValZapod** [comment]
> I have checked the latest build

From the link above? I am on 3.1.3, BTW.

When I drag and drop mp4 file with aac inside it just does not work and prints a warning. Same for .aac or .eac3 raw bare files or mp4 with eac3.

**Comment by LWinterberg** [comment]
Audacity 3.1.3 was released december 2021, FFMPEG 5.0 only was released in January. So no, 3.1.3 does not support FFMPEG 5.0. Use https://audacityteam.org/nightly instead

**Comment by ValZapod** [comment]
YES! That works perfectly, and HE-AAC does not eat sound after priming
samples as fixed recently in ffmpeg (of course the remainder is still not
removed, that was a bug forever in ffmpeg, but no matter)! Thanks!
