### ISSUE TITLE
Clips. Position of pasted selection could be accidentally changed in some cases

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2461]
**Describe the bug**
There is another flaky bug. It has minor severity but looks bizarre.
Audacity 3.1.3 still has behaviour when selection of the waveform could be done across clip boardings. 

Like this, for example:
![image](https://user-images.githubusercontent.com/25851359/150499092-adcd7cf1-6373-47e2-a5ae-038dc3b47b5c.png)

**To Reproduce**
1. Add a clip
2. Trim the clip at the left a little
3. copy, then paste the selected region after the clip, like this:
![image](https://user-images.githubusercontent.com/25851359/150499601-3c46f4d1-d8da-4ac9-9739-265cbb30b96c.png)
![image](https://user-images.githubusercontent.com/25851359/150499648-a9f86559-160d-40ac-8787-962bf32400a8.png)

4. Observe the pasted selection around the piece of the waveform is not the same as been copied.

**Expected behavior**
All these copy-paste behaviours should be reconsidered, I think. 
But relatively to the current behaviour, as a user, I expect to paste right the same waveform and selection as been copied.

**Additional information (please complete the following information):**
 - OS: All
 - Version 3.1.3

**Comment by petersampsonaudacity** [comment]
> Audacity 3.1.3 still has behaviour when selection of the waveform could be done across clip boardings.

Your use case here only looks odd because you have a single track - with multiple tracks it can look less odd:

![image](https://user-images.githubusercontent.com/50205984/150508991-c2cc5253-50d4-4f43-a2fd-4b3ce985984d.png)

**Comment by SteveDaulton** [comment]
> Your use case here only looks odd because you have a single track

I don't think so. This looks like a genuine bug to me, and it occurs when there is hidden audio at the start of a "Smart Clip".

**Expected behaviour:**

1. Generate 5 second chirp
2. Drag the chirp to the right so that it starts at 5 seconds.
3. Select from 3 to 6 seconds
4. Copy
5. Add New track
6. Paste


![Expected](https://user-images.githubusercontent.com/11681097/150514755-e64df1d7-7083-4fcd-a166-920675e73d1c.png)


**Bug behaviour**

1. Generate 10 second chirp
2. Drag the left edge of the chirp to the right so that it starts at 5 seconds.
3. Select from 3 to 6 seconds
4. Copy
5. Add New track
6. Paste

![Bug](https://user-images.githubusercontent.com/11681097/150514810-58a714c6-e89a-4c9b-b688-5278d674b857.png)

**Comment by Penikov** [comment]
> > Audacity 3.1.3 still has behaviour when selection of the waveform could be done across clip boardings.

I've simplified the bug description just to reduce STR. The bug is reproducible both with a single track or with many tracks.
Users could have a reason to copy parts of waveform everywhere (even to another project). So I don't see something odd there.

**Comment by SteveDaulton** [comment]
P4 seems a bit low considering that it can mess up projects and there's no obvious workaround.
(https://github.com/audacity/audacity/issues/2429 would provide a workaround if implemented, and https://github.com/audacity/audacity/issues/2271 would provide the user with an indication of what the problem is.)

**Probably related to:**
https://github.com/audacity/audacity/issues/2436

**Comment by Penikov** [comment]
> P4 seems a bit low considering that it can mess up projects and there's no obvious workaround.
> (#2429 would provide a workaround if implemented, and #2271 would provide the user with an indication of what the problem is.)

Makes sense

**Comment by dozzzzer** [comment]
> Bug behaviour
> 
> Generate 10 second chirp
> Drag the left edge of the chirp to the right so that it starts at 5 seconds.
> Select from 3 to 6 seconds
> Copy
> Add New track
> Paste

Not reproducible anymore
3.4.2:

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/cefb1350-ef29-48d9-a860-b638cfbe449f">
