### ISSUE TITLE
Audacity crashes on Win 8.1

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2485]
Audacity crashes at startup on Windows 8.1

![image](https://user-images.githubusercontent.com/25851359/151320818-2e1b6d7f-906f-44c8-a400-8391fc762181.png)

**Additional information (please complete the following information):**
 - OS: Windows 8.1
 - Audacity: 3.1.3

**Comment by Jojo-Schmitz** [comment]
Looks familiar (I know this from MuseScore), it indicates a missing Windows update, see https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c

**Comment by werame** [comment]
Audacity is compiled with VS2019, so my guess is a different lib is needed. That page is for VS2015, as far as I can tell. I can probably try to repro this by resurrecting a Win7 image on a old computer. It should be missing the stuff as well.

**Comment by Jojo-Schmitz** [comment]
It might not be the right page, but the right direction ;-)

**Comment by werame** [comment]
Actually it might be right page. I didn't read it too carefully:

> Microsoft Visual Studio 2015 creates a dependency on the Universal CRT when applications are built by using the Windows 10 Software Development Kit (SDK). 

Probably VS2019 creates the same dependency. It's a Win10 SDK dll that's missing on older Win versions.

**Comment by werame** [comment]
Adobe [here](https://helpx.adobe.com/download-install/kb/error_on_launch.html) points to the ["Update for Universal C Runtime in Windows"](https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c) that was previously discussed  for th missing api-ms-win-crt-runtime-l1-1-0.dll. I think MSFT does not allow redistribution of that file, since even Adobe can't include it. So users would have to get it themselves.

**Comment by Jojo-Schmitz** [comment]
As far as I can tell it is free to redistribute

**Comment by werame** [comment]
The api-ms-win-crt-runtime-l1-1-0.dll
is *not* on [that list](https://docs.microsoft.com/en-us/visualstudio/releases/2022/redistribution#-distributable-code-files-for-visual-studio-2022).

**Comment by crsib** [comment]
3.1.3 runs just fine for me using clean Windows 7 and Windows 8.1 installs
