### ISSUE TITLE
“Effect” drop-down menu covers the rest

### ISSUE THREAD

**Issue by nr1995** [audacity/audacity#2571]
Hi, noob here.
This isn't a feature or a bug exactly.
But when you click “Effect” on the top bar,
it covers **Analyze**, **Tools**, and **Help**.

I get that the list is long,
but couldn't it start a few pixels lower?
So you don't have to click somewhere else before clicking back on **Tools**, for example?
Just seems like an oversight.
Thanks.

**Comment by petersampsonaudacity** [comment]
This is a known issue (already logged IIRC - but I can't find it right now).

It's really a Windows issue rather than an Audacity issue per se - it does not happen on Mac.

The situation is even worse if you don't work with a full screen Audacity window

![image](https://user-images.githubusercontent.com/50205984/154806552-d37e81ad-e794-471b-b6ba-a31c9d5d12ef.png)

**Comment by petersampsonaudacity** [comment]
See also:    Effect menu reorganization #501

**Comment by petersampsonaudacity** [comment]
@nr1995  you can ameliorate this by setting your effects to be "Grouped by type" in Effects preferences.

Please see:  https://manual.audacityteam.org/man/effects_preferences.html

**Comment by LWinterberg** [comment]
closing in favor of #501
