### ISSUE TITLE
Make the "Warning" about saving project less alarming

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2588]
**Is your feature request related to a problem? Please describe.**
Some new users see the "[Warning](https://manual.audacityteam.org/man/warnings_preferences.html)" about saving projects as an error, and get frustrated and confused that they can't save a project without getting this "error".

**Describe the solution you'd like**
The message about saving projects was added because many users were saving projects when they really wanted to export an audio file. The explanatory  messages went a long way towards solving that problem, but it alarms some users that interpret the "warning" as an "error" when really it is just "information".

**Describe alternatives you've considered**

**Additional context**

Suggest changing this:
![warning](https://user-images.githubusercontent.com/11681097/155507485-198bd5ea-e35e-4cc1-bdcb-1d673bbb5132.png)

to this (or similar):
![info](https://user-images.githubusercontent.com/11681097/155507580-92416176-e42c-4036-90dc-be4a7989b638.png)

**Comment by shubhangi013** [comment]
I'd like to work on this issue!

**Comment by LWinterberg** [comment]
go ahead, @shubhangi013!

**Comment by CoderHuman** [comment]
I'd also like to work on this issue.

**Comment by LWinterberg** [comment]
go ahead as well! @CoderHuman 

This issue seems to be just renaming a string (or perhaps exchanging a wxWidgets element?), so having a look through the code to understand what happens where is beneficial to everyone looking to contribute :)

**Comment by SteveDaulton** [comment]
> This issue seems to be just renaming a string

A bit more than that. The "Warning" string in the title bar is hard coded into the WarningDialog class.
See: [/src/widgets/Warning.cpp](https://github.com/audacity/audacity/blob/master/src/widgets/Warning.cpp)

**Comment by CoderHuman** [comment]
> go ahead as well! @CoderHuman
> 
> This issue seems to be just renaming a string (or perhaps exchanging a wxWidgets element?), so having a look through the code to understand what happens where is beneficial to everyone looking to contribute :)

Thanks! I have been trying to find a way around this and have understood the codebase from a bird's eye view. 

My approach would be to replace the "Warning" string using a compatible string variable and check if the internalDialogName variable is equal to "FirstProjectSave". If found true, I will set the string variable to "Information". 

But like @SteveDaulton said, the "Warning" string in the title bar is hard coded and I cannot find a way to replace it using a string variable. 

I would appreciate both of your (@LWinterberg and @SteveDaulton) help in my following questions:

1. Is this approach correct or would you recommend a better one?
2. What string datatype would be compatible to replace the "Warning" in XO()?
3. While dealing with the XO object, there is a mention of 'L' internally which cannot be seen in the code. This can be seen in the attached screenshot. What does that 'L' mean?

Apologies for any mistakes in my questions or with terminologies since I am very new to all of this, and this is the first issue I have taken. Thanks.

![Screenshot (5)_LI](https://user-images.githubusercontent.com/23549264/157308674-1af37839-4926-4c1f-be3d-899bdd6bde7e.jpg)

**Comment by mfnjairah** [comment]
I think, we can write "Make sure you save your project before exporting a file or leaving a project. Do you wanna save it?". And change the "Don't show this again" feature to "Always remind me". So if the user check the box, the app will always remind them but if not, the pop up will not show anymore.

**Comment by LWinterberg** [comment]
This dialog has been removed and integrated into the local vs cloud save dialog
