### ISSUE TITLE
Show the dialog about the plugins that didn’t load

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#2609]

**Comment by dozzzzer** [comment]
When enabling a faulty plug-in, Audacity freezes.
Find the above mentioned plug-in in the attached. After plug0ins are scanned, just go to Effects > Manage Plug-ins, find that VST and click [Enable]. Then submit by clicking [OK]. After that Audacity hangs.
![image](https://user-images.githubusercontent.com/70063970/169881125-ec0f1dea-f04d-4a8e-b105-774fbbdc9cd7.png)

[adelay.zip](https://github.com/audacity/audacity/files/8757169/adelay.zip)

**Comment by LWinterberg** [comment]
this feels like expected behavior to me. We disable a plugin for you because we can tell there's a problem with it with our automatic tests. However, it may be that our automatic tests aren't accurate and that it fails because it expects something to happen which gets suppressed in our test. In this case you're given the option to re-enable it here, and if it crashes that's kinda on you.

**Comment by vsverchinsky** [comment]
> When enabling a faulty plug-in, Audacity freezes.

Agreed with Leonard.
We run out-of-process plugin validation to check if it's safe to run plugins, and disable them by default if it's not safe
