### ISSUE TITLE
Cannot paste split clips into track

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2611]
**Describe the bug**
Attempting to paste audio containing one or more splits into another clip fails with warning message

**To Reproduce**
1. Launch a new project with factory default preferences
2. Generate a Chirp
3. Generate another Chirp into a new mono track
4. Select and copy the upper track
5. Select a few seconds near the middle of the second track
6. Paste
7. Observe that pasting works as expected.
8. Undo the paste
9. Add one or more splits to the first track to create 2 or more clips
10. Select and copy the upper track
11. Select a few seconds near the middle of the second track
12. Paste
13. Observe that the paste fails with message:
"There is not enough room available to past the selection"

**Expected behavior**
The clips on Audacity's clipboard to be pasted, replacing the selected audio.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04, macOS, Windows
 - Audacity 3.2.0, 3.3.2

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with 3.1.3 and latest 3.2.0 alpha master

**Comment by dozzzzer** [comment]
Confirmed on MacOS 11.6 with 3.1.3 and latest 3.2.0 alpha master

<img width="694" alt="image" src="https://user-images.githubusercontent.com/70063970/162400684-13d90982-b241-4e8e-8dff-24d253c1ab5d.png">

**Comment by dozzzzer** [comment]
Lowering the priority: there's a workaround that makes it possible to paste a split clip into the track. 
In order to do that, one needs to enable this option in the Preferences > Track Behaviors menu:

![image](https://github.com/audacity/audacity/assets/70063970/889c35bf-ed3d-4ae1-ad8c-724d73d6f2ae)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
