### ISSUE TITLE
Clicking window titlebar might click the window behind

### ISSUE THREAD

**Issue by KoBeWi** [audacity/audacity#2669]
**Describe the bug**
When I click the top of the window's title bar, it sometimes passes the click to window below. This happens when Audacity is maximized and I click at the very top of my screen. The window under Audacity will be clicked (although it seems random, like 40% of the times).
![Audacity title bar bug Windows](https://user-images.githubusercontent.com/2223172/158028895-34fc838d-078c-41de-8ed4-8eb6646aecf2.gif)
As you can see in the GIF, I click Audacity's title bar and it clicks another window instead. In the worst case, this happens when I try to close the window and it closes the other window instead. This does not happen with other applications, so I assume it's Audacity bug.

**To Reproduce**
1. Maximize Audacity
2. Click at the very top of the screen
3. Sometimes the window behind Audacity will be focused

**Expected behavior**
I expect that clicks on the top of the title bar will always be correctly handled, so the application windows behind Audacity aren't focused.

**Screenshots**
See the GIF above.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.0 (happened with older versions too)

**Additional context**
N/A

**Comment by LWinterberg** [comment]
This is a windows bug which can happen to any program. Some examples: 

* https://answers.microsoft.com/en-us/windows/forum/all/clicking-top-of-some-maximized-applications-causes/6eecf0d9-316e-4b70-8390-204f665facb1 
* https://www.reddit.com/r/Windows10/comments/iz7rvc/windows_10_grabs_the_window_behind_when_clicking/
* https://www.windowsphoneinfo.com/threads/windows-10-grabs-the-window-behind-when-clicking-on-the-very-top-edge-of-the-title-bar-of-a.435336/

It unfortunately isn't something we can fix

**Comment by KoBeWi** [comment]
> It unfortunately isn't something we can fix

That's not really true. Out of the ~10+ apps I use regularly, only Audacity exhibits this problem. Sure, it might be caused by Windows bug, but it's possible to workaround it, by changing window flags or some initialization logic or some stuff idk. The fact that it doesn't happen with other apps means that there IS something that can be done. It probably requires more investigation though.

**Comment by KoBeWi** [comment]
It does not really explain why that bug only affects Audacity (I never changed this option for any other app), but this solution fixes the issue, thanks.

**Comment by aztral** [comment]
I have the ACTUAL solution to your problem. You have a multiple monitors setup i assume. All monitors MUST use the same scaling as the primary monitor. My problem was 2x 4k monitors. primary with 200% scaling, and the other was 150%. I lowered the scaling to 2x 150% but also had to compensate the less scaling by lowering the resolution to 1440p on the main monitor. :( ... Anyways the fix is to use the same scaling on all monitors. 

Compatibility mode did not work for me. I have had this problem for months and tried EVERYTHING. Late last night i found the fix.

You might have to restart or logout to get the fix working.

**Comment by mejobloggs-cw** [comment]
How do we report this to Microsoft, it's driving me wild. About 50% of my programs do this, not just Audacity

**Comment by dan-goyette** [comment]
This reported issue is over two years old now, and should be considered for the possibility of reopening it. Simply stating that this is based on a Windows bug, as the justification for not fixing it, would seem reasonable if it seemed that the underlying OS bug was likely to be fixed in the near future. But given how long this has remained an open bug, that doesn't seem likely. 

As others have stated, I've never seen this in any other program other than Audacity. Do the devs know of a way to fix this without waiting for Windows to fix it? What's the reason Audacity can't correct this? Is there something specific to Audacity's UI framework that behaves differently to most every other Windows program? I'd like to know if this won't be fixed because A) Audacity devs still assume Windows will fix the bug, or B) It's impossible to fix for some technical reason.

**Comment by mejobloggs-cw** [comment]
> As others have stated, I've never seen this in any other program other than Audacity.

I can reproduce it with other apps, and it also depends on what app is underneath.

Here's how I reproduce:

- Use maximised Firefox or Gimp as underneath app
- Use maximised  Notepad++ as top app
- or, maximised Microsoft Sql Server Management Studio  as top app
- Click on a specific part of the title bar right at  the top of the screen as shown in the screengrab of the original issue description

If Firefox or Gimp is not the bottom app, I cannot reproduce the issue.

I have only noticed the issue with Notepad++ and Sql Management as top app. I have tried other apps but the issue is not present for them. No doubt there is plenty more

**Comment by aztral** [comment]
They dont typically do anything about these things. Microsoft is not about being best, Its about being first and biggest. Which means shitting down consumers throat 😅

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

På man., 13 maj, 2024 kl. 04:45, mejobloggs-cw ***@***.***(mailto:På man., 13 maj, 2024 kl. 04:45, mejobloggs-cw <<a href=)> skrev:

**Comment by LWinterberg** [comment]
FWIW: We'll be changing the entire UI for Audacity 4, so it may fix itself once we do that.
