### ISSUE TITLE
Audio setup menu rework

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#2717]
@LWinterberg could you please add a few words as a description for this task?

@ksoze95 please contact @LWinterberg for designs and spec details

**Comment by LWinterberg** [comment]
This is the audio settings dropdown. 

![image](https://user-images.githubusercontent.com/87814144/159690376-0da9387f-a69a-4ad0-a16c-883469a69599.png)

**Comment by DavidBailes** [comment]
@LWinterberg .  Will the user interactions with this dropdown be the same as a standard dropdown menu?

**Comment by LWinterberg** [comment]
Yes-ish. Ideally it should stay open even after clicking on any action, and only close when you click outside it or click the "Audio Settings..." entry.

**Comment by DavidBailes** [comment]
It doesn't look like a wxWidgets menu, because it contains headings for the various sections. And if it were to stay open after clicking an item, then it really isn't a menu. In addition, I don't know how it could be made accessible for users of screen readers, as headings in menus aren't part of the msaa api.
Why not just have a dialog instead - then users can change as many things as they want before closing it, and the accessibility would be straigtforward.

**Comment by DavidBailes** [comment]
> How does the current version deal with the devices toolbar and the devices settings?

Here's NVDA's speech output when tabbing along the device toolbar:

Audio Host  combo box  Windows WASAPI  collapsed
Recording Device  combo box  Microphone (USB Audio Device)  collapsed
Recording Channels  combo box  1 (Mono) Recording Channel  collapsed
Playback Device  combo box  Speakers (Realtek High Definition Audio)  collapsed

And tabbing through device settings in Preferences:

Interface  grouping
Host:  combo box  Windows WASAPI  collapsed  Alt+h
Playback  grouping
Device:  combo box  Speakers (Realtek High Definition Audio)  collapsed  Alt+d
Recording  grouping
Device:  combo box  Microphone (USB Audio Device)  collapsed  Alt+v
Channels:  combo box  1 (Mono)  collapsed  Alt+n

On Windows you can start and stop the Narrator screen reader by pressing Ctrl+Windows Key + Enter, if you want to check this out for yourself. There are minor differences between Jaws, NVDA, and Narrator.
