### ISSUE TITLE
Simplify asynchronous stereo tracks

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2722]
The current implementation where the left and right channels are allowed to not be sync'd causes more trouble than it solves: 

* You can't trim both channels at the same time
* When collapsed, no waveform is visible at all
* The logic on when only one channel gets moved and when both get moved is weird
* It makes it seem like there's 3 types of audio tracks: Mono, Stereo and Stereo with double clip handles
* The right channel clip cannot be renamed through shortcuts

Especially in the light of clip grouping/3.3, I think we need to take a long, hard look at whether this "double clip handle" idea is still the way to go, or whether converting these tracks to double-mono tracks instead would be better, or yet something else.

related issues:

* #2708
* #1910
* #2154
* #2618

**Comment by Paul-Licameli** [comment]
My opinion was that the showing and hiding of right-channel drag handles should be an on-off switch in the user interface, and not something inherent in the track data that affects the serialized data saved in the project file.

I objected to the path the implementation ended up taking.  Two stereo tracks, identical in their contents, yet differing in the history of how they were made (one: was always stereo, another: was made by dragging equal length mono clips into alignment), are stored differently and that is weird and I think just wrong.

**Comment by petersampsonaudacity** [comment]
See also #2708 and #2709

**Comment by LWinterberg** [comment]
> My opinion was that the showing and hiding of right-channel drag handles should be an on-off switch in the user interface, and not something inherent in the track data that affects the serialized data saved in the project file.

I agree with the second half of that sentence, but not the first half. A UI toggle, in addition to being clumsy, does not address any of the other problems.

**Comment by petersampsonaudacity** [comment]
See also:
 Make Stereo Track can result in a track with different clipnames for each channel #1850

**Comment by petersampsonaudacity** [comment]
And see also #2709

**Comment by Paul-Licameli** [comment]
> > My opinion was that the showing and hiding of right-channel drag handles should be an on-off switch in the user interface, and not something inherent in the track data that affects the serialized data saved in the project file.
> 
> I agree with the second half of that sentence, but not the first half. A UI toggle, in addition to being clumsy, does not address any of the other problems.

@LWinterberg  You are not thinking this through.

The second part implies the first, as I will explain; and it's an irrelevant objection, that this doesn't address all of your points in the top comment.  It is not meant to.

But it surely is meant to address the fourth point -- that there are three "types" of tracks when there should be only two.  The distinction between stereo tracks with right drag bars, and those without, should be only an "extrinsic" and temporary display option, not an "intrinsic" distinction that gets stuck in the persistent data with no way for you to change it.

(But we now have this unfortunate persistent distinction, over my strong objections during 3.1 development. And it is a consequence of NOT IMPLEMENTING A UI TOGGLE, as I was recommending then.)

Grant my second part, but don't admit any transient UI switch either -- then, it can only be a RULE that decides how to make the display, from the instantaneous STATE of data, not from its editing HISTORY. 

Consider:

- Stereo tracks are joined into mono, and the clips align.  Right hand drag bars?  A RULE must say no, because we agree we surely don't want them in newly made whole stereo tracks either with "inherent" alignment.
- You really want to drag aligned clips out of alignment.  But then you have no way but to split stereo to mono, drag clips, and join them again, which is even clumsier.
- You want to do the opposite -- drag unaligned clips, of equal length, into alignment.  But (assuming only one clip in each channel), then the RULE implies that the right hand drag bars must disappear.  Maybe the drag bar disappears only at mouse-up -- not snapping out from under your pointer while you are dragging it.  But would that disappearance be desirable?  I doubt it.  The "thing" I was interacting with (a right hand clip) ceases to be in the UI (loses its distinct thing-ness) but I'm not expecting that.  I wasn't doing any kind of explicit merge or delete operation meant to destroy it.

So I see the need for some way to switch right hand drag bars on and off.

**Comment by SteveDaulton** [comment]
> Two stereo tracks, identical in their contents, yet differing in the history of how they were made ..., are stored differently and that is weird and I think just wrong.

Yes that is weird.

From a user perspective, an intuitive model would be:

* The track window contains none or more audio tracks
* A track contains none or more clips
* A clip contains one or more audio channels

Where there is one _kind_ of audio track, and one _kind_ of audio clip.

With this model, an audio clip would have one drag bar no matter how many channels of audio it contains.

A reasonable limitation would be that all clips in a track must contain the same number of audio channels, but other than that it provides a flexible model (could be extended to more than 2 channels) that is easy to understand and use.


> that there are three "types" of tracks when there should be only two.

Or only one "type" of audio track.

If Audacity is to ever support surround sound, then we would not want different "types" of audio track for 1, 2, 3, 4, 5... audio channels. We would want just one "type" of audio track that maps a specified number of channels (in the clips) to a specified set of "ports" (the simple case being to map 1 or 2 channels to 2 ports, aka "pan").


> * You really want to drag aligned clips out of alignment

That is an extremely rare user requirement. IMO it is sufficiently rare that the _inconvenience_ of having to split the track into separate mono tracks is acceptable. Supporting a stack of separate channel clips within a single track seems like unnecessary complication for such an uncommon use case, especially as we need to retain splitting into mono tracks anyway.

**Comment by petersampsonaudacity** [comment]
> > * You really want to drag aligned clips out of alignment
> 
> That is an extremely rare user requirement. IMO it is sufficiently rare that the _inconvenience_ of having to split the track into separate mono tracks is acceptable. Supporting a stack of separate channel clips within a single track seems like unnecessary complication for such an uncommon use case, especially as we need to retain splitting into mono tracks anyway.

I am strongly minded to agree with @SteveDaulton about this

**Comment by LWinterberg** [comment]
Paul, I think that stereo tracks (or n-channel tracks, for that matter) never need to have unaligned content. If you want content that moves independently, you should make multiple tracks.

**Comment by Paul-Licameli** [comment]
> Paul, I think that stereo tracks (or n-channel tracks, for that matter) never need to have unaligned content. If you want content that moves independently, you should make multiple tracks.

If that is agreed, then much simplification does follow.  But I don't know that this is agreed.  It's one person's opinion.  ("I think...")  I don't know that everyone on the Forum would necessarily agree.  Don't think just about music production, think about more general sound manipulation.

To commit to this is to subtract capability from Audacity, which does now allow the greater generality of unaligned clips as an unusual possibility.

If we abandon unaligned tracks, but the command to join mono tracks into stereo remains, then (without undesirable complications of the data model), it would change behavior, and lose information.  The information about where clips started and ended would be destroyed by padding clips at start or end so that they do align.  If you split stereo to mono again, you would not get the same clips you started with.

If it is agreed to preserve, not subtract, that greater generality, then I have explained why there does exist the need for some kind of UI switch to turn the display of right channel drag bars on and off.

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli  it is not just "one person's opinion" - I agree with both @LWinterberg and @SteveDaulton that what you are trying to achieve with double-drag-barred asynchronous stereo tracks avn already be readily achieved by using multiple travks and splitting stereo tracks.

The double-drag-barred asynchronous stereo tracks  look like a "classic solution in search of a problem" to me.  This will be a comapratively rare use case even among power users and can already be achieved without too much trouble at all with mutliple tracks - and we have always been proud of the fact that Audacity is and always has been a multi-track editor.

Whereas with the introduction of double-drag-barred asynchronous stereo tracks is the introduction af new issues, some of which may be yet to be discovered and a raising in complexity of the User Experience (flagging @Tantacrul as a UX/design issue).

**Comment by Tantacrul** [comment]
@Paul-Licameli couldn't agree more

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli couldn't agree more

Agree with what or whom?

I don’t argue for or against one or another user interface, but it’s my job to think about the implications for the implementation and maintainability.

**Comment by Paul-Licameli** [comment]
Re-read what I asked about what the joining of mono tracks into stereo ought to do, and answer.

**Comment by Tantacrul** [comment]
To put it simply, from a user's POV: you can have a stereo track or a mono track and that's it. No more double drag handles. If you combine two mono tracks, it becomes a stereo track. If you are unhappy with the syncing, you split it back to two mono tracks again.

**Comment by Paul-Licameli** [comment]
“whether converting these tracks to double-mono tracks instead would be better” from the OP

@LWinterberg explain please, Indont understand.

**Comment by Paul-Licameli** [comment]
“take a long, hard look” (OP)

Yes, indeed.

I think we all sense a mismatch between the user model we want, and the data model we inherited in legacy code and had to adapt.

3.1 made only an incomplete, imperfect adaptation of that data model to the demands of easy clip dragging and smart clip boundaries.  Never mind the even greater ambitions of overlapping clips to come!  And that is for me and other developers to judge.  Not for those who don’t code to presume to know and judge.  I love you, and I don’t want to sound arrogant, but that’s truth.

Original Audacity had no notion of division of tracks into clips, and doing that was a major reorganization before my time with the project.  @SteveDaulton and @petersampsonaudacity and @JamesCrook and @lllucius and @rbdannenberg could tell you more about the history than I know.

What I know is that the neat and reasonable user model @SteveDaulton described is not what legacy left us.  Channels, not clips that might span channels, are the primary division of stored audio data that we have in this program.  For good or ill (I vote ill), stereo tracks simply aren’t  “things” in the object model we have now but more like mere display artifacts.

What I also know is that 3.1, with its time pressures, ended up with an implementation I wasn’t wholly at peace with.

And I think it is the joining of mono tracks into stereo that is the root of the problem.  If this operation is still to be supported, then I suggest the “long, hard look” begins here, with a consideration of all the corner cases.

What happens when clips don’t align?  I think it’s a reasonable expectation that re-splitting should give back the clip division you started with.  But if that property can be sacrificed — ok then, it simplifies much, but do understand what is sacrificed.

Besides that, consider all the other right channel data might just have to be lost:  clip names, or clip colors, differences of sample rates, whether the clip offset times (stored as real numbers, not discrete multiples of the sample interval) must move slightly (by a fraction of the sample interval), etc etc etc.

**Comment by petersampsonaudacity** [comment]
> And I think it is the joining of mono tracks into stereo that is the root of the problem. If this operation is still to be supported, then I suggest the “long, hard look” begins here, with a consideration of all the corner cases.

This has been a fundamental part of  Adacity's functionality from it's very first release 1.0.0 that Dominic Mazzoni provided, right up to the present day 3.1.3 (and 3.2.0 alpha)  

It has always enabled users to edit and manipulate/edit the two channels of a stereo project independently.

And this is a valuable feature for many users, this I know from having read many posts on the Forum over the past 18 years or so, many times I (and others have advised users how to split a  stero track, sork on the channels indepently in split tracks and then recombine their stereo track.

The simpe answer to the issues that you raise (and they are important issues, I agree) is that:
IF you, as a user that is, want to have a stereo project made up of two (or more) separate tracks where each one has different Sample Rates and Sample Formats, may hve overlapppin clips etc. etc 
THEN you need to work with them as separate tracks up until the time you are ready to coalese thes into a stero track.

This may take several oparations if you are using more than twp tracks as you would need to Mix all the left channel contributors into a single track and likewise for the impending right channel.  This because Make Stereo Track in the TCP omly operates on two "mono" tracks one above the other.

Audacity has a fairly simple rule when it makes such a stereo track: the upper track dominates, so its Sample Rate, Sample Format and Track Name is what the merged stero track will end up with (this is similar for Mixing tracks too BTW).

_Note that multiple tracks like this and varied Sample Rates/Formats is very much power-user territory.  For most Audacity users the situation is much simpler their Sample Rates and Sample Frormats will all be the same - and their tracks' Sample Rates will match the Project Rate._

### Aside
I can recall discussions in the past wher it was suggested that there should only ever be one Sample Rate in a progect and that should be governed by the Project Rate in the Selection Toolbar:
1. all recordings are made at that rate
2. all imports are automatically converted to that rate
3. If the user changes the Project Rate, then all tracks are automatically resampled

**Comment by petersampsonaudacity** [comment]
The simpe answer to the issues that you raise (and they are important issues, I agree) is that (as @SteveDaulton said earlier in this thread):
**IF** you, as a user that is, want to have a stereo project made up of two (or more) separate tracks where each one has different Sample Rates and Sample Formats, may have overlappping clips etc. etc 
**THEN** you need to work with them as separate tracks up until the time you are ready to coalese thes into a stero track.

This may take several oparations if you are using more than twp tracks as you would need to Mix all the left channel contributors into a single track and likewise for the impending right channel.  This because Make Stereo Track in the TCP omly operates on two "mono" tracks one above the other.

Audacity has a fairly simple rule when it makes such a stereo track: the upper track dominates, so its Sample Rate, Sample Format and Track Name is what the merged stero track will end up with (this is similar for Mixing tracks too BTW).

_Note that multiple tracks like this and varied Sample Rates/Formats is very much power-user territory.  For most Audacity users the situation is much simpler their Sample Rates and Sample Frormats will all be the same - and their tracks' Sample Rates will match the Project Rate._

### Aside
I can recall discussions in the past wher it was suggested that there should only ever be one Sample Rate in a progect and that should be governed by the Project Rate in the Selection Toolbar:
1. all recordings are made at that rate
2. all imports are automatically converted to that rate
3. If the user changes the Project Rate, then all tracks are automatically resampled

**Comment by Paul-Licameli** [comment]
The more I think about, the more I like the ideal of reorganizing the audio data around, call them “wide clips” that can be multi channel, and accepting that joining mono to stereo should be a more limited operation that can lose data.

But there will great challenge to make this reorganization, with much existing code to re-examine.  3.1 met one challenge to allow the hidden data in the narrow clips, without addressing the need for wide clips too.

If 3.3 is going to be a maintenance release with few features, let there be advance work on the wide clips problem accomplished in it, with its implications for the channel joining command.

Let’s nail problem before we move on to the next difficulties in allowing overlap of clips.

Also, a different problem, is stereo track (not clip) data that doesn’t logically belong to one channel only (like the name, pan, gain, etc) but are implemented now with duplication of data in tracks.  I want to fix that too and have made some advance work on it in this release.

**Comment by SteveDaulton** [comment]
****

> What happens when clips don’t align? I think it’s a reasonable expectation that re-splitting should give back the clip division you started with. 

Before joining:

![Full Window000](https://user-images.githubusercontent.com/11681097/172046814-5977a54f-0241-41b5-9bd5-d0ffd20916ef.png)

After joining:

![Full Window001](https://user-images.githubusercontent.com/11681097/172046841-baa2631e-af80-4d9b-b4a7-efd077b4badc.png)

**Comment by petersampsonaudacity** [comment]
@SteveDaulton I don't understand what you are getting at - can you provided explicit steps to reproduce please?

**Comment by Paul-Licameli** [comment]
> @SteveDaulton I don't understand what you are getting at - can you provided explicit steps to reproduce please?

I think this was hypothetical behavior.

I'm saying the root of the design problem, that started this entire discussion, is that we have long had an operation to merge mono tracks into stereo, which lets you split the track again and get back the original.

It was unquestioned conservatism (often a good thing) that preserved this behavior in 3.1 but led to the unhappy 
"three kinds of tracks."

So I ask how should things behave if we abandon the requirement and let the joining of tracks change the boundaries of clips.

Steve illustrates one possible answer.

Still unspecified is what we must do when the given clips also carry hidden data.  Maybe they have corresponding start times but differing lengths of hidden data.

**Comment by Tantacrul** [comment]
> > What happens when clips don’t align? I think it’s a reasonable expectation that re-splitting should give back the clip division you started with.
> 
> Before joining:
> 
> ![Full Window000](https://user-images.githubusercontent.com/11681097/172046814-5977a54f-0241-41b5-9bd5-d0ffd20916ef.png)
> 
> After joining:
> 
> ![Full Window001](https://user-images.githubusercontent.com/11681097/172046841-baa2631e-af80-4d9b-b4a7-efd077b4badc.png)

This is a decent compromise, I think

**Comment by Paul-Licameli** [comment]
> 
> This is a decent compromise, I think

How indeed could it be otherwise?  Each clip boundary may have hidden wave data on it that we don't want to destroy, therefore a boundary at one time in one channel must become a boundary in the other channel.

The alternative that leaves only one clip in the right channel would destroy any hidden wave data on the short clip.

Unless, the alternative made use of the cut-lines feature.  https://manual.audacityteam.org/man/preferences_settings_that_affect_edit_behavior.html#example_cuts

**Comment by Tantacrul** [comment]
@Paul-Licameli - perhaps I didn't read enough into that visual. My opinion here is that we can go even simpler. The question for me is:

- Why is it important for a user that hidden information in clips is maintained when two mono tracks are combined?

I can't really think of a good reason other than a hypothetical that it _might_ be convenient.

I think when two clips are combined, it should be a destructive action:

- Remove all clip boundary information, including hidden audio. A stereo clip is simply one large clip with silences generated where necessary.
- Add silence where needed
- Discard the lower clip's name

If the user doesn't like this, they can always undo the action. I really think it should be that simple.

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli - perhaps I didn't read enough into that visual. My opinion here is that we can go even simpler. The question for me is:
> 
> * Why is it important for a user that hidden information in clips is maintained when two mono tracks are combined?
> 
> I can't really think of a good reason other than a hypothetical that it _might_ be convenient.
> 
> I think when two clips are combined, it should be a destructive action:
> 
> * Remove all clip boundary information, including hidden audio. A stereo clip is simply one large clip with silences generated where necessary
> * Discard the lower clip's name
> 
> If the user doesn't like this, they can always undo the action. I really think it should be that simple.

There must be some "destruction" of information, in the sense that splitting the track again (not by Undo) will not necessarily restore the tracks as they were:  the number and extents of clips may change, and details of clip properties (name, also clip waveform color https://manual.audacityteam.org/man/audacity_tracks_and_clips.html#movecolors) may be lost.

But we don't have to lose hidden wave data.  We might preserve that with only a little more effort.  I think we should, and I think the user's expectation would be that we should.

**Comment by Tantacrul** [comment]
I heavily suspect it would be extra effort for no real benefit - and possibly more complication to slow us down in future too.

Once we get into the user case of someone merging two tracks into one and then splitting them again (rather than pressing 'Undo') we've entered into the territory of the extremely unlikely.

**Comment by Paul-Licameli** [comment]
> I heavily suspect it would be extra effort for no real benefit - and possibly more complication to slow us down in future too.
> 
> Once we get into the user case of someone merging two tracks into one and then splitting them again (rather than pressing 'Undo') we've entered into the territory of the extremely unlikely.

You misunderstand:  if anyone does joint two tracks into one, and those tracks contain hidden wave data -- then that should be preserved.  (No matter whether there is then a splitting of the track again.)

That is the small extra effort I mean.  That hidden wave data is information that is not easily recreated (unlike a color or a name) and should not be destroyed.

We could, I think we should.

Otherwise, to merge tracks without losing hidden wave data, one would have to drag the clip ends out, merge the tracks, then drag the clip ends back again.

**Comment by Paul-Licameli** [comment]
If hidden wave data is not always preserved, it should be at least sometimes preserved.

Maybe we would rather make one clip in each channel, than three in each, in @SteveDaulton 's example.

Maybe we then lose hidden wave data from the short clip.  But I would want to preserve it if present on the long clip, and that implies making an equal length of hidden, silent data on the right channel clip.  I think that would be very small additional difficulty, once we have overcome the large difficulties of implementing wide clips at all.

**Comment by SteveDaulton** [comment]
> @SteveDaulton I don't understand what you are getting at - can you provided explicit steps to reproduce please?

Sorry Peter, I had a performance today so didn't have time to be more explicit.

Paul highlighted the issue (and I agree) that after joining mono tracks into a stereo (or multi-channel) track, we should be able to split the track again without losing data. The screenshots proposes a way of doing that while also having the same start and end times for each channel in a stereo clip.

In the case of joining mono track clips that have different start / end  times, every clip boundary is retained. In the example that I posted, this requires adding two new "splits" (clip boundaries) to the longer clip. Splits do not lose data. The two outer clips are padded with silence so that both channels have the same start / end times in every clip. On _exploding_ the stereo track back into mono tracks, we gain two silent clips in one channel, but all data, including start / end times are preserved.

I didn't go into what happens regarding hidden audio data as I would not want to base other changes on what I see to be a flawed design (but that's off-topic for this issue). For now I'd be tempted to go with Martin's suggestion of destroying hidden audio on joining mono tracks, as that's probably the simplest solution. Another possible (but more complex) approach could be to retain the hidden data, but only allow it to be accessed after splitting the stereo track back to mono tracks (because the hidden data is mono).

**Comment by Paul-Licameli** [comment]
> I didn't go into what happens regarding hidden audio data as I would not want to base other changes on what I see to be a flawed design (but that's off-topic for this issue). 

At the risk of side tracking this discussion I ask whether your complaint is with
- something positively in the design or
- omissions of cases from an incomplete design or
-  unaddressed bugs in the realization of the design
- 

Those are different things.  Briefly please cite issue ## that exist, or open new ones as needed.

**Comment by SteveDaulton** [comment]
> At the risk of side tracking this discussion

Let's not do that. I'll email you and we can discuss if you want to.

**Comment by petersampsonaudacity** [comment]
@crsib @LWinterberg @dozzzer 

Any chance that @Tantacrul 's decision on this can be implemented (for 3.2.0)

**Comment by Tantacrul** [comment]
I think we've arrives at consensus on the desired change. However, I suspect we're a little too late to fit it in for 3.2.0. 

We have a few things we'd like to quickly release / fix in 3.2.x and I'd place the improvement that would close this issue in there.

**Comment by Paul-Licameli** [comment]
> I think we've arrives at consensus on the desired change. However, I suspect we're a little too late to fit it in for 3.2.0.
> 
> We have a few things we'd like to quickly release / fix in 3.2.x and I'd place the improvement that would close this issue in there.
> 
> Unless the task is quite a big one to implement. Then it might take a little longer - but we should change the existing behaviour for sure.

YES!!!  This is definitely another one of those things with much deeper implementation ripples than you might guess from the surface.  Not an alpha thing, not a patch release thing.

**Comment by Paul-Licameli** [comment]
> > I think we've arrives at consensus on the desired change. However, I suspect we're a little too late to fit it in for 3.2.0.
> > We have a few things we'd like to quickly release / fix in 3.2.x and I'd place the improvement that would close this issue in there.
> > Unless the task is quite a big one to implement. Then it might take a little longer - but we should change the existing behaviour for sure.
> 
> YES!!! This is definitely another one of those things with much deeper implementation ripples than you might guess from the surface. Not an alpha thing, not a patch release thing.

Kindly @Tantacrul do not even presume to qualify your guesses about "a little" longer before you consult with programmers about it.

This requires a significant realignment of the data model, as I think I wrote up there, and as @SteveDaulton should surely know too.

**Comment by Paul-Licameli** [comment]
> @crsib @LWinterberg @DozZzeR
> 
> Any chance that @Tantacrul 's decision on this can be implemented (for 3.2.0)



> I think we've arrives at consensus on the desired change. However, I suspect we're a little too late to fit it in for 3.2.0.
> 
> We have a few things we'd like to quickly release / fix in 3.2.x and I'd place the improvement that would close this issue in there.
> 
> Unless the task is quite a big one to implement. Then it might take a little longer - but we should change the existing behaviour for sure.

At the risk of tiresomeness.  I must SCREAM!!!!!! it at you all once more:  THIS!!! IS!!!! HUGE!!!! in effort.

**Comment by Paul-Licameli** [comment]
Some context was lost.  What decision of @Tantacrul did @petersampsonaudacity just refer to?  I just reread all of this long thread and I don't know what you mean.

If it's only about this issue https://github.com/audacity/audacity/issues/2722#issuecomment-1143944901 that is minor.

What is the "consensus" @Tantacrul just said?  If it means implementing what @SteveDaulton outlines in https://github.com/audacity/audacity/issues/2722#issuecomment-1143944901, that is GIGANTIC and not to be underestimated.

**Comment by Tantacrul** [comment]
> Kindly @Tantacrul do not even presume to qualify your guesses about "a little" longer before you consult with programmers about it.

OK Paul 😄

**Comment by petersampsonaudacity** [comment]
> Some context was lost. What decision of @Tantacrul did @petersampsonaudacity just refer to? I just reread all of this long thread and I don't know what you mean.

In this very thread @Tantacrul wrote on 04Jun22
>To put it simply, from a user's POV: you can have a stereo track or a mono track and that's it. No more double drag handles. If you combine two mono tracks, it becomes a stereo track. If you are unhappy with the syncing, you split it back to two mono tracks again.

He went on to say on 05Jun22 (also in this very thread)
>I heavily suspect it would be extra effort for no real benefit - and possibly more complication to slow us down in future too.
>Once we get into the usercase of someone merging two tracks into one and then splitting them again (rather than pressing 'Undo') we've entered into the territory of the extremely unlikely.


As Martin @Tantacrul succinct;y points out:
You can work with two asynchronous mono channels, one panned left and the other panned right, quite separately up to the point where you are happy and then, and only then, combine them into a stereo track.


What he is saying (and I agree with him and Leo @LWinterberg does too) is that there is no need for this compound third type of audio track - a stereo track with asynchronous channels and two drag-bars.  There are already sufficient Audacity tools to deal with asynchronous left and right channels if required, without over-complicating the matter.

I am no longer privvy to the design decisions that Muse takes so I have no idea if this idea of an asynch compound stereo track was ever part of the design schema or not - but given that Leo and Martin are against this, I supect not.



> If it's only about this issue #2618 that is minor.
No it is not just about #2618 - more importantly it is about this issue #2722

But yes 2618 should really be fixed too.

**Comment by petersampsonaudacity** [comment]
> YES!!! This is definitely another one of those things with much deeper implementation ripples than you might guess from the surface.

Surely there should be no implementation ripples if all you do when making a stereo track from a pair of mono tracks is to simply make a normal stereo track with a single Clip-handle drag-bar.  

What is complicated about that?

**Comment by Paul-Licameli** [comment]
Of course, just removing the ability to merge stereo tracks into mono would eliminate much difficulty.  But would that be an acceptable subtraction of capability?

**Comment by petersampsonaudacity** [comment]
> Of course, just removing the ability to merge mono tracks into stereo would eliminate much difficulty. But would that be an acceptable subtraction of capability?

I presume you really are joking here Paul ...   ;-)

We have had Make ster0o track from two mono tracks since Audacity 1.0.0 (0.98b even

![image](https://user-images.githubusercontent.com/50205984/188320842-3a9915ae-1c0c-45f1-9fe3-8429ca8ab59f.png)

**Comment by Paul-Licameli** [comment]
> > Of course, just removing the ability to merge mono tracks into stereo would eliminate much difficulty. But would that be an acceptable subtraction of capability?
> 
> I presume you really are joking here Paul ... ;-)
> 
> We have had Make stereo track from two mono tracks since Audacity 1.0.0 (0.98b even
> 
> ![image](https://user-images.githubusercontent.com/50205984/188320842-3a9915ae-1c0c-45f1-9fe3-8429ca8ab59f.png)

There’s one vote no, then, for doing the easier thing (which is still not an easy thing).

**Comment by Paul-Licameli** [comment]
Wow, long before my time on the project.  Not even the sync-lock button as a pair of chain links.

Makes me want to say `awwww....`

**Comment by Paul-Licameli** [comment]
Less drastic but simplifying away certain problems:  permit joining mono tracks into stereo only when there is a correspondence of all clip boundaries, hidden clip durations, and (when overlapping clips exist) the "z-orderings" if those are not determined by an automatic rule but might be changed by the user.

And maybe other consitency criteria:  sample formats, rates, crossfade curves.  Or perhaps not:  let the left channel prevail and the right channel data be lost, such as name and color.  Reformat and resample the right to match the left.

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli @LWinterberg @Tantacrul @SteveDaulton 

I have been looking at this again today following a Forum post from a confused user who wanted to remove the right channel clip-handle drag-bars:
https://forum.audacityteam.org/viewtopic.php?f=46&t=127771&p=459128

The workaround is to Mix&Render the track - **_BUT_**:
a) any inter-clip gaps are rendered as silence so the clippiness is lost
b) the rendered track loses all the useful clip-names that the user may have carefully entered (the rendered track is renamed from the track name in the TCP

And BTW the Forum poster decided they really wanted their clip-names and the clippiness so decided just to put up with having clip-handle drag-bars per channel.

------------------------------------------------------

If the ability to have clip-handle drag-bars is a desirable piece of functionality (and I'm still not convinced it is) then we really ought to have: 
 
1) a way, a command probably, for the user to actually turn a normal stereo track with a single clip-handle drag-bar into one with clip-handles per-channel.  At the moment the only way for the user to do this is via a totally undocumented "easter-egg", splitting and then re-joining a stereo track.

2) a parallel command that turns a stereo track with per-channel Clip-handle drag-bars into a stereo track with just the one, per-track, set of clip-handle drag-bars.

3) the ability to always be able to move the clips on one channel independently from the other channel.
Right now 
a) if the clips are in any way asynchronous in the two channels then dragging in one channel will only move the clip in that channel.
b) BUT if the clips in both channels are exactly synchronous, then dragging a clip in one channel will synchronously move the track in the other channel.
This just seems silly to me.  For a start if the user wants to get two formerly synchronous clips in different channels synced again then the yellow snap guides are extremely helpful for this.

4) If the "feature" is to be kept then it jolly well ought to be documented on the GitBook Clips page (the Editing page):
https://support.audacityteam.org/basics/audacity-editing

If all the above are done then we **_might_** have something that is useful to some users - a move towards async per-channel editing/processing of a stereo track - but right now it just looks half-baked.

**Comment by JohnColket** [comment]
This issue was mentioned here: https://forum.audacityteam.org/viewtopic.php?p=464522#p464522 by forum user kentagent.

**Comment by petersampsonaudacity** [comment]
And here's a poor user on the Forum confounded by this:

https://forum.audacityteam.org/t/editing-stereo-track-channels-have-unlinked/72802

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli 

### Use Case
User has a stereo track whe only one of the channels has repairs to be made or processing to be done
User does not want the required editing/processing to affect the good channel
So user splits the stero track and works on the dirty channel
User then rejoins the two channels as a stereo track

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli
> 
> ### Use Case
> User has a stereo track whe only one of the channels has repairs to be made or processing to be done User does not want the required editing/processing to affect the good channel So user splits the stero track and works on the dirty channel User then rejoins the two channels as a stereo track

I think you mean to describe a case where there is no change of duration?

What we're contemplating now -- to simplify the design specification, and the programming work, at least for the next release -- is that when mono tracks are joined into stereo, we would simply do as if rendering the track for export, except that nondestructive effects would not be applied.

This would be destructive of hidden clip data and cut-lines.  This would also make just one long stereo clip, whatever clip division existed before.

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli  here is a real-life usa case that has just popped up on the Forum:
https://forum.audacityteam.org/t/different-audio-channels-in-stereo-track/75099

**Comment by crsib** [comment]
I'm not quite sure if this is a real life example really :-) In any case, the only issue is with joining tracks with randomly misaligned clips etc

**Comment by Tantacrul** [comment]
Yeah that's just an example of someone who wants to combine two mini clips into a stereo clip

**Comment by LWinterberg** [comment]
this has been fixed, stereo tracks no longer do asynchronous content
