### ISSUE TITLE
Error message: "There is not enough room available to paste the selection"

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2723]
**Is your feature request related to a problem? Please describe.**
Users on the forum have reported being baffled by this error message, especially as they could be doing the exact same steps in an older version of Audacity without the problem occurring.

The error occurs when applying an effect to a clip, that increases the length of the clip. In older versions of Audacity the error would not occur unless the user had explicitly disabled "Editing a clip can move other clips", whereas that option is now disabled by default.

This can happen when applying "Change Speed", "Change Tempo", "Delay", or even simply pasting audio into a gap between clips.

**Describe the solution you'd like**
Make "Split Cut" more visible in the Edit menu, and re-enable "Editing a clip can move other clips" as the default.

Ideally there would also be a "punch paste" option that would automatically fit the audio on the clipboard into the selected space. Currently [a plug-in](https://forum.audacityteam.org/viewtopic.php?p=208312#p208312) is required to do this.

**Describe alternatives you've considered**
Make the option "Editing a clip can move other clips" specific to "Edit" commands (Cut / Paste / Delete /...) only, so that it doesn't restrict effects. However, such inconsistent behaviour is likely to confuse users as much as the problem it is trying to solve.

**Additional context**
The rationale for removing the default behaviour "Editing a clip can move other clips" is described here:
https://youtu.be/HpA138b-J9s?t=28
If the user was aware of "Split Cut" then the "problem" described in that video would not have been a problem.

In many cases, moving other clips when a clip is deleted is exactly the behaviour that the user wants, but there is now no obvious way to do that.

**Comment by LWinterberg** [comment]
> In many cases, moving other clips when a clip is deleted is exactly the behaviour that the user wants, but there is now no obvious way to do that.

Turn on the setting again?

Anyhow, this change will not be reverted, as it'll disappear completely when overlapping clips get introduced.

**Comment by SteveDaulton** [comment]
> Turn on the setting again?

Yes, if they are aware of the option that is buried in a subsection of Preferences, but that's not "obvious".


> it'll disappear completely when overlapping clips get introduced.

Is that likely to happen soon? It sounds like a nice idea, but probably a lot more difficult than it first appears.

**Comment by LWinterberg** [comment]
> Is that likely to happen soon?

It's targeted as the main feature for 3.3

**Comment by petersampsonaudacity** [comment]
> > Is that likely to happen soon?
> 
> It's targeted as the main feature for 3.3

And what is the planned timeframe for that please ?

**Comment by petersampsonaudacity** [comment]
I've just had to respond to yet another user (on the Audacity Users Facebook Group)  who is baffled by the behavior caused by the change of default setting for this preference.

>Perhaps someone here knows the answer to this. So I upgraded to the latest version and now when I try to cut or paste a clip in the timeline it doesn't seem to affect the rest of the timeline and I'm not sure why.
I'll try to explain further: i have several separate sound clips I've copied and pasted into a timeline. If i delete a chunk of time, say 10 seconds, everything on that timeline moves back 10 seconds. Similarly if i paste 10 seconds of audio everything moves forward. Now instead it's telling me that it doesn't have enough space to paste anything that exceeds blank spaces in the timeline. Any help getting this back to normal would be greatly appreciated!

**Comment by developer-controls** [comment]
What about Macros that also currently produce the "There is not enough room available to paste the selection." error when the "Editing a clip can move other clips" option is turned off? If this option is completely removed in 3.3, will there be changes or additional options for the macro commands so that these can be made to work again?

Here's an example:

```
SelectTime:End="-0.5" RelativeTo="ProjectEnd" Start="0"
Silence:Use_Preset="<Current Settings>"
Select:End="0" Mode="Set" RelativeTo="ProjectEnd" Start="0.5"
Copy:
CursProjectStart:
Paste:
SelectTime:End="-0.5" RelativeTo="ProjectEnd" Start="0"
Noise:Amplitude="0.3" Type="White"
Select:End="0" Mode="Set" RelativeTo="ProjectEnd" Start="0.5"
Copy:
CursProjectStart:
Paste:
SelectAll:
Join:
Compress&dynamics:compress-ratio="0.85" floor="-32" hardness="0.6" noise-factor="2" scale-max="0.65" use-percep="0"
SelectTime:End="1" RelativeTo="ProjectStart" Start="0"
Delete:
SelectTime:End="0" RelativeTo="ProjectEnd" Start="1"
Delete:
CursProjectStart:
```

I know I can add a command to the start to set the option (SetPreference:Name="/GUI/EditClipCanMove" Reload="0" Value="1"), but if the option is gone in 3.3, will that still work?

**Comment by LWinterberg** [comment]
> What about Macros that also currently produce the "There is not enough room available to paste the selection." error when the "Editing a clip can move other clips" option is turned off

When overlapping clips are a thing, this error simply cannot happen. Even if a clip exists after the current selection, any pasted clip would simply overlap it if it collides.

Also, overlapping clips won't make it into 3.3, though still are on the shortlist for upcoming releases.

**Comment by developer-controls** [comment]
@LWinterberg  thanks. To be clear, does that mean that paste operations in macros will continue to work with their original parameters, or will some changes be needed to support the new overlapping clips feature so that if the paste is not at the end, it will function as an insert, pushing the rest of the clip back? If the paste operation just overwrites the existing audio, the macro would be as broken as it is with error message we just started getting with the default change on "Editing a clip can move other clips" from enabled to disabled (a breaking change already implemented, so skepticism by users is warranted here).
