### ISSUE TITLE
Cannot type certain regional characters into a label

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#2748]
**Describe the bug**
When adding a label, regional characters (ż, ź, ś, etc.) cannot be typed.

**To Reproduce**
1. Start adding a label by pressing Ctrl+B or Ctrl+M
2. After the cursor pops up, start typing into the field using regional characters, e.g.: ż, ć, ś etc.

**Expected behavior**
All the characters typed from the keyboard display on the label

**Additional information (please complete the following information):**
 - OS: MacOS Big Sur 11.6, Win 10x64 19041.804
 - Audacity 3.1.3

**Additional context**
The following characters can be used to test against: 
- ś ż ź ć ł (Polish keyboard), 
- Altgr+q (= @) and altgr+shift+ß (=ẞ) (German keyboard),
- Altgr+8/9 (Danish keyboard).

**Comment by DavidBailes** [comment]
As a work around, you can enable the "use dialog for the name of a new label" option which is in the track behaviors section of the Preferences dialog.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Comment by chinakov** [comment]
Tested, Altgr now works, thanks!
