### ISSUE TITLE
Combine the Mixer toolbar with the meter toolbars

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2779]
![image](https://user-images.githubusercontent.com/87814144/162411523-13074e0d-6847-4ec8-9563-8d1ebf545ae6.png)

This code already is in DarkAudacity (and perhaps as `EXPERIMENTAL_METER_SLIDERS` in Audacity itself?)

Compared to the DarkAudacity implementation, there should be some changes: 

- [ ] Keep the numbering on the meter
- [ ] Keep using the gradient style, don't use the LED or RMS style
- [ ] Change the sliders to be logarithmic relative to the meter range. That is to say, if Preferences > Interface specifies a range of -60dB, the slider should go from -60dB to 0dB. However, if the slider is dragged to the left beyond the meter area, the volume should be set to -inf. 
- [ ] Add accessibility as specified in figma
- [ ] OPTIONAL: Make the slider respond to the meter options (dB (default) vs linear).

**Comment by petersampsonaudacity** [comment]
OOH, yes please _(lets us free up some tooldock real estate)_ 

@JamesCrook  was always intending to migrate this to normal Audacity at some stage but never got around to it.  

IIRC I think Gale Andrews (RIP) blocked this particular enhancement when we worked on moving many of James' changes for DarkAudacity (including Themes) into the mainstream.

**Comment by petersampsonaudacity** [comment]
But hopefully you will do it retaining the current default of Gradient meters rather than the older RMS meters that @JamesCrook  had as his default (and as show in @LWinterberg  Leo's first post in this thread

**Comment by petersampsonaudacity** [comment]
As part of that change 0 @JamesCrook also added some rather nice digital metering that gave the meters a more modern look

![image](https://user-images.githubusercontent.com/50205984/162467284-bdd76891-179c-42ac-9f5f-103dfe7fa5c1.png)

I presume the code for that also exists in DarkAudacity - so this too should be quick and easy to implement - any chance that this can make it into 3.2.0 >

**Comment by petersampsonaudacity** [comment]
Note that @JamesCrook  removed the numbers on the metering for DarkAudacity - the Team consensus at the time was that we all felt that the numbers were useful and should remain.

**Comment by DavidBailes** [comment]
> Compared to the DarkAudacity implementation, there should be some changes:

another necessary change is that these new meters need to to be made accessible for users of screen readers - they are not in the version in dark audacity.

My suggested way of doing this is follows.
Currently each meter is a single panel, which is focusable. Change this to the meter panel containing a left and a right panel. The containing panel is no longer focusable, but both the left and right panels are.
The left hand panel contains the playback/recordinging icon, and the right hand panel contains the meter display which includes the slider.
The left panel:
- keyboard interaction is the same as the keyboard interaction of the meter in Audacity
- visual focus indication is the same
- the accessible object is the same.
The right hand panel:
- keyboard interaction is for a slider - ie the same as for one of the mixer sliders, and uses the same %changes for arrow keys and page up/down (not those in dark audacity).
- needs some visual focus indication.
- needs a new accessible object so that it is read as a slider by screen readers.

**Comment by petersampsonaudacity** [comment]
@ksoze95 @Tantacrul @LWinterberg 

I note that this has been closed - but I thought it was agreed that the sliders in these combined toolbars should be made to look more "slidery" rather than just moving over the old blue circles that we had in the old Mixer Toolbar.  In the combined toolbars the blue circles look a bit lost.

![image](https://user-images.githubusercontent.com/50205984/178970836-5f875efd-fab6-4ebb-bfe0-d6ff15c8cc4a.png)

_But I do like the way the upper tooldock is getting ever more slimmed down_

**Comment by LWinterberg** [comment]
aye, the slider images will get updated shortly

**Comment by DavidBailes** [comment]
> @DavidBailes I have created issue #3230 for this.

Thanks.
There is also the issue of ensuring that screen readers read the slider correctly (see my comment: https://github.com/audacity/audacity/pull/3133#issuecomment-1165457322)
Will issue #3230 include this?

**Comment by ksoze95** [comment]
> There is also the issue of ensuring that screen readers read the slider correctly (see my comment: [#3133 (comment)](https://github.com/audacity/audacity/pull/3133#issuecomment-1165457322))
> Will issue #3230 include this?

Yes.

**Comment by petersampsonaudacity** [comment]
This does not work at all well with vertically oriented meters.  For a start the slider still moves horizontally even though the meter orientation is vertical ...

![image](https://user-images.githubusercontent.com/50205984/178983359-37b26140-da47-4846-882e-8a58bbb1ff5e.png)

**Comment by petersampsonaudacity** [comment]
@LWinterberg @ksoze95 @Tantacrul 

Plus we now seem to have lost the ability to turn on monitoring with the combined input Toolbar - do we need a new issue logged for this?

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/179029238-17750592-108a-487a-8800-fd629d56c01b.png)
these two are buttons :)
