### ISSUE TITLE
Cosmetic changes to Incompatible Plugins popup

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#2809]
**Describe the bug**
When there's only one incompatible plug-in was found, the wordin needs to be changed

**To Reproduce**
1. Make plugin scan fail with just one incompatible plug-in
2. Check the wording

**Actual behavior**
"1 incompatible plugins"; "are disabled"

**Expected behavior**
"1 incompatible plugin"; "is disabled"

**Screenshots**
![image](https://user-images.githubusercontent.com/70063970/162964856-414452bc-4e6d-4a00-8838-c7401b642cfa.png)

**Additional information (please complete the following information):**
 - OS: Win10
 - Version 
[audacity-win-3.2.0-alpha-20220411+3cc8dd9-x64-msvc2022](https://github.com/audacity/audacity/suites/6075123286/artifacts/210202710)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
