### ISSUE TITLE
A side tone is  audible, at circa 1kHz, when playing a generated a sine tone

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2908]
**Describe the bug**
A side tone is  audible, at circa 1kHz, when playing a generated a sine tone.

This is only audible - the side tone cannot be seen on a spectrum plot of the tone

**To Reproduce**
1. Generate a 15kHz Sine tone _(this is beyond the range of my aged ears these days)_
2. Press Play
3. Observe: a tone of about 1kHz emanates from the speakers
4. select the tone
5. Tools > Analyze Spectrum
6. Observe: tone preset at 15kHz - nothing preset at circa 1kHz ( see Screenshot 1)

Note that this low tone also afflicts generated Chirps - I tested a chirp starting at 10kHz _(I can hear that)_ and ending at 15kHz and the low hum is there throughout.

**Actual behavior**
A side tone of around 1Kz is heard

**Expected behavior**
Only 1 15khz tone to be heard (providing your hearing is good enough

**Screenshots**
### Plot Spectrum
![image](https://user-images.githubusercontent.com/50205984/167621750-1c19d69f-58cc-4573-8ff6-0868516e88fc.png)

### Zooming in on the 15kHz tone
![image](https://user-images.githubusercontent.com/50205984/167621862-c671b680-ff6a-4c34-a34e-5a158fa20b8a.png)
If you zoom in to sample level on my 15kHz tone - you will observe that the tone is actually made up of 3 separate sine waves.
This makes me suspect that this is some kind of pulsing caused by the different elements of the generated tone.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version 3.1.3 and latest alpha master  3.2.0 (and all earlier)
 - Sound Device Windows MME, WDS & WASAPI - on-board Realtek soundcard

**Additional context**
This is not a regression, its has been in Audacity from its very early days.
a) It's not present in in Audacity 1.0 - but that's only because there was no tone generator in the early versions
b) 1.2.6 (the next earliest version I have) does exhibit this audible low tone - but also has a hiss. And so does 1.3.0
c) by 1.3.2 you just get the extra audible low tone and this is the same right up to 1.3.1 and 1.3.2 alpha

This was reported on the Forum by a user attempting to conduct some psychoacoustic testing - he wrote:

> I use this tones to measure students upper hearing range in a psychophysics course. It is difficult to measure this range when there are artifacts of easily hearable lower frequency sounds, despite they have lower ampliltude. The tones have ramps, so there is no clicking at the beginning and ending of each tone.
>
>Nevertheless people hear tones when the "official" frequency is well above their hearing range. I have reproduced this artifacts with the German audacity 3.0 as well as with the English version 3.1.3. I have tested 2 USB sound cards, both reproduce this bug. Interestingly, the Spectrogram does not show any tones except the high frequency "original" tone.

See full Forum thread:  https://forum.audacityteam.org/viewtopic.php?f=46&t=125509&p=450921

**Comment by Paul-Licameli** [comment]
@rbdannenberg  ? Some aliasing is happening I think, very dependent on device setup.

**Comment by rbdannenberg** [comment]
I can't explain the 1kHz yet, but the apparent "3 separate sine waves" is really a visual/perceptual artifact. Every sample at N is near to the one at N+3 because 15kHz is close to 44.1/3 = 14.7, making the signal roughly periodic with a period of 3 samples. It appears that there are 3 sine waves with frequency 15-14.7=0.3kHz.  But that's an illusion. If you actually synthesized and added these tones, you'd get one very smooth 0.3kHz tone. (I now see Steve beat me to this explanation on the Forum).

It's significant that the spectral analysis shows nothing at 1kHz. To check further, I low-pass filtered at 1500Hz and 48dB/octave roll-off. Zooming in, it appears that there is no signal left except the expected transient at the beginning.

DACs do many things. Some upsample to 48kHz in software, many use oversampling with internal upsampling. I think some aliasing outside of Audacity must be generating 1kHz in the output process. I can't reproduce any problem on my Mac using it's built-in audio.

**Comment by SteveDaulton** [comment]
In addition to Roger's comment, it's difficult to work out exactly where the aliasing is occurring because in a typical PC setup there could be resampling in multiple places.

I think that my tests in [this forum post](https://forum.audacityteam.org/viewtopic.php?p=450929#p450929) illustrate that Audacity's resampling is working correctly (low quality real-time resampling produces some noticeable aliasing, but medium or higher quality resampling don't).

Resampling may also occur in the computer's sound system and / or the sound card and / or whatever magic bluetooth is doing.

The visual _illusion_ is unavoidable at certain zoom levels unless the waveform was drawn as a line only without the sample "dots", though I think it could look less weird with a "bandwidth limited curve" option as an alternative to the "stem plot" / "Connect the dots" representations. (I do _not_ think that removing the dots would be a good idea, but connecting dots with a bandwidth limited curve would be a nice enhancement).

@petersampsonaudacity It may be interesting to repeat your tests using WASAPI in Exclusive mode.

Unless the issue here is a feature request regarding how the waveform is visually represented, I think this is "not a bug".

**Comment by petersampsonaudacity** [comment]
> @petersampsonaudacity It may be interesting to repeat your tests using WASAPI in Exclusive mode.

It already is and was - this is the default setting it came with IIRC
![image](https://user-images.githubusercontent.com/50205984/167654470-d3970d7b-0c63-4971-91d1-e47e3e8ad4c2.png)



> Unless the issue here is a feature request regarding how the waveform is visually represented, I think this is "not a bug".

I am minded to agree.

**Comment by petersampsonaudacity** [comment]
> but the sample rate in the "Speaker / Headphones Properties" is 48000, while Audacity is playing at 44100, so there is resampling. If your system will work with the "Speaker / Headphones Properties" set to 44100, then you will probably avoid this aliasing issue. (or set Audacity to 48000 for Project Rate and Track sample rate).

The HP Envy/Realtek only has 24-bit 48000 and 16-bit 48000 as the available options for output - it cannot, AFAICT, be set to 44100

Oddly for  mic input it offers 16-bit 44100 and 16-bit 48000
![image](https://user-images.githubusercontent.com/50205984/167663232-07716422-efff-452e-80b5-f83886b7b19e.png)

The Stereo Mix only has 16-bit 48000:
![image](https://user-images.githubusercontent.com/50205984/167663588-5cce71a6-89fd-4390-9945-ef58b7ff3b86.png)

**Comment by petersampsonaudacity** [comment]
And following @rbdannenberg  Roger's Mac test I tested with my Macbook Pro Monterey - and I get similar results/

a) No phantom tone with either the onboard speakers or the Sennheiser cans

b) phantom tones do occur with either of my wired active loudspeakers.

**Comment by Paul-Licameli** [comment]
I think there is no issue to fix in the software.  This is all about appropriate devices for the task.

**Comment by petersampsonaudacity** [comment]
> I think there is no issue to fix in the software. This is all about appropriate devices for the task.

I agree
