### ISSUE TITLE
Effects converted to be realtime will not be fully available (until a manual reset of pluginregistry.cfg)

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#2928]
We need to fix this because:
When we would release a new version with builtin effects made realtime, users would not be able to use them fully realtime.

steps:
1) make a non-realtime-effect capable of being realtime (must be a dev, or build a commit which does so)
2) have an audio track, DO NOT select any region of it, try instantiating the effect

expected behavior: the effect dialog comes up (this happens for instance with estabilished realtime-capable effects, e.g. wahwah)

what happens instead: a dialog saying "you must select some audio first" comes up i.e. audacity still believes that the effect is of the destructive-only kind.

Internal code inspection pointed out that the dialog came up because some effect flag was not matching the required flags (most likely, the required flags indicated "I need the effect to be realtime" but the effect's flag said "I am not realtime")

BUT... after deleting pluginregistry.cfg and restarting the app, the above does not happen anymore -
i.e. the reverb dialog comes up without problems. Internal inspection confirmed that after this, the effect's flags were different.

When deleting (or renaming) pluginregistry.cfg and restarting the app, a new pluginregistry.cfg is created;

Inspecting the rebuilt pluginregistry.cfg, confirmed that this line was present for the effect:

    EffectRealtime=1

while in the deleted pluginregistry.cfg it was:

    EffectRealtime=0

Conclusion: 
We need Audacity to do a full rescan of the builtin effects at runtime, updating the entries in pluginregistry.cfg and the runtime flags.

Question: is https://github.com/audacity/audacity/issues/2608 already fixing this?

**Comment by Paul-Licameli** [comment]
I'm not aware anyone is fixing this.  It's good that you found the problem.  Maybe you overspecify the solution.  The solution might simply be:  ignore the "EffectRealtime" information formerly written into the config file.

Because, I think this is part of a larger problem in the legacy code:  many queries of properties of effects are quite unnecessarily duplicated into a persistent form in the config file, but then the persistent forms, and not the run-time queries, are actually used again.

I think Audacity should just stop doing that.

**Comment by Paul-Licameli** [comment]
#2965
