### ISSUE TITLE
Incorrect pixel rounding for small waveforms

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2929]
**Describe the bug**
At certain zoom levels / track heights, very low signal levels may be drawn 2 px high when it should b 1 px.

**To Reproduce**
1. Generate a few seconds of Square Wave, 11025 Hz, 0.8 amplitude.
2. Normalize to -64 dB
3. Slowly drag the track height down and up

**Actual behavior**
Observe that the waveform alternates between 1 px and 2 px while dragging.

**Expected behavior**
The waveform to appear as a 1 px high horizontal line until the track height exceeds 1188 px, (or zoomed in a long way vertically).

(-64 dB == +/- 0.000630957 linear. For a track height of 792 px, the waveform height works out as 1189 x 0.000630957 x 2 = 1.500415746, which should round up to 2 px.)

**Screenshots**

![Tracks000](https://user-images.githubusercontent.com/11681097/168278568-b572e684-6ce7-4f5e-aba3-a5137f1d3ffd.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04. Expected all platforms.
 - Version Audacity 3.1.3

**Additional context**
Probably the cause of this observation: https://github.com/audacity/audacity/issues/2371#issuecomment-1125410765

**Comment by dozzzzer** [comment]
Confirm this bug on MacOS Monterey.
<img width="484" alt="image" src="https://user-images.githubusercontent.com/70063970/168285666-76dd4fd1-6936-4391-8d6a-79523473bb37.png">

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
