### ISSUE TITLE
Improved plug-in validation performance

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2951]
Reports from @SteveDaulton that checking large numbers of plug-ins is very slow.

I conjecture that the present implementation, validating no more than one plug-in at a time, is making a bottleneck that might be relieved without great difficulty.

- AsyncPluginValidator could manage not just one, but a pool of Servers, each with its own worker process.
- How many?  std::this_thread:hardware_concurrency might be a good number
- The AsyncPluginValidator can report the maximum size of the pool, and weaken the preconditions on its use, so that the number of outstanding requests at one time may be more than one but not more than the reported number

**Comment by SteveDaulton** [comment]
> Reports from @SteveDaulton that checking large numbers of plug-ins is very slow.

No, not "very slow". Searching for plug-ins hangs (stops) entirely.

**Comment by vsverchinsky** [comment]
> > Reports from @SteveDaulton that checking large numbers of plug-ins is very slow.
> 
> No, not "very slow". Searching for plug-ins hangs (stops) entirely.

This is due to a bug which stops the whole process, I have a fix for it which I'll push soon. What Paul suggests may speed up the process, but it surely can't fix this bug with freeze.

> AsyncPluginValidator could manage not just one, but a pool of Servers, each with its own worker process.
 
Or create a pool of validators, each of them could pick the plugin from the queue. Peak memory consumption will significantly raise though. The whole process of validation takes almost same amount of time as if you enabled all available plugins in previous version of Audacity.

**Comment by Paul-Licameli** [comment]
Does the freeze happen in release builds as well as in debug?
