### ISSUE TITLE
Logo is displayed incorrectly (KDE neon)

### ISSUE THREAD

**Issue by rebio** [audacity/audacity#2964]
**Describe the bug**
Logo is displayed incorrectly

**To Reproduce**
1. Open the Start menu (logo of the application in the start menu)
or
1. Open Audacity (logo of the application in the task bar)

**Actual behavior**
Logo has a square in the middle where it should have a gradient(?)

**Expected behavior**
Logo has the kinda football shaped yellow part between the headphones

**Screenshots**
How it looks:
![Audacity logo](https://user-images.githubusercontent.com/10911084/169814005-ee17c93a-e009-479b-94e5-228af5a449ac.png)

How I would expect it to look
![Audacity logo splash](https://user-images.githubusercontent.com/10911084/169814411-29ba29d6-6557-4284-9e7e-8061701a4deb.png)

**Additional information (please complete the following information):**
Operating System: KDE neon 5.24
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.13.0-41-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 4800H with Radeon Graphics
Memory: 30.8 GiB of RAM
Graphics Processor: AMD RENOIR

Audacity: 3.1.3

**Additional context**
It could very well be that KDE is the one to blame for this, however I never saw this with any other logo.

**Comment by dozzzzer** [comment]
Most likely it's KDE-related issue, thus we cannot do anything about it.

**Comment by afontenot** [comment]
Hi, I'm the author of a relevant KDE bug: https://bugs.kde.org/show_bug.cgi?id=448234

The issue is that we're using the Qt library's support for SVG images, which is only partial. Among other things, their subset of the spec does not support clip paths. Any desktop environment that relies on Qt for this should show this same issue. At KDE we would like to move to an SVG renderer with better support, but doing this in every place SVG rendering is used is difficult and probably will not happen soon.

The Audacity icon uses clip paths pretty minimally, and while it's the cleanest way of achieving the effects in the icon, it's actually easy to generate a version of the icon without clip paths that should be visually identical. In case you'd like to use this icon to enable better compatibility with Qt environments, I'm including it below.

I release the changes involved in transforming the work below into the public domain or as CC-0.

![audacity](https://user-images.githubusercontent.com/3870410/176563471-0be078b2-2cba-43b8-8763-3095bb53340c.svg)
