### ISSUE TITLE
Improper pointer type when saving a project

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3007]
**Describe the bug**
When saving a project, the cursor pointer type is 'text' while it should be 'standard' or 'link'

**To Reproduce**
1. Navigate to Save Project As window
2. Hover over Cancel/Save buttons to see the cursor pointer's type

**Actual behavior**
It's 'text'

**Expected behavior**
It's 'standard' or 'link'

**Screenshots**
<img width="361" alt="image" src="https://user-images.githubusercontent.com/70063970/170995803-e900adb1-16f7-46ae-8d4f-ae1f44979af4.png">

**Additional information (please complete the following information):**
 - OS: MacOS
 - Version: alpha 3.2.0

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
