### ISSUE TITLE
The vertical amplitude scale displays values improperly when being resized

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3010]
**Describe the bug**
When resizing a track up and down, some values (-0.9) get hidden when they should be shown.

**To Reproduce**
1. Create a mono track
2. Set the vertical scale to Linear
3. Slowly drag the lower edge of the track down so that more values can be displayed on the scale
4. Once the scale is big enough to display smaller values with intervals equal to 0.1, take a look at -0.9

**Actual behavior**
-0.9 value is missing:

**Expected behavior**
All the values with an interval of 0.1 are displayed at once

**Screenshots**
https://user-images.githubusercontent.com/70063970/171178059-88aa3510-b20a-4764-a463-3d56c1613efa.mp4

**Additional information (please complete the following information):**
 - OS: MacOS 12.3.1
 - Version: latest alpha master

**Comment by Ryan-Miller-Audacity** [comment]
Yes, this is certainly the case. Reproduce on recent 3.2 alpha on MacOS Monterey 12.3.1.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
