### ISSUE TITLE
Cannot start play with AU effect

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#3011]
**Describe the bug**
Since commit `8e51ac7` (on master) AudioUnit effect can not be used in realtime: when pressing the play button, the command is refused (a system "beep" is heard)

**To Reproduce**
1. generate a mono track
2. instantiate an AudioUnit effect (e.g. AUGraphicEQ)
3. try pressing the play button on the Audacity window (i.e. not the one on the AU dialog)

**Actual behavior**
A system "beep" is heard and playback does not start

**Expected behavior**
Playback should start and the audio be processed by the AU

**Additional information (please complete the following information):**
 - OS: MacOS 
 - Version: local build done on commit # in description

**Additional context**
Steps 1-3 were tried on Windows, with VST and builtin effects, and no bug was observed there.

**Comment by Paul-Licameli** [comment]
Closing this:  because it will be resolved when effects are moved to statelessness, and the temporary changes in `SupportsRealtime` are undone to allow those effects to go into the sidebars.

But meanwhile, when the effects are accessed from the main menu, the dialog is modal and that explains the beep.
