### ISSUE TITLE
Change location of the manual to online

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3083]
Specifically, 

1. in the interface preferences in the Display category, switch the Location of Manual to online.
2. hide the option in the preferences.
3. Don't package the manual

**Comment by petersampsonaudacity** [comment]
So will the user still have the option of downloading a local Manual and switching the Manual location to be local?

I ask this because on the Forum recently In response to @LWinterberg Leo's post about the future of the Manual there was a heartfelt plea on behalf of all "road-warrior" users of Audacity who when travelling often had no or vert limited access to the Internet for an online Manual.

**Comment by petersampsonaudacity** [comment]
And the wiki-based old_Manual for 3.2.0 has been updated for this.
