### ISSUE TITLE
Hover state of the "Add new effect" button is missing

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3113]
@vsverchinsky Hover state of the "Add new effect" button is missing:

<img width="269" alt="image" src="https://user-images.githubusercontent.com/70063970/171145417-d340a036-ccc3-46f7-9ebd-51b6d0a9760a.png">

And when the button is pressed, it should be darker:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/70063970/171146123-6f9135f6-5499-426f-ac26-de9b3c747031.png">

Compare with the designs:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/70063970/171145601-0ea15b28-7d18-45d4-b6dc-9036a58fc973.png">

_Originally posted by @dozzzzer in https://github.com/audacity/audacity/issues/2845#issuecomment-1141915844_

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
