### ISSUE TITLE
Transport toolbar cropped after moving

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3131]
**Describe the bug**
After dragging the Transport toolbar out of the dock and repositioning, the right end of the toolbar is cropped

**To Reproduce**
1. Drag the Transport Toolbar to a different position in the GUI

**Actual behavior**
The right end of the toolbar is cropped (see screenshot)

**Expected behavior**
Properly formed toolbars.

**Screenshots**

![transport](https://user-images.githubusercontent.com/11681097/175373691-8e512667-8ee6-4bd9-9e6a-954eefa84bc0.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.2.0 e46d75

**Additional context**
Also occurs in deaa3f

**Comment by dozzzzer** [comment]
I confirm this on MacOS 12.2.1:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/70063970/175541153-e62b8936-ef1e-4140-8a13-1da0b150291f.png">

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
