### ISSUE TITLE
3.2-Alpha Tools>ResetConfiguration confuses Screen Maximized State

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3132]
Windows 10 Audacity 3.2.0-alpha-20220623 e46d75

(So I encountered this problem while trying to uncover inconsistencies in the Toobar Management)

1) Start Audacity 3.1.3
2) Maximize screen if not already maximized
3) Tools > Reset Configuration
   Screen is redrawn, but remains maximized
4) Exit Audacity 3.1.3

5) Start Audacity 3.2 Alpha
   (toolbars are redrawn, but) note that Audacity starts up maximized
6) Tools > Reset Configuration
   (toolbars are redrawn, but) note that Audacity screen becomes smaller, and no longer takes up a full screen.  This is a regression.

 Right-click on Audacity's icon in far upper-left corner shows that Audacity thinks that the screen is maximized but it is not.

**Comment by Ryan-Miller-Audacity** [comment]
I reproduced this in recent master build on both MacOS Monterey 12.3.1 and Windows 10.

**Comment by Ryan-Miller-Audacity** [comment]
Note that this is still the case in the latest public release (Audacity 3.3.2). The maximized state still gets confused by Audacity.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
