### ISSUE TITLE
Volume slider moves horizontally when the metering bar orientation is set to 'Vertical'

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3242]
**STR:**

1. right-click the metering toolbar, select Options
2. set 'Orientation' to 'Vertical', submit
3. check how slider moves

**Actual result:**
The slider moves horizontally

**Expected result:**
The slider moves vertically

![image](https://user-images.githubusercontent.com/50205984/178983359-37b26140-da47-4846-882e-8a58bbb1ff5e.png)

### Compare with DarkAudacity
Note that @JamesCrook 's  DarkAudacity also had a horizontal slider in vertical meter even in vertical meter mode, but the slider was clearer being at the bottom and with  **+**/**-** annotations

![image](https://user-images.githubusercontent.com/50205984/178986629-28416d54-555d-4032-a511-8d62bc285105.png)

_Originally posted by @petersampsonaudacity in https://github.com/audacity/audacity/issues/2779#issuecomment-1184394108_

**Comment by petersampsonaudacity** [comment]
Note that in the Mixer Board the gain slider operates vertically.

And further note that the Gain slider in the Mixer Board interacts with (and is ganged to) the gain slider in the track;s Track Control Panel and _**NOT**_ the slider in the combined meter toobar (or the old Mixer Toolbar) - note that this is the intentional designed behavior.

![image](https://user-images.githubusercontent.com/50205984/179231285-5392b1af-cf06-4dde-a6cd-2dde26c7de52.png)

**Comment by petersampsonaudacity** [comment]
@dozzer @LWinterberg 

This just looks naff

Any chance we can get something done about it (for 3.2.0)

**Comment by LWinterberg** [comment]
not for 3.2, no. I honestly see it more likely that the vertical meter function gets removed altogether at this stage, though no decision has been made. I think it'll make sense to look at it again in a context of a new mixer (#1024, #3412) and multi-track recording to see what the ultimate fate of the vertical option in the meters should be.

**Comment by petersampsonaudacity** [comment]
> not for 3.2, no. I honestly see it more likely that the vertical meter function gets removed altogether at this stage, though no decision has been made. I think it'll make sense to look at it again in a context of a new mixer (#1024, #3412) and multi-track recording to see what the ultimate fate of the vertical option in the meters should be.

That sounds sensible to me.

I, personally have never used vertical meters, never seen the point. And they just don't look good.  Plus they have to be undocked which can be a pain if you move the Audacity window about or resize it.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
