### ISSUE TITLE
Effect Progress dialog has no cancel button

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3246]
- Generate 10 hours of silence (this is fast)
- Choose Echo (for instance) from the Effects menu
- See progress dialog with no Cancel button

This is a regression from 3.1.3.

It's not so bad -- the Esc key or title-bar close button can cancel the dialog.  But that's not obvious perhaps.

Bisects to 881ee943b44ed202c1ba8a4173dbbda23b6085b3

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.2.0 alpha master audacity-win-3.2.0-alpha-20220715+57c277e-x64-msvc2022 
shows this affects generators too and is also a regression on 3.1.3

1. Generate 10 hours of anything but silence
2. Observe:  progress dialog with no Cancel button

**Comment by petersampsonaudacity** [comment]
@LWinterberg @dozzzzer @Ryan-Miller-Audacity @Tantacrul 

Testing on W11 with the latest alpha master  -  audacity-win-3.2.0-alpha-20220809+6f6501c-x64-msvc2022

This looks pretty bad to me in terms of UX - with an empty non-filed dialog box - I think this deserves more than a lowly P4 rating ...

![image](https://user-images.githubusercontent.com/50205984/183866842-4f0a7a22-3c8c-4e36-8dd2-870d09876609.png)

**Comment by petersampsonaudacity** [comment]
Testing on W11 with audacity-win-3.2.0-alpha-20220822+be66b5b-x64-msvc2022

@Paul-Licameli 

I am reopening this because when I test with a one hour mono track (Chirp, Tone, DTMF etc
and then apply Amplify

a) yes I do see a Cancel button,  BUT

b) when I press it Audacity looks as though it pauses/stalls for a few seconds and then the amplification is applied to the waveform, this ignoring the user's use of the cancel button.

**Comment by petersampsonaudacity** [comment]
@crsib @dozzzzer @LWinterberg

Testing on W10 with latest 3.2.0 alpha - audacity-win-3.2.0-alpha-20220902+7c9c978-x64-msvc2022
And on macOS 12.5.1 with audacity-macOS-3.2.0-alpha-20220902+7c9c978-x86_64

This appears to be working properly now on both W10 and macOS.

I think this could accordingly be closed
