### ISSUE TITLE
Effect dialog cannot be dismissed with the Esc key

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3445]
### Steps to reproduce

1. Open an Effect (or generator, analyzer) dialog, either from main menu or sidebar
2. press Esc key

### Expected behavior

Dialog is cancelled and closed, as happens in version 3.1.3

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

Should there also be a distinction between closing the dialog with a memory of settings changes, and a cancellation of the dialog that does not remember the settings?  My opinion was yes, but last we discussed it, designers differed.

**Comment by petersampsonaudacity** [comment]
This is even more important now that the "Cancel" button has been removed from Effect dialogs.

**Comment by Paul-Licameli** [comment]
> This is even more important now that the "Cancel" button has been removed from Effect dialogs.

Some interfaces just don't give you explicit save and cancel buttons.  For instance, on this very page, changing the Labels associated with this issue is immediate.

It might be a defensible intentional design choice to leave the dialog as it is and I think our designers want that.  It is unlikely anyone will open these dialogs and change things by accident.  Though I have said, maybe you try out changed settings, don't like them, and would like to revert them all exactly as they were.  The counter to that is, you can save a user preset first and return to that if you want.

But in all of the click-drag-release actions that you can do in the track panel and rulers, I always implemented Esc key because those are drags that are easy to start unintentionally.

**Comment by crsib** [comment]
I have a very strong opinion, that cancelling a drag and reverting a bunch of operations is a very different opinion. Consider a text editor, that silently closes on esc without saving changes.

The idea behind stackable effects it that you can change settings for multiple effects simultaneously, listening how it affects the sound. The only viable option I saw so far was Ableton implementation, which generates a project history item after each parameter change. I don't think we can implement it in Audacity within the current framework.

Other DAWs behave in a way similar to Audacity.

**Comment by Paul-Licameli** [comment]
> I have a very strong opinion, that cancelling a drag and reverting a bunch of operations is a very different thing. Consider a text editor, that silently closes on esc without saving changes.
> 
> The idea behind stackable effects it that you can change settings for multiple effects simultaneously, listening how it affects the sound. The only viable option I saw so far was Ableton implementation, which generates a project history item after each parameter change. I don't think we can implement it in Audacity within the current framework.
> 
> Other DAWs behave in a way similar to Audacity.

The suggestion is separate from the question of generating undo and redo items for parameter changes (Audacity does not).

The suggestion is that the non-modal effect dialog can be dismissed with the option to revert settings as they were when the dialog opened.

**Comment by crsib** [comment]
I understand your suggestion well. This an editor that closes without warning. It should be clearly shown to the user, that he will lose part of the changes.

**Comment by Paul-Licameli** [comment]
> I understand your suggestion well. This an editor that closes without warning. It should be clearly shown to the user, that he will lose part of the changes.

Which would be more obvious with an explicit "Save Changes" button distinct from the Esc key or the close button on the title bar.  But I can understand esthetic objections to that more complicated appearance.

**Comment by Paul-Licameli** [comment]
But then, one could hit either Enter or Esc very easily to dismiss the dialog one way or the other.

**Comment by Paul-Licameli** [comment]
But also apart from the question of reversion of settings:

with no keystroke to dismiss the dialog, is that acceptable for accessibility? @DavidBailes

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli  are you lobbying for a return of the **Cancel** button ?

**Comment by crsib** [comment]
I don't think that `Save Changes` or `Cancel` buttons will be added to the stacked effects UI. 

As for accessibility, on Windows standard Alt-F4 works just great. On macOS there is a problem indeed - Cmd-W is handled by the project window.

**Comment by DavidBailes** [comment]
> As for accessibility, on Windows standard Alt-F4 works just great.

On Windows, a keyboard user would expect to be able to close a dialog by pressing Esc. They shouldn't need to have to press Alt+F4 as a workaround.

**Comment by petersampsonaudacity** [comment]
> I don't think that `Save Changes` or `Cancel` buttons will be added to the stacked effects UI.

I was thinking about and asking about the "beautified" effect (EGAT) dialogs, destructive use - not effects stack, with regard to the "Cancel" button that was removed as part of the "beautification"

**Comment by dozzzzer** [comment]
###An RT effect's dialog window cannot be closed by the Esc key after changing the effect's parameters (AU only)

STR:
1. call an AU effect from the RT panel
2. change some parameters
3. try to close by pressing the Esc key

**Comment by petersampsonaudacity** [comment]
@crsib @dozzzzer @LWinterberg 

Testing on W10 with latest 3.2.0 alpha  -  audacity-win-3.2.0-alpha-20220902+7c9c978-x64-msvc2022

This appears to be working properly now - and I think that accordingly this could/should be closed.

**Comment by petersampsonaudacity** [comment]
> An RT effect's dialog window cannot be closed by the Esc key after changing the effect's parameters (AU only)

@dozzzzer I cannot replicate this with the latest 3.2.0 alpha audacity-macOS-3.2.0-alpha-20220902+7c9c978-x86_64 

1) I added the AULowShelfFilter to the effect stack
2) Pressed Play (one hour stereo track)
3) I changed the parameter
4) Pressed Esc
5) Observe:  the effect dialog disappears, and the effect remains in the effect stack.

Even if your findings were still the case what you report regarding this would really be a new separate issue as it relates to the non-destructive effect stack and **_not_** the destructive effect dialog - plus it is AU specific.

--------------------------------------------------------
### Aside
I note that the gear wheel in the effect stack has now gone and now one must click on the effect in the effect stack to access the effect's dialog.  Is this an intentional change?  Is this how it will be in 3.2.0?

**Comment by dozzzzer** [comment]
@petersampsonaudacity you're right, with Apple's AU effects it works just fine. I will correct my previous message now. However, if you try any third-party AU effect, you'll see that you cannot close it by Esc.

However, I disagree it should be a separate issue since it relates directly to what's said in the description of the bug. The fix was supposed to work for both destructive and non-destructive cases.

Addressing your last question - it was an intentional change and yes it will be like that in 3.2.0.

**Comment by dozzzzer** [comment]
**UPD:** it now concerns not only AU effects, but VST3s too.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
