### ISSUE TITLE
ThemeBase::RegisterImage tries to copy image on Mac but doesn't

### ISSUE THREAD

**Issue by bjj** [audacity/audacity#3459]
### Bug description

This code looks like it copies the image to modify it before a bitmap conversion:

```
#ifdef __APPLE__
   // On Mac, bitmaps with alpha don't work.
   // So we convert to a mask and use that.
   // It isn't quite as good, as alpha gives smoother edges.
   //[Does not affect the large control buttons, as for those we do
   // the blending ourselves anyway.]
   wxImage TempImage( Image );
   TempImage.ConvertAlphaToMask();
   resources.mBitmaps.push_back( wxBitmap( TempImage ) );
#else
   resources.mBitmaps.push_back( wxBitmap( Image ) );
#endif
```

but the line `wxImage TempImage( Image );` just creates a new reference to the same image. If you want to copy, it should be `wxImage TempImage = Image.Copy()`

If it works, it's probably fine, in which case you could simplify the ifdef to just call `ConvertAlphaToMask()`

### Steps to reproduce

x

### Expected behavior

x

### Actual behavior

x

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

I found this while working on something else. I don't even have a mac, but I did confirm that the quoted code does *not* copy the image.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
