### ISSUE TITLE
Reset toolbar layout

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#3479]
When updating to 3.2 we need to reset some preferences. Specifically:

- [ ] Reset the toolbar layout
- [ ] Reset the window size to the new default
- [ ] Reset the "How to get help" preference (the "what's new in 3.2" video is linked in there)
- [ ] Make meters initial size two times shorter

**Comment by petersampsonaudacity** [comment]
Note carefully that a simple toolbar reset does  _**NOT**_  resize the Audacity window to the 3.2.0 default size.

Instead it remains at the 3.1.3 (or earlier) size, if the user has not changed the size in 3.1.3, if you are upgrading to 3.2.0

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.2.0 alpha  -  audacity-win-3.2.0-alpha-20220906+1bbf8bc-x64-msvc2022

This looks to be fixed with the expected layout in the upper and lower tooldocks,

**_BUT_** with the default setting for 3.2.0 the is now a lot of empty wasted space in the right hand end of the toolbar,  This appears to be because the meter toolbars have been made shorter.  Two possible solutions:

1) make the meters long enough to fill the available width, or

2) reduce the width of the default window to butt up to the end of the re-sized meters 

![image](https://user-images.githubusercontent.com/50205984/188837774-ed687686-be83-4828-a0c4-0dc70519b24d.png)

_Note that in 3.1.3 the default meters were a good 9cm wide - this has been reduced to 5cm for 3.2.0_

**Comment by Ryan-Miller-Audacity** [comment]
@vsverchinsky I was able to verify all of the behaviors listed in the item; however, the only shortcoming appears to be the thumbnail for the Audacity 3.2 video has not been updated. (It links to the correct video, just displays the wrong thumbnail). Is this going to be updated separately?

**Comment by LWinterberg** [comment]
@Ryan-Miller-Audacity #3488 is the thumbnail task
