### ISSUE TITLE
Improve the usability of the realtime effects panel for keyboard users and screen reader users

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#3532]
### Your idea

Currently the keyboard navigation of the list of effects in the realtime effects panel uses a custom scheme. It would be better to use a standard scheme, one that the user may have already come across, rather than the user having to figure out how this particular custom scheme works. For a standard scheme see: https://docs.microsoft.com/en-us/windows/apps/design/controls/nested-ui#nested-ui-handling.

Currently the list of effects is not read by screen readers as being a list. The web equivalent of this is that a list is marked up as a series of paragraphs, rather than as a list. Having an accessible object for the list of effects which is appropriate for a list would result in screen readers both immediately knowing that they are dealing with a list, and letting them know that they they can navigate it using the keyboard.

### Problem to be solved

Currently the keyboard navigation of the list of effects in the realtime effects panel uses a custom scheme, and the list of effects is not read as being a list by screen readers.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
