### ISSUE TITLE
Bottom scroll bar disregards the length of the looping region when it stretches far beyond the clip's length

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3536]
### Steps to reproduce

1. load a clip of 2s length
2. enable a looping region of 10s length
3. with the selection tool enabled, click somewhere _inside_ the clip
4. zoom in so that the right edge of the looping region becomes not visible anymore
5. now move the bottom scroll bar to the rightmost position

### Expected behavior

The rightmost position of the scroll bar would show me the right handle of the looping region I can interact with.

### Actual behavior

A few seconds (or less, depending on the current scale) behind the clip's length is as far as you could possibly navigate using the horizontal scroll bar. The right edge of the looping region isn't visible. The only way to see it is to zoom out.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/188442997-532ab818-2eff-4593-9614-b162bd7e8e0e.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/188443141-43bb7a25-979c-4482-8fd2-d5971396d782.png">

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
