### ISSUE TITLE
Melda Suite of FX - No UI displaying.

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#3569]
### Plugin

Free Melda Suite of FX

### Plugin Format

VST2

### Plugin source

https://www.meldaproduction.com/downloads

### Bug description

Tested on Pietro's Build for VST2 statelessness: https://github.com/audacity/audacity/actions/runs/3007755230

On MacOS (Arm 64)

Installed the (free) VST2 versions of Melda: none of the plugins displayed a UI. See video: https://www.dropbox.com/s/57nim4pfv7e9rqz/01-Melda_VST2_No_UI.mov?dl=0

All plugins are working when installed as VST3

### Steps to reproduce

1. Install as VST2 only
2. Test and notice lack of a UI display. No difference in sound.
3. Uninstall VST2
4. Install VST3
5. Try same experiment. UI appears correctly. Appropriate difference in sound.

### Expected behavior

IT WORK, INNIT?

### Audacity Version

other

### Operating system

macOS

### Architecture

64 bit Intel/AMD processors

### Additional context

@LWinterberg says that the UI problem is not happening for him on Windows.

**Comment by Paul-Licameli** [comment]
But this should also be tested: does the plug in work in Audacity 3.1.3 for destructive processing?

**Comment by Tantacrul** [comment]
Actually neither plugin work in Audacity 3.1.3 for destructive processing. However, the problem is so bad - and VST is now so much more infinitely valuable - that I still would not release VST2 if these known issues persisted.

Especially, since those **same** plugins work with VST3, which most people will be using. Agreed?

**Comment by Paul-Licameli** [comment]
I don't necessarily agree from two examples.  Balance it against how many VST2s do work in a longer list (I have no guess).  Are these enough good examples to outbalance those few bad ones?  Aren't those that do work enough of a win and a gain in usefulness for Audacity that we want them?

If these UIs did not work in 3.1.3, then there isn't a regression in our recent code.  Audacity is *not worse* with those effects than it was.  Although the old defect might have been undiscovered because few people were trying to use the old VST support.

But discovering the right fix for the few plug-ins may be hard.  We don't know where to find good documentation of the old API that would let us figure it out.

**Comment by Paul-Licameli** [comment]
Another possiblity though is to get old versions of Audacity back to 2.1 and identify whether there was a last version of Audacity that did show the interface. Sounds like a task @petersampsonaudacity could help with.

If they used to work in old Audacity, we might discover where in the commit history things went wrong.

**Comment by Paul-Licameli** [comment]
I say don't give up on trying to improve @pietro68 's branch just yet.
