### ISSUE TITLE
External headphones are not recognized

### ISSUE THREAD

**Issue by stefaniecg** [audacity/audacity#3715]
### Bug description

**Audacity version: 3.2.0**

With an allready working project, if i connect my **external headphones these are not recognized by Audacity** among the **Playback devices**. 

### Workaround
The workaround is to close Audacity, leave the external headsets connected and then open audacity.
Then, the external headphones are among the Playback devices. 

Please fix this but, as it is present since a loooonng time ago, but i never reported it hopping it would get fixed in newer versions. 

### Steps to reproduce

1. Open audacity, add what ever sound form you want to work on.
2. hear this sound in the computer normal speakers -> everything works perfect. 
3. Connect an external set of headphones
4. Try to choose these external headphones from the Playback devices as the output for the sound.
5. ERROR => the external headsets are not recognized by Audacity. So it is not possible to listen from my headsets. 

### Expected behavior

I want to now be able to listen this audio with my external headsets.

### Actual behavior

ERROR => the external headsets are not recognized by Audacity. So it is not possible to listen from my headsets. 

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context
After doing the workaround described above, and being able to hear audio with my headsets. 
if then i DISCONNECT the headsets, and press PLAY again, it gives me the following error:

`
{
    "timestamp": 1664382530,
    "event_id": "f9dfa412b3594bbab4842803afac881c",
    "platform": "native",
    "release": "audacity@3.2.0",
    "contexts": {
        "os": {
            "type": "os",
            "name": "Macintosh",
            "version": "10.16.0"
        }
    },
    "exception": {
        "values": [
            {
                "type": "Error",
                "value": "Error opening sound device.\nTry changing the audio host, playback device and the project sample rate.",
                "mechanism": {
                    "type": "runtime_error",
                    "handled": false
                }
            }
        ]
    }
}
`

**Comment by Ryan-Miller-Audacity** [comment]
Audacity is not built to automatically recognize new audio devices while the project is open; however, have you ever used the "Rescan Audio Devices" function? (Found in: Transport -> Rescan Audio devices). This will update the audio devices available to you within the Audio Setup menu (for both recording and playback). Similarly, Audacity doesn't automatically change your audio playback device just because you unplugged it; rather if you disconnect your audio device you just have to select a different audio device and playback will work fine (alternatively, again, you could make use of the rescan audio device feature which would remove the disconnected device and fallback on to the default playback device). 

Generally speaking, rescanning audio devices (and not automatically registering changes to such) is a common case for most DAWs, Composition software etc. 

@stefaniecg Can you try the Rescan Audio Devices function and see if that works for you?

**Comment by dozzzzer** [comment]
@stefaniecg as for the plugged in I/O devices not popping up, it's a well known issue. See these: https://github.com/audacity/audacity/issues/2409 and https://github.com/audacity/audacity/pull/2517
