### ISSUE TITLE
Suggest renaming the new (3.2) TCP Effects button to "RT Effects"

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3867]
### Your idea

Rename the new TCP Effects button that was introduced in 3.2 to RT Effects

### Problem to be solved

Beginning in 3.2, Audacity now has an Effect menu and an Effects button.  This is confusing for users and especially confusing for forum users who are trying to communicate their difficulties. "I added an effect" can be taken in two completely different ways. 😕

**Comment by petersampsonaudacity** [comment]
Funnily enough, I was thinking the exact same thing only yesterday.

I think this is a good idea.

Flagging @Tantacrul and @LWinterberg  - as a UX issue

**Comment by Tantacrul** [comment]
Localisation was my main worry to be honest. I'm not 100% satisfies with what we have now (which I saw as the hand we were dealt given how Audacity worked in the past). I would like to test 3.2 a bit with users to see how they actually interact with effects in general and spot any obvious confusion points.

One thing that worries me is that 'real-time effects' sounds a bit scary compared to 'effects' and I worry users wouldn't try the 'Effects' button out for that reason. I might be wrong and that's why I need to do some testing.

@DilsonsPickles @LWinterberg - I can set this up soon enough. You game?

**Comment by petersampsonaudacity** [comment]
> One thing that worries me is that 'real-time effects' sounds a bit scary compared to 'effects' and I worry users would be less likely to try out a 'real-time effects' button because it implies some kind of specialist knowledge

But that's exactly what you call it in the RT Effects Panel title:
![image](https://user-images.githubusercontent.com/50205984/198585483-7450a1c3-cc1c-4c44-90fd-7c86cd37daba.png)

And in your GitBook:
![image](https://user-images.githubusercontent.com/50205984/198585823-d51baddc-f413-477b-b3f6-2897affb862e.png)

**Comment by Tantacrul** [comment]
Yes. But the initial button just says 'Effects' and getting users to click on that is the most important thing. Once that panel is open, there's also a little description of what RT effects are that links to a video. In other words, we have baby-stepped users towards using the feature.

That's what's important, not rigid consistency for the sake of consistency.

**Comment by petersampsonaudacity** [comment]
> Yes. But the initial button just says 'Effects' and getting users to click on that is the most important thing. Once that panel is open, there's also a little description of what RT effects are that links to a video. In other words, we have baby-stepped users towards using the feature.

That's a fair point ...

**Comment by Tantacrul** [comment]
One thing I saw in Microsoft time and time again:

When faced with an icon or a description that doesn't immediately make sense to them, users tend to avoid clicking on it.
