### ISSUE TITLE
3.2.1 Audacity Install Not Making File Associations for MP3 Files.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3881]
### Bug description

After Installing 3.2.1, when I double click on an .aup3 file, 3.2.1 comes up OK.

However when I double-click on an .MP3 file, 3.2.0 erroneously comes up.

### Steps to reproduce

Exit Audacity. Double-click on any .MP3 file.

### Expected behavior

Audacity 3.2.1 starts up.

### Actual behavior

Audacity 3.2.0 starts up.  This is the old version.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

64-bit

This error is a regression from prior versions.

A forum user stanrob, has also reported this difficulty: https://forum.audacityteam.org/viewtopic.php?p=458215#p458215

**Comment by petersampsonaudacity** [comment]
All audio files appear to be associated with Groove Music on my W10 PC, not any version of Audacity.

**Comment by petersampsonaudacity** [comment]
The original Forum poster who initiated this "issue" wrote early today:

>I need to update my original lament. When I wrote that, my renames of folders had resulted in complete disappearance of the (old) Audacity option in that dropdown.
>
>One day after, an interesting option appeared when I tested a right-click on an mp3. The new option was "Audacity 2.3.2 Setup"! And that's exactly what it got!
>
>Two more days after, under "Audacity 2.3.2 Setup", an ADDITIONAL option appeared: "Audacity® Cross-Platform Sound Editor"! And THAT gets Audacity 3.2.1.
>
>These changes happened all by themselves!
>
>So I'm back to my normal procedure (starting Audacity by right-clicking on an mp3), which now get Audacity 3.2.1. Someday I would love to learn about Windows's slow spontaneous magic tricks.


@LWinterberg @dozzzzer 

I strongly think that this is a non-issue that should be closed.  

There is no design in Audacity to automatically associate MP3 files (or any audio files) with Audacity so that clicking the MP3 "opens" it in Audacity.

I, for one, certainly do not want or need to have my audio files with Audacity - but for those that do I believe that there as OS ways in which this can be achieved if the user so wishes.

**Comment by LWinterberg** [comment]
If I associate Audacity with .mp3 files manually, it opens just fine. I think if anything, the issue is that if you install multiple versions of Audacity side-by-side, the association doesn't automatically update. Which feels reasonable to me; if you decide to keep an old version around, why should the file association change?

**Comment by JohnColket** [comment]
Peter, Steve, and Leo, thank you for your comments.  They all make good sense to me.
