### ISSUE TITLE
Sample rate with fractional values

### ISSUE THREAD

**Issue by tkna91** [audacity/audacity#3962]
### Your idea

Allows the specification of a fractional value for the sample rate, dramatically streamlining the process of correcting misalignments during multi-track recording on multiple recording machines.

### Problem to be solved

When recording with multiple recorders over a long period of time, the recording timing inevitably deviates due to differences in the quartz crystal unit clock precision of each device.
The sample rate can be changed in Audacity to compensate for this discrepancy, but since only integer values can be input, it takes extra time and effort to set the sample rate to a high precision once to get close to the approximate value, or to open or close the sample interval.

By allowing a fractional value to be specified for the sample rate, these issues can be solved.

### Prior art

No. I have never seen anything other than Audacity capable of such advanced work.

### Additional context

https://user-images.githubusercontent.com/102382754/202869217-9ad24a71-c12d-4947-adef-f9ce3c16ab7f.mp4

See here for how to correct sample rate discrepancies in multitrack recordings made with different recording devices. (Probably requires a facebook login.) It is in Japanese, but you can use a machine translation such as DeepL to get some sense of what it means.
https://www.facebook.com/yasushi.utsunomiya.3/posts/pfbid077L5as8iPXEdzpCp1nUZfPCirCYvbo7vGm1Xei6jQaAiWHhGqqVhCx1Dqg1DU2idl

https://www.deepl.com/translator

**Comment by LWinterberg** [comment]
I'm not aware of any audio format that accepts non-integer sample rates: WAV takes a 4-byte integer, MP3 takes a handful of standard sample rates between 8 and 48 kHz, FLAC takes a 20 bit integer. So this request is technically impossible.

Additionally, even if it was possible, I don't think a fractional value is sufficient to resolve this. The rate of drift itself can change over time due to a variety of factors. So for a long recording, the difference may be 44100 vs 44099 in the beginning but 44100 vs 44102 in the end. So even if you do manage to line up the ends of the tracks, you will find that the tracks run out of sync, back into sync and then out of sync in the other direction again regardless. 

What possibly can work for your purpose is to resample the track to 441000, then do the adjustments (eg 441003), and then resample again back down to 441000.

**Comment by rbdannenberg** [comment]
Nyquist represents sample rates as floating point numbers, not integers, and Nyquist features include high-quality sinc-interpolation-based resampling. If you could track variations in sample rate due to clock drift, you could even do variable-rate resampling to correct it. Probably what you want to do is first "correct" the indicated sample rate, then resample back to the desired rate. E.g. if you have an indicated sample rate of 44100, but you know the true sample rate is 44100.3, then the the sound is too long, and you should stretch it by 44100/44100.3. In Nyquist, assuming the sound is given by *track*, that's
 (stretch (/ 44100.0 44100.3) (sound *track*))
you need the "sound" function which takes the immutable source sound s and constructs a new sound, applying the stretch factor created by "stretch".
The Nyquist implementation merely creates a virtual copy of s with a modified sample rate, so this expression does not require any resampling computation.
Next, you want to produce a result that is resampled to 44100, so use "resample":
  (resample (stretch (/ 44100.0 44100.3) (sound *track*)) 44100.0)
Note that there will be a slight amplitude change. This is because, when resampling, you can get peaks in excess of any input sample value. Nyquist scales the result by 0.95 as a compromise between (almost) preserving the original amplitude and eliminating the possibility of clipping. Resampling will *never* clip since samples are floats, but clipping could occur if the peak amplitude exceeds one after resampling. If you are resampling source recordings to be mixed, the amplitude change shouldn't matter.

**Comment by rbdannenberg** [comment]
I see that github interpreted some asterisks to mean *italic*. I meant to write
`resample (stretch (/ 44100.0 44100.3) (sound *track*)) 44100.0)`
with the asterisks.

**Comment by rbdannenberg** [comment]
Nyquist can do the resampling. Your question is more about the interface. One thing you could certainly do is make a plug-in that prompts for the amount by which the track should be stretched or reduced. E.g. "extend the selection by 3.2ms". If you fill a selection, then there must be 2 selections: (1) what content to use, and (2) what time to fill. But effects don't operate on multiple selections. You might get the equivalent by selecting the time to fill and filling it with all the content available in the same track. You should look at the nyquist effects documentation to see what info and content is available through the interface. I don't remember all the details, and I made a prototype API that *would* provide all this sort of info, so now I'm not clear on what's actually there now and what was provided in my extended API. If you want to create a plug-in, I can certainly consult on the Nyquist details.

**Comment by tkna91** [comment]
@rbdannenberg Thank you for your kindness. I was looking into the details of Nyquist a bit.
But perhaps this could be done with the standard "Change Speed" plugin - I stretched a 59:50 minute source at 48000Hz to 1 hour and it only overflowed by 385 samples.
Do you see a problem with this?

https://user-images.githubusercontent.com/102382754/203702606-ba622f67-1ebc-498e-80f2-084a45afcb35.mp4

**Comment by rbdannenberg** [comment]
That's a good point -- yes, I think change speed will do the equivalent thing. I just tested whether it had the necessary precision by stretching 100 sec of 1kHz sinusoid to 100.001 sec, which is a ratio of 1.00001, and it seems to work perfectly, adding exactly 1 msec or one period. It's amusing that you can play the original and stretched signal together , and right around 50 sec, the 180-degree phase cancellation causes the mix to become silent.

**Comment by tkna91** [comment]
@rbdannenberg The phase inversion part is indeed interesting.

https://user-images.githubusercontent.com/102382754/203813014-b2cdd0ec-9c3e-4ede-8ed3-0232a6566301.mp4

I guess Audacity's ability to create pure sine waves with high precision makes it possible to do magical things like this. I imagine the mind-boggling amount of adjustment work that would have been required to do this in the days of tape and analog oscillators.
Apart from those pure sine waves, what about using it to correct clock drift caused by multiple recorders, assuming that the number of clocks for each of them is constant, as mentioned earlier?
Is it safe to assume that this would not cause any particular problem as far as normal human listening is concerned, but rather that it would sound natural?
I would find this very useful if the processing speed is fast and this is not a problem in terms of quality.
