### ISSUE TITLE
VST2: Plain UI does not update sliders when loading preset while playing

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#3981]
### Bug description

If you use the Plain UI with a vst2 effect, and load a preset while playing is on, the sliders will not be updated right.

### Steps to reproduce

1. have some audio track
2. in the effect stack, instantiate any vst2 effect (even the simplest one, DeeGain)
3. modify the options so to show the plain UI (you will need to close and reopen the gui, if you were not in plain UI mode)
4. Start playback
5. Use the presets menu to load a preset

### Expected behavior

Sliders on the plain UI are positioned according to the preset

### Actual behavior

Sliders on the plain UI will not move from their previous position.

A second selection of any preset, will then make the sliders be updated to reflect the first preset selection.

This was observed on Windows but it very likely happens on MacOS too, it is a logical bug in the control flow.

It happens since a long time, at least since merge 7616b89 in the release branch.

**Comment by Ryan-Miller-Audacity** [comment]
Confirmed the fix in Build from PR #3982 on both Windows and MacOS. Sliders are now updating when a preset is called both in and out of playback mode for user and factory presets. (FYI TDR Kotelnikov was great for testing this since it has so many presets). 

I did notice some issues with the VST2 version of the Valhalla plugins not responding to presets at all, but that seems to be independent of these changes/fix.
