### ISSUE TITLE
Add prompt dialog when copying clips between projects

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#4004]
- Add dialog asking user to choose option to either discard trimmed data or copy all contents.
 - Dialog should allow "remember my choice"
 - There should be an option in preferences that can change remembered user selection
 - Add copy progress dialog

Addresses use case issues reported in #3820

**Comment by petersampsonaudacity** [comment]
Tested this on W10 with @vsverchinsky vVitaly's latest branch build:  audacity-win-3.3.0-alpha-20221206+9c91e83-x64-msvc2022
This works fine when you copy a clip from one project to another
![image](https://user-images.githubusercontent.com/50205984/206185599-6cb5beb9-e3d5-4762-a70e-4d772c11f0f9.png)

a) but can we **_please_** also have this dialog and option when copying clips within a project thereby helping to avoid the over-bloated projects that may users have complained about.

b) It is unclear to me whether or not the user's choice for "**Selected only**" or "**Whole**" is sticky and retained/remembered if they have ticked the "**Don't show me this again**" check-box.

c) if the user has checked the "**Don't show me this again**" check-box - then there appears to be no way for the user to set this dialog to be displayed again (except with a **Tools > reset Configuration** which may be way more drastic than the user requires).
_There appears to be no preference setting or command to control the display/hiding pf this dialog_

Flagging both these as UX/design issues to @LWinterberg @Tantacrul @DilsonsPickles

**Comment by petersampsonaudacity** [comment]
UPDATE

The message looks good - but the copy fails to work

If I copy a short selection to another project with this build choosing "Selected only"

a) the length of the selection is OK for the copy

b) no audio is copied - just a selection 

![image](https://user-images.githubusercontent.com/50205984/206187822-1da8ac2c-50c7-4f2f-9a8e-5c7f94148b62.png)

The Copy works fine if I choose the "**Whole**" option

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky Vital'ys latest branch:  audacity-win-3.2.2-alpha-20221207+12b213c-x64

a) I think the message is improved with the changes

b) with the **Paste selected audio only** selected  the audio **_now does get pasted_** and it is properly reduced to just the clip

c) BUT if I then check on **Remember my choice** it fails to do and and reverts to **Paste smart clip** - **_but_** now with no dialog displayed to show the reversion -
![image](https://user-images.githubusercontent.com/50205984/206432725-97882ee8-2709-4d2d-99c8-50036934312f.png)

d) Examining Track Behaviors prefs shows that the pref has not been changed bt checking "on" **Remember my choice**
![image](https://user-images.githubusercontent.com/50205984/206434398-19f42909-b747-4223-8dac-6febea16205d.png)


e) note that the preference text still just says "copy between projects"  rather than "copy and paste between projects"  -  is this a deliberate design choice which will be retained?

**Comment by vsverchinsky** [comment]
> f) note that the preference text still just says "copy between projects" rather than "copy and paste between projects" - is this a deliberate design choice which will be retained?

No, texts aren't final, option will move to Warnings section

Thanks!

**Comment by dozzzzer** [comment]
Several cosmetic changes are to be made to the dialog:

1. Padding of the dialog should be increased 
2. The indent between the radio buttons and their labels should be smaller
3. The indent between the Cancel/Continue buttons should be smaller
4. Change "at anytime" to "at any time" or just "anytime"

<img width="654" alt="image" src="https://user-images.githubusercontent.com/70063970/217635319-1112e167-1853-4a6e-90f7-60493665cb44.png">

**Comment by DavidBailes** [comment]
> Several cosmetic changes are to be made to the dialog:

There are also still a number of accessibility issues with this pull request, which I've previously commented upon in a different thread: https://github.com/audacity/audacity/pull/4033#issuecomment-1348672621

**Comment by petersampsonaudacity** [comment]
Testing on W10- with @vsverchinsky Vitaly's latest branch build for this:   

a)  the copy properly honor's the user's request to either copy the whole smart clip ot just the selection

b) the displayed data size does _**not**_ change when toggling between the two copy forms - I would expect the smart clip data size to be much larger than the simple selection size.

c) the "**don't ask each time**" and the "**ask each time**" settings work as intended when used fro either the copy dialog or Tracks Behaviors preferences 

d) if Ask every time is "on" then the copy dialog properly remembers the users last-used choice for the copy.

e) I note that the default is to set to copy the whole smart clip - is that intentional?

f) At default settings the dialog for Tracks Behaviors preferences is now not quite long enough for the new text:
![image](https://user-images.githubusercontent.com/50205984/217879512-4bde58f4-b40a-472e-91ed-0be591136e4e.png)

**Comment by petersampsonaudacity** [comment]
Testing on @vsverchinsky 's latest branch build:  audacity-win-3.3.0-alpha-20230210+429a3c0-x64

I confirm that the Copy dialog no longer has the "X" to cancel the process

BUT consider this use case
1. Generate a five hour chirp to simulate a long recording project
2. select a three minute "song"
3. Ctrl+N to open a new project
4. Ctrl+V to paste the entire smart clip in (the default setting in the dialog)
5. Observe: this takes 2min 24secs on my machine with _**NO**_ longer any ability to interrupt this 

If you make a mistake and intended only to copy in just the selection (which takes less than a second) 0t's like watching paint dry as you wait !

Removing the "X" cancel as a "fix" seems a very kludgy approach and poor UX.

**Comment by dozzzzer** [comment]
@petersampsonaudacity 
without re-writing the existing data models it's hardly possible to address this issue in a better way for now, which doesn't mean we won't do anything about it in the future. I'll create a separate development task for this, too.

**Comment by dozzzzer** [comment]
Verified
