### ISSUE TITLE
Invisible text in Welcome to Audacity dialog on Mac in Dark and High Contrast Themes

### ISSUE THREAD

**Issue by billw58** [audacity/audacity#4066]
### Bug description

The "Don't show this again at start up" text is not visible when you open Audacity and it is in Dark or High Contrast theme.

### Steps to reproduce

1. Start Audacity
2. In Interface Preferences, set Theme to Dark or High Contracst; check "Show 'How to Get Help' at start"
3. Quit Audacity
4. Start Audacity

### Expected behavior

The text "Don't show this again at start up" should be visible.

### Actual behavior

The text "Don't show this again at start up" is not visible.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

macOS 13.0.1, Intel and Arm. Audacity 3.2.2

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
