### ISSUE TITLE
There is no visual (or audible) cue in the TCP for an invisible active Effects Stack

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4092]
### Bug description
1) There is no visual cue in the TCP for an invisible active Effects Stack

2) the hover-text for the "Effects" button does nor change when there are active effects in the Effects Stack

### Steps to reproduce
1. get some audio
2. click the Effects button in the TCP
3. add an effect to the stack
4. Click the **X** button in the Effects Stack to hide the stack _(stack become invisible but remains active)_
5. Observe: there is no visual cue in the track or the TCP to indicate that there is a hidden, active, Effects Stack
6. Hover your cursor over the Effects button in the TCP
7. Observe: all the hover-text says is "Effects"

### Expected behavior

**1. Visual cue for the sighted users**
When the Effects Stack is active (visible or hidden) - the colorway of the Effects button in the TCP should change.
This a suggestion - perhaps the button color could be green or something else
![image](https://user-images.githubusercontent.com/50205984/208883369-c9f2ca1d-e7a7-40cc-9431-62950c5296f1.png)
Attention would need to be paid to the active button colorway for Dark and High Contrast themes.

**2. Audible cue for VI users**
When the Effects Stack is active (visible or hidden) the hover-text for the Effects button should change to indicate that the Effects Stack is active - something like "**Effects active**" or "**Effects stack active**"

It is important to ensure that the hovertext is read properly by screen-reader apps.

### Actual behavior
**1. Visible Effects Stack - _STR step 3_**
![image](https://user-images.githubusercontent.com/50205984/208885133-806cfea1-bd9e-4929-bc92-b373037f09c0.png)

**2. Invisible (but still active) Effects Stack - _STR step 5_**
![image](https://user-images.githubusercontent.com/50205984/208885396-badb0fe5-cf22-4fa1-99b6-c4fa7150a005.png)

### Audacity Version
3.2.2, 3.2.3 Beta and 3.3.0 alpha

### Operating system
Windows 10 - but assume all OS

### Additional context
Tagging @DilsonsPickles @LWinterberg and @Tantacrul  as this is a user interface issue

**Comment by LWinterberg** [comment]
Instead of a color, I much prefer simply giving a number so you know how many effects you got:

![image](https://user-images.githubusercontent.com/87814144/208893637-99375cd4-ac83-47b3-9bab-bca9b750ee93.png)

fwiw, the track header (TCP) in its entirety is inaccessible by normal means; any of its sliders and buttons must be summoned with a shortcut. If anything, accessibility would be part of the track navigation, so if you switch to a track it'd read out "1. 01 Sgt Pepper's Lonely Hearts Club Band selected. 2 realtime effects.", which I'm not a fan of. 

IMHO, both issues - track headers being inaccessible and indicating which tracks have effects - are best done in the Qt version, and it also isn't massively pressing either.

**Comment by petersampsonaudacity** [comment]
> Instead of a color, I much prefer simply giving a number so you know how many effects you got:

I could live with that @LWinterberg  Leo  -  **_most_** important is to have some form of visual cue ...

And point taken about the Qt version.

**Comment by petersampsonaudacity** [comment]
See also this "Discussion" thread:  **Mini Effects Stack on Track Headers #4223**

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
