### ISSUE TITLE
Support XDG base directory specification

### ISSUE THREAD

**Issue by shmerl** [audacity/audacity#412]
Currently on Linux, Audaicty creates `$HOME/.audacity-data` directory. Please follow XDG base directory specification to avoid cluttering `$HOME`.

**Comment by vn971** [comment]
Yes please! The correct destination for "data" should be `~/.local/share`. Additionally, `~/.config` is the right directory for configs, `~/.cache` is the right directory for cache. If there's strong resistance to the full correct thing, then at least please put everything in `~/.config`.

On another note. The directory `.audacity-data` is by itself also misleading, because it is normally read as "audacity directory that stores binary data, like audios and exports/imports". In reality, however, it also stores configuration, which is a completely different thing to the user. Having the name of the directory as just `.audacity` would avoid the wrong meaning and make it more clear that it's a directory that tries to hold everything together. (That being said, the best approach is still to follow XDG specs.)

**Comment by SteveDaulton** [comment]
Thank you for your comments. This issue is logged on the Audacity bug tracker.

**Comment by shmerl** [comment]
For the reference: https://bugzilla.audacityteam.org/show_bug.cgi?id=2201

Is there any plan to implement it?

**Comment by SteveDaulton** [comment]
We would, of course, like to fix every bug and issue, but resources are limited. Patches are welcome.

**Comment by lllucius** [comment]
We also have to conscious of compatibility with previous versions of Audacity.  If we make this change, do we automatically "migrate" the existing folder contents to the XDG folder(s)?  What do we do if the user switches back to a previous version of Audacity?

**Comment by shmerl** [comment]
I'd say it's a very unlikely scenario to support (switching to previous version). But I suppose you should know better what usage patterns are common.

**Comment by vn971** [comment]
Regarding forward compatibility though. Yeah, as always in these cases, automatic migration should be there.. It means more code to write than just changing default paths indeed. (Also, the sooner standards are fully followed, the better, if new files/directories are introduced. Not trying to be too pushy here, just saying.)

**Comment by lllucius** [comment]
Not saying it's impossible.  Might just be a simple matter of providing guidance in the release notes or something like that for those types of situations.

**Comment by serebit** [comment]
I've successfully managed to point Audacity to the correct directories in a locally patched copy. I still need to fix the backwards/forwards compatibility, though. Any suggestions for how I should handle it?

**Comment by vn971** [comment]
@serebit if you want real forward compatibility, then only (relative) symlinks I guess?

**Comment by serebit** [comment]
That's not going to be easy, but I'll give it a shot seeing as it"s realistically the best way forward.

**Comment by serebit** [comment]
Had a different idea-- if the `.audacity_data` directory *already exists*, use that. If it doesn't, use the XDG dirs (i.e. on a new install). This covers all use cases I can think of other than someone installing Audacity on a new machine, running it, and then immediately downgrading it to an older version (which seems pretty rare).

**Comment by shmerl** [comment]
yes, clearly. If it doesn't exist you don't need to create any symlinks and such. That's the whole point. Use XDG only in such case.

**Comment by shmerl** [comment]
I don't think you need to worry about downgrading, that's just too much work for not valuable use case.

**Comment by vn971** [comment]
Yes, I was arguing for symlinks if the old destination existed and was replaced by a new one, or just standard XDG -- otherwise. I do feel that complying with XDG is better than making audacity work with both directories though, but that's somewhat subjective, and I'd be very happy with either change!

**Comment by vn971** [comment]
(I would also think that omitting downgrading support is okay, in which case audacity only needs to move data to the new destination if the new destination doesn't exist (but old one does).)

**Comment by serebit** [comment]
#632

**Comment by lucas-mior** [comment]
#632 has adressed this issue, can it be merged?
