### ISSUE TITLE
Trying to Pan can Switch the current Project

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4168]
### Bug description

If two Audacity Windows are open, trying to Pan in the first project can instead activate the second project.

This problem was reported by Forum user larrysaws here: https://forum.audacityteam.org/viewtopic.php?f=46&t=128632

### Steps to reproduce

1) Generate Chirp
2) File > New
3) In new (2nd) workspace Generate DTMF
4) Change Pan of DTMF to +10
5) Alt - Tab back to 1st (Chirp)
6) Try to change Pan of Chirp to -10

### Expected behavior

Pan changes to -10 as desired; Chirp project remains in foreground

### Actual behavior

2nd (DTMF) project comes to foreground.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by SteveDaulton** [comment]
This bug also apples to the track  "Gain" slider. (tested with Audacity 3.2.3 AppImage).

**Comment by billw58** [comment]
I cannot confirm this with the steps to reproduce on Mac macOS 13.1 (intel and arm) and Audacity 3.2.3.

**Comment by dozzzzer** [comment]
I confirm the described issue on Windows 11

**Comment by robindouglasjohnson** [comment]
Confirmed for Audacity 3.2.4 on Windows 11. It's infuriating. The only workaround I can find, once this starts happening, is to close the project it insists on switching to.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
