### ISSUE TITLE
Audacity crashes while editing with real-time plugins active

### ISSUE THREAD

**Issue by audacitymike** [audacity/audacity#4177]
### Bug description

The only plugin I had running is the Waves H-EQ (Mono) on a mono voice track. Any content editing with the plugin active causes Audacity 3.2.3 to crash when pressing the space bar to play or using the transport play button. I sent multiple crash reports to Audacity as it was happening. 

### Steps to reproduce

1. Install and activate the plugin
2. Do some content editing with the plugin active
3. Play through your edits as you make them
4. Audacity crashes after 3-5 edits when playback of the latest edit is attempted. 

### Expected behavior

It shouldn’t crash. 

### Actual behavior

Audacity shuts down. 

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

2021 MacBook Pro running latest OS. M1 Pro processor with 32GB of memory.

**Comment by dozzzzer** [comment]
After spending a lot of time fiddling around with this plugin in all possible ways, I've only managed to reproduce it twice.
The details can be found below. Even though it's a crash I believe it deserves P4 since it's really hard to reproduce plus it doesn't happen too often.

Version: 3.2.4 (universal build)
Architecture: ARM64
Sentry link: https://sentry.audacityteam.org/share/issue/9e6f2590a86b453ebfc7db4adb2d410c/

STRs are not defined yet but can be vaguely described as: 
1. Have a mono track
2. Have Waves H-EQ (Mono) VST3 on it
3. Make some edits to the audio clip, such as splitting, moving the clips, copy/paste operations
4. Start playback
5. Open the plugin dialog

**Comment by dozzzzer** [comment]
@audacitymike could you check if the issue is still reproducible on your side?

**Comment by dozzzzer** [comment]
In 3.4.0 I can no longer reproduce this issue following the STRs above.
