### ISSUE TITLE
Mp3 Tag info not getting imported

### ISSUE THREAD

**Issue by markcellis** [audacity/audacity#4265]
### Bug description

Older versions of Audacity 2.x with LAME had no problem populating the Artist tag from the attached mp3 file. For some reason, the latest version of Audacity is not reading it. The artist tag in the attached file should be: KATL Ground (Rwys 9/27)/LiveAT
[KATL-Gnd-0927-Feb-02-2023-1400Z.zip](https://github.com/audacity/audacity/files/10578992/KATL-Gnd-0927-Feb-02-2023-1400Z.zip)

### Steps to reproduce

Open Audacity and drag the mp3 file to the editor.

Go to Edit/Metadata and notice that the Artist tag is blank.

You can use the free Mp3Tag tool to see that tags in that mp3 file

### Expected behavior

It should read that tag

### Actual behavior

Blank Artist tag after import

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by Ryan-Miller-Audacity** [comment]
Where was your file created? I found that I check the file you provided for Metadata after download, you are correct, it is not present; however, if I add the metadata to that track when exporting from audacity, the metadata is correctly imported with the file. 

Regardless there's no denying the metadata is present since you can see it in the file explorer and then it is not present when importing the file into audacity.

**Comment by markcellis** [comment]
That file came from LiveATC.net. One of the ATC chatter archives from Atlanta Hartsfield.

 

This all worked fine with older versions of Audacity and Lame. It was able to read the tag data fine.  If you use Mp3Tag it also has no problem reading the tag data.

 

Mark

**Comment by dozzzzer** [comment]
@markcellis I can no longer reproduce this issue as of version 3.4.2 (macOS, Windows)
