### ISSUE TITLE
Beats & Measures task: rearrangement of the bottom bar UI

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#4283]
### Your idea

To accommodate the GSoC project that has introduced the concept of beats and measures, we need to rearrange the bottom bar UI in a few places. All of this work is specified in [this figma project](https://www.figma.com/file/SKDJypvy37EAauTPgwo2tL/07_WX---Beats-%26-measures?node-id=30%3A761&t=UKmXqBrifEeSaFAe-1)

![image](https://user-images.githubusercontent.com/21022311/217006479-9edd13ec-e16f-4d3b-b020-9f542007c368.png)

---
### Components of this task
1. The creation of a **Tempo/Time** toolbar
2. The creation of a **Snapping** toolbar, which comprises our snapping dropdown. This should now contain the snapping options currently found in in the beginning/end of selection dropdowns (see image below).
![image](https://user-images.githubusercontent.com/21022311/217010198-acce337b-e429-4d50-9d5a-5939c235e784.png)
(There are also new musical options to be added to the Snapping toolbar, which are specified in a separate task

---

3. Moving the 'Project Rate' option to **Preferences** (@DilsonsPickles / @LWinterberg) please see my note in the Figma design about reconciling this with an existing option in **Quality**
4. The creation of an **Audio position** toolbar, which has slightly different UI to reveal existing selection options
![image](https://user-images.githubusercontent.com/21022311/217010663-ee80b3a3-b523-4506-96bb-2defa3606852.png)

### Problem to be solved

These changes are needed to:

- Separate the UI into discreet parts that can be hidden / shown when workspaces are introduced
- Make the relationship between snapping and selection clearer
- Introduce new UI to allow the user to manipulate beats and measures

**Comment by DavidBailes** [comment]
> * Make the relationship between snapping and selection clearer

While accepting that currently what is snapped to is not obvious, I think that the proposed change introduces problems of its own.
A user may want to change the format of the selection start/end/etc controls for reasons other than snapping - for example, just so that it's a convenient format for either reading or entering times. So removing the ability to change the format of these controls directly using one of the controls is problematic because:
- If they are wanting to change the format for a reason other than changing the snapping steps, why would they think of changing a setting on the snapping toolbar?
- For all other instances of these time controls, the format can be changed using the control, so why confuse the the user by introducing this inconsistency.

**Comment by DavidBailes** [comment]
> 2\. The creation of a **Snapping** toolbar

For keyboard users, is the specification for the check box that it can be toggled using the Spacebar key (rather than Spacebar starting and stopping playback when the check box is the focus)?

**Comment by Tantacrul** [comment]
> If they are wanting to change the format for a reason other than changing the snapping steps, why would they think of changing a setting on the snapping toolbar?

Sure, I can see that. I guess we could keep the dropdown on the selection UI element, which is simply linked to the snapping control. You can change it in either place and it changes them both together.

@DilsonsPickles @LWinterberg - does that sound sensible to you?

As to the other point about accessibility, @DilsonsPickles is creating that specification now and we'll share it in advance. Thanks!

**Comment by DavidBailes** [comment]
> 4\. The creation of an **Audio position** toolbar, which has slightly different UI to reveal existing selection options

Given the name, I think a user may well think this is something to do with the position of the audio, ie it gives the position of the audio, or allows the user to change its position, ie time shift it.
I would have expected selection to be somewhere in the toolbar's name.

**Comment by Tantacrul** [comment]
@DavidBailes agreed.

**Comment by DilsonsPickles** [comment]
@DavidBailes @Tantacrul 

I've just had a discussion with @crsib and @LWinterberg and we all agree that the Audio selection (formerly the Audio position) toolbar indicators should keep their format dropdowns so that the User can control the format independently. 

We do think however, that the formats should remain independent. Changing the snapping format will not update the Time toolbar or Audio selection timecode indicators, or vice versa. 

I do however think that we should revisit this hierarchy in Qt, when the snapping tool will live inside the timeline.

**Comment by DavidBailes** [comment]
> We do think however, that the formats should remain independent. Changing the snapping format will not update the Time toolbar or Audio selection timecode indicators, or vice versa.

It that's the case, then I presume that on the snapping toolbar menu, the menu items are snapping intervals rather than formats. Eg, rather than the three items seconds, hh::mm::ss, and dd::hh::mm::ss, there is just a single item, seconds.

**Comment by dawsoncustonscole** [comment]
The snapping intervals will be as follows:

![image](https://user-images.githubusercontent.com/80491557/220643813-ff9760f3-1f35-4c2c-9cd9-ac750213bb70.png)

**Comment by DavidBailes** [comment]
> The snapping intervals will be as follows:

Thanks.

**Comment by DavidBailes** [comment]
> As to the other point about accessibility, @DilsonsPickles is creating that specification now and we'll share it in advance.

@DilsonsPickles  Please could you share the specification for accessibility?

**Comment by DavidBailes** [comment]
> > As to the other point about accessibility, @DilsonsPickles is creating that specification now and we'll share it in advance.
> 
> @DilsonsPickles Please could you share the specification for accessibility?

@LWinterberg .Since @DilsonsPickles doesn't seem to be around, could you please share the specification?

**Comment by Ryan-Miller-Audacity** [comment]
Tested and confirmed implementation on both MacOS and Windows.

**Comment by Wesley107772** [comment]
About point 3: Why was this necessary? This couldn't just remain as its own toolbar? The functionality is still there, sure, but this adds forced unnecessary clicks to both view and edit the project rate. That at absolutely no gain because for me over half of the bottom bar is empty space regardless.

**Comment by LWinterberg** [comment]
The exporter is getting its own sample rate soon which resolves  most of the current sample rate troubles
