### ISSUE TITLE
Generating a sound of certain duration produces the result one sample shorter than it should be

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4291]
### Bug description

When generating a sound using Generate menu and providing a certain length of the desired clip, the resulting audio clip is always one sample shorter, i.e. if the specified length is, for instance, 10 seconds, the clip's actual length will be 10 seconds - 1 sample.

### Steps to reproduce

1. Generate > DTMF/Chirp/Noise etc.
2. Specify Duration, e.g. 30 seconds, click Generate
3. Zoom in and check the resulting clip's length

### Expected behavior

The clip's actual length is exactly 30 seconds

### Actual behavior

The clip's actual length is 30 seconds - 1 sample.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/70063970/217300401-b205d6f7-b04f-4b20-b612-bf17d1161c88.png">

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

when I select the whole clip by clicking in its drag-bar I note that although the last sample is before the 30 second mark as tou note - but the clip still appear to be a full 30 seconds
![image](https://user-images.githubusercontent.com/50205984/217618716-7376a310-6e76-4c02-806b-9bf157d311df.png)

**Comment by LWinterberg** [comment]
The number of samples is correct - generating 10 samples indeed generates 10 samples. 

![image](https://user-images.githubusercontent.com/87814144/217625308-4b29238d-677e-4702-9b8d-c828c2e6d22e.png)

**Comment by dozzzzer** [comment]
So, the problem is that the generated clip only _appears_ to be shorter due to the right edge of the clip not matching the time mark on the timeline?

**Comment by LWinterberg** [comment]
Yes. The underlying problem here is that while samples are just points in time, this would be a valid (abeit low-quality) interpolation:

![image](https://user-images.githubusercontent.com/87814144/217627632-bd9f8ea0-6ffe-45b4-9f7c-158786d36700.png)

There's an argument to be made that the clip boundary therefore should extend the entire sample worth of time to the right (in which case it'd line up here) - but the very same argument can be made for the current behavior, or splitting the difference and going for the middle instead: 

![image](https://user-images.githubusercontent.com/87814144/217628758-0a84cee7-483a-4bae-9526-520b29bea05a.png)

In practice, going half a sample worth to either side *probably* makes sense for the clip visualization as it prevents the border obscuring the sample - but at the same time it's an incredibly unimportant fix

**Comment by LWinterberg** [comment]
I think this is a wontfix either way
