### ISSUE TITLE
When pasting a clip into a blank project, it's half a sample shifted left to zero mark

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4297]
### Steps to reproduce

1. Have an audio clip in the project
2. Copy a portion of it
3. Ctrl + N
4. Ctrl + V
5. Observe the left-hand arrows on the left edge of the clip
6. Enable scrolling left to zero in Preferences
7. Zoom in around zero mark

### Expected behavior

The clip start is perfectly aligned with zero

### Actual behavior

The pasted clip is about half a sample left to zero:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/70063970/217641769-d0b837f1-235f-4e2b-bc25-fa23ee5f8c8f.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/70063970/217641439-a58bc189-dc7c-443d-a429-b2c943ef8489.png">

### Audacity Version

3.2.4

### Operating system

Windows, macOS

**Comment by JohnColket** [comment]
@dozzzzer - Thanks for that detective work. :smiley:  I've been wondering where all of those lovely double-arrow decorations come from....

**Comment by petersampsonaudacity** [comment]
Does **not** happen if you select the whole clip and then paste that into the new track at T=0

This implies that it has something to do with the "smart clips"

**Comment by petersampsonaudacity** [comment]
Curiouslu this does **_not_** happen with @vsverchinsky Vitaly's latest branch build:  audacity-win-3.3.0-alpha-20230209+ab085c8-x64

This is the fix that Vitaly has for the Clip Copy Dialog - and not designed to address this issue, but seemingly it does do so

**Comment by dozzzzer** [comment]
To be checked if that's a regression

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/235165141-b3a215ea-dd46-4214-9fdf-c54e3fdcbc49.png)
![image](https://user-images.githubusercontent.com/87814144/235165238-4c04abe9-6442-4520-929a-b93491c8016a.png)
This does not need to be in a new project, I was able to get it happen by just moving 2 clips repeatedly and letting them snap to 0. 

Maybe a float imprecision?

**Comment by saintmatthieu** [comment]
When copying, we don't round the boundaries of the selected region to an integer amount of samples right away. This leads to a mixture of rounded and non-rounded variables, in particular the trimming (rounded) and the offset (non-rounded) which I believe in some combination explains the results in @LWinterberg 's snapshot.

Trimming and dragging can only be done by an integer amount of samples. I see no harm in having copying abide by this rule, too. Pushing a fix proposal that goes in this direction ...

**Comment by DavidBailes** [comment]
> To be checked if that's a regression

There appears to be a regression wrt 3.1.3, at least for the following steps to reproduce:
1. Generate noise, with duration 10 samples.
2. Make a selection which starts more than half way between two adjacent samples. (If it starts less than half way, the issue does not occur.)
3. Copy the selected audio
4. Create a new track
5. Position the cursor at some arbitary position
6. Paste the audio into the new track. You would expect the the first sample of the audio to be at position of the cursor.

Using Audacity 3.3.1:
After step 2:
![image](https://user-images.githubusercontent.com/11887021/235294912-a978302b-d38f-46c4-bb52-38c49b0f76b8.png)
After step 5:
![image](https://user-images.githubusercontent.com/11887021/235294950-20be388f-6860-493a-a8d3-424f5151d8c3.png)
After step 6:
![image](https://user-images.githubusercontent.com/11887021/235294977-196fb83d-c4df-4aaa-a7dd-0fc465f02210.png)

Using Audacity 3.1.3:
After step 2:
![image](https://user-images.githubusercontent.com/11887021/235295329-2836b6a1-4100-441f-994b-d90c051e9b66.png)
After step 5:
![image](https://user-images.githubusercontent.com/11887021/235295363-0113d1d9-2a05-4a18-8a0a-02552af0ceff.png)
After step 6:
![image](https://user-images.githubusercontent.com/11887021/235295399-ff014156-22b2-4136-a953-183ef80d6bde.png)

**Comment by saintmatthieu** [comment]
@DavidBailes thanks for this demonstration.
No doubt that the current result is wrong. I question though if the 3.1.3 result makes sense ? I'm of the opinion here that the behaviour should be what-you-see-is-what-you-hear. Currently, the first sample of your last track of your last picture would be summed with the sample to its left in the track above for playback.

**Comment by saintmatthieu** [comment]
@vsverchinsky dug [this thread](https://discord.com/channels/822396597085667338/839494323736674335/888074892757594163), will process that information when I have time before proceeding, seems very relevant.

**Comment by DavidBailes** [comment]
> No doubt that the current result is wrong. I question though if the 3.1.3 result makes sense ? I'm of the opinion here that the behaviour should be what-you-see-is-what-you-hear.

Would the user be able to hear any difference if the tracks were combined using a higher quality interpolation?
If either the playback device cannot play the sample rate of the project, or an Audacity project contains tracks with different sample rates,  a user does not see what they hear.
Reaper handles this situation in a similar manner to Audacity 3.1.3.

**Comment by saintmatthieu** [comment]
The current playback works equivalently to having track samples shifted so that the closest sample falls at the cursor. Interpolation for tracks of differing sample rates comes after. Interpolating tracks of matching sample rate would bring coding complexity and processing load no one wants.
In that respect, a "true" wysiwyh would require repainting of the samples each time to cursor is replaced. (I hadn't realized that in my previous posts.) This is probably also over the top and it could be confusing for the user to see samples move. Hence so far the most obvious I can think of is to keep the samples painted such that alignment at zero is respected.
We should also consider that time stretching is upcoming. From a UX perspective things become hard to grasp. If the zero-alignment rule were easily paintable it might bring comfort to the user to see that things are halfway under control. In any case, I suggest postponing this ticket until then, since sample painting will have to be addressed anyways.

**Comment by saintmatthieu** [comment]
Of course you're right, @DavidBailes, you don't get what you hear when there's resampling and even less when there'll be time stretching. I even am not sure that what you see is what you hear without those since the DAC is processing these in ways I don't know about. In the equal-rate case, though, the user might be interested in seeing which samples add to which, or if a large leading, clipping sample gets played or skipped, that's about all the guarantee we can give.

**Comment by dozzzzer** [comment]
Fixed by https://github.com/audacity/audacity/pull/5043

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's latest 4 of 6 branch build:  audacity-win-3.4.0-alpha-20231005+7737b4b-x64

This now appears to work properly in Matthieu's 4 og 6 branch build.

I tested with copying smart clip and just the selection for both an un-shrunk clip and a shrunk/stretched clip.

In all cases there was no audio in negative time with the shrunk/stretched clips the stretch percentage was retained in the copied clip in the new project.
