### ISSUE TITLE
Incorrect WAV data when exporting with list

### ISSUE THREAD

**Issue by Theo-Bradley** [audacity/audacity#4401]
### Bug description

When exporting a .vaw file with 16 bit uncomprecced/pcm data with audacity 3.2.5 (also reproduced with 3.1), the encoder produces a valid file, but if metadata tags are added, a list block is created at the end of the file with an incorrect chunk data size (i got 170 bytes when the block was 361 bytes). The issue was found because i am writing a .wav loader so the issue could be on my end (please enlighten me if so lol) but if so i don't understand how the list block can be bigger than its listed size.
I used https://sites.google.com/site/musicgapi/technical-documents/wav-file-format#cue (although the site seemts to not be working now) for the layout of the wav file

### Steps to reproduce

1. load up a wav file and export it with the metadata/tags using uncompressed 16 bit encoding

### Expected behavior

Proper file is generated and the LIST block has the appropriate size

### Actual behavior

Proper file is generated but the LIST block has the wrong size listed (4 bytes after LIST represent the little endian unsigned 64 bit integer size)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by Ryan-Miller-Audacity** [comment]
Hey @Theo-Bradley, can you help me understand a little bit more so that I can work on reproducing this? What are you using/how are you checking the LIST block size? If you could provide clearer instructions for this portion I can take a closer look to see if this is an Audacity problem or not. Thanks!

**Comment by Theo-Bradley** [comment]
> Hey @Theo-Bradley, can you help me understand a little bit more so that I can work on reproducing this? What are you using/how are you checking the LIST block size? If you could provide clearer instructions for this portion I can take a closer look to see if this is an Audacity problem or not. Thanks!

I used a hexeditor to check the 2 bytes that represent the integer size after the 4 bytes that say LIST. If you make those two bytes into one unsigned int it should show the size of the list chunk (minus LIST and size). I got my wav loader working with modified list size btw. An easy way to find the list chunk is to export twice, once with metadata once without then go the the final byte of the first file in the second and that will be the list chunk. It should be layed out like this: L,I,S,T,xx,xx,........, Where xx and xx are the two bytes of the size (little endian integer)

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/226611006-e8ddd453-7b02-4788-8914-b453f877e97e.png)
So, if I read this correctly: 
* Following `LIST` is `12 00`, so we're looking at 18 bytes. 
* `..INFOIART....Test` are our 18 bytes as far as LIST is concerned 
* Following that is an - officially probably non-standard, but de-facto used `id3 ` chunk (with the space in it's 4-byte identifier), with `1A 00`, so 26 bytes
* `..ID3 [...] Test` are 27 bytes. I wonder if this is an off-by-one, or if the NUL bytes are supposed to be counted differently to how I did it. (maybe there's an uncounted NUL between chunk length and content start? Maybe ID3 chunks are measured in U32 and not U16? I have no idea)

I think this is where your confusion comes from anyway: There's another chunk you're not expecting. I found reference in the kde bugtracker indicating iTunes has been doing this since 2006 at least - https://bugs.kde.org/show_bug.cgi?id=131130#c3

**Comment by Theo-Bradley** [comment]
> ![image](https://user-images.githubusercontent.com/87814144/226611006-e8ddd453-7b02-4788-8914-b453f877e97e.png) So, if I read this correctly:
> 
> * Following `LIST` is `12 00`, so we're looking at 18 bytes.
> * `..INFOIART....Test` are our 18 bytes as far as LIST is concerned
> * Following that is an - officially probably non-standard, but de-facto used - `id3 ` chunk (with the space in it's 4-byte identifier), with `1A 00`, so 26 bytes
> * `..ID3 [...] Test` are 27 bytes. I wonder if this is an off-by-one, or if the NUL bytes are supposed to be counted differently to how I did it. (maybe there's an uncounted NUL between chunk length and content start? Maybe ID3 chunks are measured in U32 and not U16? I have no idea)
> 
> I think this is where your confusion comes from anyway: There's another chunk you're not expecting. I found reference in the kde bugtracker indicating iTunes has been doing this since 2006 at least - https://bugs.kde.org/show_bug.cgi?id=131130#c3

You are right, looks like I wasn't handling this id3 chunk properly, probably a compund issue of my file reader being screwy and it not being listed in the spec. Thats likely because it looks to me to be not part of the standard, and it also simply reiterates the same info as the list chunk.

I'm really not sure about audacity exporting with a chunk that isn't in the riff standard, seems like bad practice to me even if it is widely used. I suppose this issue is resolved.
Thanks for the help.

**Comment by Theo-Bradley** [comment]
> 

also sidenote: the size is actually 4 bytes (my bad), and I don't see this off by one error, as the id3 chunk in your image has 26 bytes by my count ("id3 " = 4 bytes, 1A 00 00 00 = 4 bytes, 49 44 33 03 00 00 00 00 00 0F 54 50 45 42 00 00 00 06 00 00 00 54 65 74 74 00 = 26 bytes)
