### ISSUE TITLE
Resampling a track causes part of it to be trimmed

### ISSUE THREAD

**Issue by somefoolouthere** [audacity/audacity#4417]
### Bug description

Resampling a track to any other sample rate (such as 44100 hz to 48000 hz) causes a part of the end of it to be trimmed off. The trimming only appears after undoing and redoing, or when applying macros.

### Steps to reproduce

1. If not set already, set the project rate to 44100 hz
2. Generate a 1 minute long 440 hz sine tone in Generate > Tone
3. Resample the track to 48000 hz in Tracks > Resample
4. Observe: tacks is still 1 minute long exactly
5. Undo and then redo (Edit > Undo then Edit > Redo)
6. Observe: track is now reduced to c. 55 seconds

### Expected behavior

The track would remain at about the same length after undoing and redoing.

### Actual behavior

Over 5 seconds of audio has been cut off from the end of the track after undoing and redoing.

### Audacity Version
3.3.0 alpha  -  audacity-win-3.3.0-alpha-20230315+388e332-x64-msvc2022

### Operating system

Windows

### Additional context

Tested on audacity-win-3.3.0-alpha-20230315+388e332-x64-msvc2022

**Comment by petersampsonaudacity** [comment]
Confirmed on W11 with audacity-win-3.3.0-alpha-20230315+388e332-x64-msvc2022

**Comment by Ryan-Miller-Audacity** [comment]
Confirmed I can reproduce this as described above.

Additionally, I noticed that if you change the track rate via the Track Control Panel you can see the same cut takes place so this is a case that will need to be confirmed when this issue is fixed. I was able to reproduce this case back into at least Audacity 3.2.1. 

STR: 
1. Generate tone 1 minute in length
2. Via the Track Control Panel select the header and change the rate via the context menu
3. Note the cut takes place when changing rate.

[tcp-track-change-trims-audio.webm](https://user-images.githubusercontent.com/88568755/226931085-eab2699a-e73e-4ade-bce0-6f979564716e.webm)

**Comment by Ryan-Miller-Audacity** [comment]
Tested and confirmed via PR #4458. Issue noted in comment above is a non-issue in terms of this. Simply put, "Resampling is not the same as adjusting the track rate" and effects the track differently. (Adjusting track rate changes duration, frequency etc. Resampling does not).
