### ISSUE TITLE
Project window loses focus after returning from some dialogs (macOS)

### ISSUE THREAD

**Issue by billw58** [audacity/audacity#4435]
### Bug description

Tested with 3.2.5 Universal on M1 and Intel.
Behaviour exists at least back to 3.0.2

### Steps to reproduce

1. Start Audacity
2. Generate anything
3. note that the project window widgets (zoom minimize close) are greyed out, and the newly-created track does not have keyboard focus
4. Click in the project window, create a new track and generate into it
5. you cannot move focus between tracks using the keyboard commands because no track has keyboard focus
6. Select a track and Amplify

### Expected behavior

The window should not lose focus
The current track should not lose keyboard focus

### Actual behavior

track no longer has focus

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by dozzzzer** [comment]
Great catch, @billw58 !

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
