### ISSUE TITLE
Flickering of labels in LinearDB Ruler

### ISSUE THREAD

**Issue by micpap25** [audacity/audacity#4439]
### Bug description

https://user-images.githubusercontent.com/34077605/227057891-db6ba695-b583-48d2-963d-ce73d74785cc.mp4

### Steps to reproduce

1. Create a waveform with LinearDB VRuler
2. Adust its size

Will flesh out issue further another time

### Expected behavior

No flickering

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
