### ISSUE TITLE
Help/Info button is non-clickable in Audio Settings menu

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4451]
### Steps to reproduce

1. launch Audacity
2. navigate to Preferences > Audio Settings
3. in the Quality section, click the question mark button

### Expected behavior

Clicking the button spawns a tooltip: 
"Project Sample Rate used when recording new tracks and for playback, mixdowns and exports in this project"

### Actual behavior

No action

<img width="487" alt="image" src="https://user-images.githubusercontent.com/70063970/228004369-525a799d-f04f-4802-bd05-8eddf8203942.png">

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by crsib** [comment]
Well, that is by current design more or less

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
