### ISSUE TITLE
Lower time signature value gets hidden when dragging the time signature toolbar (macOS)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4455]
### Bug description

The lower time signature value gets hidden when 
a) dragging the time signature toolbar to a different place 
b) hiding/showing the time signature toolbar

### Steps to reproduce

1. in the [latest bottom bar UI build](https://github.com/audacity/audacity/actions/runs/4532690177), select the lower time signature (LTS) value as 32 or 64
2. hide and then show the **Time Signature Toolbar** in View > Toolbars menu OR
3. drag the toolbar to a different place (e.g. on the right-hand side of the **Snapping** toolbar)
4. observe the LTS value

### Expected behavior

LTS is fully visible

### Actual behavior

LTS gets partly hidden when dragging the toolbar to a different place:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/70063970/228291611-68997f8e-9eb3-405b-b52f-09973a78ad5e.png">

...and it gets hidden even more when hiding/showing the **Time Signature** toolbar:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/70063970/228291748-471591d8-ee4c-46cd-82de-9ebad59285c3.png">

### Audacity Version

other

### Operating system

macOS

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
