### ISSUE TITLE
New (double heighted) toolbars are forced to new line 

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#4492]
### Bug description

When a new (double heighted) toolbar is created and there is a single heighted toolbar last, the new double heighted toolbar will be forced to a new line rather than falling in line with the rest of the toolbars. This is the case for the two most recent toolbar additions: The audio setup toolbar in the upper UI and the Time Signature/Tempo toolbar (BETA) in the bottom UI. 

We were able to circumvent this behavior from impacting users with the Audio Setup button in 3.2 by resetting the toolbar config as part of the update; however, since the Time Signature/Tempo toolbar is beta and hidden by default, when it is enabled it will be attached to a new line below the bottom bar and requires the user to manually drag it to the correct line. 

https://user-images.githubusercontent.com/88568755/229893461-1afe56ff-feb3-489d-bc6c-8fe3e3137bdf.mp4

### Steps to reproduce

1. Open Audacity 3.3
2. Click View -> Toolbars -> Time Signature Toolbar (Beta)
3. Note that the Time Signature toolbar was added to the bottom UI but is out of place (not in line with the other elements)
4. You can see the same in the upper UI by toggling the Audio Setup toolbar on/off 

### Expected behavior

Toolbars should be positioned appropriately with the other elements within their UI area.

### Actual behavior

Toolbars are added to an additional line rather than aligning with the other elements within their UI area.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by petersampsonaudacity** [comment]
Same thing happens with the Spectral Selection toolbar.

And not this is not a new issue with this toolbar (not a result of the new lower tooldock changes) it happens in 3.2.5 and earlier, stemming from the time the single-height Play-at-Speed Toolbar was moved from the upper tooldock to the lower tooldock.

The underlying issue is that Auadacity doesn't like to place double-height toolbars to the right in single-height ones.

![image](https://user-images.githubusercontent.com/50205984/230057573-715e98bc-b5e3-4655-bf17-6f83ab6bcc02.png)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
