### ISSUE TITLE
Beats & Measures: visible ruler denotations depend on the lower time signature selected

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4508]
### Bug description

When selecting time signatures 16/16, 32/32 and 64/64, the visible intervals on the beats and bars ruler get larger.

### Steps to reproduce

1. Enable beats & measures ruler
2. Generate a 30-sec chirp
3. Cmd (Ctrl) + F
4. Select 4/4 or 8/8 in the time signature toolbar and click anywhere outside (tracked in issue #4486)
5. Observe:  the increment of the ruler is **1 beat**
6. Now change the time signature to 16/16 or 32/32 and click anywhere outside

### Expected behavior

The increment between the denotations equals 1 beat:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/70063970/230494175-b721f9f9-f180-4ba5-9db1-160a37ea7171.png">

### Actual behavior

The increment between the denotations changes to 4 beats at 16/16:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/70063970/230494223-0d5118fa-fddd-44ad-b83d-40ef823f33a0.png">

And to 16 beats at 32/32:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/70063970/230494549-4fd489df-e4a6-443b-a949-3ee58c0ee901.png">
changes

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
