### ISSUE TITLE
When placing cursor into the snapping text box, cursor will always stay there

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4533]
### Steps to reproduce

1. Enable snapping
2. Click on the default "Seconds" value
3. Observe: cursor now flashing 
4. Click anywhere outside
5. Observe

### Expected behavior

The snapping text box is read-only, so clicking the currently selected option should not allow the cursor to be placed inside the string

### Actual behavior

The cursor keeps flashing inside the text box even when snapping is disabled:
![2023-04-11_12-24-57 (1)](https://user-images.githubusercontent.com/70063970/231145778-82bd0e85-2a38-4501-8073-4771007a0d67.gif)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by crsib** [comment]
Yeah, Focus in wxWidgets is odd...

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
