### ISSUE TITLE
Realtime builtin effects: cannot enter decimal separator if Extra menu is not shown

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#4539]
### Steps to reproduce

With the Extra menu not shown in the menubar:
1. Add Bass and Treble as a realtime effect to a track
2. Open its dialog, and in one of the text boxes, delete the current entry and try and enter a number which includes a decimal separator, eg 3.4

### Expected behavior

You can enter the number

### Actual behavior

The decimal separator is not entered.

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

There is no problem if the Extra menu is shown.

https://github.com/audacity/audacity/issues/4457 is a related bug.

**Comment by DavidBailes** [comment]
> is this the dialoge where you was getting the issue?

No, that Bass and treble dialog was opened from the Track menu.
The bug occurs in the beta version of audacity when you add the Bass and treble effect using the add effect button in the realtime effects pane, and then open its dialog.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
