### ISSUE TITLE
Crash related to `convolve` and `snd-avg`, reproduces by applying De-Clicker plugin with disabled crash workaround

### ISSUE THREAD

**Issue by alopatindev** [audacity/audacity#4689]
### Bug description

There's some ancient memory access issue, not sure whether it's ever been reported.

Crash reproduces perfectly on Gentoo GNU/Linux (x86_64), latest Audacity version 3.2.5-r1 from portage. [Stacktrace](https://gist.github.com/alopatindev/2f6872a20e8b9cb64ed160dea3e91ecd).

Please let me know if you need more details. Thanks!

### Steps to reproduce

1. Download [De-Clicker plugin](https://forum.audacityteam.org/t/updated-de-clicker-and-new-de-esser-for-speech/34283) to `~/.audacity-files/plug-ins/`
2. Change `(setq use-crash-workaround t)` to `(setq use-crash-workaround nil)` in the plugin
3. Run Audacity, open/record any sound, select all
4. Effect - De-Clicker - Apply

### Expected behavior

Should apply de-clicker plugin

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
