### ISSUE TITLE
Change default export folder to location of opened file

### ISSUE THREAD

**Issue by shankarsivarajan** [audacity/audacity#4690]
### Your idea

When I open a file for editing (Right click > Open with > Audacity, and not drag-and-drop, if that makes a difference), and then try to export the edited audio to a file, it would be better if the default export folder is the location of the opened file instead of the previously used folder, or fixed default location, which is currently the only alternative.

I'm using Audacity 3.3.2 on Windows 10.

### Problem to be solved

Implementing this change would allow users not to have to specify the export folder every time they use the app if they happen not to store all their audio files in a single folder, which appears to be the expectation for the current design.

### Prior art

The behavior I suggest is typical of most text and image editing programs I have used.

**Comment by LWinterberg** [comment]
I've run across this idea several times now, and am hesitant to advocate for a single-last-used-path solution (which would be what most other software uses which expects simple workflows). 

However: having Open also set Save and Export paths is intriguing. It wouldn't get in the way too much of people operating more complex projects and it would make OP's situation work as expected.

**Comment by petersampsonaudacity** [comment]
Curiously this requested behavior was what obtained in Audacity 1.2.6

I can't remember when (or why) this got changed.

Bur the last change was late in the 2.x.x series when @JamesCrook  added the various option default directory locations with the option of leaving that blank an using "last-used" location:
![image](https://github.com/audacity/audacity/assets/50205984/90cd9600-c33f-4efb-9f51-6ec289d3e8fb)

**Comment by petersampsonaudacity** [comment]
Exporting back to the folder location that a file was imported from makes some kind of sense when the user imports and works on a single audio file.

But what happens if the user imports several different files from several different locations?  Does Audacity use the location of the first imported file or the last one _(or maybe use the location from which the most files were imported)_?

**Comment by shankarsivarajan** [comment]
Sure, they're all equivalent for a single audio file, but I think the location of the _first_ file is the natural choice, motivated by the following intuition.
First, you have this question even when you open Audacity .aup3 files, where it's unambiguous.
I suggest that opening a file with Audacity should be thought of as creating a placeholder project file (in the same folder as the file) into which the file is imported. (I also conjecture that this is how most people imagine it already.)
Thinking of each imported file as influencing the default is contrary to this model.

**Comment by tristan00b** [comment]
I have been using the same workflow that shankarsivarajan described above and was just about to create an issue myself. I would also appreciate Audacity defaulting exporting to the location of the last opened/imported file.

**Comment by petersampsonaudacity** [comment]
I see some contention as to who requires what:

@shankarsivarajan   asks for
>I think the location of the first file is the natural choice

while @tristan00b asks for
>I would also appreciate Audacity defaulting exporting to the location of the last opened/imported file

**Comment by tristan00b** [comment]
@petersampsonaudacity Apologies, I meant in the case of a single file. For multiple files, I personally would again go with the location of the *last* opened file, but perhaps there could be an option added to preferences?

E.G.

`When multiple files are imported, offer to export to:`
  `a. the location of the first opened file`
  `b. the location of the last opened file`

**Comment by shankarsivarajan** [comment]
I never import multiple files without first creating a project file, so this doesn't affect me.

However, once a project files is created, I think its location should be default export, and _not_ the location of any of the imported files, first, last, or most common.

**Comment by LWinterberg** [comment]
This issue is one that has to be solved without an option in the preferences IMHO. Directory preferences already are rare enough in apps, a setting of "overwrite last used export directory when opening a file" is extremely niche and a "when multiple files are opened, default export to..." setting is specific to all of about 5 people. 

This also is why I'm hesitant to add a "use the same directory for all operations"-type settings: The people who would most benefit from it (ie people casually editing out silences or trimming annoyingly long applause on live performances) also are the people who are least likely to discover this option - or even have the thought cross their mind that such a option could exist. 

So to me there's only three possible ways forward with this: 

1. We find something that opinionates the existing logic slightly - eg the "having Open also set Save and Export paths" from above, or maybe something else - which improves the hit rate of this logic for what it is most users actually want to do
2. We add a file menu entry of "overwrite <opened file>" which appears under some circumstances (á la GIMP)
3. We change nothing about the logic and instead improve the export dialog. One change that currently is being worked on is to use the Windows 10/11-style explorer dialog instead of the Windows Vista one

**Comment by LWinterberg** [comment]
Number 3 is being done right now, number 2 is #762 which already has a design. With both of them in place, this feature becomes extremely niche and is hopefully no longer needed.

**Comment by LetMyPeopleCode** [comment]
Google's AI hallucinates that you can set the default export folder to "Project Folder" although that doesn't seem to be an actual option. If I open an AUP, defaulting to the directory from which it was opened shouldn't be too difficult with a fallback to last used (current default) if there's any uncertainty.

Every reason for why not that I read from people on various threads is some flavor of "it's too complicated." No, you're overcomplicating it. It doesn't need to support every possible use case and edge case. I'd happily script something up in Python but the scripting reference is not great.

**Comment by ermina** [comment]
after getting annoyed for the millionth time by this, i searched and found this issue.
Why the default export folder does not track the folder of the first opened file is beyond me.

My main use for Audacity is mainly opening a single existing file to do some super quick edit/transform and export with another name/format. No saving of project or anything. I don't want to see the folder that i used ten days ago on the other side of my data storage for another thing unrelated to the task at hand when i just need a super quick edit done locally in my current working folder; it's not so quick anymore when i have to shuffle back to this current folder just to export !
