### ISSUE TITLE
Relocate caching from SampleTrackCache to some place below WaveClip

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#4717]
### Your idea

Relocate caching from SampleTrackCache to SQLiteSampleBlock

### Problem to be solved

So far I've only come up with one reason for the SampleTrackCache, namely to limit the queries to SQLiteSampleBlock, which have a very large overhead.

However there are 3 problems with that :
1. StretchingSampleTrack is underneath SampleTrackCache, and when the latter pulls such a large amount of samples at once, the time-stretching processing time will cause a large outlier in the time it takes for SampleTrackCache::GetFloats to complete.
2. This propagates caching complexity rather high up in the stack. Why not doing it at the lowest level possible, namely in SQLiteSampleBlock?
3. Introducing time stretching makes the mapping from UI time to raw clip sample indices even more complex. I'd like to centralize this mapping logic and remove all sample index mentions from the WaveClip and WaveTrack API. SampleTrackCache uses these methods, though.

### Additional context

I've already made experiments and measurements. In the figure below, I compare the time it takes for SampleTrackCache::GetFloats to execute without any caching (each GetFloats results in an SQL query), with caching as currently done, and with a quick-and-dirty caching (to be improved) I wrote in SQLiteSampleBlock. Observations :
* Caching does improve performance by an order of magnitude, reducing from an average of roughly 1ms down to 1us,
* The caching method still has outliers, namely the few calls where GetFloats results in an SQL query,
* caching in SQLiteSampleBlock works and provides equivalent performance, even roughly written.

![GetFloats elapsed time](https://github.com/audacity/audacity/assets/22740106/f5c3b5a1-c718-4851-98e1-82c2268fd04a)

**Comment by Paul-Licameli** [comment]
I made SampleBlockCache originally because looping over an interval shorter than a block avoids repeated fetching if a block to fill up the ring buffer of samples to play.  Used to be, if you looped just some milliseconds, there was a large pause before play started.

The caches can act as an anticipatory pre fetch of data to be processed later and can also help in cases of looping or scrubbing reversing direction.

Isolated sample blocks don’t know what interval of time they cover.  I’m not sure how the benefits are then preserved.

The present caches store not more than two adjacent blocks of the track.  If you rewrite the caches, what is the eviction policy that will avoid excessive occupation of memory resources?

**Comment by Paul-Licameli** [comment]
Perhaps the best level for caching is in the Sequence class, not at the individual blocks.

This is still upstream of the time-stretching processing that will be interposed by StretchingSampleTrack while it also knows the adjacency of blocks.

This would put a cache inside each clip rather than as before associating the cache with a track.  But it could implement the policy of caching not more than two adjacent blocks.

Whever now a SampleTrackCache is destroyed as no longer needed -- I think the memory resources of the new caches could be released.

**Comment by dozzzzer** [comment]
Tested
