### ISSUE TITLE
Privacy Policy link pops up at the left upper corner of the windows after running Get Info macro command

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4803]
### Steps to reproduce

1. Enable Extra menu
2. Extra > Scriptables II > Get Info
3. Select "Type": "Preferences"
4. Click OK
5. Observe

### Expected behavior

No Privacy Policy link after the message is printed out

### Actual behavior

After the message is printed out, at the left upper corner of the windows appears the Privacy Policy link:

<img width="500" alt="Screenshot 2023-06-16 at 18 53 49" src="https://github.com/audacity/audacity/assets/70063970/912986a2-c468-48bd-a159-126b7d957db9">

### Audacity Version

The build from PR #4799 

### Operating system

Any

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
