### ISSUE TITLE
[Bug] Not able to open file if /path/to/file contains spacing.

### ISSUE THREAD

**Issue by CHJ85** [audacity/audacity#4856]
I'm using Manjaro. When I right click > open with > Audacity, I'm unable to open files if the path contains spacing.
The issue here is that the import function is not set up correctly. The file needs to contain double quotes.
Because now when I try to open an mp3 file in my "Sound Effects" folder, Audacity says "/home/chris/Sound could not be found". Then I press OK, and a new dialog window pops up saying "Effects could not be found".
This is a rather recent bug.
However, dragging the file into Audacity works fine.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Comment by CHJ85** [comment]
Okay. Thanks.
