### ISSUE TITLE
Buttons at the bottom of the Screenshot dialog are broken (Windows)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4884]
### Bug description

Screenshot dialog is partially broken on Windows.

### Steps to reproduce

1. Tools > Screenshot
2. Check the bottom of the dialog

### Expected behavior

<img width="465" alt="Screenshot 2023-07-07 at 12 33 54" src="https://github.com/audacity/audacity/assets/70063970/3c43b170-1015-4d43-a3f4-da73fb506e2d">

### Actual behavior

<img width="526" alt="Screenshot 2023-07-07 at 12 28 56" src="https://github.com/audacity/audacity/assets/70063970/e0a5d2dc-af66-4aa0-bc19-86284323cb47">

### Audacity Version

other: https://github.com/audacity/audacity/pull/4825

### Operating system

Windows

### Additional context

A regression introduced by PR #4825

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
