### ISSUE TITLE
Persistent crackling noise on Pa_Initialize() call

### ISSUE THREAD

**Issue by guskovd** [audacity/audacity#490]
When starting audacity or changing playback to my sound card, I hear a clicking noise.
I managed to find out at what exact moment this is happening. It seems to be a matter of calling Pa_Initialize

My sound card: Focusrite Scralett 2i2 USB
my OS: Archlinux

As I understand it, this is a portaudio problem, not an audacity

--
Did you come across something similar? Do you have any idea how to solve this problem?

**Comment by guskovd** [comment]
Solved the problem by switching to jack

**Comment by hamoid** [comment]
Hi, do you have a link to the portaudio problem?

I found your issue looking for a reason to the harsh clicking sound when starting Audacity.
I do not experience this issue with other software in Archlinux. This happens with the integrated sound card on a Fujitsu laptop.

The crackling sound is so strong that I think it can be damaging for ears or speakers.
I always need to remember to remove my headphones before opening Audacity.

I could provide a recording if it helps someone. It's not only one click, but many (maybe 8?).
In my imagination it happens when probing different audio configurations, but I have no idea about the actual reason.
