### ISSUE TITLE
Changing track height as well as collapsing/expanding should make project dirty

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4914]
### Steps to reproduce

1. Add a track of any type
2. Change its height OR collapse the track OR expand the track (if it's collapsed)
3. Ctrl + Z or Edit > Undo
4. Observe

### Expected behavior

Height change or collapsing/expanding is undone

### Actual behavior

The track is gone

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

The issue exists at least since 2.4.2

**Comment by LWinterberg** [comment]
This works the same way as other view changes (eg switching waveform -> spectrogram) and making selections: The view change is amended to the undo stack without creating its own step, but if you undo you enter into the state you previously had. This is intentional as otherwise you end up with tons of view changes in the undo steps, which makes undoing actual changes more cumbersome.
