### ISSUE TITLE
Add an option to disable plugin scanning at start up

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4923]
### Problem to be solved

See: https://forum.audacityteam.org/t/how-to-disable-vst-scan-at-startup/80093
And: https://forum.audacityteam.org/t/non-audacity-plugins-vsts-insist-on-loading-every-time-ignoring-disabled-tag/71271

### Your idea

Add an option to skip plugin scanning at start-up so users can launch Audacity faster.

**Comment by miyl** [comment]
Great suggestion. It also seems to be a topic popping up in several places but no solution has yet been found.
If you don't use Audacity for plugins and you have many, then it's just a hassle, especially when you're using to using Audacity for quick fixes because it boots up so quickly compared to e.g. DAWs.

**Comment by jamshark70** [comment]
To add another rationale -- I most often use Audacity for tasks for which Audacity is ideally suited -- such as: export from DAW with a little extra, and then use Audacity to trim it down precisely, apply fades etc.

One does not need every installed plug-in for this.

With Audacity 2, one of the nice features was that it was very easy to navigate to, for instance, Studio Fade Out, because there weren't so many plug-ins enabled by default.

By contrast, in my current Audacity 3 installation, it took ~20 seconds for the Effect menu to scroll to the bottom. Why to the bottom? Because while it's scrolling, you can't see when you've reached the S-es. OK, so then I tried to scroll back up a bit, but the mouse slipped, touched the neighboring menu -- start over??? Another 20+ seconds? So in that attempt, I never did actually find Studio Fade Out.

This is not a workflow improvement. This is actually the kind of thing that will make me stop using Audacity for these routine tasks (or downgrade to 2.x).

Audacity is *the best* for this kind of end-stage trimming and exporting to very specific formats... but it might not continue to be the best if it forces uses to wade through pages and pages of plugins. Do not underestimate how disruptive it is to have a bloated and un-navigable Effect menu.

So there a couple of needed features here: 1/ Allow the user to leave external plugins disabled; and 2/ If tons and tons of unwanted plugins become enabled, provide an easy way to disable them en masse.

**Comment by LWinterberg** [comment]
@jamshark70 "Group by category" puts all built-in effects on top and then the various plugins you may have at the bottom, grouped by vendor. It's the default these days.

**Comment by dreikelvin** [comment]
+1 on this feature as I really don't use VST's inside audacity. frankly, the recent updates have just added bloat to the whole application 🤷 but that's just my personal opinion. a great app should always stay simple and "grow" with the needs of its user.

**Comment by jamshark70** [comment]
> "Group by category" puts all built-in effects on top and then the various plugins you may have at the bottom, grouped by vendor. It's the default these days.

Sure... but, this reply suggests to present a less disorganized mess to the user.

The feature request is to prevent making the mess in the first place.

**Comment by Karl-Franz** [comment]
> @jamshark70 "Group by category" puts all built-in effects on top and then the various plugins you may have at the bottom, grouped by vendor. It's the default these days.

I don't understand. What is the reluctance to simply providing the ability to disable VST scanning completely? It should be obvious  by now that many of us find it a nuisance rather than a wanted feature. So, why not make the customers happy?

Not only does scanning at each and every launch slow things down, many of us encounter annoying errors that popup because of the scanning. Add me to the growing list of users who get a "-NI-/aufx/Ni$" incompatible plugin found error every time I run Audacity. Disabling VST scanning would get rid of this problem.

**Comment by LWinterberg** [comment]
What makes you think there's a reluctancy here? This issue is assigned P2 and targeted for 3.x (it may make it into 3.5 actually). I was just pointing out that, if you have a bunch of plugins and can't find Audacity's built-in effects anymore, we have an effects sorting option which alleviates that issue.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @crsib 's latest branch build for this:  audacity-win-3.5.0-alpha-20240213+cf42988-x64

This seems to be working properly in Dmitry's branch.

I note the new checkbox in Effects prefs to turn off plugin scanning.

1. On my initial run of this branch my plugins got scanned
2. I then set the new no-scanning checkbox to "on"
3. deleted the plugins cfg files from the audacity settings folder
4. relaunched 
5. Observe: my plugins were not scanned and not available
6. reset the no-scanning to be "off"
7. relaunched
8. Observe: my plugins were scanned and made available
