### ISSUE TITLE
"Linear dB" on track's vertical ruler fails to handle vertical zoom

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#4980]
### Bug description

When zoomed in vertically with the "Linear dB" scale, the ruler may be sparse or empty.

### Steps to reproduce

1. Select "Linear dB" as a track's vertical scale.
2. Zoom in vertically.

### Expected behavior

Additional numbers to be added to the scale according to the amount of available space.

### Actual behavior

![First Track000](https://github.com/audacity/audacity/assets/11681097/8d66616a-21f8-4a42-9a05-b03ae6c067de)

### Audacity Version

current master / alpha / nightly build

### Operating system

Any

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
