### ISSUE TITLE
Uneven layout of number on "Linear dB" vertical ruler

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#4981]
### Bug description

Depending on a track's height, the numeric values may be spaced unevenly.

### Steps to reproduce

Try resizing the track vertically and observe how numbers are distributed.

### Expected behavior

![First Track002](https://github.com/audacity/audacity/assets/11681097/1d5dee38-1236-4d0a-a0cd-0f50e92dec29)

### Actual behavior

![First Track001](https://github.com/audacity/audacity/assets/11681097/1c0e1f1e-dcb1-4859-83c0-45a58f8db6f7)

Observe that there is as much space between -6 and -inf dB as there is between -6 and 0 dB, but the latter gets an additional number (-3), but the former does not (-12).

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by dozzzzer** [comment]
Might be the same one as #3010

**Comment by SteveDaulton** [comment]
I suspect that it is a different issue.
In #3010, there is less space for "-0.9" than there is for the other numbers due to the raised position of the "-1.0".
In #4981 there is plenty of space available for the "-12 dB" between "-inf dB" and "-6 dB".

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
