### ISSUE TITLE
Fully collapsed smart clip cannot be expanded

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#4984]
### Bug description

If an audio clip  is resized to zero length, it cannot be expanded.

### Steps to reproduce

1. Generate a Chirp
2. Drag  left and/or right side of the clip to resize the clip to zero length.
3. Release the mouse button
4. Drag the right or left edges of the clip  to expand the length.

### Expected behavior

Click and drag in the top half of the clip will expand the clip.

### Actual behavior

It is impossible to resize the clip.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Is this a regression?

**Comment by petersampsonaudacity** [comment]
Duplicate of

 **Shrinking clip size to 0 width (actually 1 sample) makes clip unable to re-expand #2053**

**Comment by LWinterberg** [comment]
https://github.com/audacity/audacity/actions/runs/5728256978 this already shows an improvement, telling you which side of the clip you actually are grabbing for resizing. 

![image](https://github.com/audacity/audacity/assets/87814144/b5391a04-6d32-48a8-91c6-b411b1b79632)

**Comment by saintmatthieu** [comment]
Looks related to https://github.com/audacity/audacity/issues/5145. Both should get fixed with https://github.com/audacity/audacity/pull/5043. There, maximally shrunk clips by either stretching or trimming become indeed very small, but zooming enough gets the trim/stretch handle to work again and allow you expand again.

I think @petersampsonaudacity suggested some display improvement for such small clips, so that they don't appear as barely visible vertical lines, right? This would need an enhancement ticket with another description, and I don't think there is one, is there?

**Comment by petersampsonaudacity** [comment]
> I think @petersampsonaudacity suggested some display improvement for such small clips, so that they don't appear as barely visible vertical lines, right? This would need an enhancement ticket with another description, and I don't think there is one, is there?

@saintmatthieu  -  it's not just visibilty for extremely small clips _(and btw you can also get these by zooming out a long way)_ - but there are alos some odd behaviors with the grabbers as you shring the clip to very snall and then invisibly small.  

I will write up  a ticket for this later.

**Comment by dozzzzer** [comment]
Fixed by https://github.com/audacity/audacity/pull/5043

**Comment by saintmatthieu** [comment]
> Fixed by https://github.com/audacity/audacity/pull/5043

Following up on this.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's latest 4 o 6 branch build:  audacity-win-3.4.0-alpha-20231005+7737b4b-x64

This is possible to do but first you need to find the cliplet - see #5145

And then it requires a LOT of zooming in - and because of the small size you have to 
1. Zoom out a bit
2. expand the clip
3. repeat - a **_LOT_** (and this is tedious, extremely so)

**Comment by SteveDaulton** [comment]
> This is possible to do but first you need to find the cliplet - see #5145
> And then it requires a LOT of zooming in

My mistake, I didn't zoom in enough (and now we have slower mouse wheel zoom it takes forever).
I'll close this again as it is clearly working as intended, albeit not obvious.
