### ISSUE TITLE
Multi-Tool drag bar conflicts with clip resizing

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#4985]
### Bug description

When the Multi-Tool is selected, the double arrow mouse pointer for resizing clips is the same as the the double arrow mouse pointer for moving the clip, and at the upper half of a track edge, both may exist in the same hot-zone.

### Steps to reproduce

Test the drag behaviour of the Multi-Tool.

### Expected behavior

The Multi-Tool drag bar is redundant and should have been removed when clip drag bars were added.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
