### ISSUE TITLE
3.4 project files with stereo tracks should not split to mono when opened in earlier versions

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4995]
### Bug description
A stereo track created in 3.4.0 alpha and saved, when opened in 3.3.3 (or earlier) it opens as two separete mono tracks .

This destroys backwards compatibility of projects.

It is a regression as a stereo track created in 3.3.3 opens fine as a stereo track in 3.3.2 and earlier.

### Steps to reproduce
1. launch 3.4.0 alpha
2. create a 30 second stereo chirp
3. Save the project
4. Exit 3.4.0
5. launch 3.3.3 (or earlier)
6. Open the project saved at step 3
7. Observe: 2 separate mono tracks

### Expected behavior
Attempting to open 3.4.0 stereo project in 3.3.3 (and earlier) should show a stereo track

### Actual behavior
The 3.4.0 stereo project opens in 3.3.3 (and earlier) as separate mono tracks

### Audacity Version
3.4.0 latest alpha master

### Operating system
All

### Additional context
Discovered while testing #4941 for @Paul-Licameli

**Comment by LWinterberg** [comment]
It might be worth _actually_ destroying backwards compatibility here and raising the project file format version here. We did that for 3.1 (smart clips), and it's probably better to prompt a user to upgrade than to put their project in a weird state without them noticing, and having them save/overwrite the broken version.

**Comment by petersampsonaudacity** [comment]
@LWinterberg  by "destroying" do you mean actually blocking 3.4 projects from ever being opened in 3.3 and earlier?

**Comment by LWinterberg** [comment]
aye

**Comment by dozzzzer** [comment]
Slightly changed the content of the ticket according to @LWinterberg 's suggestion to prompt for upgrade

**Comment by LWinterberg** [comment]
NB @Paul-Licameli - compatibility already is broken. Only minorly, but broken nonetheless.

**Comment by Paul-Licameli** [comment]
The problem bisects so far to 5a625f888b9e5b960f634b667bb73b829678e008..ab110a4c6125525332c269513c81c9423dedef5c

Rather than do as the issue title, I would fix the unexplained behavior Peter discovered.

Note that it is impossible now to change the behavior of version 3.3.3.  But it is possible to write version numbers into project files, so that 3.3.3 sees them as future files and refuses to open them.  This was recently done at commit f2a39969ced5394db590460460d30a236953f1c2 but only for 3.4 projects that have any stretch applied to any clips.

**Comment by Paul-Licameli** [comment]
The problem bisects to cfbd0b0603512fbacc079f5a45d6ebab9f3e50e3

**Comment by chinakov** [comment]
Tested, stereo tracks saved in 3.4.x now open as stereo tracks in 3.3.3. 

Thank you!
