### ISSUE TITLE
Effect menu reorganization

### ISSUE THREAD

**Issue by silverbacknet** [audacity/audacity#501]
- [x] #2659
- [x] ~~#2660~~
- [x] #2661

<details>
<summary>original enhancement request</summary>

This is a is a tracking bug for ideas and PRs for updating the Effect menu.

Rationale: The effect menu is a continuous source of pain if you have many effects installed. The crazy thing is that I actually do enable and disable plugins for what I need, half of mine are disabled currently, but it still required hovering to scroll down the list. I also find the automatic promotion of built-in effects to be a distraction, when I would much rather have my "favorite" filters on top, particularly ones that effectively replace builtins. On smaller screens, even with no external plugins and *only* the builtins, the menu still has to be scrolled.

![effect-menu](https://user-images.githubusercontent.com/1977016/80279797-a0e7c300-86b4-11ea-8bb2-ee8c1f35e0a3.png)

</details>

**Comment by lllucius** [comment]
I know your pain, but from a testing point of view. I have over 400 plugins installed for testing purposes and it's a REAL pain to find specific ones.

But, look at the Effects category in Preferences.  The dropdown allows you to group the effects by type or publisher.  It can help somewhat.  I generally group by Type, but you might want Publisher.

One day I'd like to add a "favorites" toolbar where you can store your favorites with the ability to load/save different combinations.

We also have a customizable menu system in the works that should play a big role in taming the effects.

**Comment by petersampsonaudacity** [comment]
If you don't want or need the built-in effects you can always disable them with the Plug-in Manager (use the Add/Remove Plug-ins command at the top of the Effect menu)

**Comment by roa-nyx** [comment]
Might I suggest a search toolbar like something you find in Blender or the mac os finder?

I imagine the use-case would be: I want effect X.

I press the search toolbar shortcut (I know spacebar is already used, maybe ctrl+spacebar or something else?)

I get a plain textbox floating over the UI (click anywhere to dismiss, or escape to dismiss).

I start typing and get autocomplete of effects (could be expanded to include tools, generate, and other functionality).

I hit enter and the effect I selected pops up immediately. I know this doesn't entirely solve the effects clutter and doesn't really help with discoverability, but I think it will at least allow us to circumvent the bulky UI (almost entirely unusable in Windows 10 btw).

**Comment by werame** [comment]
The scrolling is really annoying especially since Audacity already comes with a nearly full Effects menu (on a screen with 1200px vertical), so adding almost anything results in scrolling, which is pretty slow. And one has to decide "I'm never going to use that plug-in, so I can turn it off so it doesn't clutter the menu". But it's not easy to do this at first because you don't know many of them do. My suggestions would be:

* Make a "multi-flap" menu that opens additional pages instead of scrolling the menu. Technically that's a sub-menu at the end of the screen for the first menu that gets populated with what doesn't fit on one screen. This is pretty old-school though. It's not like MS owns the bible on this, but nowadays they [suggest](https://docs.microsoft.com/en-us/windows/win32/uxguide/cmd-menus) "Don't put more than 25 items within a single level of a menu (not counting submenus)."
* Have some kind of plugin sets/profiles that can be easily turned on and off.
* Search box as suggested further above. Some of "competition" (I'm thinking Audition) does stuff coming close to that with "Favorite Actions", which in Audition applies to all sorts of things, not just effects. Audition doesn't have a search box for those (which is a bit silly, because they have one for markers, their equivalent for Audacity labels, for instance), but Audition allows both a default and a custom order for Actions, togglable by a little button, so at least one can have their commonly used stuff at the top in the Actions list in the custom order. A better design in this regard is VSCode's Command Palette that is both searchable and remembers what you've used most recently. (The default VSCode shortcut for that Ctrl+Shift+P is a bit too long given how often that's actually used, at least if use some REPL kind of stuff.)

The above are not mutually exclusive. I realize that some of these are hard to do in a framework like wxWidgets, which is still a pretty traditional UI.
