### ISSUE TITLE
Visual programming interface for Audacity

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5015]
### Your idea

A ["Blockly"](https://developers.google.com/blockly) style visual programming interface for creating Nyquist scripts, plugins and macros.

### Problem to be solved

Audacity has exceptional scripting ability with macros and Nyquist, but only a tiny percentage of users make use of these abilities because of  the steep learning curve.

Visual programming is successfully used to introduce young children to programming, and has a solid track record for making programming accessible to non-programmers. A Blockly type interface for scripting in Audacity would open up much of the power of Audacity's amazing scripting language to a much greater number of Audacity users.

### Prior art

Blockly type visual programming is commonly used to introduce programming to school  children.

**Comment by Paul-Licameli** [comment]
In my opinion, Audacity’s scripting ability is not exceptional.  The C++ foundations implementing macros and Nyquist are not robust, understandable, or easily maintainable.

The XLisp interpreter is in many ways primitive (too much consing just to interpret code, too small a subset of Common Lisp) and the interfacing of Audacity with it was badly done and never fixed.

XLisp lacks any kind of namespace scoping (none of Common Lisp packages) and we simply reinterpret the .ny file each time and effect is invoked, then throw away all changes in the Lisp runtime!  With the ad hoc exception of the ‘scratch property.

Common Lisp was a dead end of programming language evolution anyway, pace fanatics, and kids these days won’t want to learn it.

I would love to have the time and liberty to address all these problems, and even wrote some languishing pull requests to fix some of it, but the truth is, I see the project’s priorities lying elsewhere for several releases yet to come.

**Comment by SteveDaulton** [comment]
> In my opinion, Audacity’s scripting ability is not exceptional.

You know of a graphical audio editor with better, or even comparable scripting ability? I must try it. What is it called?

**Comment by LWinterberg** [comment]
My preferred solution for scripting in Audacity is one that doesn't involve scripting. That is to say, to the end user, Nyquist plugins and VST plugins feel like features you just install, the way they work rarely needs to be inspected and the end user generally doesn't need to engage with anything related to scripting or programming. 

Audio is tricky enough to understand as it is to end users, with surprising amounts of physics sneaking up on the unsuspecting musician or podcaster. Expecting a significant portion to also want to figure out programming - even in a simplified form - is unlikely. 

From what I can tell, the vast majority of Nyquist plugins written are from David Sky and you, Steve. This isn't because Nyquist is too hard or because nobody could understand your tutorials, it's because creating plugins and scripts is a different skillset and interest to making a podcast. 

If we take a look at [blender market's stats](https://blendermarket.com/market-stats), we can see that they have some 4200 creators for some 450000 users, and less than 2000 scripts and addons. At the same time, addons are the most popular on there, with 18/20 of their most sold items being addons. All of these addons are essentially purchesable features. Under the hood they're all python scripts but they have the ability to embed themselves into the UI as to feel native and in some cases, near-magical - they can insert new tabs, new gizmos, they can put options into any menu, they can create IPC sockets to communicate with other programs.

So with all that in mind, the problem I'd like to solve one day is to allow developers to provide and distribute addons (and VST/LV2/... plugins) to users, and for users to easily find and install these addons and plugins.

Getting users into developing themselves feels very out of scope for what Audacity is trying to do, and frankly to what users are trying to do.

**Comment by teetow** [comment]
> You know of a graphical audio editor with better, or even comparable scripting ability? I must try it. What is it called?

The obvious answer is Reaper. Their scripting API very likely contributed to the rapid adoption in workflow-heavy industries like gamedev, music production, film and TV.

However, Leo correctly points out that script *developers* is almost as niche of a user group as they come, and it's not because scripting needs to be made easier. Any professional user who needs a problem solved is either capable of solving it with actual code, or can reach out to someone who does. This narrows the target users for a system like this down to people who possess that understanding, but don't feel comfortable opening up a code editor. 

I think it's safe to say that's a slim cut of the Venn diagram.

**Comment by Paul-Licameli** [comment]
The foundations of such scripting as Audacity now possesses are not very sound and need a lot of fixing.

That’s my opinion.  I wish it were not so, but I have struggled long to understand how this stuff really works and see the deficiencies.

I wish I could contribute to fixing it, but there are so many other more important corners of the foundation that need their fixing too and they occupy all my efforts.

**Comment by SteveDaulton** [comment]
>  It is unlikely a significant portion of users also want to figure out programming - even in a simplified form.

Maybe I'm wrong, but I think that macros for batch processing are rather important to a lot of Audacity users.


> The obvious answer is Reaper. 

I'm not sure that I understand your point. I was asking about graphical audio editors rather than DAWs, video editors, command line apps or other kinds of software.

> The foundations of such scripting as Audacity now possesses are not very sound and need a lot of fixing.

Heck, Audacity generally needs a lot of fixing. The last time I looked there were around 40 issues tagged as P2 or higher. I don't recall there ever being so many serious issues in Audacity at one time. Nevertheless I think it's always worth considering ways that Audacity may be improved in the future.

**Comment by Paul-Licameli** [comment]
> > It is unlikely a significant portion of users also want to figure out programming - even in a simplified form.
> 
> Maybe I'm wrong, but I think that macros for batch processing are rather important to a lot of Audacity users.

The old feature called "Chains" was and surely remains important to users.  It's the specification of a post-processing effect stack that you can apply each time you make a podcast, say.

These users probably want to set-and-forget and aren't interested in programming so much.

Macros were a generalization of chains to allow other things in the sequence like selection changes.

I don't know how important or successful these extensions are.  I suspect, not much, but maybe I'm out of touch with Forum discussions.

Even with the extensions, macros aren't really a programming language with variables and flow of control structures, but still no more than a list of commands.

**Comment by SteveDaulton** [comment]
All computer programs are basically just a list of commands, though most languages implement a lot more capabilities than just running a linear sequence, whereas Audacity's macros are _only_ a linear sequence of commands.

Over the years I have helped _many_ users that needed to do _a little bit more_ than can be done with a simple list of commands. The solution invariably requires a massive step up for non-programmers into the world of Python or Nyquist programming. This feature request is about enabling those users.

**Comment by Tantacrul** [comment]
> The last time I looked there were around 40 issues tagged as P2 or higher. I don't recall there ever being so many serious issues in Audacity at one time. 

The price of improving a product is bugs. I applaud the efforts that went into avoiding bugs in the past but it's clear it came at the cost of Audacity changing or improving as a tool. Also, for me some of the significant limitations were themselves major bugs. We refer to them as 'usability bugs' or 'feature bugs'

**Comment by LWinterberg** [comment]
A blockly interface doesn't make the *little bit more* case accessible in a manner that lets a user achieve it with just a *little bit more* effort. It only simplifies the syntax, it doesn't simplify logic and it doesn't simplify knowing how to approach a problem. 

The idea that simplifying the syntax makes programming accessible to the masses has been around for a while, but it just doesn't. After the second loop and the third branch in a function, programming becomes a primarily a logic puzzle, and I know plenty musicians who have opted out of maths and physics as quickly as they could to become musicians precisely to *avoid* logic puzzles. On blender, the scripts to users ratio is below 0.001:1 - this already is python, whose predecessor [boasts about being a very good language to teach](https://homepages.cwi.nl/~steven/abc/teaching.html), and this is blender users, who already are much more likely to be adjacent to the tinkerer, game developer, maker and builder space and thus much more exposed to logic puzzles than Audacity users are. Even with a syntax simpler than python, even with blockly, I expect this to be the ballpark of users reached with this feature. 0.1%.

What does solve the *little bit more* case much more easily are people like you, Paul and Steve. Some of the most popular threads in the forum are your plugins, and they solve problems for a ton of users. Some plugins may be a bit too specialized to ship by default, but if they're easy enough to find, that's fine. And because you're experts, the features that you could build as plugins or addons far exceed what a beginner could do in blockly, both in terms of time required, quality and scope. 

Modernizing Audacity's scripting solutions is in the cards eventually. Making addons, plugins, presets and similar functionality more shareable and discoverable is as well. A blockly-like interface is not.

**Comment by Paul-Licameli** [comment]
> Thanks for the explanation Leo.
> 
> I did actually make a "proof of concept" some years ago, and yes it was quite a lot of work. Under the covers it used Python to communicate with Audacity via mod-script-pipe (using a variation of the pipeclient module), where the Python commands were generated by a blockly type interface running in a web browser. Then, as now, other priorities took over, so it never developed beyond a proof of concept. Nevertheless, dragging blocks into a chain was a lot more fun than using Audacity's current "Manage Macros". I do hope that at some point the team is able to make creating and managing macros a lot more user friendly.

It’s interesting that mid-script-pipe was sufficient to allow that development non-intrusively in Audacity’s own source.  Maybe the project could be elaborated along those lines.
