### ISSUE TITLE
File Naming Textbox Blinking and Invisible Text on Save in Audacity (Ubuntu 22.04.2 LTS)

### ISSUE THREAD

**Issue by abdullahfarwees** [audacity/audacity#5061]
### Bug description

 When attempting to save a file, I've noticed that the textbox in which the filename is entered starts blinking, rendering the text invisible and making it difficult for users to interact with it effectively. Attached screen record. 

https://github.com/audacity/audacity/assets/11908787/d77dabab-ead7-4b21-b74b-a783b3a782ff

OS info:
Distributor ID: Ubuntu
Description: Ubuntu 22.04.2 LTS
Release: 22.04
Codename: jammy

### Steps to reproduce

1. Install fresh Audacity from Ubuntu Software
2. open the "Audacity" software
3. Record sound for 30 seconds
4. save the file (File->Export->Export as MP3)
5. Issue appears while editing the name of the file in the textbox.

### Expected behavior

The filename textbox should remain stable and display the entered text clearly during the save process, allowing users to view and edit the filename without any issues.

### Actual behavior

The filename textbox blinks, causing the entered text to be hidden from view, making it challenging for users to interact with the textbox properly.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

It appears in dark mode as well as light mode.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
