### ISSUE TITLE
Disable Vertical Zoom When Using Horizontal Zoom

### ISSUE THREAD

**Issue by BenMcLean** [audacity/audacity#5096]
### Your idea

Disable the vertical decibel zoom while you're using the horizontal time zoom.

### Problem to be solved

It is often a big problem in Audacity that I will mean to scroll the mouse wheel to zoom in on a specific time period but my aim will be off and I will instead accidentally hit the vertical decibel-based zoom instead, which I and everyone else almost never wants, and absolutely never at the same time we're trying to do the horizontal time-based zoom.

### Additional context

I think how zooming works in general could use a look. I am often accidentally zooming it way off from where I'm trying to focus, especially when the part I'm aiming for is towards the beginning or end of the timeline. I'm not sure how this could be solved with code though.

**Comment by LWinterberg** [comment]
Such a feature is not planned, however, there are two other things which should alleviate this particular issue: 
* An overall improved zoom behavior so that you won't need to be as close to the start of the track as before (#4212)
* Putting a per-track meter in the place of the vertical ruler (and moving the vertical ruler to the other side), again preventing accidental vertical zooms at the start of the track.

**Comment by BenMcLean** [comment]
> * Putting a per-track meter in the place of the vertical ruler (and moving the vertical ruler to the other side), again preventing accidental vertical zooms at the start of the track.

One concern about this: We don't want to cause this same issue to happen at the end of the timeline either. Hopefully the new changes won't just move the issue! :)

**Comment by LWinterberg** [comment]
If you're at the end of the timeline, you can just zoom out more before you even reach the edge.
