### ISSUE TITLE
Re-enable the Timeline option to Disable Quick Play

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5103]
### Discussed in https://github.com/audacity/audacity/discussions/4565

<div type='discussions-op-text'>

<sup>Originally posted by **audacitymike** April 17, 2023</sup>
Can the option to disable quick play be re-introduced soon? </div>

**Comment by petersampsonaudacity** [comment]
Ah now I look at the 3.1 release notes I recall the history:
https://wiki.audacityteam.org/wiki/Release_Notes_3.1

There it says:
>Timeline Quick Play for regions and locked regions have been replaced by playback looping.

With that version Muse added a new version of looped playback which at the time they thought made TQP entirely redundant.

Many users (including me, _I use TQP a LOT_ _as Audacity's scrubbing is not usable IMVHO_) did not agree and campaigned to get TQP added back as an adjunct to new looping.  But when it was added back the former option to turn it off, if required, was apparently not added back.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
