### ISSUE TITLE
Make selection in clips more visually distinct

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5136]
### Your idea

Let's consider making the selection of audio clips more visually distinct by letting the selection layer sit above, not underneath the waveform.

### Problem to be solved

Currently, especially at certain zoom levels, when selecting a region of an audio clip with dense loud peaks (e.g. a heavily compressed song), it's really hard to see what you're selecting because the selection layer is covered by the waveform, leaving almost no room for the distinct selection color to fill in:

<img width=450 src="https://github.com/audacity/audacity/assets/70063970/f9bcd807-294f-424d-bb68-66be6d781f83">

https://github.com/audacity/audacity/assets/70063970/7561efc1-5692-4e7f-90c6-27242dd75883

**Comment by petersampsonaudacity** [comment]
The problem can, of course, be worse when using the dB waveform view.

**Comment by LWinterberg** [comment]
We're taking this into consideration for the Qt version. Current iteration has us change the RMS color together with the background color, and also the clip header:

![Image](https://github.com/audacity/audacity/assets/87814144/c18d5660-eeec-4592-995f-7f19548a30de)

I expect the details to change, but we'll definitely make sure you can see the selection with more than just the track background. It won't be fixed in 3.x though.
