### ISSUE TITLE
Ruler Breaks if First and Second Time Signature Number is 1

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#5141]
### Bug description

If the User has the 'Tempo and Time Signature' panel available, and uses the Beats and Measures ruler, and adjusts either of the Time Signature numbers to 1, the User will be blocked from increasing these 2 numbers further. 

This can only be fixed via restart. 

### Steps to reproduce

1. Launch Audacity
2. Go to View -> Toolbars -> Time Signature Toolbar (Beta)
3. Observe Time Signature Toolbar appearing in the UI
4. Import, record or generate an audio clip
5. Adjust any of the 2 Time Signature values to 1 
6. Try to increase the Time Signature value from 1 to any higher number
7. Observe Result

### Expected behavior

User should be able to freely adjust the time signature, and the ruler should adjust accordingly. 

### Actual behavior

The ruler becomes 'stuck' if the values of Time Signature become 1.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by LWinterberg** [comment]
Additionally, there's an assert violation for any x/1 time signature.

![image](https://github.com/audacity/audacity/assets/87814144/82f6acf1-b9c3-4949-a76e-336c4d6c2870)

I'll quickly check if there are good reasons for x/1 time sigs and if not, I'd propose we simply remove 1 as an option for the dropdown.

**Comment by LWinterberg** [comment]
After a brief talk with an expert, it turns out that this is something 16th century music does technically, even though they didn't necessarily notate it as such:

<details><summary>funky notation examples</summary>

![image](https://github.com/audacity/audacity/assets/87814144/6971a349-ea63-4471-b79f-c971796c9ad4)
![image](https://github.com/audacity/audacity/assets/87814144/bf89b7a2-8513-4587-9d8d-9f73ee7ecfe9)

</details>

So I'd say it's safe to just hide that option until such time we tackle 16th century music composition and beatmaking or something.

**Comment by chinakov** [comment]
There's still a bug regarding the first number of the Time Signature - @LWinterberg will take a look at it later, I approved the previous PR, and re-opened this task.

**Comment by DavidBailes** [comment]
Just ran into this bug - it was very confusing. Given it's a spin box, it would be easy to accidentally undershoot and set a value of one even if was aiming to set a higher value.
??:
![image](https://github.com/audacity/audacity/assets/11887021/53a60294-695a-4fae-95b8-e1dd4bd1279d)

**Comment by LWinterberg** [comment]
I meant to figure out how to clamp a spinbox to a lower limit but I haven't gotten around to it.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
