### ISSUE TITLE
Effects fail to work on stretched clips - hangs with longer clips, odd results with shrunk clips

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5146]
### Bug description
Effects fail to work on stretched clips - Audacity hangs with longer clips, and you get odd results with shrunk clips

### Steps to reproduce
**long stretch**
1. generate a 30 second chirp
2. zoom out 2 levels
3. Stretch the clip to be 1min 30 secs long
4. select the clip
5. apply an effect (I used Amplify - and other effects
6. Observe Audacity hangs

**short stretch - no amplification and silence inserted at the beginning**
1. generate a 30 second chirp
2. stretch the clip so that it is 10 seconds long
3. select the clip
4. apply an effect (I used Amplify - and other effects
5. Observe the odd result

### Expected behavior
Effects to work correctly on stretched clips

### Actual behavior
**long stretch after amplify**
![image](https://github.com/audacity/audacity/assets/50205984/80e81e26-32da-47f3-bac1-1bc374521462)

**short stretch after Amplify**
![image](https://github.com/audacity/audacity/assets/50205984/773c3f1f-f82c-4449-a817-8f09d8e2642e)
Most effects do this but both the EQ effects and Noise Reduction just produce complete silence for the 10 seconds
Loudness Normalization crashes Audacity with this use case,

### Audacity Version
Latest 3.4.0 master:  audacity-win-3.4.0-alpha-20230905+fead386-x64-msvc2022

### Operating system
Windows 10 - but assume all OS

### Additional context
Flagging @saintmatthieu @LWinterberg @crs

**Comment by saintmatthieu** [comment]
Yes indeed, master is currently in an unreleasable state.

Since we do not render stretching upon each project tempo change or stretch-handle usage, enabling time stretching for audio clips violates the assumption made in many places that samples on a track are evenly spaced (by the sampling period).

There initially was one massive PR that attempted (feebly) to introduce stretching and fix everything around. But to get things moving, we decided to break it down in smaller pieces and accept to have something not releasable until all pieces were merged.

You will also notice problems when copy/pasting clips with different stretching on top of one another. Or problems when drawing the samples of stretched clips.

Here's an overview of the PRs for these smaller pieces:
* repair pencil and brush tools : https://github.com/audacity/audacity/pull/5042
* repair copy-paste-merge: https://github.com/audacity/audacity/pull/5043
* repair effects and generators (which is what you uncovered here): https://github.com/audacity/audacity/pull/5044

It'd be great if you could assist with testing those once they are ready for QA ?
We can talk about it all more tomorrow.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu   ACK

**Comment by petersampsonaudacity** [comment]
@saintmatthieu 

See also:   Plot Spectrum analyzer causes freeze when applied on a clip with extreme stretch #5119
