### ISSUE TITLE
An exported stretched clip exhibits a vastly different waveform when re-imported

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5148]
### Bug description
If you stretch a clip (either direction), export it as a WAV file and then re-import it, it exhibits a vastly different waveform from the original.

Both tracks appear to sound the same (mute swap testing

### Steps to reproduce
1. generate a 30 second chirp
2. stretch the clip to 1 min 30 secs
3. export it as a WAV file
4. import the WAV file 
5. select one second at say 30 seconds
6. Zoom to fit the selection
7. Observe: the waveforms look very different

### Expected behavior
The waveforms to look the same

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/2362c9f4-3fb0-4dda-b519-fec90efde57d)

### Audacity Version
latest 3.4.0 alpha:  audacity-win-3.4.0-alpha-20230905+fead386-x64-msvc2022

### Operating system
Windows 10 - but assume allOS

### Additional context
Tagging @saintmatthieu @LWinterberg @cr

**Comment by petersampsonaudacity** [comment]
If after Step 6 you send the cursor to T=0 you will see and odd glitch at the beginning of the imported file for about 0.05 seconds
![image](https://github.com/audacity/audacity/assets/50205984/81ee9ed1-4d31-4254-94ee-d3e1af350edf)

**Comment by petersampsonaudacity** [comment]
If I repeat the exercise omitting Step 2 (i.e. no stretching) the the two waveforms at Step 7 appear to be identical

**Comment by LWinterberg** [comment]
The problem is that frequency has a time component: If you have a 100Hz wave and stretch it to be 2x as long while preserving waveform, you no longer have a 100Hz wave - you have a 50Hz wave. This is what Change Speed does. If you want to change the speed without affecting pitch, you have to do *something* to the waveform that mangles it.

The difference between our two Change Tempo algorithms (SoundTouch and SBSMS) and the Staffpad algorithm is that the new thing works realtime, so you only see the effect it had on the waveform after exporting/rendering.
