### ISSUE TITLE
Recording more than 2 channels creates one stereo and other mono tracks

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5255]
### Bug description

When recording multiple tracks (more than 2), there is no reason to assume that the first 2 channels will be a stereo pair and the rest will be mono. It's far more likely that they will all be mono. 

(It's also possible that they will all be stereo pairs, or perhaps a mix of stereo pairs and mono channels, or even quadrophonic / 5.1 surround, or something else.)

Previous versions of Audacity made no assumptions about channel grouping when recording multiple (more than 2) channels, treating them consistently as "all mono".

The current alpha version has reverted to an older model that assumes (without reason) that groups the first two channels into a stereo track. I'm assuming that this is unintended (a bug) rather than poor design.

### Steps to reproduce

Record more than 2 channels at the same time.

### Expected behavior

Each channel recorded into a separate track.

### Actual behavior

The first 2 channels are grouped into a stereo pair, and the rest are recorded as separate mono tracks.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by chinakov** [comment]
So, I've encountered an issue with multitrack recording...
When I try to use my Clarett 4pre audio interface, it seems that recording is totally broken - there's only 2 tracks recording and the tracks that are recording are offset by a large margin.

I've checked this on the latest Master, and the issue is the same. 

Here's a video:

https://github.com/audacity/audacity/assets/139755141/022142d6-bab7-4108-86a4-c8ff528f313f

**Comment by chinakov** [comment]
Ready to merge as the tracks are now all mono. The issue above is logged as a separate issue.
