### ISSUE TITLE
Cmake requirement is too high for Debian "Buster" (actual stable) - 2.4.1

### ISSUE THREAD

**Issue by trebmuh** [audacity/audacity#529]
Trying to compile audacity 2.4.1 on a Debian Buster (actual stable) doesn't work. The error message is:

`CMake 3.15 or higher is required.  You are running version 3.13.4`

Since the next Debian stable isn't going to be there before approximately 1 year, would that be possible to relax the CMake requirement to 3.13.4 since this would open the possibility to build on actual Debian stable, or is 3.15 is really needed?

**Comment by lllucius** [comment]
The easiest way to find out if it would work is to change the cmake_minimum_required() line at the top of audacity/CMakeLists.txt and see how far CMake gets.

I'm (almost) certain it won't work though because of the use of multi-valued generated expressions.  

The CMake folks make it really easy to get the latest version though.  Their prebuilt binaries have always worked for me without having any dependency problems.

**Comment by trebmuh** [comment]
It stops almost at the beginning when tweaking the CMakeLists.txt.

Thanks for your answer, and no worries from my side.
