### ISSUE TITLE
nyquist plugins (*.ny) not installed anymore since 2.4.0

### ISSUE THREAD

**Issue by dvzrv** [audacity/audacity#530]
**Describe the bug**
The `*.ny` plug-ins are not installed by the autotools based build system anymore since 2.4.0. Are they obsolete?
I'm packaging audacity for Arch Linux and received a [bug report](https://bugs.archlinux.org/task/66733) in regards to those plug-in files.

**To Reproduce**
```
autoreconf -vfi
./configure --prefix="/usr" \
    --with-libsndfile="system" \
    --with-ffmpeg="system" \
    --with-expat="system" \
    --with-lame="system" \
    --with-libsoxr="system" \
    --with-portaudio \
    --with-portmidi \
    --with-libflac \
    --with-libid3tag \
    --with-libsamplerate \
    --with-sbsms \
    --with-soundtouch \
    --with-libtwolame \
    --with-libvorbis \
    --with-lv2
  make
  make DESTDIR="${pkgdir}" install
```

**Expected behavior**
The *.ny plug-in files are still installed to `/usr/share/audacity/plug-ins`.

**Additional information (please complete the following information):**
 - OS: Arch Linux
 - Version Audacity >= 2.4.0

**Additional context**

**Comment by SteveDaulton** [comment]
Audacity 2.4.0 has now been replaced with 2.4.1 due to a critical bug in the former.

From version 2.4.0, the build system has changed to cmake.
The autotools based build system is probably still usable, but may need a bit of manual tweaking.
The .ny files in the plug-ins directory are required and should be copied to Audacity's plug-ins folder. Assuming that Arch is the same as Debian based distros in this respect, then yes that should be
`/usr/share/audacity/plug-ins`.

**Comment by dvzrv** [comment]
Thanks for the clarification! I'll copy it over manually for the time being then.
I still have a few issues with the cmake setup, that prevent me from using it (#519, #521, #522).
I guess this can be closed then.

**Comment by dvzrv** [comment]
It seems, that also only a subset of the `*.lsp` files is installed using autotools (see downstream bug report https://bugs.archlinux.org/task/66739).
