### ISSUE TITLE
When Lower Time Signature is 16 or 32 or 64, tick isn't displayed in Time and Selection toolbars with bar:beat:tick selected

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5346]
### Steps to reproduce

1. add a mono track
2. set bpm to 120.0
3. set time signature to 4/16 or 4/32 or 4/64
4. set the Selection toolbar format to **bar:beat:tick**
5. set the Time toolbar format to **bar:beat:tick**
6. observe the values shown in both toolbars

### Expected behavior

001bar01beat01

### Actual behavior

001bar01beat

<img width="450" alt="Screenshot 2023-10-10 at 12 42 32" src="https://github.com/audacity/audacity/assets/70063970/7ff0f6e5-583f-40fc-a44a-9ca23aaed3ca">

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by LWinterberg** [comment]
Lowering priority - These timesigs are pretty rare to begin with. Also, funnily enough, Ableton has the same bug at x/16 signatures, with their ticks being stuck at 0 at this point

**Comment by crsib** [comment]
>  Also, funnily enough, Ableton has the same bug at x/16 signatures

I wouldn't call it a coincidence xD

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
