### ISSUE TITLE
With snapping enabled, stretching by miniscule amounts is possible

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5347]
### Steps to reproduce

1. Enable Snapping to 1/32
2. Set BPM=145 and 3/16 as the time signature
3. Add an empty mono track and select an interval of 1/32
4. Generate > Tone
5. Press **K** to put the cursor exactly at the end of the clip
6. Zoom in enough to see individual samples
7. By holding **Alt** (Option) start slowly stretching the clip by dragging the edge left and right
8. Observe

### Expected behavior

No change in speed until the next snapping point is reached (in that case the stretch factor changes to 2 and the speed value would be 50%); the clip's samples stay in place.

### Actual behavior

The speed of the clip jumps from 99.9% to 100.1% and the samples start crossing the edge of the clip:

https://github.com/audacity/audacity/assets/70063970/05fc6e5f-f1d1-4c58-8ca4-24af233dd166

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
