### ISSUE TITLE
Linux - Initial Focus for Chirp, Noise and Tone is 'Presets & Settings'

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#5360]
### Bug description

If the User opens the dialog window for either Chirp, Noise or Tone generators, the initial focus of the window will be on 'Presets and Settings'	

### Steps to reproduce

1. Open Audacity
2. Go to Generate -> Chirp/Tone/Noise
3. Press Enter
4. Observe Settings being opened

### Expected behavior

The initial focus of the dialog window should be 'Generate' for quick usage of the generators. 

### Actual behavior

The initial focus of the dialog window is on 'Presets & Settings' for Chirp, Noise and Tone.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Only reproduced on Linux.

**Comment by chinakov** [comment]
I would also like to note that this is also reproducible on 3.3.3.

**Comment by luzpaz** [comment]
@chinakov on 3.4.2 Appimage i can only reproduce this for: 
**Generate** :arrow_right: **Chirp**
**Generate** :arrow_right: **Noise**

However, **Generate** :arrow_right: **Tone**  is not affected by this bug. The focus is on the 'Generate' button.

**Comment by luzpaz** [comment]
I tried to look this up in the source. Went unsuccessfully.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
