### ISSUE TITLE
Label Tracks are selected incorrectly via 'Select' in TCP Panel

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#5414]
### Bug description

If a User has a label track, and a label within the label track, and  then uses the 'Select' button on the TCP, the selected region will not be correct, not selecting the space between the start of the label track and the start of the label track itself.

In 3.3.3, the entire track until the end of the actual label is selected. 

### Steps to reproduce

1. Launch Audacity
2. Create a label track
3. Add a label within the label track after 0:00
4. Use 'Select' via TCP
5. Observe result

### Expected behavior

The entire label should be selected, including the space before the first added label.

![image](https://github.com/audacity/audacity/assets/139755141/d8a8b236-1723-4283-96b1-535207aeeb51)

### Actual behavior

The space before the first added label is not selected. 

![image](https://github.com/audacity/audacity/assets/139755141/abe3a36a-48e2-48b2-8fca-204c83ae6db6)

### Audacity Version

latest beta

### Operating system

Windows

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
