### ISSUE TITLE
Bar formats: there can be more digits than needed

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5434]
### Steps to reproduce

1. Open Audacity
2. In the selection toolbar, change the format of selection start to bar:beats
3. In the selection toolbar, press the settings button, and choose start and length of Selection.

### Expected behavior

Selection length: 000 bar 00 beat

### Actual behavior

Selection length: 00000 bar 00 beat

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

This is a regression wrt 3.3.3

**Comment by petersampsonaudacity** [comment]
@DavidBailes 

Testing on W10 with lastest 3.4.0 Beta

This looks fine to me:
![image](https://github.com/audacity/audacity/assets/50205984/26e493a8-e612-4ae3-ba67-4dfe7eddc3e7)

**Comment by DavidBailes** [comment]
@petersampsonaudacity . Note step 3. In the selection toolbar, press the settings button, and choose start and length of selection. I'll edit step 3 to make it clearer.
![image](https://github.com/audacity/audacity/assets/11887021/23bbcc7b-edae-472d-8abc-1ca09c1d9af6)

**Comment by petersampsonaudacity** [comment]
Yepper, I see what you mean @DavidBailes 

Happens with any of the three choices that have a "length" component:
![image](https://github.com/audacity/audacity/assets/50205984/fa372ccc-5d93-49e7-a8c7-dfdcfbcdb6d0)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
