### ISSUE TITLE
When trimming, first snapping interval doesn't snap

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5435]
### Steps to reproduce

1. generate chirp of 6.5 seconds long
2. enable snapping to seconds
3. using the trim handle, slowly start dragging the right edge of the clip leftwards
4. observe

### Expected behavior

The clip doesn't get trimmed until the 6.0s time mark is reached. Then, clip snaps to it.

### Actual behavior

Before reaching the nearest snapping point, i.e. the 6.0-second time mark, the clip can be trimmed freely, as if snapping was turned off.
When trimming further, snapping behaves as expected.

https://github.com/audacity/audacity/assets/70063970/b0ee3fed-f4a0-42cd-b171-fd3250a4f35b

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
