### ISSUE TITLE
Label edit mode issues

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#5587]
### Bug description

Originally reported on the forum: https://forum.audacityteam.org/t/version-3-4-1-two-small-bugs-in-the-label-track-behaviour/89621

### Steps to reproduce

1. Add a label track
2. Add another one
3. In the lower one, create a label and type smth in it
4. While still in the Edit mode, delete the upper label track
5. Press the Left arrow key to move the cursor leftwards
6. Press Enter to submit

### Expected behavior

step 5: One can see the cursor moving to the left every time the Left arrow key is pressed on the keyboard
step 6: Once the Enter key is pressed, the label should escape the Edit mode (turn purple) immediately

### Actual behavior

step 5: One cannot see the cursor moving to the left; the current cursor position can only be seen by typing a character or by pressing Delete/Backspace
step 6: Once the Enter key is pressed, the label doesn't escape the Edit mode and retains the white background

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Addition Information

A regression introduced in 3.2.0

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
