### ISSUE TITLE
Amplify (and Normalize) incorrect on time-stretched clips

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5588]
### Bug description
The Amplify (and Normalize) effects act incorrectly on time-stretched clips

### Steps to reproduce
1. generate a 30 second chirp with default 0.8 amplitude
2. select it
3. Effect Amplify
4. Observe Amplification amount is correctly 1.938
5. apply the effect
6. Observe: it works as expected
7. Undo
8. Time-stretch (shrink) the clip to 15 seconds from the right
9. Effect Amplify
10. **Observe: amplification amount is wrongly 0.346**
11. Apply the effect
12. **Observe: it actually slightly reduces the amplitude**

### Expected behavior
Stretched clips to be amplified correctly

### Actual behavior
**Step 4**
![image](https://github.com/audacity/audacity/assets/50205984/f8baa87d-519d-4614-bd75-203fec3a1aca)

**Step 10**
![image](https://github.com/audacity/audacity/assets/50205984/ab2c71e5-7e6a-4592-bcdf-a6da98d57009)

### Audacity Version
all 3.4 versions including 3.4.2 Beta

### Operating system
Windows10 - but assume all OS

### Additional context
Flagging @saintmatthieu 

See Closed issue:
 **Stretched clip: amplify doesn't amplify enough #5170** 

And see this still open issue:
**Shrinking or stretching a clip reduces its loudness #5160**

**Comment by petersampsonaudacity** [comment]
I do note that if after step 8 I Render the speed of the clip then the amplitude of the clip is reduced before step 9

But I still get incorrect amplification - with the amount still showing as 0.346

**Comment by petersampsonaudacity** [comment]
I note too that applying EQ effects to the shrunk clip after Step 8 also result in the amplitude of the clip being reduced.

_(I don't have any time to test any other EGATs right now, sorry)_

**Comment by petersampsonaudacity** [comment]
Testing on the other shipped efffects AFAICT they all seem to work on a time-stretched clip - but all of them look like thay reduce the amplitude of a similar unstretched clip.

I suspect this is down to the pre-effect rendering and is down to #5160

BTW the test bed I have been using to aid ready comparison is this:
![image](https://github.com/audacity/audacity/assets/50205984/8689051c-a160-408b-8b7b-91eebd6b9002)

**Comment by saintmatthieu** [comment]
Thanks for this report, @petersampsonaudacity.
I admit that the behaviour and figures seen from a UX point of view are quite cryptic, and we may do something better here, but for now it behaves as #5170 intended it to:
I've retraced steps 1. to 12., which results in
![image](https://github.com/audacity/audacity/assets/22740106/340b1861-706b-424b-9f1b-362b59ca59f5)
The dialog said "New peak amplitude" would be 0dB, so at first sight this result seems wrong. But there's a catch: zoom in closely on the beginning ...
![image](https://github.com/audacity/audacity/assets/22740106/9f1fcf4b-e415-4fcb-9d8e-b62883a357ff)
#5160 would only marginally improve the experience, I think, because the effect of stretching on the waveform peaks is out of our hands (at best we could guarantee RMS preservation by solving #5160).
I can't think of a good UX improvement. Disabling the amplify effect for stretched clips ? The user would be less baffled, but consistency might then command that we do the same for other effects ?

**Comment by LWinterberg** [comment]
NB: The peaks of a stretched clip are different to the peaks of a normal clip. In the case of a square wave, *massively* so: 
![image](https://github.com/audacity/audacity/assets/87814144/f8379f73-3a9d-4618-943c-48e25e558753)

The beginning at the end seem to have their peaks much higher than the rest of the clip. I wonder if the sort of "virtually duplicate a few seconds of audio before the beginning and after the end" would help so that the stretcher doesn't run out of content and keeps the edges down?

**Comment by petersampsonaudacity** [comment]
@saintmatthieu @LWinterberg 

>I admit that the behaviour and figures seen from a UX point of view are quite cryptic, and we may do something better here, but for now it behaves as https://github.com/audacity/audacity/issues/5170 intended it to

But surely a stretched an the rendered clip should behave normally with Amplify ?

Try these steps:
1. Generate a 30 second tone default 0.8 amplitude
2. Shrink it to 200% speed, 15 seconds
3. Effect > Amplify
4. Observe the amplification factor is -2.517
5. Abort the Amplify
6. Render the clip speed 
7. Observe appears to be no longer a shrunk/clip - no speed change in the Clip-handle
8. Observe also the amplitude has reduced a little - OK we live with that
9. Effect > Amplify
10. Observe the amplification factor is still -2.517 and the desired New Peak Amplitude is 0.0 dB
11. Apply the amplify 
12. Observe:
13. Observe:

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

Your stretched aquare wave looks extremely wacky.

Not so for a stretched ((shrunk to half size) sinusoidal wave:
![image](https://github.com/audacity/audacity/assets/50205984/d3722437-c47f-4cd3-851f-227f1744b4a8)

**Comment by petersampsonaudacity** [comment]
I also note if I create a 0.8 amplitude Square waveform tone , sgrink it to halgf its size.

When I render it, unlike the sine tone it increases amplitude rather than reducing it - and to the extent of provoking clipping:
![image](https://github.com/audacity/audacity/assets/50205984/9a144dcd-14dc-430d-a378-4541f782e434)

**Comment by saintmatthieu** [comment]
@petersampsonaudacity about https://github.com/audacity/audacity/issues/5588#issuecomment-1807872035, I'd need an exact tone setting to be able to reproduce. Depending on waveform (sawtooth, square, etc.), and possibly frequency, the stretch-rendering might yield very different peak amplitudes.

I don't expect I'd find a bug, though. I tried with a sawtooth of frequency 100Hz and amplitude 0.8. After stretch-rendering, yes, the peak amplitude has augmented drastically, hence the negative dB amplification default when invoking `Amplify`.

In general, you'll get surprising results when stretch-rendering complex synthetic waveforms of geometrical shapes such as sawtooth, square, etc. With such artificial waveforms, the phase relationship between the waveform's components is of the essence. Time-stretching modifies these relationships, likely yielding very different-looking waveforms, with very different peak values. It's just how the algorithm works. It's not smart enough to, when e.g. expanding a square wave by a factor of two, to draw e.g. 200 square cycles instead of 100. It will still indeed draw 200 cycles, but the phase relationships won't be preserved.

So far, this has explained everything I've seen in your report.

**Comment by saintmatthieu** [comment]
@LWinterberg it would make things look better only under the condition that there is a round number of periods within the clip. Else, that would introduce a discontinuity that we'd then stretch-render, which would probably bring new problems.
Note, though, that if you select a part of a stretched clip for rendering, it's data immediately left and right of the selection will be used for the rendering of the selection, the very same way you are suggesting. Only we don't extrapolate when there is not data left and right.

**Comment by petersampsonaudacity** [comment]
OK so now I thought I'll try a real life example

This is my touch-stone stereo track track 1 of Sgt Pepper
![image](https://github.com/audacity/audacity/assets/50205984/eaa0aead-9a8f-4896-bd8b-0235b8c06cc9)

Here it is clip-stretched to 125%
![image](https://github.com/audacity/audacity/assets/50205984/658b87d8-406f-4467-894f-6ed287b0aa9b)

And here it is after Amplify
![image](https://github.com/audacity/audacity/assets/50205984/52b4cfbf-908c-428c-8756-5267519c122a)

Observe that it looks visually yo have destroyed George Martin's "careful" stero image - and playing it also indicates that this is indeed the case

Actually its the auto-rendering that does the damage to the stero - this is Clip Speed Render without Amplify
![image](https://github.com/audacity/audacity/assets/50205984/e0254454-ef0f-45ae-a396-22868dd16716)

**Comment by petersampsonaudacity** [comment]
And here's an extreme example of stereo image destruction
1. generate a chirp
2. generate a DTMF tone on a new track
3. make the mono pair a stereo track
4. Clip-stretch to 125% speed
5. Effect > Amplify
6. Onserve

![image](https://github.com/audacity/audacity/assets/50205984/6e6ac5b7-3dbc-44d8-8e52-859f75cf5b4c)

**Comment by petersampsonaudacity** [comment]
> @saintmatthieu Does this imply, perhaps, that each of the two stereo channels should be Clip Speed rendered separately??

I certainly get a better result with Sgt Pepper if I split the stereo track to mono after the stretch to 125% and then Clip Speed Render each mono track separately and the rejoin them to be a stereo track:
![image](https://github.com/audacity/audacity/assets/50205984/65af4ea8-4920-451e-bc29-eabe415ac3bb)
Proper stereo with this

**Comment by saintmatthieu** [comment]
I wasn't aware that stretch-rendering of clips with "hard" left-right panning had such a dramatic "averaging" effect. This is probably because of the mid/side encoding and decoding before and after the processing. Stretch-rendering as dual mono in cases of more normal panning leads to phase interferences yielding worse results, though, see https://github.com/audacity/audacity/issues/5390.

In any case, this should be logged separately, and as enhancement request rather than bug. I don't know yet how and if this could be improved on, though, without deteriorating other, more common situations.

**Comment by petersampsonaudacity** [comment]
> In any case, this should be logged separately, and as enhancement request rather than bug. I don't know yet how and if this could be improved on, though, without deteriorating other, more common situations.

Ok I will log it later - but I will be logging it as a bug _**NOT**_ as an enhancement request as it involves the loss of users' data.

**Comment by LWinterberg** [comment]
I think with all we've discussed in here, this can be closed: 

* There is no miscalculation here
* With our usual testing methods (generating chirps and tones), we're getting the worst results possible
* In real projects we can expect a) there to be data beyond the cutoff point which alleviates this effect, or b) the highest peak of the project to be nowhere near the first and last couple of ms.

The one time where we *can* expect the highest peak to be in the beginning would be drum loops. That said, I expect drum loops to be normalized already so I wouldn't chuck an amplification on it anyway. Together with proper gain staging in the mix, it likely is going to be a non-issue.
