### ISSUE TITLE
Hovering over a label also highlights labels other tracks.

### ISSUE THREAD

**Issue by FTGCocolandia** [audacity/audacity#5589]
### Bug description

When there is multiple label tracks if you hover or select a label it will highlight other labels from other tracks.

### Steps to reproduce

1. Create multiple label tracks.
2. Create a label in each track. 
3. Hover over the label multiple times until it happens.

### Expected behavior

It should only highlight / select the desired label.

### Actual behavior

https://github.com/audacity/audacity/assets/91145640/429646b7-ee61-49c2-86a1-361c764ab9a7

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
Testing on W10 shows that this is a regression on 3.0.5, introduced in 3.1.0

Note that 3.1.0 was when the Label behaviors were changed when the label bars were made visually fatter and they became drag-bars for label repositioning.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
