### ISSUE TITLE
Consistent time / speed stretch terminology

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5645]
### Your idea

90% real-time stretch == -10% Change Tempo
Please use the same terminology consistently.

### Problem to be solved

- From the Change Speed effect (now called "Change Speed and Pitch"), I can see that stretching from 10 seconds to 8 second is a **speed change of 25.000%** (speed x 1.25).
- In Change  Tempo it's the same: 25% change reduces 10 seconds to 8 seconds.
- In Sliding Stretch it's the same: 25% change reduces 10 seconds to 8 seconds.

In the new real-time stretching, Change Speed 25% _increases 10 seconds to 40 seconds_

**Comment by LWinterberg** [comment]
Clips are absolute value (*set to* 25%), the effects are relative value (*change by* 25%). 

Clips being absolute value is beneficial because resetting to 100% returns you to the original state. Effects being relative value is beneficial because the source data is not remembered. Speeding up by 50% (to 150%) and then summoning the effect again to set it to 100% would keep the clip at 150% - in other words, changing the effects to absolute values would *cause* an inconsistency. 

There is of course an argument to be made to remove destructive operation of change tempo. In that scenario, change tempo could become absolute. This would make the effect consistent with the in-timeline operation and remove this particular bit of confusion. 

I don't think it's necessarily worth doing that right now, I'd want there to be some more options for realtime stretching modes first (Rubberband, sonic and trivial speed-and-pitch stretching come to mind), so that change tempo and change speed and pitch could be moved over to that system together.
