### ISSUE TITLE
The Time toolbar display format isn't preserved upon project open

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5655]
### Steps to reproduce

1. In the Time toolbar, select "seconds + milliseconds" as display format
2. Ctrl + S
3. Ctrl + W
4. In the Time toolbar, select "seconds" as display format
5. Re-open the project
6. Check the Time toolbar display format

### Expected behavior

It has been changed to the "seconds + milliseconds".

### Actual behavior

The display format is "seconds".

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Other

### Additional context

Both **Selection** and **Spectral Selection** toolbars behave differently: they preserve their per-project display formats.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
