### ISSUE TITLE
Remove mouse preferences page

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5713]

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @LWinterberg 's branch build for this:  audacity-win-3.5.0-alpha-20231128+30b6e43-x64

This looks to be fixed in Leo's branch.

There is no **Mouse** entry in Preferences:
![image](https://github.com/audacity/audacity/assets/50205984/18e483e3-2c8b-413a-bc92-b59fab5baa90)

I have P1s to the Manual for this for when this gets pulled into master for 3.5.0

**Comment by petersampsonaudacity** [comment]
I have added a new page to the alpha 3.0.5 manual so that users can "discover" the Mouse bindings:

Snapshot here is the alpha manual is locked for viewing:
![image](https://github.com/audacity/audacity/assets/50205984/746e4ff9-23ff-4f99-89f1-34793229bdf0)

it is linked to directly from a new entry in the front page (reference section of the Manual:
