### ISSUE TITLE
the DEFAULT published OSX binary on the WEBSITE should not be asking me to install the OPTINAL FFMPEG it should just work

### ISSUE THREAD

**Issue by dataf3l** [audacity/audacity#5739]
### Bug description

I drag and drop a m4a file, it doens't work and tell me some stuff about ffmpeg, I am a user, I don't care about ffmpeg, I just want to drag and drop

### Steps to reproduce

drag a m4a into audacity and see it fail

### Expected behavior

I expect that it doesn't fail

### Actual behavior

why is ffmpeg even optinoal? the ffmpeg binary is already there, so why can't audacity even TRY to run ffmpeg in the first place? this is a fail IMHO

### Audacity Version

latest beta

### Operating system

macOS

### Additional context

I am frustrated

**Comment by LWinterberg** [comment]
> why is ffmpeg even optinoal? the ffmpeg binary is already there, so why can't audacity even TRY to run ffmpeg in the first place? this is a fail IMHO

Due to patent restrictions, FFmpeg cannot be bundled with Audacity. and Audacity doesn't ship with them. What you may be seeing are the binaries which connect the actual FFmpeg binaries to Audacity. But you still have to install FFmpeg from third parties (like homebrew or [buanzo.org](https://lame.buanzo.org/ffmpeg.php))
