### ISSUE TITLE
Remove the Stop button in the Import dialog

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5796]
### Bug description

In the Import progress dialog, there are two buttons – Stop and Cancel – that are supposed to serve the same purpose which is really unnecessary. Moreover, clicking the Stop button doesn't work as expected: when clicked, it simply freezes the progress but ends up successfully importing the file anyway.

### Steps to reproduce

1. Ctrl (Cmd) + Shift + I
2. Select a somewhat large file
3. In the Import progress dialog, click Stop 

### Expected behavior

Should cancel the import

### Actual behavior

Doesn't cancel the import, the progress just freezes for as long as it takes to import the rest of the file.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by chinakov** [comment]
The 'Stop' button should be removed from the dialog, according to @LWinterberg

**Comment by Cygon** [comment]
I found the stop button rather useful.

**Cancel button**: aborts the import and discards everything that was loaded
**Stop button**: stop decoding and open partially loaded channels

This was very useful, i.e. when inspecting large audio projects where importing the whole file would take several minutes, letting me see if there are any dummy channels and if channels have been normalized/compressed.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
