### ISSUE TITLE
(macOS) Crash when launching AUMultibandCompressor

### ISSUE THREAD

**Issue by templehead** [audacity/audacity#5799]
### Bug description

Attempting to use AUMultibandCompressor results in crash every time

### Steps to reproduce

1 - open audio file
2- select audio 
3 - open AUMultibandCompressor

### Expected behavior

AUMultibandCompressor should appear, instead app crashes

### Actual behavior

crash

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by kitijarudevica** [comment]
I'm having the same problem :(

**Comment by templehead** [comment]
I have just upgraded OS X to 14.2 and the issue remains.

**Comment by petersampsonaudacity** [comment]
Another report of this today on the Forum from a different user:

**https://forum.audacityteam.org/t/audacity-3-4-2-crashing/93481**

**Comment by Markioa** [comment]
I am having the same issue

**Comment by koendebruijn** [comment]
Same issue here...

**Comment by chinakov** [comment]
Confirmed on 14.3, Apple Silicon.

**Comment by templehead** [comment]
Still happening after update to OS X 14.4 (Intel)

**Comment by saintmatthieu** [comment]
The crash happens if I execute this statement,
<img width="1005" alt="Screenshot 2024-03-21 at 08 50 36" src="https://github.com/audacity/audacity/assets/22740106/9cf9de2d-5e29-4c8c-bafd-53fffde00efd">
but I cannot debug deeper as this is an OS binary, or whatever this is called.
For other Audio Units, this statement can get executed and things work just fine. 
This got me to Google for reports on this particular audio unit, and this is the first I found: https://discussions.apple.com/thread/255189775
That brought me to trying it in GarageBand, too, and this AU there indeed shows an empty UI:
<img width="751" alt="Screenshot 2024-03-21 at 09 05 15" src="https://github.com/audacity/audacity/assets/22740106/c2e960d3-1333-4ce6-9d18-9e653ceba812">
So the question I'm asking myself right now is how we should handle this situation until Apple fixes this.

**Comment by petersampsonaudacity** [comment]
> So the question I'm asking myself right now is how we should handle this situation until Apple fixes this.

@saintmatthieu @LWinterberg 

This is really a more general question ...

Ideally no third-party plugin should _**crash**_ Audacity (and several perhaps many do) - rather the failure should be _gracefully_ captured and reported to the user.

**Comment by crsib** [comment]
> Ideally no third-party plugin should crash Audacity (and several, perhaps many, do

This implies that plugins are run out-of-process, which is rarely a thing due to performance reasons.
