### ISSUE TITLE
Open-Vino fails to run on Audacity 3.5.0 alpha

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5840]
### Bug description
I installed the OpenVino components in my latest 3.5.0 alpha - and it fails to run, I get the following message when I launch this modified 3.5.0
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/50205984/949895ac-a2cb-4069-b513-f5c45cbcab5f)

I can dismiss that message with the OK button and Audacity launches,

But when I go to Modules preferences I see that the mod-openvino is marked as **Failed** (I had previously enabled it on initial launch as per your installation instructions_
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/50205984/b1a50114-e228-476e-86ff-8d19f18cb438)

### Steps to reproduce
1. clear Audacity settings folder
2. download 3.5.0 alpha
3. download the OpenVINO modules and install them
4. launch 3.5.0
5. Edit > Preferences > Modules
6. enable mod-openvino
7. Exit Audacity
8. Relaunch Audacity
9. Observe: error message - unable to load the mod-openvino module

### Expected behavior
mod-openvino should load on 3.5.0 alpha

### Actual behavior
mod-openvino fails to load on 3.5.0 alpha

But runs fine on my W10 PC with 3.4.2

### Audacity Version
current master / alpha / nightly build
audacity-win-3.5.0-alpha-20240103+70cd387-x64-msvc2022

### Operating system
Windows 10

### Additional context
Also reported on the OpenVino GitHub issues log
https://github.com/intel/openvino-plugins-ai-audacity/issues/16

Logged her as OpenVINO was announced recently on the Muse website:
https://www.audacityteam.org/blog/openvino-ai-effects/

**Comment by petersampsonaudacity** [comment]
@crsib @LWinterberg 

Note that the method of installation for these AI plugins/modules involves copying many downloaded files into the users folder that contains the Audacity executable.

I am unclear as to the implications of when a user upgrades in the future to a newer version of Audacity as to whether or not the user will need to re-install the OpenVINO modules or whether they will persist following the upgrade.

Clearly the above comment only applies to "normal" users who always upload into C:\Program Files\Audacity - for users/testers like me who place each version of Audacity in its own appropriately named folder - then a re-installation into each version folder will certainly be required.

**Comment by RyanMetcalfeInt8** [comment]
Hi @petersampsonaudacity

> I installed the OpenVino components in my latest 3.5.0 alpha - and it fails to run

This is expected. Right now, the OpenVINO module is tied very closely with a very specific version of Audacity, as the effects, generators, analyzers directly inherit from internal Audacity (C++) classes. As there's been quite a bit of refactoring for Audacity effect classes since 3.4.2 tag, what you are probably experiencing are DLL load failures due to some kind of ABI mismatch.

Even if internal Audacity class API's hadn't changed at all, there is a module version check after DLL load. Basically, Audacity asks the module what version of Audacity is was compiled against... if the response doesn't match the version of Audacity loaded, it will throw an error message and exit.


> Note that this is very unlike what happens with "normal" plugins that a user downloads onto their PC for use in Audacity

Correct. And the technical difference here is that this is a 'module', not a 'plugin' (not that the user should know or care about this distinction). 

Anyway -- it's certainly not ideal, and we'll definitely work toward having this module work across Audacity upgrades, so happy to figure out how to make that work.

Thanks,
Ryan

**Comment by crsib** [comment]
@petersampsonaudacity it's a huge problem with Audacity modules API. We offer no stable API, nor ABI, so the module should be built against the specific Audacity version.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with the recently released 3.5.0

Using the OpenVino installation (recently upgraded for 3.5.0)
a) the installation works
b) the OpenvVino EGATs appear to work

@LWinterberg @dozzzzer  - I think this issue can thus be closed
