### ISSUE TITLE
AppImage release depend on "Golang IDE by JetBrains" through libthai.so.0

### ISSUE THREAD

**Issue by ygaeon** [audacity/audacity#5846]
### Bug description

AppImage release depend on "Golang IDE by JetBrains" through `libthai.so.0`

```
$ audacity-linux-3.4.2-x64.AppImage
/tmp/.mount_audaciHNd3kf/bin/audacity: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory
```

On 6.1.33-gentoo

### Steps to reproduce

1. `wget https://github.com/audacity/audacity/releases/download/Audacity-3.4.2/audacity-linux-3.4.2-x64.AppImage`
2. chmod +x audacity-linux-3.4.2-x64.AppImage
3. ./audacity-linux-3.4.2-x64.AppImage

### Expected behavior

The app is launched

### Actual behavior

The app doesn't launch

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

Gentoo package information:
https://www.portagefilelist.de/?fs=libthai.so.0#panchor

**Comment by crsib** [comment]
I can run AppImage on a clean Ubuntu. It surely doesn't depend on anything by JetBrains, as none of their products are installed on CI

**Comment by ygaeon** [comment]
Well, "it works on my computer" doesn't help me, but thanks. 👍🏻

**Comment by crsib** [comment]
Very quick search that libthai has nothing to do with JetBrains. It's a library for Thai language support.

https://linux.thai.net/projects/libthai

**Comment by ygaeon** [comment]
Indeed it is but why does Audacity AppImage want to load it? I have nothing thai on my system.

**Comment by Korne127** [comment]
@crsib It has nothing to do with Jetbrains (I have no idea how they got to that issue title), but the issue still exists independently to that, doesn't it?
In any case, this has been fixed by https://github.com/AppImageCommunity/pkg2appimage/pull/555. `libthai` is now included in new AppImages as it has been removed from the excludelist. So hopefully this issue won't happen with new Audacity releases anymore.
