### ISSUE TITLE
Non-destructive pitch shifting

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5891]
Now that we've done the hard work integrating StaffPad's time-and-pitch library for non-destructive time stretching, non-destructive pitch shifting is a low-hanging fruit.

Figma design: https://www.figma.com/file/6kBToiSyv40MOWaNzkxCdj/32_WX---Pitch-%26-Onset-snapping?type=design&node-id=30-761&mode=design&t=NXQu7CHTFSEalCZ6-0

Not every single aspect of this design have to be implemented with this ticket, leftovers can be addressed separately. At least this ticket should make the feature usable.

**Comment by DavidBailes** [comment]
@saintmatthieu . Re the use of the shortcut Alt + P for the pitch and speed dialog. Shortcuts of the form Alt + letter aren't ideal, as this can potentiality lead to conflicts with the access keys used for the menu names in the menubar in translations of Audacity. There are already 5 existing shortcuts of the form Alt + letter, but I'm not sure it's a good thing to add any more.

**Comment by saintmatthieu** [comment]
@DavidBailes sounds like a sensible remark. I saw that "Ctrl+Alt+letter" were widespread, maybe that instead ? @LWinterberg ?

**Comment by LWinterberg** [comment]
Ctrl+Shift+P works.

**Comment by saintmatthieu** [comment]
Ok

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's latest branch for this:  audacity-win-3.5.0-alpha-20240202+81dc5f9-x64-msvc2022

Pitch and Speed  changing appears to work while Audacity is playing - but there are some issues of note:

1) when Audacity is playing and you hover the cursor over the Clip-handle drag bar the cursor icon that you get is a **white no-entry**  icon - to me this implies that no action is available but clicking on it still brings up the drag-bar context menu, including the **Pitch and Speed** command

2) when Audacity is playing the **Clip Speed %** in the **Pitch and Speed** dialog is grayed-out and unavailable.  
This is _**not**_ the case when the command is invoked while Audacity is not playing.
![image](https://github.com/audacity/audacity/assets/50205984/8383c245-1445-45e4-b5cf-474e9d6cbb54)

3) The **Pitch and Speed** context menu :command has a much reduced UI compared to the **Effect > Pitch and Tempo > Change Speed and Pitch** menu command:
![image](https://github.com/audacity/audacity/assets/50205984/b633326e-093c-4d2e-865e-81a65800f672)

4) I was really expecting the **Change Speed and Pitch** effect to be a further Audacity command that would now be available in the Real-time effects stack - and not just a clip-handle context menu.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu  @LWinterberg 

Perhaps most importantly:

6) the PR #5900  states that the dynamic pitch change in the  clip being played is "non-destructive".

BUT testing shows that the pitch change is actually applied destructively (the change goes on the Undo/History stack).
![image](https://github.com/audacity/audacity/assets/50205984/1a172236-e9e5-46f1-8030-70e587dbae83)
And Undo/Redo can be applied.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu @LWinterberg 

7)  the dialog seems un-necessarily wide

![image](https://github.com/audacity/audacity/assets/50205984/c2664111-7532-4c7e-a281-2c9cd6f5cce6)

**Comment by petersampsonaudacity** [comment]
@saintmatthieu @LWinterberg 

8) in the old clip-handle context menu the command was **Change Speed** - in the new menu it is just **Pitch and Speed**.

Surely it would be better to add back the "Change" and make the new command be **Change Pitch and Speed**
a) for clarity of purpose  ("does what it says on the tin")
b) to differentiate from the **Render Pitch and Speed** just beneath it

![image](https://github.com/audacity/audacity/assets/50205984/bf3f75df-1ddb-4084-ae3d-15bc3386719f)

**Comment by petersampsonaudacity** [comment]
I have updated the Manual for the changes as they currently are - but retained P1s just in case further changes are effected.

**Comment by LWinterberg** [comment]
@petersampsonaudacity 

1. is because moving the clip is not available during playback. Other actions may still be available though. It would be slightly more correct to use a different cursor on the ..., indeed. 
2. That is correct; you cannot stretch a clip during playback but you can change pitch. This is due to technical limitations. 
3. For this release, the important thing for this dialog is that it works. Other data displays (% vs bpm vs new length, semitones vs hz) may come later. 
4. speed/tempo changes are not a good candidate as realtime effects, change pitch would be though. It may be interesting generally replacing the destructive effects we currently have with the non-destructive clip-level versions that just got introduced. 
5. Correct, and it's annoying. If it turns out to be an issue, I'd propose renaming the "Change Speed and Pitch" fka "Change Speed" effect to "Tape-style stretching", "tape speed change" or something like that. Also, this new dialog may be renamed itself as more features are added. 
6. Changes in realtime effects generally *can* go onto the undo stack. What makes them realtime/non-destructive is that the source data remains untouched and can be restored by simply telling the computer to stop applying the effects (ie resetting the pitch and speed). This is distinct to destructive effects which, once the effect is written into the waveform, can *only* be restored to a previous state via undo, and once the undo state is deleted, cannot be restored.
7. There's a practical minimum size to dialogs. Generate > Silence is another one which could simply be made smaller if all you cared about is making the window size hug the controls. I don't dislike the current size of it. 
8. That causes a full naming collision with the effect (change speed and pitch vs change pitch and speed).

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

> 5\. Correct, and it's annoying. If it turns out to be an issue, I'd propose renaming the "Change Speed and Pitch" fka "Change Speed" effect to "Tape-style stretching", "tape speed change" or something like that. Also, this new dialog may be renamed itself as more features are added.

More than annoying - it's potentially very confusing methinks ...

_Thanks for the detailed replies on the other points Leo._

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

I have added notes in the alpha manual for the two pages on speed/pitch changing to highlight the differences.

**Comment by saintmatthieu** [comment]
Hi @petersampsonaudacity, thanks for the thorough report!

> 1. when Audacity is playing and you hover the cursor over the Clip-handle drag bar the cursor icon that you get is a white no-entry icon - to me this implies that no action is available but clicking on it still brings up the drag-bar context menu, including the Pitch and Speed command.
By "clicking on it", you probably mean right-clicking?

2. @LWinterberg how about adding explanatory text ?

Besides that, I have nothing to add to Leo's also comprehensive response - thank you both.
