### ISSUE TITLE
Non-destructive pitch shifting: implement overflow button

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5901]
* A `...` button in the top right corner of clips, which allow to open the clip context menu in one click.
* Pitch and speed indicators become clickable, too.

Figma design (private): https://www.figma.com/file/6kBToiSyv40MOWaNzkxCdj/32_WX---Pitch-%26-Onset-snapping?type=design&node-id=30-761&mode=design&t=PhFBhnaOKVhnO3s8-0

**Comment by DavidBailes** [comment]
@saintmatthieu . I appreciate that this hasn't been reviewed yet, but leaving this comment just in case it's of some use.
I noticed a couple of things. The first is if a clip is only partially visible at either the start or end of the waveform display - the buttons are shown in preference to the clip name. I assume that is not intentional. Eg:
Visible clip:
![image](https://github.com/audacity/audacity/assets/11887021/3edea9c7-123d-4cca-9bc2-e3c41d1fbc3d)

Partially visible:
![image](https://github.com/audacity/audacity/assets/11887021/dd27e407-0191-42cc-856f-25e55c7f3144)

Partially visible:
![image](https://github.com/audacity/audacity/assets/11887021/324807c5-610a-4ad3-8342-a3e5264ce4f8)


The second issue is if the cursor is over one of the new buttons, and you then hold down the left mouse button, move the cursor off the button and release the mouse button, a dialog opens. Standard practice is that a button is not activated if you do this (for example the buttons in the track control panel). In this particular situation the existing behaviour may cause people to accidentally open one of the dialogs when they are trying to drag a clip, but are not using a non-button part of the clip handle.

**Comment by saintmatthieu** [comment]
Thanks a lot, @DavidBailes for these findings. I just pushed two commits for each of these issues.

**Comment by chinakov** [comment]
Tested.
