### ISSUE TITLE
Auto Project Rate + Toolbar

### ISSUE THREAD

**Issue by Njsmooth** [audacity/audacity#5946]
### Your idea

An option to have the project rate be automatically set based on the first file imported into a blank project + a toolbar for easily seeing and changing the project rate as needed.

### Problem to be solved

About half a year ago or so, Audacity would set the project rate to whatever the rate of the first audio clip was, and it was easily visible in the toolbar. Now, I have to manually change the project rate each time and risk mixing and exporting at the wrong rate (which matters for me because I'm working with sample-based loop points). There's also [this](https://forum.audacityteam.org/t/project-rates-and-recording/32238/2) post on the forum from only 2 months ago that mentions this "special case", but that does not appear to be the case.

**Comment by LWinterberg** [comment]
The step for the project rate for exporting is now moved to the exporter. Instead of taking the first file and using it for everything, including new recordings and exporting, it now uses the highest sample rate present in the project during export, and you can change the sample rate in the exporter directly (which you couldn't before). If you want to export at a specific samplerate, you never have to touch the project rate.

Sample-based looping points is not something we're looking to support natively at the moment. 

> There's also [this](https://forum.audacityteam.org/t/project-rates-and-recording/32238/2) post on the forum from only 2 months ago

That post is from 11 years ago.

**Comment by qwertymodo** [comment]
The fact that this behavior that existed for decades was changed without warning and without any user option to set it back is REALLY frustrating.  Audacity has been a great tool for finding exact sample numbers within files to be used with other workflows like loop generators for years, and this completely breaks that, because the project sample rate affects the sample numbers that are displayed in the position and selection dialogs.

> Sample-based looping points is not something we're looking to support natively at the moment.

I'm not asking you to support anything new, it would just be nice if you wouldn't break existing things without giving users the option to retain existing functionality.  A simple "auto" option in the project sample rate drop-down that gives the old behavior of automatically changing the project rate to match the first imported audio would be sufficient.  I understand that there is a lot going on with the project since the muse group acquisition, but completely breaking people's workflows without at least giving them the ability to recreate them is not ok.

**Comment by JunkiEDM** [comment]
> The step for the project rate for exporting is now moved to the exporter. Instead of taking the first file and using it for everything, including new recordings and exporting, it now uses the highest sample rate present in the project during export, and you can change the sample rate in the exporter directly (which you couldn't before). If you want to export at a specific samplerate, you never have to touch the project rate.

Ignoring the "special case" OP mentioned of sample-based looping points, I still think the sample-rate toolbar should be added back. 
I'm really not sure why it was removed since it wasn't really in the way of anything.
The situation you described of only setting sample rates in the exports is only convenient when **downsampling**.
If you're trying to **upsample** the audio before applying any effects (oversampling) then, because the toolbar is removed, this workflow goes from 2 clicks to 5+ clicks. 
`Audio Setup -> Audio Settings -> Project Sample Rate -> change -> OK` is the quickest path i could find, which is very obtuse compared to a simple toolbar.
IMO removing existing functionality should be a last resort unless the functionality is replaced with a better-or-similar workflow.

**Comment by LWinterberg** [comment]
Changing the project rate does *not* resample existing tracks in the project and never has. To resample a track, use Tracks -> Resample. That behavior has not been changed.
