### ISSUE TITLE
When uploading audio to audio.com, track title cannot be submitted by pressing the Enter key

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6003]
### Steps to reproduce

1. Navigate to the Share Audio dialog
2. type something into the Track Title text box
3. press Enter

### Expected behavior

Track Title is submitted and file uploading starts as if the Continue button was clicked.

### Actual behavior

Nothing happens

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS, Linux

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
