### ISSUE TITLE
User is not notified about syncing that is happening in background

### ISSUE THREAD

**Issue by ianalarina** [audacity/audacity#6027]
### Bug description

Currently, when saving the project, we have a screen that indicates an exporting process, and syncing process progress in bottom right corner. Exporting dialog disappears faster than syncing is completed

![image](https://github.com/audacity/audacity/assets/128831621/6ef406ac-0b66-46bb-82ef-b3c1e4275cd6)

### Steps to reproduce

1. Generate Chirp
2. Start saving it to the Cloud
3. Wait till export dialog disappears

### Expected behavior

- User needs to be notified that syncing is going to happen in the background for the cases when the whole process takes longer than 5 seconds
@LWinterberg 

### Actual behavior

![image](https://github.com/audacity/audacity/assets/128831621/822c20c7-9e89-43cc-a029-93818dd3771f)

### Audacity Version

other

### Operating system

Windows, macOS, Linux

**Comment by LWinterberg** [comment]
![image](https://github.com/audacity/audacity/assets/87814144/6ba1677c-06b0-485c-9445-311481c988f8)
A solution here is to

1. move the appearance of the dialog to "after mixdown completes", rather than "after sync completes"
2. Change the wording such that it shows it's a) syncing in the background and b) has an indicator in the bottom right. 
3. Show the dialog once per project (unless disabled by the user), rather than once, ever, so that there's more chances to see what's going on here. 

Ultimately, this sort of messaging would benefit from a snackbar/toast-type UI pattern, but we don't have that and adding it definitely is out of scope for 3.5.

**Comment by dozzzzer** [comment]
@LWinterberg @Tantacrul 
> Expected behavior
> User needs to be notified that syncing is going to happen in the background for the cases when the whole process takes longer than 5 seconds

Is the 5-second rule still relevant?

**Comment by LWinterberg** [comment]
no, we want to keep the cloud project text there all the time instead if i recall the last discussion on it correctly.
