### ISSUE TITLE
Export Multiple: Edit Metadata Tags should have a way to skip further for the current save

### ISSUE THREAD

**Issue by eharris** [audacity/audacity#6037]
### Your idea

When using the `Export Multiple` feature with the `Show Metadata Tags editor before export` enabled, it presents a separate dialog for each and every file that will be generated.
When you have dozens/hundreds of files (for example, when splitting by labels), it is extremely tedious to have to either click past each dialog, or to enable the `Don't show this when exporting audio` option, finish the export, then manually go back into settings to re-enable the Metadata Editing option.

Almost always, I only want to make metadata changes that apply to every file, so only want the Metadata Edit dialog to be shown once.  So it would be really helpful for there to be another button added, like "Ok (apply to all)", which bypasses any further Edit Metadata tags for the current export, but does NOT disable the Edit Metadata dialog for later exports.

Another option would be to add another option to the "Edit Metadata Tags" dialog that will bypass the dialog for any additional files on the current export, rather than changing the global setting to disable the "Edit Metadata Tags" dialog completely.

### Problem to be solved

Improve behavior when `Export Multiple` is used with Edit Metadata enabled.

**Comment by petersampsonaudacity** [comment]
This has changed a LOT in the latest version of Audacity 2.4.2

In 3.4.2 Muse consolidated all the audio exports back into a single dialog and  with all the export options available in the dialog (rather than hidden away in preferences etc.).

As part of this there is now an **Edit Metadata** button at the bottom left.  This enables you to set the common metadata for a multiple export (ar the full metadata for a single file export).  If you don't use that button then export will use whatever you may (or may not) have set in the default metadata set.

![image](https://github.com/audacity/audacity/assets/50205984/043a5292-cb38-4631-bb50-8516f9bd1a54)


Unfortunately there are a couple of errors/bugs that affect this in 3.4.2

1.  The default metadata is not stored and recalled by Audacity - this has recently been fixed for 3.5.0

2. The other bug remains open
 **With new Multiple Files Export dialog user supplied Metadata applies only to the first exported file ... #5825** 
https://github.com/audacity/audacity/issues/5825

I'm hoping that this second bug gets fixed for the upcoming 3.5.0  -   but there is no guarantee of that happening.
