### ISSUE TITLE
Adding the ability to export and import audacity user settings

### ISSUE THREAD

**Issue by brahimjarallah** [audacity/audacity#6088]
### Your idea

Audacity is an awesome audio editing software, yet it worth a crucial enhancement to make users have the ability to export and import their audacity  settings so they do not need modify audacity settings each time we open the software.

### Problem to be solved

Add export and import audacity user settings functionality

**Comment by LWinterberg** [comment]
This already is possible - the audacity.cfg can be copied from system to system. If you copy the Audacity executable between places, adding a folder called Portable Settings with that file will cause Audacity to use that instead of the one in AppData. See https://manual.audacityteam.org/man/portable_audacity.html
