### ISSUE TITLE
Exporting stereo as mono file 6dB too high

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6100]
### Bug description

When exporting stereo as a mono file, the stereo channels should be "mixed down to mono", producing the average of the two channels, rather than just mixed (summed).

### Steps to reproduce

1. Import or generate a stereo track.
2. Export to mono (I've only tested WAV and MP3)
3. Import the exported track

### Expected behavior

The imported track should be essentially the same as if we mixed down the stereo track to mono.

### Actual behavior

The imported track is around double the expected amplitude.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Reported on the forum: https://forum.audacityteam.org/t/exporting-to-mp3-and-wav-dramatically-increases-volume/74386/14

**Comment by LWinterberg** [comment]
![image](https://github.com/audacity/audacity/assets/87814144/865b0cf0-a95d-459f-a642-15f00b40e5b9)
I can reproduce this.

**Comment by petersampsonaudacity** [comment]
Note that **Tracks > Mix > Mix stereo down to mono** command does _**NOT**_ do this.

the proper amplitude is maintained.

**Comment by petersampsonaudacity** [comment]
Testing on W10 shows that this is a regression on 3.3.3, introduced in 3.4.0 with the introduction of the new consolidated Export dialog

**Comment by LWinterberg** [comment]
It's not a regression, mixing to mono wasn't an option before that. Only MP3 had a "force mono", which had LAME mix it after Audacity gave it stereo.

**Comment by SteveDaulton** [comment]
It is a regression for MP3 export (which did have a mono option).

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's test branch build for this:  audacity-win-3.5.0-alpha-20240325+36a0164-x64

This looks to be properly fixed in Vitaly's test branch.

1. I generated a stereo tone at 0.4 amplitude
2. Exported it as mono
3. Imported the audio file
4. Observed: amplitude is a smidgeon under 0.4  _(and certainly not longer doubled to 0.8)_

![image](https://github.com/audacity/audacity/assets/50205984/cfaa158b-b3f0-4111-8110-a3607015687f)

**Comment by chinakov** [comment]
Tested, thanks!
