### ISSUE TITLE
Open from cloud dialog: no indication of default button

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6191]
### Steps to reproduce

Open the Open from cloud dialog

### Expected behavior

The default button has a blue outline, and the Jaws screen reader can read to the user the name of the default button.

### Actual behavior

No buttons have a blue outline, and the Jaws screen reader can't work it out either.

### Audacity Version

latest beta

### Operating system

Windows

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
