### ISSUE TITLE
Save to audio.com dialog: When account not linked, explanatory text not read by screen readers. 

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6197]
### Steps to reproduce

With a screen reader running, and no linked account:
1. Open the file menu and choose save to cloud. The following dialog opens:
![image](https://github.com/audacity/audacity/assets/11887021/0cbf73a6-564b-4297-b79c-2c104086bbbb)

### Expected behavior

A user of a screen reader can easily read the explanatory text: "Cloud saving requires..." 

### Actual behavior

The explanatory text is automatically read when the dialog opens, and neither is it read when a user tabs round the dialog.

A solution to this problem would be to place the explanatory text as the first item in the dialog. I think this would make sense for sighted users as well.

### Audacity Version

latest beta

### Operating system

Windows

**Comment by DavidBailes** [comment]
@LWinterberg . Just to note that I won't be able to fix this problem for 3.5.0 by moving the explanatory text to be the first item in the dialog, as the text would have to be changed - the link account button would no longer be above the text, and I assume we're in string freeze.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
