### ISSUE TITLE
On Ubuntu 22.04 (ARM64), building Audacity was successful, but with errors

### ISSUE THREAD

**Issue by prko** [audacity/audacity#6223]
### Bug description

[audacity build success with errors.txt](https://github.com/audacity/audacity/files/14878655/audacity.build.success.with.errors.txt)

### Steps to reproduce
```
sudo apt-get update

sudo apt-get install -y build-essential cmake git python3-pip

sudo pip3 install conan

sudo apt-get install libgtk2.0-dev libasound2-dev libjack-jackd2-dev uuid-dev

sudo apt install graphviz

git clone https://github.com/audacity/audacity/

cd ~

mkdir build && cd build

cmake -G "Unix Makefiles" ../audacity

cd Debug/bin

mkdir "Portable Settings"

./audacity

cd ~/build

sudo make install
```

### Expected behavior

build without errors

### Actual behavior

Building Audacity was successful but with errors.
The details of errors are included as a txt file in the "Bug description".

### Audacity Version

other

### Operating system

Linux

**Comment by LWinterberg** [comment]
for later convenience: The only error in the log is

```vst3sdk/3.7.7@audacity/stable: ERROR: Don't specify 'build_type' at build time for single-config build systems```

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
