### ISSUE TITLE
The program interface is very laggy, almost impossible to use

### ISSUE THREAD

**Issue by NeiroNext** [audacity/audacity#6224]
### Bug description

The interface lags a lot, you can work, but because of the lags it is extremely inconvenient.
I opened only 5 audio recordings, 2 stereo and 3 mono (recording).

### Steps to reproduce

1. Open a couple of audio recordings
2. Try scrolling horizontally or
3. Try to move the position of the audio recording in time or
4. When playing, just move the mouse

### Expected behavior

It just shouldn’t lag, by eye there’s 1-2 fps, but no less, with these actions, I’m expecting 144 or 60 fps

### Actual behavior

When performing the above actions, the interface lags, by eye it’s 1-2 fps, it’s almost impossible to edit something like that

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Windows 11
64 Gb RAM
GTX 1070

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
