### ISSUE TITLE
Open from cloud: Cancelling cloud project incomplete dialog results in Audacity not responding to keyboard input

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6247]
### Steps to reproduce

1. Arrange for a cloud project to be not fully uploaded.
2. Open the open from cloud dialog.
3. Open that project. A cloud project incomplete dialog opens.
4. Press cancel.

### Expected behavior

The cloud project incomplete dialog closes, and focus is returned to the open from cloud dialog.
This dialog responds to keyboard input.

### Actual behavior

The cloud project incomplete dialog closes, but focus "apparently" returns to the Audacity main window.
Audacity doesn't respond to any keyboard input.

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

See also: https://github.com/audacity/audacity/issues/6198

**Comment by DavidBailes** [comment]
I think that the problem is probably that the parent of the "cloud project incomplete" dialog is the project window, rather than the open from cloud dialog.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
