### ISSUE TITLE
Save to audio.com success dialog: closing it  can leave Audacity unresponsive to keyboard input

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6259]
### Bug description

If another modal dialog is open when the success dialog opens, then canceling it leaves Audacity completely unresponsive to keyboard input.

### Steps to reproduce

1. Generate some audio.
2. Open save to cloud from the File menu. A save to audio.com dialog opens.
3. Type in a project name and press save. A syncing your project dialog opens.
4. Press continue.
5. Open a modal dialog, eg the about dialog.
6. At some point a Success dialog opens. Press Esc to cancel it.

![image](https://github.com/audacity/audacity/assets/11887021/2004c6b6-fbf2-4402-8ce3-75255b6ab5cd)

### Expected behavior

Focus returns to the About dialog.

### Actual behavior

Focus "appears" to return to the main window.
However Audacity is unresponsive to any keyboard input.

### Audacity Version

other

### Operating system

Windows

### Additional context

version: release-3.5.0

see also: https://github.com/audacity/audacity/issues/6247

**Comment by DavidBailes** [comment]
Found that the problem occurs if you press the Done button as well as cancelling the dialog, so updated title and steps to reproduce.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
