### ISSUE TITLE
Audacity's ffmpeg plugin automatically scales the volume when importing lossy audio files

### ISSUE THREAD

**Issue by Kratos291** [audacity/audacity#631]
When you import lossy audio files in audacity (ac3 etc.) and export them, the export has a lower volume than the source. This is not an expected behaviour when you want to edit audio losslessly. This is because the ffmpeg plugin automatically scales the volume during the import process. Pure ffmpeg does this also. In ffmpeg you can fix it with "-drc_scale 0". 

My suggestion is to make Audacity automatically use "-drc_scale 0" when importing a lossy audio source.

- Windows 10
- Happens in all audacity versions

**Comment by pcroland** [comment]
Here's [Audacity](https://emma.cloud.tabdigital.eu/s/CSiTMH2Tj35egFi) with updated - ffmpeg@9d80f3e, lame@59a722d (3.99.5), libsndfile@06ebde5, libogg@0bbcba4, libvorbis@f1c1e44.
Use with ffmpeg:
- Version - some of the versions under "Git";
- Architecture - Windows 32-bit;
- Linking - Shared.
2) Follow "Locating the FFmpeg library manually" from [here](https://manual.audacityteam.org/man/installing_ffmpeg_for_windows.html).

I tested the `-drc_scale 0` thing with both ffmpeg and Audacity.
I converted an AC3 to wav with and without `-drc_scale 0` and they had the same md5 hash.
In audacity I imported both the AC3 and the wav file, inverted one of them, mixed them together, and the resulting mix was empty, so no difference in Audacity either.

**Comment by JamesCrook** [comment]
Believed fixed, but the bugzilla item and/or commit needs tracking down.

**Comment by JamesCrook** [comment]
Tracked down to https://github.com/audacity/audacity/issues/398#issuecomment-835825236 
https://ffmpeg.org/pipermail/ffmpeg-devel/2015-March/170985.html
#741 has been merged, so closing.

**Comment by petersampsonaudacity** [comment]
I tested this on my W10 PC with Audacity 3.0.2  and I can hear no difference when playing - but measurement shows slightly otherwise

1) Generate default Tone
2) Effect Amplify
3) Observe: amplification factor **1.938 dB**
4) Cancel - i.e. don't apply the Amplification
5) Export as AC3 - say tone.ac3
6) Close Audacity
7) Relaunch Audactity
8) import tone.ac3
9) Export the audio as say tone-exported.ac3
10) Import tone-exported.ac3
11) select top track, labelled "tone"
12) Effect > Amplify
13) Observe: amplification factor **1.901 dB**
14) Cancel
15) select bottom track, labelled "tone-exported"
16) Effect > Amplify
17) Observe: amplification factor **1.872 dB**
18) Cancel

So this looks to meas though Audacity is scaling  when importing lossy AC3 audio files - but  from the measurements it looks like Audacity is slightly scaling up rather than down.

But this begs the question:
are the two amplitudes close enough - or does this remain an issue

@JamesCrook  - your thoughts please ?

@Kratos291 can you please reconduct my experiment with:
a) your original Audacity version from July 2020,
b) the latest release 3.0.2 ?

**Comment by JamesCrook** [comment]
Dmitry reminded me that #741 had been reverted, so reopening.

**Comment by petersampsonaudacity** [comment]
> 
> 
> Dmitry reminded me that #741 had been reverted, so reopening.

It was reverted as we were unsure how to handle
a) backwards compatibility issues
b) hosting two versions of FFmpeg for each platform
c) managing users' FFmpeg upgrades

**Comment by petersampsonaudacity** [comment]
Logged on our bugtracker Bugzilla as Bug #2796
https://bugzilla.audacityteam.org/show_bug.cgi?id=2796
FFmpeg automatically scales the volume when importing lossy audio files

So closing this Bugzilla Issue in favor of the tracked Bugzilla entry.

**Comment by ValZapod** [comment]
> https://ffmpeg.org/pipermail/ffmpeg-devel/2015-March/170985.html

That is the correct behaviour. Anyway, much later https://patchwork.ffmpeg.org/project/ffmpeg/patch/20200201193443.22419-1-rcombs@rcombs.me/

**Comment by ValZapod** [comment]
Wait a second, so this (drc_scale forced to 0) was not applied in https://github.com/audacity/audacity/pull/1623?

**Comment by crsib** [comment]
The patch you point to is an ffmpeg patch. Audacity doesn't ship with ffmpeg nor it does much codec-per-codrc configuration, so I'm not sure that I understand your question. 

We are open to suggestions and patches.

**Comment by ValZapod** [comment]
> The patch you point to is an ffmpeg patch.

I linked to a discussion, did you read that? It says that even though it would be more different from original lossless audio, Dolby recommends using the DR compressed version. Arguable (no roundtrip), but whatever.

>it does much codec-per-codrc configuration,

That is needed to fix this issue, since FFmpeg will not chnage the default for this.

**Comment by crsib** [comment]
We have no plans to do per codec configurations besides what "Custom FFmpeg Export" allows. Patches are welcome, but changes to the default behavior will be carefully considered.

**Comment by ValZapod** [comment]
> "Custom FFmpeg Export" allows

Does it allow specifying drc_scale 0 though? Anyway, you should know that TrueHD, ac3 and eac3 are the only codecs that have this. You know what DRC is, right? It is for night mode, when you do not want to to bother your neighbours or your family, it "compresses" the sound, so that it is less noise or so that music would not break the dialog (dialnorm) on bad sound systems.

**Comment by pcroland** [comment]
> We have no plans to do per codec configurations besides what "Custom FFmpeg Export" allows. This is especially true for importing.
> 
> Patches are welcome, but changes to the default behavior will be carefully considered.
`-drc_scale 0` should be applied for every dolby audio and it doesn't do anything for other codecs, so you can just pass it as an argument no matter what the source is.

**Comment by ValeZAA** [comment]
> > We have no plans to do per codec configurations besides what "Custom FFmpeg Export" allows. This is especially true for importing.
> > Patches are welcome, but changes to the default behavior will be carefully considered.
> 
> `-drc_scale 0` should be applied for every dolby audio and it doesn't do anything for other codecs, so you can just pass it as an argument no matter what the source is.

This is still not done 4 years later. Tsk.
