### ISSUE TITLE
Preferences dialog is too wide

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6343]
### Steps to reproduce

1. Launch Audacity
2. Reset configuration
3. `Cmd + ,` or `Ctrl + P`

### Expected behavior

The Preferences dialog's width hasn't changed.

### Actual behavior

The Preferences dialog is way too wide. Compare:

#### 3.5

<img width="468" alt="image" src="https://github.com/audacity/audacity/assets/70063970/f728f155-70e4-456e-8696-b4a2c88f8738">

####
<img width="409" alt="image" src="https://github.com/audacity/audacity/assets/70063970/0e650ad6-43f6-4238-a14e-6151fd4d2ed7">

#### 3.4.2

<img width="395" alt="image" src="https://github.com/audacity/audacity/assets/70063970/52ec3097-bb69-4a3f-b584-a6b641979f00">

####
<img width="336" alt="image" src="https://github.com/audacity/audacity/assets/70063970/ae40cdfb-9660-4240-9e83-d49b20e40d1e">

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS, Linux

**Comment by petersampsonaudacity** [comment]
@dozzzzer  and @LWinterberg 

Spectrograms is the only one that fills that entire width.

But looking at the page history for it's image in the Manual in older versions the 3 blocks were stacked vertically:
![image](https://github.com/audacity/audacity/assets/50205984/97694998-ebc0-4b8a-b30a-ab7b03fb9354)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
