### ISSUE TITLE
Support FFmpeg 7.0

### ISSUE THREAD

**Issue by teknoraver** [audacity/audacity#6389]
### Your idea

FFMpeg 7.0 is out which includes  libavformat61, but Audacity doesn't support it

### Problem to be solved

Update Audacity to support libavformat61

**Comment by vsverchinsky** [comment]
FFmpeg 7.0 PR has already been merged into master
https://github.com/audacity/audacity/pull/6241

**Comment by teknoraver** [comment]
Wow, it will be in next 3.5.2 release then?

**Comment by lgarron** [comment]
How soon can we look forward to this in an Audacity release?

I just spent half an hour trying to figure out what was going on in https://github.com/audacity/audacity/issues/3747#issuecomment-2099715925 because a routine `ffmpeg` upgrade from Homebrew broke my ability to drag and drop different formats into Audacity. I'd love to save others the pain!

**Comment by 0xdevalias** [comment]
> Just to summarize the best workaround for now:
> 
> ```shell
> brew install ffmpeg@6
> sudo rm -rf "/Library/Application Support/audacity/libs"
> sudo ln -s "/opt/homebrew/opt/ffmpeg@6/lib" "/Library/Application Support/audacity/libs"
> ```
> 
> And once the next version of Audacity is released, you can clean up with:
> ```shell
> sudo rm -rf "/Library/Application Support/audacity/libs"
> brew uninstall ffmpeg@6
> ```
> 
> Since `ffmpeg@6` is tagged with a version, it is not linked into the default system paths and will not interfere with `ffmpeg` 7 as the system default for other purposes.
> 
> _Originally posted by @lgarron in https://github.com/audacity/audacity/issues/3747#issuecomment-2099741598_
