### ISSUE TITLE
track list redraw problem using wxGTK gtk3 variant

### ISSUE THREAD

**Issue by nick87720z** [audacity/audacity#639]
As in 2.4.2, track list refreshes are very rare, probably at some major update. Scroll, scale and track height change don't ensure refresh happening. Scale makes it to redraw occasionally. The only 100% working way is window resize. Same problem appears when track list content is damaged. In xfwm4, when switching to other desktop then back, it will show content from previous desktop.

**To Reproduce**
1. Run audacity
2. Add some tracks from menu, they are not visible immediately
3. Resize window, should redraw immediatelly.
4. X11 only, no compositing: try to switch windows or desktops, it will show last content before audacity window is on top again.
5. Open audio file in new project, this time it's visible initially, but refresh problems are same (at least it's more clear now, how refresh happens).

**Expected behavior**
A clear and concise refresh.

**Screenshots**
Desktop switching example.
![audacity-2 4 2-redraw](https://user-images.githubusercontent.com/3896190/89532416-2da13180-d80b-11ea-9952-6aabe41422dd.png)

**Additional information:**
- audacity-2.4.2 (last unaffected is 2.3.2)
- calculate linux (gentoo + additional utils)
- gtk3: wxGTK-3.0.4-r302, gtk2: wxGTK-3.0.4-r2, gcc 7.4.0.

**Additional context**
First time redraw problem appeared in 2.3.3, so I stayed at 2.3.2 until today. But that time it was not so hard - scrolling usually made forced refresh, and even track change triggered it, though each frame was previous. This time it's way harder.

**Comment by SteveDaulton** [comment]
Audacity 2.4.2 should be built with wx3.1. There's a note about this in the release announcement: https://www.audacityteam.org/audacity-2-4-2-released/

"The main change since 2.4.1 is that we have upgraded the wxWidgets library that Audacity uses from 3.1.1 (with patches by us) to 3.1.3 (with patches by us). We wanted to do this as a release in its own right, before we start on a longer and more complex release.

If you’re using Audacity 2.4.2 on Linux, do use the right wxWidgets library. We’ve in the past had a lot of reports of problems on Linux that turned out in the end to be because some distributions were using system wxWidgets (3.0.0) with Audacity."

**Comment by leio** [comment]
Distributions are using wxWidgets 3.0.x for a very good reason - it is the last available stable release.

3.1.x are development releases with no ABI guarantees, and as far as I as one of the downstreams are concerned, stable release applications should not require a development release library.

That said, identifying what needs to be backported to 3.0.x packages in terms of bug fixes, would be a way to hold out until wxWidgets upstream finally releases stable 3.2 series. Best if also getting them backported upstream to their WX_3_0_BRANCH

**Comment by SteveDaulton** [comment]
and wxWidgets say:
"Please notice that while 3.1.4 is officially a “development” version because it is not fully compatible with the “stable” 3.0.x, the list of backwards incompatible changes is very short, so you shouldn’t have any problems updating to this version from 3.0.x in practice, and you’re encouraged to use this release, including in production."
https://www.wxwidgets.org/

**Comment by nick87720z** [comment]
It seems to be due to very movement to gtk-3 based wxWidgets. I tried 2.4.2 with wxGTK 3.1.3 from one of gentoo overlay, with some changes to ebuild. It worked, but above issue (as on screenshot) still there. Same happened when I tried ebuild 2.3.2 by backporting from 2.3.3 since they removed 2.3.2 (it was build with gtk2). 2.3.3 is built with gtk3 and without modifications it caused same issue for 2.3.2. It disappeared only when I rebuilt with gtk2-based wxGTK.

**Comment by nick87720z** [comment]
Is it necessary to use wxGTK built against gtk2, was gtk3 variant ever tested?
At least gentoo is getting rid of gtk2 since it's unmaintained, not sure in other distros. I use 2.3.2, because it's last ebuild, which required wxGTK gtk2 variant. Since 2.3.3 it depends in wxGTK gtk3 variant.

**Comment by notaz** [comment]
As a heavy audacity user, I was also unpleasantly surprised to get this after Ubuntu 18.04 -> 20.04 upgrade. According to the "about" screen Ubuntu links against wxWidgets 3.0.4 (without Audacity paches?), which itself is built against gtk3. Building Audacity 2.4.2 according to instructions (with patched wxWidgets 3.1.3 built for gtk2) gives a well working version.

I don't know if it's because of Ubuntu's use of wxWidgets 3.0 or GTK2, but if it's the later, with distributions moving away from GTK2 it will a problem

**Comment by nick87720z** [comment]
Despite official requirements, I could build both 2.3.3 and 2.4.2 versions against wxGTK-3.0.4 (gtk2) variant.
No more issue.
Though one time trying 2.3.3 this way, I got Envelop button (in 3x2 grid in toolbar) black unless hovered. But next time with same versions it did not reproduce.

**Comment by aaaaadrien** [comment]
WHY use a development version of wxGTK ???
Same problem for me

**Comment by kenoh** [comment]
FWIW, running with `GTK_IM_MODULE=ibus audacity` fixed this for me on Fedora 37 (KDE on X11):

> Build type: CMake Debug build (debug level 1), 64 bits
> Compiler: GCC 12.2.1
> wxWidgets (Cross-platform GUI library) 3.2.1
