### ISSUE TITLE
After changing the order of the effects in the stack, navigating between effects using the keyboard is in the wrong order

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6416]
### Steps to reproduce

1. Add an audio track
2. Add a realtime effect to the stack (a)
3. Add another one (b)
4. Move the (b) above the (a)
5. Change the (b) to a different effect (c)
6. Try tabbing up and down the stack using keyboard 

### Expected behavior

The order (top to bottom) is:
1. Realtime Effects header
2. Effect (c)
3. Effect (a)
4. Add effect button

### Actual behavior

The order (top to bottom) is:
1. Realtime Effects header
2. Effect (a)
3. Effect (c)
4. Add effect button

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
