### ISSUE TITLE
MIDI playback ignores Note Track offset

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6426]
### Bug description

Audacity ignores the start position of a Note Track

### Steps to reproduce

1. Configure Audacity and your system for MIDI playback.
2. Import a MIDI track
3. Drag the imported track so that it starts at around 10 seconds
4. Ensure that the cursor is at time = 0.0
5. Play

### Expected behavior

About 10 seconds of silence, and then the track to play.

### Actual behavior

The track starts playing immediately (though very glitchy, but that is a different issue).

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by petersampsonaudacity** [comment]
This is probably a special case or:

 MIDI playback starts from beginning regardless of cursor position #2359

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
