### ISSUE TITLE
Clicking again the "Presets & Settings" button in an effect dialog won't close the dropdown menu (Windows)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6470]
### Steps to reproduce

1. Open up any effect's dialog either from the realtime effects panel or from the main Effect/Generate menu
2. Click "Presets & Settings"
3. Observe: the dropdown menu expands
4. Click "Presets & Settings" again

### Expected behavior

The dropdown menu gets closed

### Actual behavior

The dropdown menu remains open

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows 10 & 11

### Additional context

This goes all the way back to at least 2.4

**Comment by petersampsonaudacity** [comment]
In fact it dates back to 2.1.1 when presets for effects were first introduced - but notice that back then (and indeed in 2.4.2 even) the presets were invoked with a **Manage**  button rather than a **Presets & Settings** button:
![image](https://github.com/audacity/audacity/assets/50205984/a0aa71e0-1f64-434e-906d-e7b70dcb762d)

And note that a second click on the **Manage** button never did close the dropdown presets menu.

----------------------------------------------------------------------------------

However, having said that as a user I do not really expect a second press on **Manage** or **Presets&Settings** to close the menu.

So for me the UI is working properly in this regard and I really don't think this is a bug (or design flaw) to be corrected.

**Comment by dozzzzer** [comment]
>  I really don't think this is a bug (or design flaw) to be corrected

It definitely should be corrected one way or another, simply for the sake of consistency across platforms. Currently, both on macOS and Linux, clicking again the Presets & Settings _does_ close the menu.

**Comment by LWinterberg** [comment]
Note that we don't need consistency across platforms, but consistency within platforms. This means stuff like https://github.com/audacity/audacity/issues/5963 is something we should do to get in line with the host OS (mac: Cancel/OK, windows: OK/Cancel), rather than getting the buttons to be in the same order across all OSes.

As for consistency within Audacity on Windows: 
* Clicking again on true dropdowns (like the one in the time signature) closes them
* Clicking again on the fake dropdown we use for the snapping thing closes it. 
* Clicking again on the NumericTextControl... is actually impossible as the options overlap the control.
* Clicking again on the Audio Setup button reopens it.
* Clicking again on the timeline gear reopens it.
* Clicking again on the Preferenes > Shortcuts > Defaults button reopens it (though the context menu tends to overlay).

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
