### ISSUE TITLE
New Limiter clips transients

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6482]
### Bug description

Rather than _compressing_ transients, the new limiter _clips_ them.

### Steps to reproduce

Apply the new limiter, with default settings, to audio that has a suddenly high peak, where the preceding audio is below -5dB (the limiter threshold)

### Expected behavior

The peak will be compressed as shown in the third track below.

![new-limiter vs old](https://github.com/audacity/audacity/assets/11681097/24e85791-6a62-4af0-a6a9-38ecad518e84)

### Actual behavior

The initial peak is  clipped, as shown in the second track below.

![new-limiter vs old](https://github.com/audacity/audacity/assets/11681097/24e85791-6a62-4af0-a6a9-38ecad518e84)

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Although there is  measurable distortion caused by the new limiter effect, the clipping described in this issue can me mitigated by setting "Lookahead" greater than zero.  This issue could be largely resolved by simply setting a lower bound to "Lookahead" of 1ms.

**Comment by SteveDaulton** [comment]
In this screenshot, both tracks have been processed with the new Limiter effect.

The upper track used default settings.
The lower track had the same settings except for Lookahead which was set to 1ms.

![1ms](https://github.com/audacity/audacity/assets/11681097/000fa891-ad07-441f-be36-76e757a410b8)

**Comment by saintmatthieu** [comment]
As of now I don't see what qualifies this as a bug. In the "Nyquist Limiter" track, yes, there doesn't seem like there is distortion, but the waveform doesn't look amplified either. You can see that the "New Limiter" track has been amplified, seemingly by the 4dB increase promised by the settings (-5dB threshold, -1dB make-up gain target).
I do not oppose to setting the default look-ahead to 1ms, but I wouldn't set this as lower bound either. Look-ahead has side effects that may or may not be desirable - see [this comment](https://github.com/audacity/audacity/issues/6339#issuecomment-2127776500).

**Comment by LWinterberg** [comment]
I'd agree that a default of 1ms for the lookahead would be nice but that it doesn't need to be a lower bound.

**Comment by SteveDaulton** [comment]
I think the default setting is the more important part of this issue, as clipping is not usually expected when using a limiter (avoiding clipping is a primary use for limiters).

If the effect is clearly documented as a "lookahead limiter", then there should be no surprise if the lookahead must be > 0. I can't think of many practical use cases where it is advantageous to have lookahead (or release time) == 0, but I agree that technically "hard clipping" can be considered to be a form of limiting.

Rather than the effect supporting hard clipping, I would have preferred the effect to support "Hold". The real-world benefit of "hold" is that it can be used to avoid _fluttering_ when applied to low frequencies with fast attack and release. Of course I recognise that there are many different limiters, and deciding on the features and character of a new limiter is a job for the design team. It's great to see a real-time limiter in Audacity.

**Comment by saintmatthieu** [comment]
> Rather than the effect supporting hard clipping, I would have preferred the effect to support "Hold".

@SteveDaulton I saw somewhere following the links of [this comment](https://github.com/audacity/audacity/issues/6305#issuecomment-2078345512) that the sound-gambit limiter has such a feature. IIRC, the rectified input is also low-passed, then the maximum is taken of both low-passed and fullband, and the fluttering you mention is then indeed reduced. (I think the 100Hz burst in [these pictures](https://kokkinizita.linuxaudio.org/linuxaudio/zita-dpl1-doc/quickguide.html) is intended to demonstrate this.)

I don't think this would be too hard to add, but I wonder how often this would actually kick in: one would need low-frequency components to be above the threshold in a sustained way, meanwhile a limiter is more to deal with transient sounds.

There are other features I would prioritize before because I think they'd be useful more often, such as channel de-linking, or maybe true-peak limiting.

What do you think ?
