### ISSUE TITLE
"Issue opening record device, Code of Issue -9999. issue -9999 Unanticipated host error"

### ISSUE THREAD

**Issue by kalinushkin** [audacity/audacity#663]
**Describe the bug**
Then u change an ears with microphone to just ears( without microphone) *and u still not have either input devices - system warn you a text that use in the title.  

I start audacity with my ears audiotechnica ATH-SR30BT with microphone, after that, then audacity was open i change  my ears on sennheiser HDR 180 without micro and back to Audacity. 

So i get an error modal window 
 
**To Reproduce**
1. Go to 'Audacity'
2. Change one of your input devices (i think - this is problem) to device without an input, only output(like usual ears)  
3. Go back to 'Audacity'

**Expected behavior**
A system warn you what "You have no input devices now"

**Screenshots**

![изображение](https://user-images.githubusercontent.com/8788849/92506575-518ed300-f20e-11ea-8f13-14cfa9357bec.png)

**Additional information (please complete the following information):**
 - OS: [Windows 10]
 - Version [Audacity 2.4.2]
 - (if relevant) Sound Device [Windows HDAD]

**Additional context**

**Comment by petersampsonaudacity** [comment]
Audacity does not expect you to change you input devices (unplug one and plug in a different one) while it active, or even while it is just open and inactive.   In particular Audacity does not dynamically re-scan periodically for changed devices (you can do this manaully by using Transport > Rescan Audio Devices.

Yes the message could be clearer as to what the issue is - but that message IIRC comes from Portaudio and not Audacity.

It is explained clearly in the Audacity Manual on this page:
https://manual.audacityteam.org/man/error_opening_sound_device.html
where it says at the bottom of the page:

-9999 Unanticipated host error: this means means "something is wrong". And appears to most often be due to either:
    A lost connection to a USB audio device.
    Recent Windows / Mac update requiring that user gives permission for Audacity to access the microphone.
