### ISSUE TITLE
Playback speed display on top of already open playback editing box is annoying

### ISSUE THREAD

**Issue by nalin243** [audacity/audacity#6704]
### Your idea

No need to have the playback value showing box pop up if the user has double clicked on the playback slider and already has the playback speed box open. 

### Problem to be solved

When we double click on the playback slider a small box opens that allows us to manually input the playback value. On moving the slider in that box another box opens up on top of the already open box showing us the live playback changes which seems a little annoying and redundant. 

### Additional context

[Screencast_20240617_162941.webm](https://github.com/audacity/audacity/assets/29351098/20e8809d-b847-4859-8d08-df6ae87364e2)

**Comment by SteveDaulton** [comment]
> When we double click on the playback slider

Are you referring to the [Play at Speed](https://manual.audacityteam.org/man/play_at_speed_toolbar.html) slider?
If so, that is so that you can set the playback  speed.

**Comment by nalin243** [comment]
@SteveDaulton Yes that is what I was talking about. Did you watch the attached video? I am talking about the additional small box that shows up on top of the already open playback speed editor. We can already see the playback speed changing in the text box, what is the point of another box showing the same thing appearing on top of it?

**Comment by LWinterberg** [comment]
What's happening here is that the tooltip is getting its own window for non-modal dialogs. This appears to be a linux-specific bug, or perhaps even a DE/WM-specific bug.

**Comment by SteveDaulton** [comment]
I don't think it's a  bug Leo. I believe it is an accessibility feature.

Sighted users can drag the slider to the required speed, and the speed is indicated in the tooltip.

Screen reader users enter a double click on the slider widget, that opens a dialog window (as shown in [nalin243](https://github.com/nalin243)'s video), so that they can enter the required playback speed.

**Comment by LWinterberg** [comment]
The tooltip is supposed to look like this: 
![image](https://github.com/audacity/audacity/assets/87814144/13957a25-c0cc-4349-b2b4-8cb1e20c98ea)

It's not supposed to have a separate window titled <2> as shown in OP: 

![image](https://github.com/audacity/audacity/assets/87814144/4e4ea2c7-ac67-4856-869b-fe7a584f5043)

**Comment by SteveDaulton** [comment]
> It's not supposed to have a separate window titled <2> as shown in OP:

Yes, that is a bug. I mistakenly thought that nalin243 was complaining about the pop-up window on double-click.
FWIW, it looks like this on my machine (Ubuntu + XFCE):

![Screenshot_2024-06-19_15-45-35](https://github.com/audacity/audacity/assets/11681097/bc6e887d-8186-49c6-9800-c696f1a04cd8)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
