### ISSUE TITLE
End of clip is sometimes drawn incorrectly

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6709]
### Bug description

This only happens a certain zoom levels.

### Steps to reproduce

1. Create an audio clip.
2. Press Ctrl + F to  fit to width.

If this doesn't produce the problem, try viewing the end of the clip at different zoom levels.

### Expected behavior

End of clip is always drawn correctly

### Actual behavior

![image](https://github.com/audacity/audacity/assets/11887021/47702e5e-dc11-4130-99d5-c9ddc326a1df)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
