### ISSUE TITLE
Audacity crashes when scrolling with mouse wheel on POP!_OS

### ISSUE THREAD

**Issue by CleiAlb** [audacity/audacity#6828]
### Bug description

Audacity crashes unexpectedly when I use the scroll wheel on my mouse. This happens consistently every time I scroll within a project.

### Steps to reproduce

1. Open Audacity.
2. Open any project or create a new one.
3. Use the scroll wheel on the mouse to scroll up or down.
4. Audacity crashes.

### Expected behavior

Audacity should not crash when using the scroll wheel.

### Actual behavior

[Gravação de tela de 05-07-2024 11:37:58.webm](https://github.com/audacity/audacity/assets/174813183/fcac450e-3160-4755-8c58-2f8bbfe6c1ef)
- OS: POP!_OS 22.04 LTS
 - Audacity version: 3.5.1
 - Mouse model: Logitech M150
 - Installation method: Flatpak

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

I have tried updating the OS, drivers, and Audacity. I also tried running Audacity in safe mode, but the issue persists.

**Comment by dozzzzer** [comment]
@CleiAlb could you try to reproduce it using the Appimage build?

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
