### ISSUE TITLE
Make it possible to position envelope control points exactly

### ISSUE THREAD

**Issue by rulatir** [audacity/audacity#689]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when... I try to add an envelope control point without also dragging the envelope up or down by a small value. 

**Describe the solution you'd like**

I want the new control point to ONLY be inserted, without affecting the envelope in any way if the segment of the envelope I am adding the point to is flat. I understand that splitting an exponential fade section with an extra control point may not be feasible without affecting the envelope, but in that case I would still expect the new point to be added with the exact gain value computed from pre-existing envelope at the time offset where the point is being added.

**Describe alternatives you've considered**

There are no viable alternatives. Zooming in to gain a little more precision is deemed insufficient. I need to preserve relative dynamics exactly in those fragments that I am not intentionally changing.

**Comment by SteveDaulton** [comment]
I think there's an underlying issue that Audacity's envelopes are too fiddly. I think this could be greatly improved by providing an option for linear envelopes rather than exponential envelopes. You may find that envelopes are a bit easier to use if you switch between normal "Waveform" view and "Waveform (dB)" (See: https://manual.audacityteam.org/man/audio_tracks.html#scale). I find it helpful to set the start and end levels in the normal "Waveform" view, then switch to "Waveform (dB)" if I need to tweak the envelope between those points.

> I want the new control point to ONLY be inserted, without affecting the envelope in any way if the segment of the envelope I am adding the point to is flat.
You could make a Nyquist plug-in that allows you to add envelope points with keyboard entry for the gain value. If you are not sure how to do that, feel free to ask on the Audacity help forum: https://forum.audacityteam.org/viewforum.php?f=42

**Comment by rulatir** [comment]
> You could make a Nyquist plug-in that allows you to add envelope points with keyboard entry for the gain value.

"Learn a new programming language and its library, then write a program that does what you want" is the wrong response to a user asking that you fix your UI so that it won't add random error to the value it is supposed to control.

**Comment by LWinterberg** [comment]
Envelope controls are scheduled for a redesign
