### ISSUE TITLE
Loudness meter/analyzer

### ISSUE THREAD

**Issue by RiseT** [audacity/audacity#692]
I'll make this very short (and potentially sweet):

Since Audacity now has loudness normalization, wouldn't it make sense to integrate a loudness meter/analyzer?

Feel free to close this if it doesn't make any sense to you.

**Comment by shikhindahikar** [comment]
I believe the playback level indicator in Audacity already does that job.

**Comment by SteveDaulton** [comment]
The playback meters already have an option to show RMS level (See: https://manual.audacityteam.org/man/meter_toolbar.html#recording)
It is not possible for the meters to show the same measurement as Loudness Normalization because that measures the average loudness over the entire duration of the selection.
It would be possible for the meters to show the "short term" or "momentary" loudness measurement, or any number of other measurements and scales, should someone choose to develop new meters.

**Comment by reedacartwright** [comment]
I would love this feature either as a meter showing short term, momentrary, and integrated loudness (similar to Shotcut), or the ability to select a section and output its integrated loudness.
