### ISSUE TITLE
Please create Appimage

### ISSUE THREAD

**Issue by hinkali** [audacity/audacity#695]
Please create Appimage? once every six months or a year at least

**Comment by ainola** [comment]
Perhaps this is not helpful but it's worth noting: Audacity has a [flatpak](https://www.flathub.org/apps/details/org.audacityteam.Audacity) available for your installation.

**Comment by SteveDaulton** [comment]
On the [Audacity forum ](https://forum.audacityteam.org) we have received multiple reports of problems with the flatpak and Snap builds. At this time I would not recommend either.

I agree that an official Appimage would be good, but we currently do not have the developer resources to produce and test. If anyone would like to help with this, please get in touch via the [developer's mailing list](https://sourceforge.net/projects/audacity/lists/audacity-devel).

**Comment by joe733** [comment]
Related #172

**Comment by probonopd** [comment]
> If anyone would like to help with this, please get in touch via the developer's mailing list.

Hello @SteveDaulton, I had [tried](https://sourceforge.net/p/audacity/mailman/audacity-devel/thread/CAADtZXBFD=B2MjHwBA-LMiXmffQvMknMenfW1zJfwU6KYJq_uQ@mail.gmail.com/?page=1) this back in 2017 but it seemed that the project did not want to publish an AppImage at that time. I am happy to help if someone from the Audacity project wants to pick this topic up again.

**Comment by SteveDaulton** [comment]
Hello @probonopd , I recently posted some issues on your Audacity AppImage branch because it was the most promising AppImage fork that I could find. I had hoped that my comments would help others to see what else still needs to be done to produce a fully functional Audacity AppImage. Unfortunately my comments appear to have disappeared.

I'm hoping that there will eventually be an official AppImage, though due to the demands of end user support, testing of the official branch,  plus my own development work, I don't have much free time left to work on an AppImage myself.

**Comment by probonopd** [comment]
Hi @SteveDaulton thanks for your interest in getting an AppImage published. Your issues are still [there](https://github.com/probonopd/audacity/issues?q=is%3Aissue+author%3ASteveDaulton) for reference however I did archive that repository. It was my working repository back when I tried to get the Audacity project to produce and support official AppImages, but since this never materialized I am no longer working on it.

Should you or anyone from the Audacity team have real interest in producing and supporting official AppImages as part of the Audacity build pipeline, then I'd be more than happy to help.
