### ISSUE TITLE
Audacity creates insanely large file sizes

### ISSUE THREAD

**Issue by weluvgoatz** [audacity/audacity#7103]
### Your idea

My idea is to reduce the filesize of the aup3 file, by some method.

### Problem to be solved

I have an aup3 file that is around 2 minutes in length, but it is an enormous 7GB in size for some reason.  I've tried closing the project, and it still retains that same size.  

### Additional context

If there is already a duplicate issue, please close this one!  I just want this to be known.

**Comment by petersampsonaudacity** [comment]
@weluvgoatz 

This is because Audacity now has "**smart clips**" which means that when you delete data it doesn't actually get deleted, it just gets hidden in case you want or need to restore it later,  There is no way within Audacity to purge this hidden data bloat.

**_BUT_** there is a workaround 
1. select the project - Ctrl-A (Cmd+A on Mac)
2. Copy the selection - Ctrl-C (Cmd+C on Mac)
3.  create a new project
4. Paste into the new project - Ctrl+V (Cmd+v on Mac)
5. choose the option that says "**Selected Audio only**"
![image](https://github.com/user-attachments/assets/d1da0577-d2e0-4638-9367-d02df2a8aea5)
6. Save this new project
7. delete the old bloated project

==================================================

The screenshot is from a test example I has.  A two hour stereo project 2.3 GB - after following the steps above afte removing all but two and a half minutes of the audio my new AUP3 file was only 265 MB.

**Comment by petersampsonaudacity** [comment]
@weluvgoatz 

See this existing logged issue:

 **Allow deletion of unused smart clip data** #4715

**Comment by LWinterberg** [comment]
closing in favor of #4715
