### ISSUE TITLE
Welcome to the 21st Century (macOS Installer Package and App Store)

### ISSUE THREAD

**Issue by implicitall** [audacity/audacity#7235]
The drag and drop macOS .dmg package requires someone to click a security warning. No matter what your opinion is of your own importance, you will replace the .dmg package with an installer. For a while, you will most likely continue to believe that macOS was somehow better "back in the day", but then eventually read this: https://developer.apple.com/documentation/xcode/packaging-mac-software-for-distribution and create an appropriate installer package or an App Store app like everyone else in the 21st century. Contrary to whatever you think of yourselves, it actually is some sort of delusional cognitive dissonance that your team has about Apple Computer that you sadly really believe you can hold on to your nostalgia of dragging an app to the Applications folder forever. Instead of simply ending up irrelevant to audio professionals by not adopting the latest Apple notarization best practices, replace your macOS packages and please don't reply because I don't care about your supposed professional opinion.

**Comment by LWinterberg** [comment]
A) if you think this language is gaining you any favor, it's not. The only delusional person here is you.
B) our release dmgs are signed and notarized, alphas intentionally are not. 
C) changing to a pkg is perhaps desirable but ultimately extremely low priority, similar to switching the exe installer to msi on windows. There's just nobody out there who gets confused or intimidated by the older approach, as it's hardly rare. Even Google Chrome is distributed as a dmg. I also don't see any indication on the apple site you linked indicating dmgs are being deprecated or advised against otherwise.

**Comment by shoogle** [comment]
Also, it's [not even allowed](https://apple.stackexchange.com/a/59495) because Apple's T&Cs are incompatible with the GPL, so certainly not a case of "self-importance" or "can't be bothered".

We could relicense our code to enable distribution via the App Store, but we can't relicense the third-party GPL code that's in Audacity and its libraries.
