### ISSUE TITLE
When "Use half-wave display when collapsed" is set on, then a track that was set to half-wave will revert to full wave after collapse and expand

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#7347]
### Bug description
When **Use half-wave display when collapsed** is set on in **Tracks,* preferences* then a track that was set to half-wave will revert to full wave after using Collapse followed by Expand from the track's Vertical Scale dropdown context menu, thereby over-riding the users original setting for half-wave display,

This does _**NOT**_ appear to be a regression - the same is true in Audacity back to and including 2.4.2

### Steps to reproduce
1. set the option to **Use half-wave display when collapsed**
2. get some audio 
3. from the Vertical Scale context menu select **Half Wave**
4. Observe: tracks is in half-wave view mode
5. Collapse the track - use chevron in TCP
6. Observe: track remains in half-wave view mode
7. Expand the track - use chevron in TCP
8. Observe: the track has reverted to full-wave display mode - **_not_** what the user set at Step 3

Note carefully that if you omit step 1 the waveform properly remains **(as the user set it)** in half-wave view mode throughout.

### Expected behavior
A track that has been set do half-wave display should remain in half-wave display until the user elects to reset it to full-wave display

### Actual behavior
See STRs

### Audacity Version
3.6.3, 3.6/4 Beta and 3.7.0 alpha - all versions at least back to and including 2.4.2

### Operating system
Windows 10

### Additional context
See this related Enhancement Request:

 **Ability to select HalfWave Mode View as default** #7261

**Comment by petersampsonaudacity** [comment]
Note too that the app is inconsistent in its terminology regarding half-wave display.

### In Tracks preferences it is lower case and hyphenated as **half-wave**
![image](https://github.com/user-attachments/assets/bce513b7-afda-4688-ba83-5cd553c6d172)

### In the Vertical Scale context menu it is capitalized and non-hyphenated as **Half Wave**
![image](https://github.com/user-attachments/assets/526b8302-1c7c-4d81-85e3-2db758be9c0f)

**Comment by Kurtsley** [comment]
Line 145 will always set the zoom to full when maximized regardless of previous zoom level.
https://github.com/audacity/audacity/blob/0ec33a7c72e729694106729d12fac7b925a4868c/src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp#L132-L146

**Comment by skynetradio** [comment]
> Line 145 will always set the zoom to full when maximized regardless of previous zoom level.
> 
> https://github.com/audacity/audacity/blob/0ec33a7c72e729694106729d12fac7b925a4868c/src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp#L132-L146

Hello Kurtsley

Have I understood correctly that I open the WaveformView.cpp file and enter your data here and save it again.

cache.SetDisplayBounds( -0.01f, 1.0f );
At least then I would have a workaround until Audacity provides an update.

Because always selecting halfwave mode after recording or opening a song, as @petersampsonaudacity showed in the screenshot, is extremely unnecessary and unlogical.

Regards Seven

**Comment by Kurtsley** [comment]
Yes, you could change that line and build your own version to work with while waiting for the fix. Unfortunately it isn't as simple as saving the file, instructions to build can be found [here](https://github.com/audacity/audacity/blob/master/BUILDING.md) (apologies if you already knew this.)

Better yet, change it to this:
```
   if (wt &&  bHalfWave) {
      auto &cache = WaveformScale::Get(*wt);
      // Zoom to show fractionally more than the top half of the wave.
      cache.SetDisplayBounds( -0.01f, 1.0f );
   }
```
This doesn't bother checking if it is minimized, it just sets it to half-wave.

This change seems to work with both newly created tracks and loaded tracks from a previous project. The only issue is it doesn't change the zoom level on tracks immediately when the preference checkbox is hit. It takes a action like minimizing and maximizing the track to work.

I suspect the default vertical zoom level will need to be changed based on the existing collapseToHalfWave preference (could be renamed). This will probably be a quick fix for someone who has worked in this codebase for a while, but sadly I just started poking around a couple days ago.

**Comment by skynetradio** [comment]
Yes, great, then I'll try that today. Thanks for the current workaround @Kurtsley.

**Comment by skynetradio** [comment]
Phew, I thought that would be much easier.
I'll have to read up on it first, because unfortunately I have no idea whatsoever about programming.
Can you see the changes in real time in Visual Studio or do you have to create a whole build again and again?

Greetings, Sky.

**Comment by Kurtsley** [comment]
The first build will take the longest. After that, it only builds the files that are associated with the changes you make. When you have what you want, you can make a shortcut to your newly built audacity.exe file within your build folder. It should be in audacity-build/Release/audacity.exe. This assumes you build a release version to use (which is a good idea.) Your settings should be the same since they are located in another location on Windows.

This is the process I would use:
- Build a debug version of audacity
- Make any changes you want
- Build again with these changes and see if it works like you expect
- If you are satisfied, build a release version
- Make a shortcut to this new audacity.exe file and use it until this gets fixed

*OR*  you could wait until the next version. I think it would be worth messing around in Visual Studio, you may even be able to fix an existing bug!

**Comment by skynetradio** [comment]
Thanks for your instructions.
I'll take a closer look at it.
Greetings skynetradio

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Comment by skynetradio** [comment]
> Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

Hello LWinterberg

That's wonderful to hear, thanks for the information.
I just hope it doesn't get lost.
When is Audacity 4.0 expected to be released?

Kind regards, skynetradio
