### ISSUE TITLE
Joining clips in non-default wave color changes the wave color to default

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#7459]
### Bug description
If you join two clips that are in a non-default wave color, after the join the waveform color is changed to the default Instrument-1.

However examining the TCP dropdown context menu shows tah Audacity thinks the track is still in the original non-default colorway.

Testing shows that this is a regression on 3.5.1, introduced in 3.6.0

### Steps to reproduce
1. Generate a 30 second chirp
2. Split the clip at 15 seconds
3. In the TCP context menu change the clip colorway to Instrument-2, Instrument-3 or Instrument-4
4. Select around the shared clip boundary
5. Ctrl+J to join the two clips
6. **Observe: the clip reverts to default Instrument-1**
7. Click on Wave Color in the TCP context menu
8. **Observe:  the setting is as made at step 3**

### Expected behavior
The joined clips should retain the user's setting for Wave Color

### Actual behavior
The joined clips revert to Instrument-1 colorway 

### Audacity Version
3.6.4 and latest 3.7.0 alpha test build - all versions from 3.6.0 onwards

### Operating system
Windows 10 - but assume all OS

### Additional context
Originally reported on the Forum:

https://forum.audacityteam.org/t/wave-color-resets-on-clip-joining/119527

**Comment by petersampsonaudacity** [comment]
See also #5465

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
