### ISSUE TITLE
Minimized Stereo and Mono tracks differ

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7562]
### Bug description

If the User minimizes a Stereo and a Mono track, the amplitude of the track is shown differently. 

![image](https://github.com/user-attachments/assets/a203d454-f29b-4052-9221-8bf66b372ea0)

### Steps to reproduce

1. Launch Audacity
2. Create a Mono Track
3. Create a Stereo Track
4. Generate or paste some audio into both tracks
5. Minimize both tracks
6. Observe result

### Expected behavior

The minimized view for Stereo and Mono tracks should be the same. 

### Actual behavior

The minimzed view differs. 

### Audacity Version

Audacity 3.7.x

### Operating system

Windows

### Additional context

This is not a regression, but a new issue.

**Comment by LWinterberg** [comment]
Uh, what do you mean by differ? one of them shows mono, the other stereo. Stereo necessarily has half the space

**Comment by skynetradio** [comment]
> Uh, what do you mean by differ? one of them shows mono, the other stereo. Stereo necessarily has half the space

Hi
I've thought of something on this topic that would fit well with mine.
https://github.com/audacity/audacity/issues/7261

It would be nice to have the option to display a stereo recording as a mono halfwave anyway. (Force)
(maybe as a new display option in the new Audacity 4.0)

The reason is as follows: displaying two audio tracks (stereo) is not important for editing in the moderation area (radio studio) and would only take up unnecessary space.

Because at the moment I have to record mono separately to have this view. (As you said, my display problem will be solved #LWinterberg with version 4.0)

Greetings skynetradio
