### ISSUE TITLE
When performing a non-consecutive audio data copying and pasting, it's pasted consecutively

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7682]
### Steps to reproduce

1. Have four audio tracks
2. Select and copy audio data on tracks 1, 3 and 4
3. Select tracks 1, 3 and 4
4. Paste

### Expected behavior

The copied audio data is pasted onto tracks 1, 3 and 4.

### Actual behavior

The copied audio data is pasted onto tracks 1, 2 and 3:

https://github.com/user-attachments/assets/0c51f80c-3e87-4d74-b0c2-7fcf92e35e53

### Audacity Version

Audacity 4 alpha

### Operating system

Windows, macOS, Linux

**Comment by LWinterberg** [comment]
There was some talk about simplifying the rules to just paste consecutively from the first selected track, so this may be intentional. @DilsonsPickles @Tantacrul ?

**Comment by Tantacrul** [comment]
OK, with this, I have two thoughts:

- If Audacity 3 provides the behaviour @dozzzzer is expecting, then we should match it
- Otherwise, if the expected result is that we paste into the three selected tracks, I think it's too edge-case-y to spend time on.

I do recall we agreed on some basic rule where we paste from the upper-most selected track in all cases. This satisfies that rule.

@dozzzzer am I missing anything?

**Comment by DilsonsPickles** [comment]
In AU3 we can observe that pasting from a non-consecutive track selection does respect the non-consecutive spacing on paste. I think @dozzzzer is correct here that this is a change in behaviour.

**Comment by Tantacrul** [comment]
OK, cool

**Comment by chinakov** [comment]
Tested, thanks!
