### ISSUE TITLE
Scripting not working under GBK charset.

### ISSUE THREAD

**Issue by imbazhang** [audacity/audacity#775]
**Describe the bug**
I'm a user from China. To support Chinese in the computer system, we use the GBK charset. When running the script _docimages_all.py_, the process terminated with following information:

```
Traceback (most recent call last):
  File "docimages_all.py", line 31, in <module>
    exec( inner( 'tracks' ) )
  File "<string>", line 90, in <module>
  File "<string>", line 16, in track_image1and8
  File "<string>", line 109, in capture
  File "<string>", line 71, in do
  File "<string>", line 66, in doCommand
  File "<string>", line 58, in getResponse
UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 51: illegal multibyte sequence
```

This bug related to the unique encode style of the GBK charset.

**To Reproduce**
1. enable 'mod-script-pipe'
2. switch language to '简体中文' or 'Chinese(simplified)'
3. run any python script

Since this bug may be difficult to understand for those whose primary language is not Chinese, I will try to fix it. Further information will be updated in this issue and discord channel.

**Comment by petersampsonaudacity** [comment]
There has been a known Windows issue  for Japanese, Korean and Chines with a recent Windows update.  I believe that microsoft may have issued a further update to address this.

**Comment by JamesCrook** [comment]
But the scripting too has/will-have its own issues.
Once past the issue @imbazhang reports, I'd expect labels with surrogate pairs in them to be a particular problem.

This would be very welcome as part of a Google summer of code, which I see you are taking part in.

**Comment by rbdannenberg** [comment]
After seeing Unicode issues in Audacity and comments on Nyquist's lack 
of Unicode, I decided to "bite the bullet" in another language project 
and support Unicode. One thing I've learned is C and C++ probably 
adopted wide characters prematurely, and many more recent languages are 
using UTF-8 internally. Some general conclusions I've come to:

  * general text processing, if you just want to read/store/write text
    without looking at it, is simpler/faster without any conversion, and
    works pretty much like ASCII if you are really concerned about
    performance.
  * to compare strings, text must be "normalized" so that ligatures and
    some other interesting compound characters have a canonical
    representations. Normalized strings have to be renormalized if you
    concatenate or append them -- it's ugly.
  * Strings used as identifiers are even messier because you can have
    very similar-looking strings that compare as unequal (the surrogate
    pairs James mentions). A different form of normalization, e.g. NFKC,
    is recommended to map similar-looking strings to a canonical form to
    avoid security loopholes like creating a user-ID that looks like
    someone else, and maybe just basic sanity for variable and field
    names. You could do this for everything, but it does not preserve
    typographic details, so it seems inevitable that you have to work
    with at least 2 different kinds of normalization.

This may be old hat to everyone, but I'd be happy to share what I know 
and the code I found for UTF-8.

-Roger

**Comment by JamesCrook** [comment]
Roger, just to note that under Windows the wxString we use right now is UTF-16.  The surrogate pairs there are pairs of 2 byte characters that together represent one 20 bit code point.  Windows itself uses UTF-16.  We can I believe switch wxWidgets to use UTF-8 even on Windows, and that seems to me worth doing to simplify our code and keep it consistent across platforms.  Possibly worth doing at the same time as moving to 64 bit for Windows.
I learned recently that I can tell directly from the current character whether I am on the start of a code point.  I do not need to parse from the start of string.

**Comment by rbdannenberg** [comment]
I misunderstood "surrogate pair" thinking it was a codepoint pair such 
as a letter plus an accent.

My take on UTF-16 is unless you restrict yourself to character sets with 
16-bit code points (we don't), you get all the pain of UTF-8 and up to 
double the memory space.

Since UTF-16 is pretty much just windows, I think it's a good idea to 
use UTF-8. For Audacity, which is not text-intensive, UTF-32 isn't 
crazy, but you still should deal with normalization and input/output to 
UTF-8, so I'm not sure it helps much.

Yes, the UTF-8 encoding is really ingenious. Unicode is still a pain, 
but maybe if I didn't "grow up" with ASCII, it would be routine pain 
just like memory management, stack overflow, case-sensitivity, and so 
many other gotchas.

-Roger

**Comment by petersampsonaudacity** [comment]
> Since this bug may be difficult to understand for those whose primary language is not Chinese, I will try to fix it. 
>Further information will be updated in this issue and discord channel.

I have also created an entry for this in our Bugzilla bugtracker:
https://bugzilla.audacityteam.org/show_bug.cgi?id=2790
Bug 2790 - Scripting not working under GBK charset

But as **imbazhang** aims to try to fix this themselves, I will also leave this GitHub Issue open

**Comment by petersampsonaudacity** [comment]
@imbazhang have you manged to fix this ?
