### ISSUE TITLE
filter curve EQ - result with less energy is displayed with more amplitude 

### ISSUE THREAD

**Issue by jserquera** [audacity/audacity#7864]
### Steps to reproduce

1. create 15 min of White noise, at 0,8 of amplitude
2. open curve filter EQ and design a high-pass with cut-frequency at 4000 Hz. Below that freq, and very abruptly, we attenuate at maximum (-120 dB)
3. The resulting waveform does not display with less amplitude as expected

### Expected behavior

waveform with lower amplitude

### Actual behavior

already said.

Also, as we zoom-in, the amplitude changes to a bit lower

### Audacity Version

Audacity 3.7.x

### Operating system

Windows

### Additional context

Audacity 3.6.2

**Comment by LWinterberg** [comment]
![image](https://github.com/user-attachments/assets/3e256e37-6c2c-4939-9a98-7f60f960d0ca)

yup, sure does. The same is true for highpass filters and any other filter, really. 

And this is expected: The amplitude of the wave *is not* the energy of it. We're working in a system where you have plenty  of interference, and while taking away some frequencies lowers the energy, the remaining frequencies might still interfere just as strongly as before in some spots. This is easier to see when we use a square wave instead of noise:

![image](https://github.com/user-attachments/assets/d07200b2-ebd0-4a37-8faf-30801ede12f2)

Here, the energy has noticably decreased, being almost entirely confined into little clicks, but the peaks are still just as high as before. And this really is what the waveform is showing at higher-zoomed out levels: The highest peak it can find in a group of samples.

**Comment by jserquera** [comment]
Thanks
