### ISSUE TITLE
Effect on multiple clips messes up the clip selection

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#7885]
### Bug description

Effect on multiple clips messes up the clip selection

### Steps to reproduce

1. select multiple clips (shift+click)
2. apply an effect (e.g. fade in)

### Expected behavior

Effect is applied and clip selection remains intact.

### Actual behavior

Only one of the clips remains selected.

### Audacity Version

Audacity 4 alpha

### Operating system

Windows, macOS, Linux

### Additional context

`ClipsListModel::onSelectedClips` isn't implemented properly: will in fact only select one clip.
I suspect this to be the case because programmatically selecting several clips at once was never needed yet.
Discovered while developing and testing [effects on multiple clips](https://github.com/audacity/audacity/issues/7801).

**Comment by dozzzzer** [comment]
@saintmatthieu The issue is fixed for all the effects except for Amplify which cannot be applied to the multiple selected clips and throws an error:

<img width="500" alt="image" src="https://github.com/user-attachments/assets/47d07a43-6c00-43d6-9f6b-36b9c42ec23c" />

For that, I've created a separate ticket: https://github.com/audacity/audacity/issues/7942
