### ISSUE TITLE
Broken links on the audacity website

### ISSUE THREAD

**Issue by BeayemX** [audacity/audacity#792]
Sorry to use a github issue for this but I could not find a better way to contact you devs.

There are some broken links on the audacity website.
For one link I found the correct address. 
But for the donations-link I could not find the desired site.

**Donations**

Here
```
https://www.audacityteam.org/contact/advertising-and-monetization-opportunities/
```

it points to the non-existing link:

```
https://www.audacityteam.org/donate/
```

**Contacts**

On this website
```
https://www.audacityteam.org/about/credits/ 
```

there is a link in the second line to the following address that does not work:

```
http://audacityteam.org/contact/
```

It should probably link to this address:

```
https://www.audacityteam.org/contact/
```

**Comment by SteveDaulton** [comment]
Thanks for the report. This is being dealt with.

Generally the best way to contact us is via the Audacity forum as that is constantly monitored across multiple time zones.
https://forum.audacityteam.org

**Comment by Rajeta-Sarkar** [comment]
Hi @SteveDaulton I would like to work in this issue.
How can I start?

**Comment by SteveDaulton** [comment]
Thanks  for the offer.
I've already fixed some of the bad links. The remaining bad links are due to redirects not working correctly, and that requires root  access to the server. Only the system administrators have that access, so we're waiting for them.

If you notice any other broken links on the website, it would be very useful if you could report them here: https://forum.audacityteam.org/viewforum.php?f=32

Steve

**Comment by LWinterberg** [comment]
This appears to have been fixed
