### ISSUE TITLE
When editing an MP3 format file, deleting the selected range freezes.

### ISSUE THREAD

**Issue by ghost** [audacity/audacity#804]
**Describe the bug**
When editing an MP3 format file, deleting the selected range freezes.

**To Reproduce**
1.Import MP3 format files.
2.Deletes the selected range.
3.See error

**Expected behavior**
Software freezes

**Screenshots**
![image](https://user-images.githubusercontent.com/62015371/114358878-61a8cf80-9bae-11eb-8c28-b6a72fb020b2.png)

**Additional information:**
 - OS: Windows 10 20H2
 - Version: Audacity 3.0.0
 - Sound Device: Windows MME

**Comment by petersampsonaudacity** [comment]
Woks fine for me on W10 with 3.0.0 and the latest RC02 release candidate build I have for the upcoming 3.0.2

**Comment by petersampsonaudacity** [comment]
Since I can't reproduce this on my W10 PC or my Big Sur 11.2.3 Macbook Pro on 3.0.0, 3.0.2 and the latest alpha test build I have for 3.0.3
can you please provide more detailed steps to reproduce, in particular:
a) how you make the selection,
b) how you attempt to make the deletion ?

Please note that you Issue title is a little misleading as you are not actually editing an MP£ file - rather what happens when you Import it is that Audacity coverts it into its own internal 32-bit float format for working on.

So can I please also ask yo the repeat your deletion test with:
1) some audio that you Record.
2) some audio that you make with one of the generators in the Generate menu?

Thanks

**Comment by petersampsonaudacity** [comment]
In the lack of response from the OP and due to the fact that such deletions work fine on my W10 PC and my Macbook Pro with macOS 11.3.1 Big Sur I shall close this issue.
