### ISSUE TITLE
updating and devendoring dependencies

### ISSUE THREAD

**Issue by Be-ing** [audacity/audacity#853]
Currently, Audacity vendors (manually copies the code of) every dependency. This is widely [considered a bad practice](https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries) to be avoided as much as possible. It increases the work to maintain Audacity and exposes its users to security vulnerabilities, which has [in fact occurred for years](https://github.com/audacity/audacity/pull/835#issuecomment-835790791). It violates Linux distributions' packaging policies which makes it unusually difficult to package Audacity compared to other software. Additionally, Audacity has forked (modified the code of) many of these dependencies, including its biggest dependency, wxWidgets (#625), which amplifies the problem.

How do we move forward from here? As a first step, I suggest auditing every one of Audacity's dependencies and updating them to the newest compatible version before changing how dependencies are handled, then make a release which focuses on updating those dependencies. Considering the Audacity maintainers are [intent on introducing networking capabilities](https://github.com/audacity/audacity/pull/835#issuecomment-835880865) which will require an external library, I suggest as a second step to use the introduction of those external libraries as an opportunity to start introducing a better way of managing cross-platform dependencies.

I suggest using the [vcpkg](https://github.com/microsoft/vcpkg) package manager for Audacity's dependencies. It is cross platform with Windows, macOS, and Linux all supported. This makes it quite convenient for developers to maintain because they can work on vcpkg packaging from any OS and test builds locally, provided that the dependency's build system is cross platform (CMake or Meson). vcpkg is well maintained by Microsoft with a very strong contributor base, currently at 1202 contributors. Microsoft intends to [ship vcpkg in Visual Studio and VSCode](https://github.com/microsoft/vcpkg/wiki/Roadmap) soon which will make it easy for Windows developers to help maintain Audacity's dependencies.

@Holzhaus and I recently spent a month [setting up vcpkg for Mixxx's Windows dependencies](https://mixxx.org/news/2021-02-23-build-infrastructure-updates/). Audacity and Mixxx share many dependencies so many of Audacity's dependencies are already packaged in vcpkg. The notable exception is PortMidi, which has been unmaintained for many years. It builds with vcpkg on Windows, but not on macOS or Linux currently. PortMidi uses a very old CMake build system that I was unable to debug without a lot of effort. Do official Audacity builds use PortMidi or is it an old unmaintained feature? I would be glad to collaborate on resolving this to get PortMidi packaged for vcpkg on macOS and Linux, which I was already planning to work on for Mixxx 2.4. I suggest either Audacity or Mixxx fork PortMidi and host a new upstream repository. Then we could write a new build system for it with modern CMake, which would hopefully be easy to package with vcpkg on macOS, Linux, and Windows.

For our setup for Mixxx, we maintain a [fork](https://github.com/mixxxdj/vcpkg) of Microsoft's upstream vcpkg repository. Using [vcpkg's overlay feature](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md), we are able to easily vendor a few specific dependencies while keeping all other dependencies up to date easily. We use a [GitHub Actions workflow](https://github.com/mixxxdj/vcpkg/blob/2.3/.github/workflows/build.yml) to build all of Mixxx's dependencies. That uses `vcpkg archive` to package all the built dependencies in one big ZIP archive which is scp'ed to https://downloads.mixxx.org/dependencies/. This ZIP archive is [downloaded](https://github.com/mixxxdj/mixxx/blob/main/tools/windows_buildenv.bat#L45) and [cached](https://github.com/mixxxdj/mixxx/blob/main/.github/workflows/build.yml#L179) in the GitHub Actions workflow for the application code repository. I tried using [vcpkg's binary caching feature](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md) with Azure Artifacts. However, this only works if build environment for the application build is exactly the same as the dependency build, so Windows developers building locally would have to rebuild the entire dependency graph from scratch, which for Mixxx takes about 4 hours on GitHub Actions. Using the ZIP archive from `vcpkg archive` avoids this issue.

**Comment by Be-ing** [comment]
Initially, I suggest using vcpkg's overlay feature to package your vendored dependencies. However this should be done with the goal of upstreaming Audacity's changes as much as possible. Once upstream releases a new version with Audacity's changes and upstream vcpkg is updated, the package can be removed from Audacity's overlay. We can start with PortAudio: #840.

**Comment by SteveDaulton** [comment]
> As a first step, I suggest auditing every one of Audacity's dependencies and updating them to the newest compatible version

Do you mean that this is a task that YOU are going to start doing, or is it a task  that you expect someone else to start doing?

**Comment by Be-ing** [comment]
You are distributing software to millions of people. Please start taking security seriously.

**Comment by Be-ing** [comment]
I am happy to help Audacity but only if the maintainers are in agreement that this is needed and important. I expect that pull requests get at least an initial response quickly, as in within a few days at most. That does not mean I expect a thorough review of pull requests that quickly.

**Comment by Be-ing** [comment]
> But but... upstreaming changes is no fun!

I actually do think it is fun because it means less work in the long term.

**Comment by Paul-Licameli** [comment]
> See also #852 which appears to be a preliminary step in doing this.

Nice to hear from you again, Poke!  I remember your contributions to 2.2.0 in summer 2017, for MIDI playback.

I don't understand the bearing of my pull request on this issue.  I consider the matters of the present issue thread outside of my competence and I'm neutral on them all.

I'm just a C++ guy and I reason about source code.  What I have been up to, for years in Audacity, and continuing now, is the breaking-up of the monolithic tangle of compilation and linkage dependencies withing the Audacity executable, so that, perhaps, some reusable low-level libraries can be abstracted from it, and perhaps, some of the existing features can be spun off into optional extension modules, and the discovery of the interfaces and protocols necessary for that, might serve for the writing of new features by analogy as plug-ins, from the beginning.

**Comment by Pokechu22** [comment]
> I don't understand the bearing of my pull request on this issue

I assumed it was relevant based on this part of your pull request description:

> This will be a useful preliminary for later refactoring work to make separate
> libraries.

I assumed "separate libraries" meant separating libraries out from the main audacity tree, but it sounds like you instead meant splitting parts of the audacity codebase into libraries.  If so, my mistake, sorry!

**Comment by Paul-Licameli** [comment]
> > I remember your contributions to 2.2.0 in summer 2017, for MIDI playback.
> 
> Well I guess that answers my question about whether building with PortMidi is needed.

Be-ing, you don't know the whole story.

My work on untangling the monolith in Audacity will make it possible to segregate all of the dependencies on PortMidi into an optional, drop-in extension module.  A reduced Audacity, minus the MIDI track features, might be built; a shared library giving it back all the MIDI capabilities (import, export, display, playback) might be separately compiled, installed, dropped in, and enabled only if you want it.

Similar stories might be told about other third party library dependencies, such as SBSMS (only for a few time-stretching effects), and libraries that are used to import and export certain sound file formats.

Audacity's underexploited support for modules so far only extends to the scripting pipe https://manual.audacityteam.org/man/scripting.html which is what enables the cooperation of Audacity and Blender https://forum.audacityteam.org/viewtopic.php?f=21&t=116598&p=420427&hilit=blender#p419757

But modularization isn't the free magical result of having a module loader in the program.  Much other code must be re-organized and re-designed for it.

My very big experimental branch misc-modules (over 500 commits long) contains an accumulation of refactoring maneuvers, so that I can even strip out such things as all of label track support, or all of spectrogram view.

That work ran far ahead of my ability to carefully test, review, and merge it, but I am expecting support of my efforts to do so under the new management.

**Comment by Be-ing** [comment]
I'm glad to learn about your work modularizing the Audacity code @Paul-Licameli. If official builds support MIDI, then the dependencies must include PortMidi. It would be nice to make building with MIDI optional, but that's a bit tangential. I'll attempt to get PortMidi building with vcpkg locally on Linux this week, which has also been on my to-do list for Mixxx.

**Comment by Be-ing** [comment]
> While I don't have much to offer in terms of coding skills (I haven't written any serious code in 25-30 years), I'll offer any assistance I can to working on this issue.

How about making a table of the versions of dependencies Audacity uses, the release dates of those versions, the current version number, and the release date of the current version?

**Comment by crsib** [comment]
@Be-ing Thank you a lot for the suggestion. Switching to some sort of package management was in the very short plan! I was leaning toward Conan though but after the research of Conan usage for the Linux packageable software. 

I will examine the VCPKG thoroughly, thank you a lot for your input and for the example of how it is used in FOSS!

Speaking of the way **master** is currently built - there is a switch for every library, which will force the build system to use FindPackage instead of compiling the included source. This was true libcurl as well. I will check if that works shortly after I will have access to my workstation.

Also, there are plans to switching to vanilla wxWidgets, but I'm not sure if it will really help the Linux distributions. I'm really doubtful that it will be able to go below 3.1.4. 

(Anyway, how do you feel about Conan?)

**Comment by Holzhaus** [comment]
For reference: https://github.com/52doho/vcpkg-vs-conan

Mixxx uses vcpkg because a) it has more packages, b) it allows both release debug libraries c) packaging a dependency is pretty easy it already uses CMake.

Stuff that is not already packages or stuff that we need a special version of has been packages into a special overlay directory: https://github.com/mixxxdj/vcpkg/tree/2.3/overlay/ports

**Comment by crsib** [comment]
Conan supports debug/release builds and is integrated well with cmake :)

Main advantage for the **vcpkg** - the ease of adding a package.

**Comment by Be-ing** [comment]
Please continue the discussion about details for the wxWidgets fork in #625.

**Comment by crsib** [comment]
@SndChaser we are on 3.1.3 already. I really doubt, that amount of work to support the vanilla version of the 3.0 branch is feasible. And even with 3.1.3 we have a lot of issues with high DPI displays, which are becoming more and more common. @lllucius probably knows more.

**Comment by lllucius** [comment]
> 
> 
> @SndChaser we are on 3.1.3 already. I really doubt, that amount of work to support the vanilla version of the 3.0 branch is feasible. And even with 3.1.3 we have a lot of issues with high DPI displays, which are becoming more and more common. @lllucius probably knows more.

Yea, it can be difficult to support multiple versions of wxWidgets.  It's not as simple as just building against a newer version.  When we upgraded from wx3.1.1 to wx3.1.3 several changes were needed to correct display issues, like colors and window sizing.  Sometimes it's a problem in wxWidgets and we have to wait for (or backport) a fix.  Sometimes we can work around it.  But, sometimes those workarounds can only be done for the wxWidgets version we're building against and don't work with older versions of wxWidgets.

We used to try and support multiple versions of wxWidgets using #ifdef()s, but it got to be a real hassle and tended to cause compromises to be made.  A (fairly) recent example is commit 9eaa2f2.  It was made so that Audacity could build with older versions of wxWidgets, but it also reintroduced the problem that commit 036efda fixed.

In the near future, we "may" have to require wxWidgets v3.1.4 or v3.1.5 as I'm currently in the process of TRYING to remove the need for an Audacity-specific wxWidgets by getting rid of our patches to the wxWidgets source.  However, doing this "may" require at least v3.1.4 and if we have to spend the time to retest everything against a new version of wxWidgets, we might as well jump to v3.1.5 since that's the currently released version.

**Comment by falkTX** [comment]
I can help with Obj-C, have a mac m1 machine where I test things occasionally.

**Comment by Be-ing** [comment]
Again I ask that discussion about the details of what to do with wxWidgets continue on #625. Let's keep the discussion here focused on package management in general. If the maintainers choose vcpkg I am happy to help. Feel free to copy code from Mixxx's GitHub Actions workflows and scripts and adapt it for Audacity. I've never used Conan before.

**Comment by Be-ing** [comment]
Now that I have peeked down the rabbit hole (#871), I am no longer willing to work on this code base. I would not work on code with this much technical debt even if I was offered a lot of money. However, I am happy to answer questions and give advise about setting up vcpkg if you choose to use it, so feel free to ping me about that.

**Comment by Be-ing** [comment]
@lllucius please explain why you [reverted](https://github.com/audacity/audacity/commit/95bcb08b4b300eeff1c430aecf353ff31c97a727#comments) the update of FFmpeg (#741) yesterday.

**Comment by Be-ing** [comment]
> And what will be your proposal?

I said it in the first post:

> As a first step, I suggest auditing every one of Audacity's dependencies and updating them to the newest compatible version before changing how dependencies are handled

> https://bugzilla.audacityteam.org/show_bug.cgi?id=2775

That's unfortunate. That bug report should have been linked in the commit message for 95bcb08b4b300eeff1c430aecf353ff31c97a727. I suggest to repeat #741 and take care of whatever fixes are needed to update to the new FFmpeg version in the same pull request and test exporting all file formats that FFmpeg handles before merging again.

**Comment by crsib** [comment]
https://github.com/audacity/audacity/projects/1

**Comment by Be-ing** [comment]
So you have decided to use Conan rather than vcpkg? I'm curious what led you to that decision.

**Comment by crsib** [comment]
I've tried to describe it in the project description. TL;DR: they are very similar package-wise in our case, but Conan has a more clean approach to "features".

**Comment by Be-ing** [comment]
> feel free to copy code from the GitHub Actions workflows and scripts we wrote for Mixxx that I linked above.

This no longer applies because of the imposition of the CLA (#932). Muse Group does not have permission to apply the terms of the CLA to GPL licensed code whose copyright holders have not agreed to the CLA.

**Comment by crsib** [comment]
>This no longer applies

It stopped applying the moment Conan was chosen

**Comment by Be-ing** [comment]
That was a general comment not limited to Mixxx's CI scripts. Muse Group has chosen to prohibit using a lot of useful code in Audacity that could have been used before.

**Comment by LWinterberg** [comment]
This issue was split up into individual tasks which are kept track of in https://github.com/audacity/audacity/projects/1
