### ISSUE TITLE
Request for clarification on Muse Group's involvement and vision for the Audacity project

### ISSUE THREAD

**Issue by domsson** [audacity/audacity#855]
Both the [Audacity website](https://www.audacityteam.org/audacity-musescore-announcement/) as well as [Muse Group's website](https://mu.se/muse-products) states that Muse Group has acquired Audacity. However, hardly any details have been given. The information given on the [Wikipedia page on Muse Group](https://en.wikipedia.org/wiki/Muse_Group) is also vague and questionable at best. All we have to work with is this quote from Tantacrul's video: 

> Audacity has just joined Muse Group, a collection of brands that includes another popular open source music app called MuseScore, which I’m currently in charge of.

This raises several important questions. To name a few:

 - Is it even possible for a company to acquire a free and open source project licensed under the GPL?
 - How exactly did Muse Group acquire Audacity?
 - What rights and power does Muse Group legally have over the Audacity project?
 - Can Muse Group even legally claim ownership over the project or do they simply own the trademarks to the name and logo?
 - Who exactly is behind Muse Group; what roles do these people have?
 - What are Muse Group's visions and goals for Audacity?
 - How does Muse Group plan on going about putting these goals and visions into practice?
 - How does Muse Group plan on handling situations where they want a new feature but the community rejects it (see [PR 835](https://github.com/audacity/audacity/pull/835))?
 - Are any of the core maintainers and team members of Audacity now on the pay roll of Muse Group?
 - What is the project father's and core maintainer's role and view of these events?

**Comment by domsson** [comment]
Both the Audacity website as well as Muse Group's website states that Muse Group has _acquired_ Audacity. However, hardly any details have been given.

This raises several questions:

- Is it even possible for a company to acquire a free and open source project licensed under the GPL?
- How exactly did Muse Group _acquire_ Audacity?
- Are any of the core maintainers and team members of Audacity now on the pay roll of Muse Group?
- What rights and power does Muse Group legally have over the Audacity project?
- Can Muse Group even legally claim ownership over the project or do they simply own the trademarks to the name and logo?
- What are Muse Group's visions and goals for Audacity?
- How does Muse Group plan on going about putting these goals and visions into practice?

**Comment by illwieckz** [comment]
I'm specially interested in the questions about defining the relationship between Muse Group and external developers like contributors who have their own interest, will and schedule.

Because to speak about myself [one of my main concern and interest](https://github.com/audacity/audacity/pull/835#issuecomment-836355997) for Audacity right now is to never see a split of efforts and other waste like I have seen so many time in other projects, either because one group has the name and the other group the workforce, either because of disagreements between parts, either because of lack of interest in being part of a whole.

Without much information I assume it's good and welcome if Muse Group can put paid people on making Audacity better and putting Audacity in places it's not there yet, but defining relationship with the community seems to be an important point to address to begin with. Hello people.

**Comment by ethindp** [comment]
I'm also curious about this. "Acquiring" an open-source project that's licensed under the GPL2 -- or licensed under an open-source license at all -- seems really sketchy to me. (Is it even legal under the GPL to do something like that to begin with?) The lack of information about the acquisition, supposedly from a company who holds a stance that Audacity will remain "free and open-source", is also suspect. I think that we as the community have a right to know a lot more than what the company has provided us. If Muse Group -- whoever they are because I've never heard of them -- are trying to put on the face of transparency and trustworthiness, they're failing big time at it.

**Comment by malberts** [comment]
The "Audacity" logo trademark was filed on 21 March 2021:
https://tmsearch.uspto.gov/bin/showfield?f=doc&state=4808:oh9d5r.2.12

**Comment by illwieckz** [comment]
> I'm also curious about this. "Acquiring" an open-source project that's licensed under the GPL2 -- or licensed under an open-source license at all -- seems really sketchy to me. (Is it even legal under the GPL to do something like that to begin with?)

@ethindp Indeed it's possible to acquire an open-source project and it's fully legal, GPL2 has nothing to do with this, GPL2 is mostly about making sure the copy you get once under GPL2 will still be GPL2 forever in your hands (even if yourself don't agree with this).

A company can acquire the name, hence the brand and trademark. It's not the project per se, but a project with its renowned brand is as fragile as a newborn again, so yes selling the brand makes huge part of acquiring a project. Selling only a brand [already happened in the past](https://en.wikipedia.org/wiki/Xonotic#Development) with some other projects, though it appears that's not what is happening with Muse Group and Audacity there, there is multiple articles on the web clearly stating about taking care of the open source side of Audacity, the freeness of it, improving it [1](https://mu.se/newsroom/tpost/6dhedma301-muse-group-acquires-audacity-expanding-c), [2](https://www.musictech.net/news/industry/audacity-acquired-muse-group-ultimate-guitar-musescore/), [3](https://www.minimachines.net/actu/muse-group-rachete-le-logiciel-audacity-99063) and even testimony from a developer who joined the team to work on Audacity (and one who know about open source), one who already worked for another open source software previously acquired by Muse Group: [Muse Score](https://musescore.org/). So time will tell, but for now we can't assume it's bad per se, and don't look harmful at first glance (though they may still have to learn a bit about some expectations of open source users given #835).

A company can also hire the key developers of a project, hence owning the workforce. A company can hire project heads, acquiring the decision.

In some case (if the sellers got copyright assignment) it may even be possible for a company to buy the copyright of the open source project with right to remove the GPL2 itself. I doubt it would happen with Audacity, and that's not what Muse Group does with MuseScore they acquired before anyway.

> So, the fork "FOSS-Audacity" most probably cannot keep this name but would be fine if named "Aefkaa" (Audio editor formally known as Audacity)...

@Locutus74 A fork would be the worst thing for everyone ([see my comment there](https://github.com/audacity/audacity/pull/835#issuecomment-836355997)), after a decade [Xonotic](https://xonotic.org/) never recovered the Nexuiz coverage after the Nexuiz trademark was sold, after a decade [LibreOffice](https://www.libreoffice.org/) haven't recovered yet the other half of users using OpenOffice because they don't own the OpenOffice trademark… Such a fork would be bad for users, for audacity as a project, and for muse group. No one has something to gain from a fork. This only have to be done on last resort.

If MuseGroup seems to have to learn a bit about open source communities, for now all they did were mistakes they can fix and learn from, they didn't tried to harm the project intentionally yet.

**Comment by Locutus74** [comment]
At least at a first glance "MuseCY Holding LTD." seems to be a typical letterbox (money laundry?) company in Cyprus. 
It therefor most probably is impossible to find out the real owner. And yes, this looks a little bit (more) shady, now...

**Comment by illwieckz** [comment]
> @illwieckz ... nope, a fork is not necessarilly the worst thing for everyone. LibreOffice is the very best example for this.

@Locutus74 This is not contradictory. My opinion is that the Xonotic fork was the best thing that happened to Nexuiz, in term of direction. The LibreOffice fork is very successful and can be named among the most successful fork in history.

But the sad reality around this is even if the fork was the best thing that happened to Xonotic, Xonotic never recovered its recognition and reputation 10 years later, French Wikipedia even [deleted three times the Xonotic page](https://fr.wikipedia.org/wiki/Xonotic) because of lack of recognition.

The sad reality is that even if LibreOffice is one of the more successful fork in history, half of the users still use OpenOffice, most of them probably don't know LibreOffice about at all, 10 years later, and I verified this around me.

Forking is engaging oneself for a full time job. This is just wasting time for every parts.

Xonotic didn't have the choice to lose the brand. LibreOffice didn't have the opportunity to keep the brand.

Note that LibreOffice is a special situation. LibreOffice was based on GO-Office which was an enhanced OpenOffice (basically all the Microsoft docx/xslx things were implemented in GO-Office first), at the time, and before LibreOffice existed, almost all Linux distributions shipped GO-Office under OpenOffice name. It was like, OpenOffice with GO-Office patches. But after all that Oracle buying and other details, the definitive split from OpenOffice was inevitable. LibreOffice suffered from the lose of the name, but they already had the workforce from before Oracle bought OpenOffice wen acquiring Sun.

So yes LibreOffice is a perfect example of successful fork, but also the perfect example that even after a decade such fork can't recover the same brand recognition and only gets something like half the users…

At this point nothing in MuseGroup acting makes a fork inevitable. They clearly made a mistake, but they can learn from it. No door is closed.

> And the name may be more important in the first place. But not on the long run...

Both Xonotic and LibreOffice examples show that a long run of 10 years is not long enough.

Anyway this thread is about getting answers from MuseGroup. At this point we need answers from MuseGroup and they made many people angry, but they did not made any unrecoverable mistake yet that would make a fork inevitable… So better not be responsible for greater harm than they did by causing the fork oneself.

**Comment by Locutus74** [comment]
> Muse Group has imposed a CLA on MuseScore. That's another topic though. Let's discuss that in #844.

They have **WHAT?**

If I would have contributed there I would not sign this but asking them to remove my contribution... They're not on ones right mind... (I really need to clarify if I possibly can except them from using/linking against/derive from my GPLed code (with a lawyer, obviously).)

**Comment by kuberlog** [comment]
If the logo was in a repo with a GPL license, doesn't that mean the logo is also GPL. Same with the name. It doesn't seem like a GPL2 project can be owned at all, even the trademarks. AFAIK the JPEG of the Audacity logo was shipped with the app as a whole and therefore covered by the GPL.

**Comment by kuberlog** [comment]
I went ahead and deleted the "acquired" part of the wiki page since GPL projects can't be aquired.

**Comment by orenwatson** [comment]
So, the number of months in which MuseCY Holdings Ltd aka "muse group" operated in secret is raised from 4 to 8, as they did not reveal company's existence until 8 months after its actual formation.

**Comment by orenwatson** [comment]
They are currently attempting to stop another company, Holland and Hart LLP, from using the name "audacity plus".
https://ttabvue.uspto.gov/ttabvue/v?pno=91267301&pty=OPP

**Comment by MrAureliusR** [comment]
First of all, I want to address @illwieckz comment about forking. LibreOffice is *way* more successful than OpenOffice. Libre is the default office software for all the major distros. I don't know the numbers for sure, but I would be **extremely** surprised if OO had maybe 5% of the users Libre has at this point. I don't know of any distro that still includes OpenOffice over LibreOffice. The fork has gone incredibly well.

Honestly, forking Audacity should definitely be on the table. So what if they have the name? Coming up with a name isn't that hard. Sure, it'd be a blow to the project, but taking that known blow over the unknown damage this company could cause seems like the logical course of action (if it comes down to it, of course -- we still have to wait and see if the company responds in any way). The major distros would almost certainly switch over to the new fork within a very short period of time, as that's where all the work and improvements would be done. If all they've done is acquire the name, then they can't stop anything else. I'm also interested in the fact that they've registered the logo -- my initial assumption would be that someone in the community created that logo under some sort of license (maybe CC?) and contributed it to the project. Perhaps it was the original founder of the project who made it, in which case they could sell the copyright to it. But again, I think it's best to make sure this can't ever happen again. Who knows if they will sell the name and logo to someone else down the line? Making some kind of Audacity Foundation (with whatever the new name would be) and assigning the name and logo to them, to be run by the community, seems like the best safety net.

No matter what the company says, remember that they are a for-profit. Their motive lies in making money, not in making good free software. Their bank account will always come first over the community. If they have the correct ideals then open source and making money can go hand in hand with everyone benefiting, but they've not shown any indication of that so far... so I'm definitely hesitant to trust anything they say.

**Comment by Be-ing** [comment]
> Making some kind of Audacity Foundation (with whatever the new name would be) and assigning the name and logo to them, to be run by the community, seems like the best safety net.

This is somewhat like what Blender does.

**Comment by illwieckz** [comment]
> Guess what my native language might be

I'm not assuming you're the only one on earth reading that thread neither this thread is about you.

**Comment by Locutus74** [comment]
> I'm not assuming you're the only one on earth reading that thread neither this thread is about you.

Fine. So, we can just discuss the main topic, again?

**Comment by domsson** [comment]
> I have begun editing the wikipedia page for muse group to insert the correct date of its formation, namely july 2020, not april 2021. (I have citations proving this, of course.)

@orenwatson Thank you for your efforts! As long as there is no statement from Muse Group or the people in charge of Audacity, we might as well collect as much information as we can. In this vein, would it be helpful to try and make a list of all people we _know_ are involved with (employed by) Muse Group? For now, I am only aware of:

- [Tantacrul](https://github.com/Tantacrul) - UI/UX, "in charge"
- [crsib](https://github.com/crsib) - Programmer
- [workedintheory](https://github.com/workedintheory) - Head of Strategy

**Comment by Blu3wolf** [comment]
> in some case (if the sellers got copyright assignment) it may even be possible for a company to buy the copyright of the open source project with right to remove the GPL2 itself.

No, this is not possible. The company may choose to develop a closed source version and release that under a different license, but they have no ability to revoke a license granted already. This is a key part of the GPL. Anyone who has used the software may use it, may distribute it, and may modify it and distribute the modifications, provided they comply with the requirements of the GPL. 

If the company purchased the copyright from all original contributors (a practical impossibility at this point), they could themselves breach the GPL, as they would be using the code as the owners of it, rather than as licensees - but they could not revoke other people's valid licenses, and they could not prevent others from using and sharing their GPL'd versions.

**Comment by illwieckz** [comment]
> > in some case (if the sellers got copyright assignment) it may even be possible for a company to buy the copyright of the open source project with right to remove the GPL2 itself.
> 
> No, this is not possible. The company may choose to develop a closed source version and release that under a different license, but they have no ability to revoke a license granted already.

@Blu3wolf Please don't extrapolate on other people words. I never said such company would be able to retroactively remove GPL2 on something delivered. It looks like you assumed words at the end of my sentence, words I never wrote. I never added “retroactively” at the end of the sentence.

I never wrote those words about retroactivity because I even made it clear some sentence before in the same post you quoted it is not possible to revoke a license granted already:

> GPL2 is mostly about making sure the copy you get once under GPL2 will still be GPL2 forever in your hands (even if yourself don't agree with this)

- “The copy you get once under GPL2 will still be GPL2 forever” → not possible to revoke a license granted already.
- “even if yourself don't agree with this” → even if the company buying copyrights and/or getting CLA signed don't don't agree with this.

Clearly, what have been GPL2 is GPL2 forever, but the ones who may buy copyrights, obtain CLA etc. have rights to add new licenses to the existing code (that would be dual licensing, even with non-free licenses) and have rights to legally publish new version with code that was never GPL2 and will never be, meaning the users can't backport the change to the GPL2 version they got first.

> If the company purchased the copyright […] they could not revoke other people's valid licenses, and they could not prevent others from using and sharing their GPL'd versions.

This is exactly what I said. We were just agreeing on that topic, so better not assume contradiction first.

This is exactly why CLAs can be problematic and people can be concerned about it.

A company can't buy the copy you already got in the past, but a company can buy almost everything about the future of the software: the name, the brand, the recognition, the workforce, the decision, and the right to change license for the future code.

Of course people can share their GPL'd version, but we can't assume those GPL'd versions will carry the brand, the recognition, the workforce and the decision. For example LibreOffice carried the workforce and the decision but did not carried the brand and had to build up recognition from scratch.

This is pretty problematic, and history shows that even among most successful forks may have hard time to fully recover. I'm not happy with this, but to properly deal with a problem we have to look at things the way they are and not the way we want them to be.

**Comment by Locutus74** [comment]
> ... but the ones who may buy copyrights, obtain CLA etc. have rights to add new licenses to the existing code (that would be dual licensing, even with non-free licenses)...

Erm, not quite... They cannot change the license of existing code. They however could republish the old code using a dual-license model (would not make too much sense for them) and they could **try** to add new code using a non-free license.

Why only "try"? 

If there only remains one single line of code of which they do not have a CLA and which is originating as GPL before they added their shiny new stuff, then everything they add for new automatically becomes licensed under GPL, too (key word is "derivative work").

GPL is predatory in this regard: This is one of the main security features built into the GPL because RMS had foreseen situations like this. That twist is all but new... 

> ... but to properly deal with a problem we have to look at things the way they are and not the way we want them to be...

I really would like

**Comment by illwieckz** [comment]
> They cannot change the license of existing code.

I did not said change, I said _add_.

> They however could republish the old code using a dual-license model

That's exactly what I said: “_add new licenses to the existing code (that would be dual licensing […])_”

Anyway, we are focusing on details about each other words, not about the specific questions related to Muse Group acquisition of Audacity. So we're loosing our time each other.

If something is not perfect in someone's word or may induce misinterpretation, this looks pretty minor compared to the topic, and those minor things can be handled later if they become non-minor at some point anyway.

**Comment by Be-ing** [comment]
I don't know where [this poster](https://discuss.pixls.us/t/libre-arts-ultimate-guitar-launches-muse-group-and-acquires-audacity/24795/4) got this information and if it is accurate...

> It has not been widely publicized, but Muse group acquired rights to code contributions from many of the major contributors to the codebase. This doesn’t negate the GPL license, but would probably permit them greater control and maybe the ability to make a non-GPL version, but they haven’t suggested they are interested in that. If they did that, it would kill off the huge user support community and volunteer coder staff, and because the 3.0 codebase is still available, it could be forked from there or their latest GPL release. They may have plans to require license assignment from future third-party contributors, which might reduce the volunteer developer community, but it is not super-active anyway. I’m sure there are bug fix contributions that have not completely been acquired–from anonymous contributors, contributors who have died, and others who are just unfindable, but these would mostly have been reviewed, revised, and committed by identifiable team members who did license their contributions. There could be an issue with these contributions if Muse wanted to roll a pro version not under the GPL. It might require a substantial code audit if they wanted to do this which would be a huge obstacle, but If they tried that and somebody complained, it would mean the un-acquired code would then be clearly identified, and Muse could just pull it out or rewrite it or pay the contributor relicense it.

**Comment by Be-ing** [comment]
https://mu.se/newsroom/tpost/3dkxig59m1-muse-group-launches-to-support-music-tec

> Executive roles and company leadership of Ultimate Guitar will transition into similar roles in Muse Group with no other major structural or operational changes within the individual portfolio companies.

**Comment by domsson** [comment]
@illwieckz and @Locutus74 

Just a quick reminder that this issue is about clearing up Muse Group's involvement and vision for the project. The details of copyright, while still to some degree very relevant here, are probably better discussed in detail over at [844](https://github.com/audacity/audacity/issues/844).

**Comment by orenwatson** [comment]
Do we need a seperate issue for demanding that the people behind MuseCY Holdings Ltd and/or MuseCY SM Ltd. identify themselves and stop hiding behind Cypriot shell companies?

**Comment by domsson** [comment]
> Do we need a seperate issue for demanding that the people behind MuseCY Holdings Ltd and/or MuseCY SM Ltd. identify themselves and stop hiding behind Cypriot shell companies?

I don't think so. After all, one of the questions listed is: _"Who exactly is behind Muse Group; what roles do these people have?"_

I've got to say though, I'm quite astonished that there is still _no_ reply from _any_ of the people who do have at least _some_ of the answers.

**Comment by JamesCrook** [comment]
You're going to have to rely on public statements from https://mu.se/ and what you can work out for yourselves form publicly available information.  

Beyond that, rely on actual behaviour of people actively working on Audacity.  You can't tell that from immediate actions over the short term, only from longer term.

We use GitHub issues for issues with code.  If someone closes this, it will be closed and locked pretty quickly.  I'm converting this to a discussion so that it can stay open, at least for now.
