### ISSUE TITLE
Meta Issue: Issue Labels

### ISSUE THREAD

**Issue by IGBC** [audacity/audacity#858]
Can we get some Issue labels, so we can more quickly filter between bugs, feature requests, etc?

I would really like to be able to keep an eye on just bugs, for one thing it'll make it way quicker to pick out something to code on. But as of right now we don't have any way of filtering them in GitHub.

**Comment by crsib** [comment]
Hi! We will be going in that direction soon. For now, bugs are tracked using https://bugzilla.audacityteam.org/

**Comment by JamesCrook** [comment]
@IGBC - Do you want to propose some issue labels?

My thoughts are that GitHub issues will become issues that we actually are able to and expect to close, whereas GitHub discussions (newly opened up) will be ongoing discussions open to different points of view.  The distinction between actual QA bug work (in bugzilla) and general open to anyone to add to wish list and questions and ideas (here on GitHub) is one reason we've in the past kept bugzilla as a closed invitation only platform.  People have to understand what we mean by P2, P3, Enh: and how we work, for their contributions to be useful there.

FYI the issue labels we have in Bugzilla are:

* Repeatable, RepeatableAll (i.e. all platforms), Locale, Accessibility, MoonPhase, Enhancment.
* Slow, 64Bit, JACK, AudioUnits, WASAPI, NoteTrack, LV2....

**Comment by IGBC** [comment]
I think starting with high level labels: bug, feature request, suggestion, etc is the place to start, then as groups working on such things identify areas where subdivision is needed create a new set of sub labels. In my work below the category I usually split by module, but being new to the audacity code base I don't know how applicable modules are.

**Comment by JamesCrook** [comment]
So I've added more labels.
Probably the two most important are bug and bug-distro.

The distinction is that 'bug' is used for platforms we build and test for, and 'bug-distro' is for distros or variants that we don't yet build and test for.

@IGBC - How do you want to handle the next step for this issue, either:
* Close it since there now are some labels on most GitHub issues
* Convert this issue to a general discussion of future bug handling (and so move it to discussions and retitle)
* Some other option.

**Comment by JamesCrook** [comment]
I've adding labels.  I think the meta-issue is addressed now.  Closing.
