### ISSUE TITLE
Create final strings. Create email to send to translators.

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#912]
Also: encourage a move to Discord and a move away from mailing list.

**Comment by Gootector** [comment]
"Also: encourage a move to Discord and a move away from mailing list."
I'm against. I'm **also** MuseScore translator and reviewer over 10 years, so I have over 10 years of experience with your fantastic Team.
I'm **also** EU citizen. When I wanted to delete my account (https://musescore.org/pl/user/13434) from MuseScore.org - You never answered my request, so I deleted MuseScore.com account only (https://musescore.com/user/7876). (Old) MuseScore.org accounts are 'undeletable' (???!!!). First - fix MuseScore.org website, next - write your claims.
I value my privacy and I'm not going to use Discord, because you decide it does.
I prefer Transifex (https://www.transifex.com/klyok/audacity/) and sending PR.

**Comment by niwla23** [comment]
What about using matrix? It is privacy oriented and federated.
https://matrix.org
