### ISSUE TITLE
Hotkeys doesn't work with non-english keyboard layout on linux

### ISSUE THREAD

**Issue by Yanpas** [audacity/audacity#96]
Ctrl+O doesn't work
Opening menu via keyboard (Alt+Ф for Файл) highlights File(Файл) entry, but does not expand it. (see screenshot)
I use two layouts : russian and american. version 2.0.5
![_2015-12-28_17-36-34](https://cloud.githubusercontent.com/assets/7345761/12020118/90df4fd6-ad89-11e5-8c7d-b85a54c4d454.png)

**Comment by windinthew** [comment]
2.0.5 is long obsolete, and probably built with a version of Widgets we no longer support. If it's a packaged version of Audacity, please report the problem to your distribution. 

If the problem occurs in the tarball "Linux 2.1.2 RC1 minimal source (for testing)"  available from http://www.fosshub.com/Audacity.html , please let us know. This is the bug report address: http://audacityteam.org/contact/#feedback . However I don't see those problems on Ubuntu 14.04 in 2.1.2 RC1 using English or Czech QWERTY layouts.

**Comment by Yanpas** [comment]
I've tried audacity from ubuntu 16.04 beta. (audacity version 2.0.6). Bug with Alt+F is fixed, but Ctrl+O still doesn't work, seems like wxwidgets problems
I've tried to build latest audacity, but make returns error. Are there binary builds somewhere?
![_2015-12-28_19-52-21](https://cloud.githubusercontent.com/assets/7345761/12022000/bb872494-ad9c-11e5-8d84-4d02f13e2cec.png)

**Comment by windinthew** [comment]
The packaged 2.0.6 might be built with wx3 but that was an error by Ubuntu because 2.0.6 did not support wx3 at the time.  

I do not recommend using Ubuntu 16.04 because that OS is still four months before release. 

You could build the 2.1.2 tarball on Ubuntu 15.x  - try these steps:
http://forum.audacityteam.org/viewtopic.php?f=19&t=88922 .

To resolve your compilation error, configure Audacity with --disable-dynamic-loading or even better,
--without-ffmpeg .

Please note this not a support channel. Please use http://forum.audacityteam.org/viewforum.php?f=48 if you need more help.

**Comment by JamesCrook** [comment]
QA believe this is fixed in current Audacity (when built correctly) and so closing this bug.
Thanks for the bug report.
