### ISSUE TITLE
Unexplained "broken MP3" error importing a song

### ISSUE THREAD

**Issue by djechelon** [audacity/audacity#960]
**Describe the bug**
Trying to import an MP3 file (Blade Encoder 128k CBR) into Audacity for editing.
Audacity fails with message "Import failed. Possible cause is a broken MP3"

**To Reproduce**
1. Download from YouTube [this song](https://www.youtube.com/watch?v=CkbHmhUDpKs) in M4A format
2. Use VLC to convert it to WAV
3. Use CDex with Blade Encoder to convert it to MP3 CBR 128K, equal to all the files in the existing collection
4. (Store the file somewhere, burn it to DVD, whatever)
2. Drag the resulting file to Audacity for subsequent processing
3. BOOM

Yes, I could share some bytes of the mp3 file I own. Something that won't get any of us to legal trouble.

**Expected behavior**
Audacity to import the file and show the wave trace

**Screenshots**

(Do you speak Italiano? 🇮🇹)
![immagine](https://user-images.githubusercontent.com/3042285/120942123-1252cb80-c727-11eb-9546-a787ef985be7.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 3.0.2
 - All my tracks are encoded using the old Blade Encoder of which I still own a copy

**Additional context**
I just wanted to make a ringtone-suitable cut of an [audio track](https://www.youtube.com/watch?v=CkbHmhUDpKs). I already "converted" and tagged it for my personal music collection. I know that if I re-download the track again from Youtube as a WAV audio or M4A Audacity will import it.

I just want to understand why Audacity fails to import all my MP3s. I have tried with multiple tracks of my collection. All ripped using CDex (the original, not the adware-powered) with Blade Encoder.

**Comment by djechelon** [comment]
I know that without the file or its structure you can't investigate the bug, I'm just not posting any link to cloud storage **right now** otherwise someone could file a DMCA compliant to harm the project

**Comment by petersampsonaudacity** [comment]
See this Forum post, it should help you:  https://forum.audacityteam.org/viewtopic.php?f=46&t=117436&p=426850&hilit=import#p426850

**Comment by Tantacrul** [comment]
Could you tell us what the song is (and possibly where you got it from) so we can check ourselves?

Thanks!

**Comment by djechelon** [comment]
Sorry I thought I posted the YouTube link. I edited the post with the instructions.

Yes, I **did** create the ringtone using the M4A version re-downloaded from YT but the bug still persists with existing MP3s from my dj set collection

**Comment by djechelon** [comment]
@petersampsonaudacity my list is empty by default

![🇮🇹](https://user-images.githubusercontent.com/3042285/121790678-fc8b4d80-cbe1-11eb-90b4-8a44dd9b6323.png)

**Comment by petersampsonaudacity** [comment]
You beat me to it djechelon - glad you discovered for yourself how to do that - and really glad that it worked for you.  

The underlying issue is that a couple of releases back we tightened up on not allowing "imperfect" or "flawed" MP3 files.  It did need some toghtening up (to avoid other issues) but it may still be a little overzealous and could possibly be relaxed a little.  

This is something we are aware of and are keeping an eye on - in the meanwhile I will consider adding something in tha Manual about the workaround (so for now I'll keep this GitHub issue open as a reminder-to-self).

Peter.

**Comment by djechelon** [comment]
@petersampsonaudacity here you go

https://drive.google.com/file/d/1sq03RZU0nw4TyE5QX6FWrPMmhojIDvV4/view?usp=sharing

**Comment by petersampsonaudacity** [comment]
@djechelon 

firstly, maby thanks for the malformed MP3  :-)

As a result of this I decided to formalize the help we can offer in such circumstannces and wrote this new page in the alpha Manual for the upcoming 3.0.3 release - https://alphamanual.audacityteam.org/man/Opening_malformed_MP3_files

I've also filed a request for a ?" help button to be added to that error message - that button would send the user to that new page (so hopefully they could help themselves solve their issue).

Peter.

**Comment by petersampsonaudacity** [comment]
@djechelon 

I've just been testing you MP3 - yes it still fives the error message in 3.0.2 - but when I import it into the latest alpha test build it imports just fine.

What puzzles me about this is I don't recall any changes we made to the importer libraries for 3.0.3

**Comment by vladkosi** [comment]
Latest master build https://github.com/audacity/audacity/actions/runs/942194968 can't open any MP3 file, libmad is disabled.

![1](https://user-images.githubusercontent.com/6567423/122212718-748a9980-cea8-11eb-81f9-2788ac850613.png)
![2](https://user-images.githubusercontent.com/6567423/122212728-781e2080-cea8-11eb-8dba-b8ab94851485.png)

**Comment by crsib** [comment]
@vladkosi whoa, that is unfortunate. That is fixed now in #985, it will be merged shortly

Thanks for pointing it out!

**Comment by petersampsonaudacity** [comment]
However testing this morning with the latest alpha  -  audacity-win-3.0.3-alpha-20210616+e83210d-32bit

Now today with the latest alpha I can no longer import djechelon's malformed MP3.

From looking at the GitHub commits I notice this recent one from Dmitry
Fixes the libmad disabled by mistake
https://github.com/audacity/audacity/commit/c8e0bf343dbecbb1e1d181ceef124705bdc72079

And this did get pulled in Master after my last set of tests yesterday.

I tested again with the builds I had yesterday - and then yes I could import those malformed MP3s again.


So I'm inferring that it worked before because libmad was accidentally disabled and that thus all MP3 imports were via FFmpeg.

This may also explain why I was seeing no metadata being imported with audio files.
