### ISSUE TITLE
Plug-in Manager

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#999]
Design in Figma

Automatically detecting new installed VST/AU plugins, scanning them at startup, and clean up of the current plugin manager
Related to: #992 

- [x] Automatic scan, test and enabling of plugins
- [ ] New UI 
- [ ] Manually adding search paths

**Comment by jounih** [comment]
Currently, when using external (VST, AudioUnit, LADSPA or LV2) plugins, you have to manually enable them in the Audacity "Manage Plug-ins" dialog. This is a somewhat unnecessary manual task for users, and one that is not clear to users unless they read the manual.

What many DAWs do instead is scan the system plugin paths for any new plugins at the start of the audio application (in case a new plugin causes a crash), and silently auto-enable any new plugins, so that they are automatically available for user and shown in the effects menu.

We should do the same with Audacity - auto-scan for new plugins at startup, and auto-enable them. If the plugins cause issues at the scan/validation stage, we should display a dialog letting the user know which of the plugins are incompatible or have issues, and not auto-enable those.

The "Manage Plug-ins" dialog in current Audacity is also somewhat confusing, and would benefit from an UX cleanup (see below).

Finally, it would be nice to have some UI in preferences for defining custom search paths for plugins (in addition to the baked in OS specific search paths already in Audacity)

![new plugins - errors@2x](https://user-images.githubusercontent.com/10109867/124119223-265dc480-da6a-11eb-96bf-a92b1062a712.jpg)

![Manage plug-ins@2x](https://user-images.githubusercontent.com/10109867/124119220-25c52e00-da6a-11eb-9fd4-b039d09f595c.jpg)

![plugin paths@2x](https://user-images.githubusercontent.com/10109867/124121748-2ca17000-da6d-11eb-9bee-cf19bec9a003.jpg)

**Comment by petersampsonaudacity** [comment]
Be aware of Bug 2565
1215 https://bugzilla.audacityteam.org/show_bug.cgi?id=2565
Bug 2565 - Mac: AU instruments may be installed but do not work

And I seem to recall that not all Audio Unit plug-ins shipped by Apple work in Audacity (but I can't find a logged issue for that right now).

**Comment by petersampsonaudacity** [comment]
> Currently, when using external (VST, AudioUnit, LADSPA or LV2) plugins, you have to manually enable them in the Audacity 
>"Manage Plug-ins" dialog. This is a somewhat unnecessary manual task for users, and one that is not clear to users unless they 
>read the manual.

The worst is that when you click "Enable" the plug-in moves from new to enabled status in the dialog GUI - so certainly looks like it's enabled.

**BUT** you have to remember also to click "OK" to make the setting(s) stick - and many's the time I've forgotten to do that and got caught out ...

**Comment by LWinterberg** [comment]
the plugin scanning (and rescanning: #3359) has been/will be implemented in 3.2; the rest of this can probably wait until 4.x
